import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/models/generator_config.dart';
import 'package:zuraffa/src/plugins/mock/mock_plugin.dart';

/// Spec 1001 (issue #1001), deliverable 4: deterministic seeds —
/// `zfa mock create <Entity> --seed=<int>` produces identical mocks for
/// the same seed (replayable generation).
///
/// The capability's execute() path is driven through MockPlugin directly
/// (same code path `zfa mock create` dispatches to), in two independent
/// fresh directories, and the generated bytes are compared.
void main() {
  Directory scaffoldProject(String path) {
    final outputDir = p.join(path, 'lib', 'src');
    final entityDir = Directory(
      p.join(outputDir, 'domain', 'entities', 'login'),
    );
    entityDir.createSync(recursive: true);
    File(p.join(entityDir.path, 'login.dart')).writeAsStringSync('''
class Login {
  final String id;
  final String username;
  const Login({required this.id, required this.username});
}
''');
    return Directory(outputDir);
  }

  Future<Map<String, String>> generateMock(String root, {int? seed}) async {
    final outputDir = scaffoldProject(root);
    final plugin = MockPlugin(
      outputDir: outputDir.path,
      options: const GeneratorOptions(dryRun: false, force: true),
    );
    final files = await plugin.generate(
      GeneratorConfig(
        name: 'Login',
        methods: const ['get', 'update', 'toggle'],
        generateMock: true,
        generateData: false,
        generateDataSource: false,
        generateRepository: false,
        appendToExisting: false,
        outputDir: outputDir.path,
        seed: seed,
      ),
    );
    final result = <String, String>{};
    for (final file in files) {
      final rel = p.relative(file.path, from: outputDir.path);
      if (file.action == 'skipped') continue;
      final onDisk = File(file.path).existsSync()
          ? File(file.path).readAsStringSync()
          : file.content;
      if (onDisk != null && onDisk.isNotEmpty) {
        result[rel] = onDisk;
      }
    }
    return result;
  }

  group('spec 1001 — deterministic seeds (--seed)', () {
    test('same seed (42) reproduces byte-identical mock output', () async {
      final dirA = await Directory.systemTemp.createTemp('zfa_seed_a_');
      final dirB = await Directory.systemTemp.createTemp('zfa_seed_b_');
      try {
        final filesA = await generateMock(dirA.path, seed: 42);
        final filesB = await generateMock(dirB.path, seed: 42);

        // Same file set, and every file's bytes are identical.
        expect(filesA.keys.toSet(), filesB.keys.toSet());
        expect(filesA, isNotEmpty);
        for (final rel in filesA.keys) {
          expect(
            filesA[rel],
            filesB[rel],
            reason: 'byte drift for $rel between two --seed=42 runs',
          );
        }
      } finally {
        await dirA.delete(recursive: true);
        await dirB.delete(recursive: true);
      }
    });

    test('seeded records derive from the seed (42, not 1/2/3)', () async {
      final dir = await Directory.systemTemp.createTemp('zfa_seed_c_');
      try {
        final files = await generateMock(dir.path, seed: 42);
        final mockData = files.entries
            .firstWhere((e) => e.key.endsWith('login_mock_data.dart'))
            .value;
        expect(mockData, contains("Login(id: 'id 42',"));
        expect(mockData, contains("Login(id: 'id 43',"));
        expect(
          mockData,
          isNot(contains("Login(id: 'id 1', ")),
          reason: 'the historical unseeded first record must not appear',
        );
      } finally {
        await dir.delete(recursive: true);
      }
    });

    test('different seeds produce different (but stable) mocks', () async {
      final dir7 = await Directory.systemTemp.createTemp('zfa_seed_d_');
      final dir9 = await Directory.systemTemp.createTemp('zfa_seed_e_');
      try {
        final files7 = await generateMock(dir7.path, seed: 7);
        final files9 = await generateMock(dir9.path, seed: 9);
        final mockData7 = files7.entries
            .firstWhere((e) => e.key.endsWith('login_mock_data.dart'))
            .value;
        final mockData9 = files9.entries
            .firstWhere((e) => e.key.endsWith('login_mock_data.dart'))
            .value;
        expect(mockData7, isNot(mockData9));
        expect(mockData7, contains("Login(id: 'id 7',"));
        expect(mockData9, contains("Login(id: 'id 9',"));
      } finally {
        await dir7.delete(recursive: true);
        await dir9.delete(recursive: true);
      }
    });

    test('no seed keeps the historical record seeds (1/2/3) — semantics '
        'unchanged', () async {
      final dir = await Directory.systemTemp.createTemp('zfa_seed_f_');
      try {
        final files = await generateMock(dir.path);
        final mockData = files.entries
            .firstWhere((e) => e.key.endsWith('login_mock_data.dart'))
            .value;
        expect(mockData, contains("Login(id: 'id 1',"));
        expect(mockData, contains("Login(id: 'id 2',"));
        expect(mockData, contains("Login(id: 'id 3',"));
      } finally {
        await dir.delete(recursive: true);
      }
    });
  });
}
