import 'dart:io';

import 'package:test/test.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/plugins/provider/provider_plugin.dart';

/// Spec 979, order 5 — append/inject round-trip for the provider plugin
/// (`MethodCapability(targetType: 'provider')` and
/// `InjectCapability(targetType: 'provider')`).
///
/// The generated provider skeleton must remain a stable host for the AST
/// append engine: appending a method preserves the `// GENERATED by zfa
/// provider` provenance header and every existing member, is idempotent
/// (re-append does not duplicate), and the appended method lands with the
/// stub-first body (unchanged semantics — the TDD flow fills it).
/// Injecting a dependency adds the field + constructor parameter without
/// disturbing the header or the members.
void main() {
  late Directory tempDir;
  late String outputDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('zfa_provider_append_');
    outputDir = '${tempDir.path}/lib/src';
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
  });

  /// Generates a provider for `Product` against a hand-written
  /// `ProductService` interface (the create-capability path).
  Future<String> generateProvider() async {
    final services = Directory('$outputDir/domain/services');
    await services.create(recursive: true);
    await File('${services.path}/product_service.dart').writeAsString('''
import 'package:zuraffa/zuraffa.dart';

abstract class ProductService {
  Future<void> execute(NoParams params);
}
''');

    final plugin = ProviderPlugin(
      outputDir: outputDir,
      options: const GeneratorOptions(force: true),
    );
    final create = plugin.capabilities.firstWhere((c) => c.name == 'create');
    final result = await create.execute({'name': 'Product'});

    expect(result.success, isTrue, reason: 'provider create must succeed');
    return result.files.firstWhere((f) => f.endsWith('product_provider.dart'));
  }

  test('method append preserves the GENERATED header + existing members and '
      'is idempotent', () async {
    final providerPath = await generateProvider();
    final before = File(providerPath).readAsStringSync();
    expect(before, contains('// GENERATED by zfa provider'));
    expect(before, contains('Future<void> execute(NoParams params)'));

    final plugin = ProviderPlugin(
      outputDir: outputDir,
      options: const GeneratorOptions(force: true),
    );
    final methodCapability = plugin.capabilities.firstWhere(
      (c) => c.name == 'method',
    );

    final result = await methodCapability.execute({
      'target': 'ProductService',
      'name': 'syncInventory',
      'params': 'NoParams',
      'returns': 'void',
      'type': 'usecase',
      'force': true,
    });

    expect(result.success, isTrue, reason: 'append must succeed');

    final after = File(providerPath).readAsStringSync();
    // Provenance header survives the AST surgery.
    expect(
      after.trimLeft().startsWith('// GENERATED by zfa provider'),
      isTrue,
      reason: 'the append engine must not strip the provenance header',
    );
    // The original member survives.
    expect(
      after,
      contains('Future<void> execute(NoParams params)'),
      reason: 'the existing member must survive the append',
    );
    // The appended member lands on the provider class with the
    // stub-first body (semantics unchanged — spec 979 hard constraint).
    expect(after, contains('syncInventory'));
    final stubMatches = RegExp(
      'UnimplementedError\\(.syncInventory[^)]*\\)',
    ).allMatches(after);
    expect(
      stubMatches,
      isNotEmpty,
      reason: 'the appended method keeps the stub-first body',
    );

    // Idempotent: re-append the same method — no duplication.
    await methodCapability.execute({
      'target': 'ProductService',
      'name': 'syncInventory',
      'params': 'NoParams',
      'returns': 'void',
      'type': 'usecase',
      'force': true,
    });
    final afterTwice = File(providerPath).readAsStringSync();
    expect(
      'syncInventory'.allMatches(afterTwice).length,
      equals('syncInventory'.allMatches(after).length),
      reason: 're-appending the same method must be idempotent',
    );
  });

  test('inject adds the dependency to the provider class without disturbing '
      'the header or members', () async {
    final providerPath = await generateProvider();

    final plugin = ProviderPlugin(
      outputDir: outputDir,
      options: const GeneratorOptions(force: true),
    );
    final injectCapability = plugin.capabilities.firstWhere(
      (c) => c.name == 'inject',
    );

    final result = await injectCapability.execute({
      'target': 'ProductProvider',
      'dependency': 'AuthService',
    });

    expect(
      result.success,
      isTrue,
      reason: 'inject must succeed: ${result.message ?? ''}',
    );

    final after = File(providerPath).readAsStringSync();
    expect(
      after.trimLeft().startsWith('// GENERATED by zfa provider'),
      isTrue,
      reason: 'the inject engine must not strip the provenance header',
    );
    expect(after, contains('AuthService'));
    expect(
      after,
      contains('Future<void> execute(NoParams params)'),
      reason: 'the existing member must survive the inject',
    );
  });
}
