// GENERATED - DO NOT EDIT
// Generated by zfa for: Login
import 'package:go_router/go_router.dart';

import '../presentation/pages/auth/login_view.dart';

abstract class AuthRoutes {
  static const String login = '/login';
}

List<GoRoute> authRoutes() {
  return [
    GoRoute(
      path: AuthRoutes.login,
      name: 'login',
      builder: (context, state) => const LoginView(),
    ),
  ];
}

// END GENERATED
