import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: ConnectedAccount

import '../presentation/pages/connected_account/connected_account_view.dart';

abstract class ConnectedAccountRoutes {
  static const String connectedAccountList = '/connected_account';

  static const String connectedAccountDetail = '/connected_account/:id';
}

List<GoRoute> connectedAccountRoutes() {
  return [
    GoRoute(
      path: ConnectedAccountRoutes.connectedAccountList,
      name: 'connected_account_list',
      builder: (context, state) => const ConnectedAccountView(),
    ),
  ];
}

// END GENERATED
