import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: DeviceInfo

import '../presentation/pages/device_info/device_info_view.dart';

abstract class DeviceInfoRoutes {
  static const String deviceInfoList = '/device_info';

  static const String deviceInfoDetail = '/device_info/:id';
}

List<GoRoute> deviceInfoRoutes() {
  return [
    GoRoute(
      path: DeviceInfoRoutes.deviceInfoList,
      name: 'device_info_list',
      builder: (context, state) => const DeviceInfoView(),
    ),
  ];
}

// END GENERATED
