import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: DynamicFormField

import '../presentation/pages/dynamic_form_field/dynamic_form_field_view.dart';

abstract class DynamicFormFieldRoutes {
  static const String dynamicFormFieldList = '/dynamic_form_field';

  static const String dynamicFormFieldDetail = '/dynamic_form_field/:id';
}

List<GoRoute> dynamicFormFieldRoutes() {
  return [
    GoRoute(
      path: DynamicFormFieldRoutes.dynamicFormFieldList,
      name: 'dynamic_form_field_list',
      builder: (context, state) => const DynamicFormFieldView(),
    ),
  ];
}

// END GENERATED
