import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: FormSubmission

import '../presentation/pages/form_submission/form_submission_view.dart';

abstract class FormSubmissionRoutes {
  static const String formSubmissionList = '/form_submission';

  static const String formSubmissionDetail = '/form_submission/:id';
}

List<GoRoute> formSubmissionRoutes() {
  return [
    GoRoute(
      path: FormSubmissionRoutes.formSubmissionList,
      name: 'form_submission_list',
      builder: (context, state) => const FormSubmissionView(),
    ),
  ];
}

// END GENERATED
