import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: GrocerySubVariety

import '../presentation/pages/grocery_sub_variety/grocery_sub_variety_view.dart';

abstract class GrocerySubVarietyRoutes {
  static const String grocerySubVarietyList = '/grocery_sub_variety';

  static const String grocerySubVarietyDetail = '/grocery_sub_variety/:id';
}

List<GoRoute> grocerySubVarietyRoutes() {
  return [
    GoRoute(
      path: GrocerySubVarietyRoutes.grocerySubVarietyList,
      name: 'grocery_sub_variety_list',
      builder: (context, state) => const GrocerySubVarietyView(),
    ),
  ];
}

// END GENERATED
