import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: GroceryItem

import '../presentation/pages/grocery_item/grocery_item_view.dart';

abstract class GroceryItemRoutes {
  static const String groceryItemList = '/grocery_item';

  static const String groceryItemDetail = '/grocery_item/:id';
}

List<GoRoute> groceryItemRoutes() {
  return [
    GoRoute(
      path: GroceryItemRoutes.groceryItemList,
      name: 'grocery_item_list',
      builder: (context, state) => const GroceryItemView(),
    ),
  ];
}

// END GENERATED
