// GENERATED - DO NOT EDIT
// Generated by zfa
import 'package:go_router/go_router.dart';

import 'ai_conversation_routes.dart';
import 'app_config_routes.dart';
import 'app_notification_routes.dart';
import 'auth_request_routes.dart';
import 'auth_routes.dart';
import 'authentication_routes.dart';
import 'barcode_listing_routes.dart';
import 'barcode_routes.dart';
import 'barcode_spark_routes.dart';
import 'category_routes.dart';
import 'chat_message_routes.dart';
import 'chat_session_routes.dart';
import 'connected_account_routes.dart';
import 'customer_address_routes.dart';
import 'customer_routes.dart';
import 'deal_detail_routes.dart';
import 'deal_routes.dart';
import 'device_info_routes.dart';
import 'device_routes.dart';
import 'dynamic_form_field_routes.dart';
import 'dynamic_form_routes.dart';
import 'error_log_routes.dart';
import 'extracted_invoice_routes.dart';
import 'feedback_routes.dart';
import 'form_option_routes.dart';
import 'form_submission_routes.dart';
import 'grocery_item_routes.dart';
import 'grocery_price_comparison_routes.dart';
import 'grocery_price_result_routes.dart';
import 'grocery_product_routes.dart';
import 'grocery_routes.dart';
import 'grocery_store_routes.dart';
import 'grocery_sub_variety_routes.dart';
import 'listing_offer_routes.dart';
import 'listing_routes.dart';
import 'locale_routes.dart';
import 'main_shell.dart';
import 'metric_detail_routes.dart';
import 'nearby_grocery_store_routes.dart';
import 'price_alert_routes.dart';
import 'price_check_invoice_routes.dart';
import 'price_drop_notification_routes.dart';
import 'profile_routes.dart';
import 'scan_barcode_routes.dart';
import 'scan_url_routes.dart';
import 'splash_routes.dart';
import 'store_price_routes.dart';
import 'subscription_routes.dart';
import 'telemetry_event_routes.dart';
import 'text_listing_routes.dart';
import 'text_spark_routes.dart';
import 'url_listing_routes.dart';
import 'url_spark_routes.dart';
import 'user_routes.dart';
import 'walkthrough_routes.dart';
import 'walkthrough_step_routes.dart';
import 'walkthrough_view_routes.dart';
import 'zik_zak_config_routes.dart';
import 'zik_zak_routes.dart';
import 'zik_zak_score_routes.dart';

export 'ai_conversation_routes.dart';
export 'app_config_routes.dart';
export 'app_notification_routes.dart';
export 'app_routes.dart';
export 'auth_request_routes.dart';
export 'auth_routes.dart';
export 'authentication_routes.dart';
export 'barcode_listing_routes.dart';
export 'barcode_routes.dart';
export 'barcode_spark_routes.dart';
export 'category_routes.dart';
export 'chat_message_routes.dart';
export 'chat_session_routes.dart';
export 'connected_account_routes.dart';
export 'customer_address_routes.dart';
export 'customer_routes.dart';
export 'deal_detail_routes.dart';
export 'deal_routes.dart';
export 'device_info_routes.dart';
export 'device_routes.dart';
export 'dynamic_form_field_routes.dart';
export 'dynamic_form_routes.dart';
export 'error_log_routes.dart';
export 'extracted_invoice_routes.dart';
export 'feedback_routes.dart';
export 'form_option_routes.dart';
export 'form_submission_routes.dart';
export 'grocery_item_routes.dart';
export 'grocery_price_comparison_routes.dart';
export 'grocery_price_result_routes.dart';
export 'grocery_product_routes.dart';
export 'grocery_routes.dart';
export 'grocery_store_routes.dart';
export 'grocery_sub_variety_routes.dart';
export 'listing_offer_routes.dart';
export 'listing_routes.dart';
export 'locale_routes.dart';
export 'main_shell.dart';
export 'metric_detail_routes.dart';
export 'nearby_grocery_store_routes.dart';
export 'price_alert_routes.dart';
export 'price_check_invoice_routes.dart';
export 'price_drop_notification_routes.dart';
export 'profile_routes.dart';
export 'scan_barcode_routes.dart';
export 'scan_url_routes.dart';
export 'splash_routes.dart';
export 'store_price_routes.dart';
export 'subscription_routes.dart';
export 'telemetry_event_routes.dart';
export 'text_listing_routes.dart';
export 'text_spark_routes.dart';
export 'url_listing_routes.dart';
export 'url_spark_routes.dart';
export 'user_routes.dart';
export 'walkthrough_routes.dart';
export 'walkthrough_step_routes.dart';
export 'walkthrough_view_routes.dart';
export 'zik_zak_config_routes.dart';
export 'zik_zak_routes.dart';
export 'zik_zak_score_routes.dart';

List<RouteBase> getAllRoutes() {
  return [
    GoRoute(path: '/', name: 'root', redirect: (_, _) => SplashRoutes.splash),
    ...aiConversationRoutes(),
    ...appConfigRoutes(),
    ...appNotificationRoutes(),
    ...authRequestRoutes(),
    ...authRoutes(),
    ...authenticationRoutes(),
    ...barcodeListingRoutes(),
    ...barcodeRoutes(),
    ...barcodeSparkRoutes(),
    ...categoryRoutes(),
    ...chatMessageRoutes(),
    ...chatSessionRoutes(),
    ...connectedAccountRoutes(),
    ...customerAddressRoutes(),
    ...customerRoutes(),
    ...dealDetailRoutes(),
    ...dealRoutes(),
    ...deviceInfoRoutes(),
    ...deviceRoutes(),
    ...dynamicFormFieldRoutes(),
    ...dynamicFormRoutes(),
    ...errorLogRoutes(),
    ...extractedInvoiceRoutes(),
    ...feedbackRoutes(),
    ...formOptionRoutes(),
    ...formSubmissionRoutes(),
    ...groceryItemRoutes(),
    ...groceryPriceComparisonRoutes(),
    ...groceryPriceResultRoutes(),
    ...groceryProductRoutes(),
    ...groceryRoutes(),
    ...groceryStoreRoutes(),
    ...grocerySubVarietyRoutes(),
    ...listingOfferRoutes(),
    ...listingRoutes(),
    ...localeRoutes(),
    ...metricDetailRoutes(),
    ...nearbyGroceryStoreRoutes(),
    ...priceAlertRoutes(),
    ...priceCheckInvoiceRoutes(),
    ...priceDropNotificationRoutes(),
    ...profileRoutes(),
    ...scanBarcodeRoutes(),
    ...scanUrlRoutes(),
    ...splashRoutes(),
    ...storePriceRoutes(),
    ...subscriptionRoutes(),
    ...telemetryEventRoutes(),
    ...textListingRoutes(),
    ...textSparkRoutes(),
    ...urlListingRoutes(),
    ...urlSparkRoutes(),
    ...userRoutes(),
    ...walkthroughRoutes(),
    ...walkthroughStepRoutes(),
    ...walkthroughViewRoutes(),
    ...zikZakConfigRoutes(),
    ...zikZakRoutes(),
    ...zikZakScoreRoutes(),
    ...mainShellRoute(),
  ];
}

// END GENERATED
