import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: ListingOffer

import '../presentation/pages/listing_offer/listing_offer_view.dart';

abstract class ListingOfferRoutes {
  static const String listingOfferList = '/listing_offer';

  static const String listingOfferDetail = '/listing_offer/:id';
}

List<GoRoute> listingOfferRoutes() {
  return [
    GoRoute(
      path: ListingOfferRoutes.listingOfferList,
      name: 'listing_offer_list',
      builder: (context, state) => const ListingOfferView(),
    ),
  ];
}

// END GENERATED
