import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: NearbyGroceryStore

import '../presentation/pages/nearby_grocery_store/nearby_grocery_store_view.dart';

abstract class NearbyGroceryStoreRoutes {
  static const String nearbyGroceryStoreList = '/nearby_grocery_store';

  static const String nearbyGroceryStoreDetail = '/nearby_grocery_store/:id';
}

List<GoRoute> nearbyGroceryStoreRoutes() {
  return [
    GoRoute(
      path: NearbyGroceryStoreRoutes.nearbyGroceryStoreList,
      name: 'nearby_grocery_store_list',
      builder: (context, state) => const NearbyGroceryStoreView(),
    ),
  ];
}

// END GENERATED
