import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: PriceCheckInvoice

import '../presentation/pages/price_check_invoice/price_check_invoice_view.dart';

abstract class PriceCheckInvoiceRoutes {
  static const String priceCheckInvoiceList = '/price_check_invoice';

  static const String priceCheckInvoiceDetail = '/price_check_invoice/:id';
}

List<GoRoute> priceCheckInvoiceRoutes() {
  return [
    GoRoute(
      path: PriceCheckInvoiceRoutes.priceCheckInvoiceList,
      name: 'price_check_invoice_list',
      builder: (context, state) => const PriceCheckInvoiceView(),
    ),
  ];
}

// END GENERATED
