// GENERATED - DO NOT EDIT
// Generated by zfa for: Profile
import 'package:go_router/go_router.dart';

import '../presentation/pages/profile/profile_view.dart';

abstract class ProfileRoutes {
  static const String profile = '/profile';
}

List<GoRoute> profileRoutes() {
  return [
    GoRoute(
      path: ProfileRoutes.profile,
      name: 'profile',
      builder: (context, state) => const ProfileView(),
    ),
  ];
}

// END GENERATED
