// GENERATED - DO NOT EDIT
// Generated by zfa for deep-link: ScanUrl
import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';

class ScanUrlRoutes {
  static const String scanUrl = '/scan/url';
}

List<GoRoute> scanUrlRoutes() {
  return [
    GoRoute(
      path: ScanUrlRoutes.scanUrl,
      name: 'scan_url',
      builder: (context, state) => const SizedBox.shrink(),
    ),
  ];
}

// END GENERATED
