import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: StorePrice

import '../presentation/pages/store_price/store_price_view.dart';

abstract class StorePriceRoutes {
  static const String storePriceList = '/store_price';

  static const String storePriceDetail = '/store_price/:id';
}

List<GoRoute> storePriceRoutes() {
  return [
    GoRoute(
      path: StorePriceRoutes.storePriceList,
      name: 'store_price_list',
      builder: (context, state) => const StorePriceView(),
    ),
  ];
}

// END GENERATED
