import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: Subscription

import '../presentation/pages/subscription/subscription_view.dart';

abstract class SubscriptionRoutes {
  static const String subscriptionList = '/subscription';

  static const String subscriptionDetail = '/subscription/:id';
}

List<GoRoute> subscriptionRoutes() {
  return [
    GoRoute(
      path: SubscriptionRoutes.subscriptionList,
      name: 'subscription_list',
      builder: (context, state) => const SubscriptionView(),
    ),
  ];
}

// END GENERATED
