import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: TextListing

import '../presentation/pages/text_listing/text_listing_view.dart';

abstract class TextListingRoutes {
  static const String textListingList = '/text_listing';

  static const String textListingDetail = '/text_listing/:id';
}

List<GoRoute> textListingRoutes() {
  return [
    GoRoute(
      path: TextListingRoutes.textListingList,
      name: 'text_listing_list',
      builder: (context, state) => const TextListingView(),
    ),
  ];
}

// END GENERATED
