import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: UrlListing

import '../presentation/pages/url_listing/url_listing_view.dart';

abstract class UrlListingRoutes {
  static const String urlListingList = '/url_listing';

  static const String urlListingDetail = '/url_listing/:id';
}

List<GoRoute> urlListingRoutes() {
  return [
    GoRoute(
      path: UrlListingRoutes.urlListingList,
      name: 'url_listing_list',
      builder: (context, state) => const UrlListingView(),
    ),
  ];
}

// END GENERATED
