import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: User

import '../presentation/pages/user/user_view.dart';

abstract class UserRoutes {
  static const String userList = '/user';

  static const String userDetail = '/user/:id';
}

List<GoRoute> userRoutes() {
  return [
    GoRoute(
      path: UserRoutes.userList,
      name: 'user_list',
      builder: (context, state) => const UserView(),
    ),
  ];
}

// END GENERATED
