import 'package:go_router/go_router.dart';
// GENERATED - DO NOT EDIT
// Generated by zfa for: ZikZak

import '../presentation/pages/zik_zak/zik_zak_view.dart';

abstract class ZikZakRoutes {
  static const String zikZakList = '/zik_zak';

  static const String zikZakDetail = '/zik_zak/:id';
}

List<GoRoute> zikZakRoutes() {
  return [
    GoRoute(
      path: ZikZakRoutes.zikZakList,
      name: 'zik_zak_list',
      builder: (context, state) => const ZikZakView(),
    ),
  ];
}

// END GENERATED
