/// `zfa tdd run-engine <feature>` — the run engine's Tier-1 mock
/// certification gate (spec 1001, issue #1001).
///
/// The TDD loop's make path generates mocks for entity-traced behaviors
/// by default (#909/#935). "Mocks the framework certifies, not the
/// agent" (VISION §9) means the engine must refuse to proceed when a
/// CORE entity's mock is present but uncertified — a mock that exists
/// without a green `mock-cert.<Entity>.json` receipt is exactly the
/// agent-graded-its-own-homework state the certification exists to
/// forbid.
///
/// CORE entities are the feature's declared **Key Entities** (the
/// entities the run driver's phase 0 orchestrates, bug #829). Gate
/// semantics, per entity:
///
/// - no mock datasource on disk → nothing to enforce, the engine
///   proceeds (mocks are generated by the loop, not required up front);
/// - mock datasource present + a receipt proving every method
///   `satisfied: true` → certified, proceed;
/// - mock datasource present + receipt missing, corrupt, or any method
///   unsatisfied → REFUSE (exit 1, the entity and fix are named).
///
/// `zfa tdd run` invokes this same gate as a pre-start preflight, so
/// the engine cannot bypass it.
///
/// Machine contract: the final line is
/// `run-engine: feature=<f> core-entities=<n> mocks=<n> certified=<n> uncertified=<n>`
/// plus ` blocked=<entity>` when refused. Exit codes: 0 certified (or
/// nothing to enforce), 1 refused (uncertified core mock), 2 usage /
/// missing feature.
library;

import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;

import '../../../core/project/project_root.dart';
import '../../mock/certification/mock_cert_receipt.dart';
import '../services/entity_lookup.dart';
import '../services/test_list_reader.dart';
import '../tdd_plugin.dart';

/// The gate's decision.
class RunEngineGateResult {
  const RunEngineGateResult({
    required this.coreEntities,
    required this.mocks,
    required this.certified,
    required this.uncertified,
    required this.blockedEntity,
  });

  /// The feature's declared Key Entities (CORE entities).
  final List<String> coreEntities;

  /// CORE entities that have a mock datasource on disk.
  final List<String> mocks;

  /// Mock-holding CORE entities with an all-satisfied receipt.
  final List<String> certified;

  /// Mock-holding CORE entities without a valid certification.
  final List<String> uncertified;

  /// The first uncertified entity (the refusal names it), or null.
  final String? blockedEntity;

  bool get ok => uncertified.isEmpty;
}

class RunEngineCommand extends Command<void> {
  RunEngineCommand(this.plugin) {
    argParser.addOption(
      'project',
      aliases: const ['project-root'],
      help:
          'Project root containing specs/, test/, and .specify/ (the '
          'fixture or target project). When omitted, the current working '
          'directory is used.',
    );
  }

  final TddPlugin plugin;

  @override
  String get name => 'run-engine';

  @override
  String get description =>
      'Tier-1 mock certification gate for the run engine: refuse to '
      'proceed when any CORE (declared Key Entity) mock is present but '
      'uncertified (spec 1001).';

  @override
  String get invocation => 'zfa tdd run-engine <feature> [--project <dir>]';

  static const _exitOk = 0;
  static const _exitRefused = 1;
  static const _exitUsage = 2;

  @override
  Future<void> run() async {
    final rest = argResults?.rest ?? const <String>[];
    if (rest.isEmpty) {
      stderr.writeln(
        'zfa tdd run-engine: missing <feature> — name the spec directory '
        'whose Key Entities gate the engine (e.g. 049-tdd-run)',
      );
      _printSummary(
        feature: '-',
        result: RunEngineGateResult(
          coreEntities: const [],
          mocks: const [],
          certified: const [],
          uncertified: const [],
          blockedEntity: null,
        ),
      );
      exitCode = _exitUsage;
      return;
    }
    final feature = _stripSpecsPrefix(rest.first);
    final projectFlag = argResults?['project'] as String?;
    final projectRoot = projectFlag != null && projectFlag.isNotEmpty
        ? p.absolute(projectFlag)
        : ProjectRoot.find(anchorDir: 'specs');

    final featureDir = p.join(projectRoot, 'specs', feature);
    if (!await Directory(featureDir).exists()) {
      stderr.writeln(
        'zfa tdd run-engine: no feature directory at '
        '${p.relative(featureDir, from: projectRoot)} (project root: '
        '$projectRoot)',
      );
      _printSummary(
        feature: feature,
        result: RunEngineGateResult(
          coreEntities: const [],
          mocks: const [],
          certified: const [],
          uncertified: const [],
          blockedEntity: null,
        ),
      );
      exitCode = _exitUsage;
      return;
    }

    final result = await checkFeature(
      projectRoot: projectRoot,
      featureDir: featureDir,
    );

    if (!result.ok) {
      final entity = result.blockedEntity!;
      stderr.writeln(
        'zfa tdd run-engine: CORE entity "$entity" has a mock on disk '
        'that is NOT certified — the engine refuses to proceed '
        '(spec 1001: mocks the framework certifies, not the agent).',
      );
      stderr.writeln(
        '--> fix: zfa mock certify $entity '
        '(or zfa mock create $entity --certify), then re-run.',
      );
      _printSummary(feature: feature, result: result);
      exitCode = _exitRefused;
      return;
    }

    _printSummary(feature: feature, result: result);
    exitCode = _exitOk;
  }

  /// The gate itself — also invoked by `zfa tdd run` as its pre-start
  /// preflight.
  static Future<RunEngineGateResult> checkFeature({
    required String projectRoot,
    required String featureDir,
  }) async {
    final entities = await TestListReader(featureDir).readEntities();
    final coreEntities = entities.map((e) => e.name).toList();
    final mocks = <String>[];
    final certified = <String>[];
    final uncertified = <String>[];

    for (final name in coreEntities) {
      final snake = toSnakeCase(name);
      final mockPath = p.join(
        projectRoot,
        'lib',
        'src',
        'data',
        'datasources',
        snake,
        '${snake}_mock_datasource.dart',
      );
      if (!File(mockPath).existsSync()) continue;
      mocks.add(name);
      final receipt = loadMockCertReceipt(projectRoot, name);
      if (receipt != null && receipt.allSatisfied) {
        certified.add(name);
      } else {
        uncertified.add(name);
      }
    }

    return RunEngineGateResult(
      coreEntities: coreEntities,
      mocks: mocks,
      certified: certified,
      uncertified: uncertified,
      blockedEntity: uncertified.isNotEmpty ? uncertified.first : null,
    );
  }

  static void _printSummary({
    required String feature,
    required RunEngineGateResult result,
  }) {
    stdout.writeln(
      'run-engine: feature=$feature '
      'core-entities=${result.coreEntities.length} '
      'mocks=${result.mocks.length} '
      'certified=${result.certified.length} '
      'uncertified=${result.uncertified.length}'
      '${result.blockedEntity != null ? ' blocked=${result.blockedEntity}' : ''}',
    );
  }

  static String _stripSpecsPrefix(String feature) {
    var f = feature.trim();
    while (f.endsWith('/')) {
      f = f.substring(0, f.length - 1);
    }
    if (f.startsWith('specs/')) {
      f = f.substring('specs/'.length);
    }
    return f;
  }
}
