// GENERATED - DO NOT EDIT
// Generated by zfa for: NearbyGroceryStore
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/nearby_grocery_store/nearby_grocery_store.dart';
import '../../repositories/nearby_grocery_store_repository.dart';

class ToggleNearbyGroceryStoreUseCase
    extends
        UseCase<
          NearbyGroceryStore,
          ToggleParams<String, Field<NearbyGroceryStore, dynamic>>
        > {
  ToggleNearbyGroceryStoreUseCase(this._repository);

  final NearbyGroceryStoreRepository _repository;

  @override
  Future<NearbyGroceryStore> execute(
    ToggleParams<String, Field<NearbyGroceryStore, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
