// Generated by zfa for: FormSubmission
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'form_submission_controller.dart';
import 'form_submission_presenter.dart';

class FormSubmissionView extends CleanView {
  const FormSubmissionView({super.key, super.routeObserver});

  @override
  State<FormSubmissionView> createState() {
    return _FormSubmissionViewState(
      FormSubmissionController(FormSubmissionPresenter()),
    );
  }
}

class _FormSubmissionViewState
    extends CleanViewState<FormSubmissionView, FormSubmissionController, void> {
  _FormSubmissionViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('FormSubmission')),
      body: ControlledWidgetBuilder<FormSubmissionController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
