// GENERATED - DO NOT EDIT
// Generated by zfa for: ConnectedAccount
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/connected_account/connected_account.dart';
import '../../mock/connected_account_mock_data.dart';
import 'connected_account_datasource.dart';

/// Mock data source for ConnectedAccount
class ConnectedAccountMockDataSource
    with Loggable, FailureHandler
    implements ConnectedAccountDataSource {
  ConnectedAccountMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ConnectedAccount> get(QueryParams<ConnectedAccount> params) async {
    logger.info('Getting ConnectedAccount with params: $params');
    await Future.delayed(_delay);
    final item = ConnectedAccountMockData.connectedAccounts.query(params);
    logger.info('Successfully retrieved ConnectedAccount');
    return item;
  }

  @override
  Future<ConnectedAccount> update(
    UpdateParams<String, ConnectedAccountPatch> params,
  ) async {
    logger.info('Updating ConnectedAccount: ${params.id}');
    await Future.delayed(_delay);
    final existing = ConnectedAccountMockData.sampleConnectedAccount;
    logger.info('Successfully updated ConnectedAccount');
    return existing;
  }

  @override
  Future<ConnectedAccount> toggle(
    ToggleParams<String, Field<ConnectedAccount, dynamic>> params,
  ) async {
    logger.info(
      'Toggling ConnectedAccount: ${params.id} on field ${params.field}',
    );
    await Future.delayed(_delay);
    final existing = ConnectedAccountMockData.sampleConnectedAccount;
    logger.info('Successfully toggled ConnectedAccount');
    return existing;
  }
}

// END GENERATED
