// Generated by zfa for: PriceAlert
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'price_alert_controller.dart';
import 'price_alert_presenter.dart';

class PriceAlertView extends CleanView {
  const PriceAlertView({super.key, super.routeObserver});

  @override
  State<PriceAlertView> createState() {
    return _PriceAlertViewState(PriceAlertController(PriceAlertPresenter()));
  }
}

class _PriceAlertViewState
    extends CleanViewState<PriceAlertView, PriceAlertController, void> {
  _PriceAlertViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('PriceAlert')),
      body: ControlledWidgetBuilder<PriceAlertController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
