import 'dart:io';

import '../../../core/plugin_system/capability.dart';
import '../../../models/generated_file.dart';
import '../../../utils/file_utils.dart';
import '../builders/mcp_scaffold_builder.dart';
import '../mcp_plugin.dart';

/// `zfa mcp scaffold [--name <name>] [--force] [--dry-run] [--verbose]`
///
/// Scaffolds a runtime MCP server into a Zuraffa app by writing:
///
///  * `lib/src/mcp/tools.dart` — the app's declared [McpTool] list
///    (initially a placeholder `EchoTool` so the server runs out
///    of the box).
///  * `bin/mcp_server.dart` — standalone entrypoint that boots the
///    engine + `McpServerPlugin` and serves stdio (or SSE with
///    `--sse`). Supports `--list-tools` for `zfa mcp list-tools`.
///
/// Both files are stamped `// Generated by zfa` so subsequent runs
/// can identify them. `--force` overwrites; without it, existing
/// files are skipped (so user customisations survive re-runs).
class ScaffoldMcpServerCapability implements ZuraffaCapability {
  final McpPlugin plugin;

  ScaffoldMcpServerCapability(this.plugin);

  @override
  String get name => 'scaffold';

  @override
  String get description =>
      'Scaffold a runtime MCP server (lib/src/mcp/tools.dart + bin/mcp_server.dart) '
      'so the app can expose its features as MCP tools callable by AI agents.';

  @override
  JsonSchema get inputSchema => {
    'type': 'object',
    'properties': {
      'name': {
        'type': 'string',
        'description':
            'Optional name for the MCP server (defaults to the package name '
            'from pubspec.yaml).',
      },
      'force': {
        'type': 'boolean',
        'description': 'Overwrite existing files',
        'default': false,
      },
      'dryRun': {
        'type': 'boolean',
        'description': 'Preview without writing files',
        'default': false,
      },
      'verbose': {
        'type': 'boolean',
        'description': 'Enable detailed logging',
        'default': false,
      },
      'revert': {
        'type': 'boolean',
        'description': 'Delete the scaffolded files',
        'default': false,
      },
    },
    'required': [],
  };

  @override
  JsonSchema get outputSchema => {
    'type': 'object',
    'properties': {
      'generatedFiles': {
        'type': 'array',
        'items': {
          'type': 'object',
          'properties': {
            'path': {'type': 'string'},
            'type': {'type': 'string'},
            'action': {'type': 'string'},
          },
        },
      },
    },
  };

  @override
  Future<EffectReport> plan(Map<String, dynamic> args) async {
    final files = await _generateFiles(args, dryRun: true);
    return EffectReport(
      planId: 'plan_${DateTime.now().millisecondsSinceEpoch}',
      pluginId: plugin.id,
      capabilityName: name,
      args: args,
      changes: files
          .map((f) => Effect(file: f.path, action: f.action, diff: null))
          .toList(),
    );
  }

  @override
  Future<ExecutionResult> execute(Map<String, dynamic> args) async {
    final files = await _generateFiles(args, dryRun: args['dryRun'] ?? false);
    return ExecutionResult(
      success: true,
      files: files.map((f) => f.path).toList(),
      data: {'generatedFiles': files},
    );
  }

  /// Generates the two scaffolded files using [McpScaffoldBuilder].
  Future<List<GeneratedFile>> _generateFiles(
    Map<String, dynamic> args, {
    required bool dryRun,
  }) async {
    final force = (args['force'] as bool?) ?? false;
    final verbose = (args['verbose'] as bool?) ?? false;
    final revert = (args['revert'] as bool?) ?? false;

    final packageName = await _resolvePackageName(args);
    final builder = McpScaffoldBuilder();

    final toolsContent = builder.buildToolsFile(appName: packageName);
    final binContent = builder.buildBinServer(
      appName: packageName,
      outputDir: plugin.outputDir,
    );

    final toolsPath = _joinPath(plugin.outputDir, 'mcp', 'tools.dart');
    final binPath = 'bin/mcp_server.dart';

    final toolsFile = await FileUtils.writeFile(
      toolsPath,
      toolsContent,
      'mcp_tools',
      force: force,
      dryRun: dryRun,
      verbose: verbose,
      revert: revert,
      fileSystem: plugin.fileSystem,
    );
    final binFile = await FileUtils.writeFile(
      binPath,
      binContent,
      'mcp_server_entrypoint',
      force: force,
      dryRun: dryRun,
      verbose: verbose,
      revert: revert,
      fileSystem: plugin.fileSystem,
    );

    return [toolsFile, binFile];
  }

  /// Resolves the Dart package name from pubspec.yaml (looking for
  /// `name: <name>`), falling back to `'my_app'` when no pubspec
  /// is found (e.g. in tests on a temp directory). Reads pubspec.yaml
  /// through plugin.fileSystem so the lookup shares the generated
  /// files' root.
  Future<String> _resolvePackageName(Map<String, dynamic> args) async {
    final explicit = args['name'] as String?;
    if (explicit != null && explicit.isNotEmpty) return explicit;

    final pubspecPath = 'pubspec.yaml';
    if (await plugin.fileSystem.exists(pubspecPath)) {
      final content = await plugin.fileSystem.read(pubspecPath);
      final match = RegExp(
        r'^name:\s*([A-Za-z][A-Za-z0-9_]*)',
        multiLine: true,
      ).firstMatch(content);
      if (match != null) return match.group(1)!;
    }
    return 'my_app';
  }

  /// Platform-agnostic path joiner. Uses `path` package semantics
  /// without importing it (the capability is pure Dart and the
  /// project convention is forward slashes in lib/ and bin/).
  String _joinPath(String a, String b, String c) => '$a/$b/$c';
}
