// GENERATED - DO NOT EDIT
// Generated by zfa for: ListingOffer
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/listing_offer/listing_offer.dart';
import '../../repositories/listing_offer_repository.dart';

class UpdateListingOfferUseCase
    extends UseCase<ListingOffer, UpdateParams<String, ListingOfferPatch>> {
  UpdateListingOfferUseCase(this._repository);

  final ListingOfferRepository _repository;

  @override
  Future<ListingOffer> execute(
    UpdateParams<String, ListingOfferPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
