import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/zfa_cli.dart' as cli;

/// SPEC 1127, order 5 — `zfa service create --explain`.
///
/// Explains WHAT will be generated and WHY — the service shape (class,
/// file path, knobs), the provider binding (from the per-entity provider
/// receipts, then the conventional provider file), and the methods the
/// grammar will create — without running generation and without writing
/// anything. With `--json` the explanation rides the canonical envelope
/// (verdict `skip` — a pure explanation executes nothing).
void main() {
  late Directory workspace;
  late String outputDir;

  setUp(() async {
    workspace = await Directory.systemTemp.createTemp('zfa_service_explain_');
    outputDir = p.join(workspace.path, 'lib', 'src');
    await Directory(outputDir).create(recursive: true);
    await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: zuraffa_service_explain_test
environment:
  sdk: ^3.11.0
''');
    exitCode = 0;
  });

  tearDown(() {
    exitCode = 0;
    if (workspace.existsSync()) {
      try {
        workspace.deleteSync(recursive: true);
      } on PathNotFoundException {
        // Already gone.
      }
    }
  });

  Future<String> zfa(List<String> args) =>
      cli.runCapturing(['-C', workspace.path, ...args]);

  group('zfa service create --explain', () {
    test(
      'describes the service shape and methods without generating',
      () async {
        final output = await zfa([
          'service',
          'create',
          'SendEmail',
          '--params',
          'EmailParams',
          '--returns',
          'SendResult',
          '--explain',
        ]);

        expect(output, contains('SendEmailService'));
        expect(output, contains('send_email_service.dart'));
        expect(output, contains('sendEmail'));
        expect(output, contains('usecase'));
        // Nothing was generated by an explain run.
        expect(
          File(
            p.join(outputDir, 'domain', 'services', 'send_email_service.dart'),
          ).existsSync(),
          isFalse,
          reason: '--explain must not generate',
        );
        expect(exitCode, equals(0));
      },
    );

    test('reports the provider binding when one exists', () async {
      // Generate a service, then a provider bound to it.
      await zfa(['service', 'create', 'Payment', '--returns', 'Receipt']);
      await zfa([
        'provider',
        'create',
        '--name',
        'Payment',
        '--returns',
        'Receipt',
      ]);

      final output = await zfa([
        'service',
        'create',
        'Payment',
        '--returns',
        'Receipt',
        '--explain',
      ]);

      expect(
        output,
        contains('PaymentProvider'),
        reason: 'the explain surface must name the bound provider:\n$output',
      );
    });

    test(
      '--explain --json rides the canonical envelope (verdict skip)',
      () async {
        final output = await zfa([
          'service',
          'create',
          'Audit',
          '--returns',
          'Audit',
          '--explain',
          '--json',
        ]);

        Map<String, dynamic>? decoded;
        for (final line in output.split('\n')) {
          final trimmed = line.trim();
          if (!trimmed.startsWith('{')) continue;
          try {
            final value = jsonDecode(trimmed);
            if (value is Map<String, dynamic>) decoded = value;
          } catch (_) {}
        }
        expect(decoded, isNotNull, reason: output);
        expect(decoded!['schema'], equals('zuraffa.verdict.v1'));
        expect(decoded['verdict'], equals('skip'));
        expect(decoded['exit_class'], equals(0));
        final details = decoded['details'] as Map;
        expect(details['serviceClass'], equals('AuditService'));
        expect(decoded['explain'], isA<Map>());
        // Nothing generated.
        expect(
          File(
            p.join(outputDir, 'domain', 'services', 'audit_service.dart'),
          ).existsSync(),
          isFalse,
        );
      },
    );
  });
}
