/// Public surface of the `notes_package` package.
///
/// The scaffold starts with the runtime module (lifecycle entry point) and
/// the package registrar (auto-DI registration unit); as architecture is
/// generated, the package author exports the public domain surface here —
/// consuming apps import ONLY this barrel (spec 025).
library;

export 'src/module/notes_package_package_module.dart';
export 'src/di/notes_package_package_registrar.dart';

// Public domain surface (generated by `zfa entity create` + `zfa make`).
export 'src/domain/entities/note/note.dart';
export 'src/domain/repositories/note_repository.dart';
export 'src/domain/usecases/note/get_note_usecase.dart';
export 'src/domain/usecases/note/toggle_note_usecase.dart';
export 'src/domain/usecases/note/update_note_usecase.dart';
export 'src/data/datasources/note/note_datasource.dart';
export 'src/data/datasources/note/note_mock_datasource.dart';
export 'src/data/datasources/note/note_remote_datasource.dart';
