// GENERATED - DO NOT EDIT
// Generated by zfa for: Note
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/note/note.dart';
import '../../repositories/note_repository.dart';

class GetNoteUseCase extends UseCase<Note, QueryParams<Note>> {
  GetNoteUseCase(this._repository);

  final NoteRepository _repository;

  @override
  Future<Note> execute(
    QueryParams<Note> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
