// GENERATED - DO NOT EDIT
// Generated by zfa for: Note
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/note/note.dart';
import '../../repositories/note_repository.dart';

class ToggleNoteUseCase
    extends UseCase<Note, ToggleParams<String, Field<Note, dynamic>>> {
  ToggleNoteUseCase(this._repository);

  final NoteRepository _repository;

  @override
  Future<Note> execute(
    ToggleParams<String, Field<Note, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
