// GENERATED - DO NOT EDIT
// Generated by zfa for: TextSpark
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/text_spark/text_spark.dart';
import '../../mock/text_spark_mock_data.dart';
import 'text_spark_datasource.dart';

/// Mock data source for TextSpark
class TextSparkMockDataSource
    with Loggable, FailureHandler
    implements TextSparkDataSource {
  TextSparkMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<TextSpark> get(QueryParams<TextSpark> params) async {
    logger.info('Getting TextSpark with params: $params');
    await Future.delayed(_delay);
    final item = TextSparkMockData.textSparks.query(params);
    logger.info('Successfully retrieved TextSpark');
    return item;
  }

  @override
  Future<TextSpark> update(UpdateParams<String, TextSparkPatch> params) async {
    logger.info('Updating TextSpark: ${params.id}');
    await Future.delayed(_delay);
    final existing = TextSparkMockData.sampleTextSpark;
    logger.info('Successfully updated TextSpark');
    return existing;
  }

  @override
  Future<TextSpark> toggle(
    ToggleParams<String, Field<TextSpark, dynamic>> params,
  ) async {
    logger.info('Toggling TextSpark: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = TextSparkMockData.sampleTextSpark;
    logger.info('Successfully toggled TextSpark');
    return existing;
  }
}

// END GENERATED
