// GENERATED - DO NOT EDIT
// Generated by zfa for: Note
import '../../domain/entities/note/note.dart';

/// Mock data for Note
class NoteMockData {
  static final List<Note> notes = [
    Note(id: 'id 1', body: 'body 1'),
    Note(id: 'id 2', body: 'body 2'),
    Note(id: 'id 3', body: 'body 3'),
  ];

  static Note get sampleNote => notes.first;

  static List<Note> get sampleList => notes;

  static List<Note> get emptyList => <Note>[];

  static List<Note> get largeNoteList =>
      List.generate(100, (index) => _createNote(index + 1000));

  static Note _createNote(int seed) {
    return Note(id: 'id $seed', body: 'body $seed');
  }
}

// END GENERATED
