// Generated by zfa for: AppNotification
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'app_notification_controller.dart';
import 'app_notification_presenter.dart';

class AppNotificationView extends CleanView {
  const AppNotificationView({super.key, super.routeObserver});

  @override
  State<AppNotificationView> createState() {
    return _AppNotificationViewState(
      AppNotificationController(AppNotificationPresenter()),
    );
  }
}

class _AppNotificationViewState
    extends
        CleanViewState<AppNotificationView, AppNotificationController, void> {
  _AppNotificationViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('AppNotification')),
      body: ControlledWidgetBuilder<AppNotificationController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
