// Generated by zfa
// zfa generate Todo --methods=update --test

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:zuraffa/zuraffa.dart';
import 'package:example/src/domain/entities/todo/todo.dart';
import 'package:example/src/domain/repositories/todo_repository.dart';
import 'package:example/src/domain/usecases/todo/update_todo_usecase.dart';

class MockTodoRepository extends Mock implements TodoRepository {}

class MockTodo extends Mock implements Todo {}

void main() {
  late UpdateTodoUseCase useCase;
  late MockTodoRepository mockRepository;

  setUp(() {
    registerFallbackValue(
        UpdateParams<int, TodoPatch>(id: 1, data: TodoPatch()));
    mockRepository = MockTodoRepository();
    useCase = UpdateTodoUseCase(mockRepository);
  });

  group('UpdateTodoUseCase', () {
    final tTodo = MockTodo();

    test('should call repository.update and return result', () async {
      // Arrange
      when(() => mockRepository.update(any())).thenAnswer((_) async => tTodo);

      // Act
      final result =
          await useCase(UpdateParams<int, TodoPatch>(id: 1, data: TodoPatch()));

      // Assert
      verify(() => mockRepository.update(any())).called(1);
      expect(result.isSuccess, true);
      expect(result.getOrElse(() => throw Exception()), equals(tTodo));
    });

    test('should return Failure when repository throws', () async {
      // Arrange
      final exception = Exception('Error');
      when(() => mockRepository.update(any())).thenThrow(exception);

      // Act
      final result =
          await useCase(UpdateParams<int, TodoPatch>(id: 1, data: TodoPatch()));

      // Assert
      verify(() => mockRepository.update(any())).called(1);
      expect(result.isFailure, true);
    });
  });
}
