// Auto-generated by Zorphy
// Generated at: 2026-08-14T10:19:17.852024

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'barcode_spark.zorphy.dart';
part 'barcode_spark.g.dart';

/// BarcodeSpark entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $BarcodeSpark {
  String get id;
  String get barcode;
  String? get sourceChannel;
}
