name: example
description: >-
  Example app demonstrating Zuraffa Clean Architecture with
  Zorphy v2.1 entity generation.

publish_to: none
version: 7.0.0

environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  zuraffa:
    path: ../

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4
  hive_ce_generator: ^1.11.1
  build_runner: ^2.16.0

dependency_overrides:
  meta: ^1.19.0
  test_api: ^0.7.9
  analyzer: 14.1.0
  zorphy:
    path: ../../zorphy/zorphy
  zorphy_annotation:
    path: ../../zorphy/zorphy_annotation
