// GENERATED - DO NOT EDIT
// Generated by zfa for: WalkthroughStep
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/walkthrough_step/walkthrough_step.dart';
import '../../mock/walkthrough_step_mock_data.dart';
import 'walkthrough_step_datasource.dart';

/// Mock data source for WalkthroughStep
class WalkthroughStepMockDataSource
    with Loggable, FailureHandler
    implements WalkthroughStepDataSource {
  WalkthroughStepMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<WalkthroughStep> get(QueryParams<WalkthroughStep> params) async {
    logger.info('Getting WalkthroughStep with params: $params');
    await Future<void>.delayed(_delay);
    final item = WalkthroughStepMockData.walkthroughSteps.query(params);
    logger.info('Successfully retrieved WalkthroughStep');
    return item;
  }

  @override
  Future<WalkthroughStep> update(
    UpdateParams<String, WalkthroughStepPatch> params,
  ) async {
    logger.info('Updating WalkthroughStep: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = WalkthroughStepMockData.walkthroughSteps.firstWhere(
      (item) => item.id == params.id,
      orElse: () =>
          throw notFoundFailure('WalkthroughStep not found in mock data'),
    );
    final updated = params.data.applyTo(existing);
    final index = WalkthroughStepMockData.walkthroughSteps.indexOf(existing);
    WalkthroughStepMockData.walkthroughSteps[index] = updated;
    logger.info('Successfully updated WalkthroughStep');
    return updated;
  }

  @override
  Future<WalkthroughStep> toggle(
    ToggleParams<String, Field<WalkthroughStep, dynamic>> params,
  ) async {
    logger.info(
      'Toggling WalkthroughStep: ${params.id} on field ${params.field}',
    );
    await Future<void>.delayed(_delay);
    final existing = WalkthroughStepMockData.walkthroughSteps.firstWhere(
      (item) => item.id == params.id,
      orElse: () =>
          throw notFoundFailure('WalkthroughStep not found in mock data'),
    );
    final updated = existing.copyWithField(params.field, params.value);
    final index = WalkthroughStepMockData.walkthroughSteps.indexOf(existing);
    WalkthroughStepMockData.walkthroughSteps[index] = updated;
    logger.info('Successfully toggled WalkthroughStep');
    return updated;
  }
}

// END GENERATED
