import 'package:code_builder/code_builder.dart';

import '../../../core/builder/shared/spec_library.dart';
import '../../../utils/string_utils.dart';

/// Builds the route module file for a deep link
/// (`zfa route deep-link <Name> --path <path> --scheme <scheme>`).
///
/// The generated file mirrors the shape of an entity-routes module so
/// the existing `RouteBuilder._regenerateIndexFile` auto-discovery
/// picks it up and aggregates it inside `getAllRoutes()` without any
/// changes to the index regenerator:
///
/// ```dart
/// // lib/src/routing/<name>_routes.dart
/// import 'package:go_router/go_router.dart';
/// import 'package:flutter/material.dart';
/// import 'package:zuraffa/zuraffa.dart';
///
/// abstract class <Name>Routes {
///   static const String <nameCamel> = '<path>';
/// }
///
/// List<GoRoute> <nameCamel>Routes() {
///   return [
///     GoRoute(
///       path: <Name>Routes.<nameCamel>,
///       name: '<name_snake>',
///       builder: (context, state) => const SizedBox.shrink(),
///     ),
///   ];
/// }
/// ```
///
/// When a [view] is supplied (and the caller has already
/// verified the corresponding view file exists on disk), the builder
/// returns that view instead of the placeholder `SizedBox.shrink()`.
class DeepLinkRoutesBuilder {
  final SpecLibrary specLibrary;
  final DartEmitter emitter;

  DeepLinkRoutesBuilder({
    this.specLibrary = const SpecLibrary(),
    DartEmitter? emitter,
  }) : emitter =
           emitter ??
           DartEmitter(orderDirectives: true, useNullSafetySyntax: true);

  /// Builds the deep-link route module source.
  ///
  /// - [namePascal]: e.g. `ScanBarcode` — used for the class name
  ///   (`ScanBarcodeRoutes`) and the routes getter (`scanBarcodeRoutes`).
  /// - [path]: e.g. `/scan/barcode/:barcode`.
  /// - [nameSnake]: e.g. `scan_barcode` — used as the GoRoute `name`.
  /// - [view]: optional target view class name. When `null`,
  ///   the route builder emits `const SizedBox.shrink()` so the app
  ///   still compiles before the user wires a real view.
  String buildFile({
    required String namePascal,
    required String nameCamel,
    required String nameSnake,
    required String path,
    String? view,
    String? leadingComment,
  }) {
    final className = '${namePascal}Routes';
    final routeConstantName = nameCamel;
    final routeName = nameSnake;

    final routesClass = Class(
      (c) => c
        ..name = className
        ..fields.add(
          Field(
            (f) => f
              ..name = routeConstantName
              ..static = true
              ..modifier = FieldModifier.constant
              ..type = refer('String')
              ..assignment = literalString(path).code,
          ),
        ),
    );

    final pathExpr = refer(className).property(routeConstantName);
    final nameExpr = literalString(routeName);

    final builderBody = view == null
        ? const Code('const SizedBox.shrink()')
        : refer(view).constInstance([]).code;

    final goRoute = refer('GoRoute').call([], {
      'path': pathExpr,
      'name': nameExpr,
      'builder': Method(
        (m) => m
          ..requiredParameters.addAll([
            Parameter((p) => p..name = 'context'),
            Parameter((p) => p..name = 'state'),
          ])
          ..lambda = true
          ..body = builderBody,
      ).closure,
    });

    final getter = Method(
      (m) => m
        ..name = '${nameCamel}Routes'
        ..returns = refer('List<GoRoute>')
        ..body = literalList([goRoute]).returned.statement,
    );

    final directives = <Directive>[
      Directive.import('package:go_router/go_router.dart'),
      Directive.import('package:flutter/material.dart'),
      Directive.import('package:zuraffa/zuraffa.dart'),
    ];

    final library = specLibrary.library(
      specs: [routesClass, getter],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment: leadingComment ??
          '// Generated by zfa for deep-link: $namePascal',
    );
  }

  /// Validates that [namePascal] is a non-empty Dart identifier and
  /// that [path] starts with `/`. Throws [ArgumentError] otherwise.
  static void validate({
    required String namePascal,
    required String path,
    required String scheme,
  }) {
    if (!RegExp(r'^[A-Z][A-Za-z0-9]*$').hasMatch(namePascal)) {
      throw ArgumentError.value(
        namePascal,
        'name',
        'must be a PascalCase identifier (e.g. ScanBarcode)',
      );
    }
    if (!path.startsWith('/')) {
      throw ArgumentError.value(path, 'path', 'must start with "/"');
    }
    if (!RegExp(r'^[a-z][a-z0-9+.\-]*$').hasMatch(scheme)) {
      throw ArgumentError.value(
        scheme,
        'scheme',
        'must be a lowercase URL scheme (e.g. gozuzu, https, my-app)',
      );
    }
  }

  /// Returns the camelCase route constant name derived from a
  /// PascalCase name (`ScanBarcode` → `scanBarcode`).
  static String pascalToCamel(String pascal) =>
      StringUtils.pascalToCamel(pascal);

  /// Returns the snake_case form derived from a PascalCase name
  /// (`ScanBarcode` → `scan_barcode`).
  static String pascalToSnake(String pascal) =>
      StringUtils.camelToSnake(pascal);
}
