import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

import '../../../core/builder/shared/spec_library.dart';
import '../../../utils/string_utils.dart';

/// Branch spec for a `StatefulShellRoute.indexedStack` shell.
///
/// Each branch becomes one `StatefulShellBranch` whose single child `GoRoute`
/// lives at [path] and renders [view] (or `const SizedBox.shrink()` when
/// [view] is null). The [label] and [icon] are surfaced in the bottom nav
/// `NavigationBar.destinations` and the desktop `NavigationRail.destinations`
/// when `--bottom-nav` / `--adaptive` is requested.
class ShellBranchSpec {
  final String label;
  final String path;
  final String? view;
  final String? icon;

  const ShellBranchSpec({
    required this.label,
    required this.path,
    this.view,
    this.icon,
  });
}

/// `zfa route shell <name> --branch <Label>:<path> ... [--bottom-nav|--rail]
/// [--adaptive]`
///
/// Emits `lib/src/routing/<name_snake>_shell.dart` containing:
///
/// 1. A `<Name>Shell` `StatelessWidget` wrapping a `StatefulNavigationShell`:
///    - `--bottom-nav` (default): `Scaffold(body: navigationShell,
///      bottomNavigationBar: NavigationBar(...))` with one
///      `NavigationDestination` per branch (Material 3).
///    - `--adaptive`: also emits `<Name>ShellDesktop` with a
///      `NavigationRail` variant for desktop layouts.
/// 2. A top-level getter `<nameCamel>ShellRoute()` returning
///    `List<RouteBase>` containing a single
///    `StatefulShellRoute.indexedStack` whose `branches:` list has one
///    `StatefulShellBranch` per `--branch` argument. Each branch holds a
///    placeholder `GoRoute(path: <path>, builder: ... => SizedBox.shrink())`
///    so the shell compiles even when no entity route exists at that path
///    yet. Existing entity routes at the same path are still discovered by
///    `RouteBuilder._regenerateIndexFile` and merged into `getAllRoutes()`
///    — the shell's placeholder `GoRoute` only fires when no real route
///    claims the branch root.
///
/// The shell file follows the `*_shell.dart` naming convention so the
/// existing index regenerator (extended in this PR to also scan for
/// `*_shell.dart`) auto-discovers it and spreads the result of
/// `<nameCamel>ShellRoute()` into `getAllRoutes()`. The return type of
/// `getAllRoutes()` changes from `List<GoRoute>` to `List<RouteBase>` so
/// `StatefulShellRoute` is acceptable (Dart list covariance keeps the
/// existing `...entityRoutes()` spreads valid).
class ShellRoutesBuilder {
  final SpecLibrary specLibrary;

  const ShellRoutesBuilder({this.specLibrary = const SpecLibrary()});

  /// Builds the shell route module source.
  ///
  /// - [namePascal]: e.g. `Main` — drives the class name `MainShell` and
  ///   the getter `mainShellRoute()`.
  /// - [branches]: one entry per `--branch Label:/path` flag.
  /// - [bottomNav]: when `true` (default), `<Name>Shell` renders a Material
  ///   3 `NavigationBar` bound to `navigationShell.currentIndex` +
  ///   `onTap: navigationShell.goBranch`.
  /// - [adaptive]: when `true`, also emits `<Name>ShellDesktop` with a
  ///   `NavigationRail` for wide layouts.
  String buildFile({
    required String namePascal,
    required List<ShellBranchSpec> branches,
    bool bottomNav = true,
    bool adaptive = false,
    String? leadingComment,
  }) {
    ShellRoutesBuilder.validate(namePascal: namePascal, branches: branches);

    final nameCamel = StringUtils.pascalToCamel(namePascal);
    final className = '${namePascal}Shell';
    final getterName = '${nameCamel}ShellRoute';

    final specs = <Spec>[];

    // --- <Name>Shell widget ---
    specs.add(
      _buildShellClass(
        className: className,
        branches: branches,
        bottomNav: bottomNav,
      ),
    );

    // --- <Name>ShellDesktop (adaptive) ---
    if (adaptive) {
      specs.add(
        _buildDesktopShellClass(
          className: '${namePascal}ShellDesktop',
          branches: branches,
        ),
      );
    }

    // --- <nameCamel>ShellRoute() getter ---
    specs.add(
      _buildShellRouteGetter(
        getterName: getterName,
        namePascal: namePascal,
        branches: branches,
        adaptive: adaptive,
      ),
    );

    final directives = <Directive>[
      Directive.import('package:flutter/material.dart'),
      Directive.import('package:go_router/go_router.dart'),
    ];

    final library = specLibrary.library(
      specs: specs,
      directives: directives,
    );

    final raw = specLibrary.emitLibrary(
      library,
      leadingComment: leadingComment ??
          '// Generated by zfa for shell: $namePascal '
          '(${branches.length} branches)',
      // The shell file is meant to be edited by the user (they swap the
      // placeholder builders for real views), so do NOT wrap with
      // GENERATED markers — keep it editable.
      wrapWithGeneratedMarkers: false,
    );

    // The SpecLibrary already formats via DartFormatter when format=true
    // (default), but be defensive and re-format in case the caller
    // suppressed formatting upstream.
    try {
      return DartFormatter(
        languageVersion: DartFormatter.latestLanguageVersion,
      ).format(raw);
    } catch (_) {
      return raw;
    }
  }

  Class _buildShellClass({
    required String className,
    required List<ShellBranchSpec> branches,
    required bool bottomNav,
  }) {
    return Class(
      (c) => c
        ..name = className
        ..extend = refer('StatelessWidget')
        ..constructors.add(
          Constructor(
            (ctor) => ctor
              ..constant = true
              ..optionalParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'key'
                    ..named = true
                    ..toSuper = true,
                ),
              )
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'navigationShell'
                    ..type = refer('StatefulNavigationShell'),
                ),
              ),
          ),
        )
        ..fields.add(
          Field(
            (f) => f
              ..name = 'navigationShell'
              ..modifier = FieldModifier.final$
              ..type = refer('StatefulNavigationShell'),
          ),
        )
        ..methods.add(
          Method(
            (m) => m
              ..name = 'build'
              ..annotations.add(refer('override'))
              ..returns = refer('Widget')
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'context'
                    ..type = refer('BuildContext'),
                ),
              )
              ..body = _buildShellBuildBody(
                branches: branches,
                bottomNav: bottomNav,
              ),
          ),
        ),
    );
  }

  Code _buildShellBuildBody({
    required List<ShellBranchSpec> branches,
    required bool bottomNav,
  }) {
    if (!bottomNav) {
      // No nav bar — just render the navigationShell.
      return refer('Scaffold').call([], {
        'body': refer('navigationShell'),
      }).returned.statement;
    }

    final destinations = literalList(
      branches.map(
        (b) => refer('NavigationDestination').newInstance([], {
          'icon': refer('Icon').constInstance([
            refer(b.icon ?? 'Icons.widgets'),
          ]),
          'label': literalString(b.label),
        }),
      ),
    );

    return refer('Scaffold').call([], {
      'body': refer('navigationShell'),
      'bottomNavigationBar': refer('NavigationBar').call([], {
        'selectedIndex': refer('navigationShell').property('currentIndex'),
        'onDestinationSelected': Method(
          (m) => m
            ..requiredParameters.add(
              Parameter((p) => p..name = 'index'),
            )
            ..lambda = true
            ..body = refer('navigationShell')
                .property('goBranch')
                .call([
                  refer('index'),
                ], {
                  'initialLocation':
                      refer('index')
                          .equalTo(refer('navigationShell').property('currentIndex')),
                })
                .code,
        ).closure,
        'destinations': destinations,
      }),
    }).returned.statement;
  }

  Class _buildDesktopShellClass({
    required String className,
    required List<ShellBranchSpec> branches,
  }) {
    return Class(
      (c) => c
        ..name = className
        ..extend = refer('StatelessWidget')
        ..constructors.add(
          Constructor(
            (ctor) => ctor
              ..constant = true
              ..optionalParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'key'
                    ..named = true
                    ..toSuper = true,
                ),
              )
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'navigationShell'
                    ..type = refer('StatefulNavigationShell'),
                ),
              ),
          ),
        )
        ..fields.add(
          Field(
            (f) => f
              ..name = 'navigationShell'
              ..modifier = FieldModifier.final$
              ..type = refer('StatefulNavigationShell'),
          ),
        )
        ..methods.add(
          Method(
            (m) => m
              ..name = 'build'
              ..annotations.add(refer('override'))
              ..returns = refer('Widget')
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'context'
                    ..type = refer('BuildContext'),
                ),
              )
              ..body = _buildDesktopShellBuildBody(branches: branches),
          ),
        ),
    );
  }

  Code _buildDesktopShellBuildBody({
    required List<ShellBranchSpec> branches,
  }) {
    final destinations = literalList(
      branches.map(
        (b) => refer('NavigationRailDestination').newInstance([], {
          'icon': refer('Icon').constInstance([
            refer(b.icon ?? 'Icons.widgets'),
          ]),
          'label': literalString(b.label),
        }),
      ),
    );

    return refer('Scaffold').call([], {
      'body': refer('Row').call([], {
        'children': literalList([
          refer('NavigationRail').call([], {
            'selectedIndex': refer('navigationShell').property('currentIndex'),
            'onDestinationSelected': Method(
              (m) => m
                ..requiredParameters.add(
                  Parameter((p) => p..name = 'index'),
                )
                ..lambda = true
                ..body = refer('navigationShell')
                    .property('goBranch')
                    .call([refer('index')])
                    .code,
            ).closure,
            'destinations': destinations,
          }),
          refer('Expanded').call([], {
            'child': refer('navigationShell'),
          }),
        ]),
      }),
    }).returned.statement;
  }

  Method _buildShellRouteGetter({
    required String getterName,
    required String namePascal,
    required List<ShellBranchSpec> branches,
    required bool adaptive,
  }) {
    final branchExprs = branches.map((b) {
      final builderBody = b.view == null
          ? const Code('const SizedBox.shrink()')
          : refer(b.view!).constInstance([]).code;
      final goRoute = refer('GoRoute').call([], {
        'path': literalString(b.path),
        'name': literalString('${namePascal.toLowerCase()}_${b.label.toLowerCase()}'),
        'builder': Method(
          (m) => m
            ..requiredParameters.addAll([
              Parameter((p) => p..name = 'context'),
              Parameter((p) => p..name = 'state'),
            ])
            ..lambda = true
            ..body = builderBody,
        ).closure,
      });
      return refer('StatefulShellBranch').newInstance([], {
        'routes': literalList([goRoute]),
      });
    });

    final shellBuilderBody = adaptive
        ? refer('LayoutBuilder').newInstance([], {
            'builder': Method(
              (m) => m
                ..requiredParameters.addAll([
                  Parameter((p) => p..name = 'context'),
                  Parameter((p) => p..name = 'constraints'),
                ])
                ..body = Block(
                  (b) => b
                    ..statements.add(
                      declareFinal('isDesktop')
                          .assign(
                            refer('constraints')
                                .property('maxWidth')
                                .greaterThan(literalNum(600)),
                          )
                          .statement,
                    )
                    ..statements.add(
                      refer('isDesktop')
                          .conditional(
                            refer('${namePascal}ShellDesktop').newInstance([], {
                              'navigationShell': refer('navigationShell'),
                            }),
                            refer('${namePascal}Shell').newInstance([], {
                              'navigationShell': refer('navigationShell'),
                            }),
                          )
                          .returned
                          .statement,
                    ),
                ),
            ).closure,
          })
        : refer('${namePascal}Shell').newInstance([], {
            'navigationShell': refer('navigationShell'),
          });

    final statefulShellRoute = refer(
      'StatefulShellRoute',
    ).property('indexedStack').call([], {
      'builder': Method(
        (m) => m
          ..requiredParameters.addAll([
            Parameter((p) => p..name = 'context'),
            Parameter((p) => p..name = 'state'),
            Parameter((p) => p..name = 'navigationShell'),
          ])
          ..lambda = true
          ..body = shellBuilderBody.code,
      ).closure,
      'branches': literalList(branchExprs.toList()),
    });

    return Method(
      (m) => m
        ..name = getterName
        ..returns = refer('List<RouteBase>')
        ..body = literalList([statefulShellRoute]).returned.statement,
    );
  }

  /// Validates the shell spec:
  /// - [namePascal] must be a PascalCase identifier.
  /// - [branches] must be non-empty.
  /// - Each branch's [path] must start with `/`.
  /// - Each branch's [label] must be a non-empty string.
  static void validate({
    required String namePascal,
    required List<ShellBranchSpec> branches,
  }) {
    if (!RegExp(r'^[A-Z][A-Za-z0-9]*$').hasMatch(namePascal)) {
      throw ArgumentError.value(
        namePascal,
        'name',
        'must be a PascalCase identifier (e.g. Main, App)',
      );
    }
    if (branches.isEmpty) {
      throw ArgumentError.value(
        branches,
        'branches',
        'at least one --branch <Label>:<path> is required',
      );
    }
    for (var i = 0; i < branches.length; i++) {
      final b = branches[i];
      if (b.label.isEmpty) {
        throw ArgumentError.value(
          b.label,
          'branches[$i].label',
          'must be a non-empty label',
        );
      }
      if (!b.path.startsWith('/')) {
        throw ArgumentError.value(
          b.path,
          'branches[$i].path',
          'must start with "/"',
        );
      }
    }
  }

  /// Parses a `--branch <Label>:<path>` argument into a [ShellBranchSpec].
  /// Accepts an optional third colon-separated segment as the icon name:
  /// `Home:/home:Icons.home`.
  static ShellBranchSpec parseBranchArg(String raw) {
    final parts = raw.split(':');
    if (parts.length < 2 || parts[0].isEmpty || parts[1].isEmpty) {
      throw ArgumentError.value(
        raw,
        'branch',
        'must be <Label>:<path> (e.g. Home:/home)',
      );
    }
    return ShellBranchSpec(
      label: parts[0],
      path: parts[1],
      icon: parts.length >= 3 && parts[2].isNotEmpty ? parts[2] : null,
    );
  }
}
