// GENERATED - DO NOT EDIT
// Generated by zfa for: AppNotification
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/app_notification/app_notification.dart';
import '../../mock/app_notification_mock_data.dart';
import 'app_notification_datasource.dart';

/// Mock data source for AppNotification
class AppNotificationMockDataSource
    with Loggable, FailureHandler
    implements AppNotificationDataSource {
  AppNotificationMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<AppNotification> get(QueryParams<AppNotification> params) async {
    logger.info('Getting AppNotification with params: $params');
    await Future<void>.delayed(_delay);
    final item = AppNotificationMockData.appNotifications.query(params);
    logger.info('Successfully retrieved AppNotification');
    return item;
  }

  @override
  Future<AppNotification> update(
    UpdateParams<String, AppNotificationPatch> params,
  ) async {
    logger.info('Updating AppNotification: ${params.id}');
    await Future<void>.delayed(_delay);
    final existing = AppNotificationMockData.appNotifications.firstWhere(
      (item) => item.id == params.id,
      orElse: () =>
          throw notFoundFailure('AppNotification not found in mock data'),
    );
    final updated = params.data.applyTo(existing);
    final index = AppNotificationMockData.appNotifications.indexOf(existing);
    AppNotificationMockData.appNotifications[index] = updated;
    logger.info('Successfully updated AppNotification');
    return updated;
  }

  @override
  Future<AppNotification> toggle(
    ToggleParams<String, Field<AppNotification, dynamic>> params,
  ) async {
    logger.info(
      'Toggling AppNotification: ${params.id} on field ${params.field}',
    );
    await Future<void>.delayed(_delay);
    final existing = AppNotificationMockData.appNotifications.firstWhere(
      (item) => item.id == params.id,
      orElse: () =>
          throw notFoundFailure('AppNotification not found in mock data'),
    );
    final updated = existing.copyWithField(params.field, params.value);
    final index = AppNotificationMockData.appNotifications.indexOf(existing);
    AppNotificationMockData.appNotifications[index] = updated;
    logger.info('Successfully toggled AppNotification');
    return updated;
  }
}

// END GENERATED
