// EPIC 3 / issue #1134, lane 2 — the view-generation contract: the
// shared seam the two view generators consult (the FIRST code they
// share, deliberately). The mainline `zfa view` ported the
// deterministic contract from `zfa tdd view` (the already-implemented
// verdict + the machine summary line), and the fence classifies a
// target file by ownership: a `zfa tdd view` subject is never silently
// clobbered by the mainline generator.
//
//  U-1134-v1: inspect() classifies the four file kinds by marker —
//             the mainline generation marker, the tdd subject doc
//             comment, hand-written (neither), and absent/empty.
//  U-1134-v2: machineSummary() renders the deterministic machine line
//             `view: entity=<n> outcome=<o> files=<n>` — same inputs,
//             same bytes (the contract pipelines grep for).
library;

import 'package:test/test.dart';
import 'package:zuraffa/src/tdd/services/view_generation_contract.dart';

void main() {
  test('U-1134-v1: inspect classifies by ownership marker', () {
    // Absent / empty → notFound.
    expect(
      ViewGenerationContract.inspect(null),
      ViewFileKind.notFound,
    );
    expect(ViewGenerationContract.inspect(''), ViewFileKind.notFound);
    expect(ViewGenerationContract.inspect('  \n '), ViewFileKind.notFound);

    // The mainline generator's leading comment → generatorWritten.
    expect(
      ViewGenerationContract.inspect(
        '// Generated by zfa for: Login\n'
        "import 'package:flutter/material.dart';\n"
        'class LoginView extends CleanView {}\n',
      ),
      ViewFileKind.generatorWritten,
    );

    // The tdd view generator's subject doc comment → tddSubject (the
    // behavior-driven generator's output — the fence).
    expect(
      ViewGenerationContract.inspect(
        '/// View-builder subject for behavior A-001 (issue #939): returns\n'
        'Widget subject_a_001() => A001View();\n',
      ),
      ViewFileKind.tddSubject,
    );
    // The tdd gen STUB carries the same doc comment — same owner.
    expect(
      ViewGenerationContract.inspect(
        '/// View-builder subject for behavior A-001.\n'
        '///\n'
        '/// Throws [UnimplementedError] until the real implementation lands.\n'
        'Widget subject_a_001() => throw UnimplementedError();\n',
      ),
      ViewFileKind.tddSubject,
    );

    // Hand-written (the #1005 seam, tracked by receipt) — neither
    // marker → handWritten.
    expect(
      ViewGenerationContract.inspect(
        'class LoginView extends StatefulWidget {}\n',
      ),
      ViewFileKind.handWritten,
    );
  });

  test('U-1134-v1b: the tdd marker wins over the mainline marker '
      '(a tdd subject is a tdd subject)', () {
    expect(
      ViewGenerationContract.inspect(
        '// Generated by zfa for: Login\n'
        '/// View-builder subject for behavior A-001 (issue #939).\n',
      ),
      ViewFileKind.tddSubject,
      reason: 'a file carrying BOTH markers is the tdd generator\'s '
          'output — the stricter ownership wins, never a silent guess',
    );
  });

  test('U-1134-v2: machineSummary renders the deterministic machine '
      'line', () {
    expect(
      ViewGenerationContract.machineSummary(
        entity: 'Login',
        outcome: MainlineViewOutcome.scaffolded,
        files: 2,
      ),
      'view: entity=Login outcome=scaffolded files=2',
    );
    expect(
      ViewGenerationContract.machineSummary(
        entity: 'Login',
        outcome: MainlineViewOutcome.alreadyImplemented,
      ),
      'view: entity=Login outcome=already-implemented files=0',
    );
    expect(
      ViewGenerationContract.machineSummary(
        entity: 'Product',
        outcome: MainlineViewOutcome.error,
      ),
      'view: entity=Product outcome=error files=0',
    );
    // The outcome labels are the tdd view contract's vocabulary
    // (ViewOutcome.label) — one machine grammar across both generators.
    expect(
      [
        for (final o in MainlineViewOutcome.values) o.label,
      ],
      containsAll(['scaffolded', 'already-implemented', 'error']),
    );
  });
}
