// GENERATED - DO NOT EDIT
// Generated by zfa for: BarcodeListing
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/barcode_listing/barcode_listing.dart';
import '../../repositories/barcode_listing_repository.dart';

class ToggleBarcodeListingUseCase
    extends
        UseCase<
          BarcodeListing,
          ToggleParams<String, Field<BarcodeListing, dynamic>>
        > {
  ToggleBarcodeListingUseCase(this._repository);

  final BarcodeListingRepository _repository;

  @override
  Future<BarcodeListing> execute(
    ToggleParams<String, Field<BarcodeListing, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
