// GENERATED - DO NOT EDIT
// Generated by zfa for: BarcodeListing
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/barcode_listing/barcode_listing.dart';
import '../../repositories/barcode_listing_repository.dart';

class UpdateBarcodeListingUseCase
    extends UseCase<BarcodeListing, UpdateParams<String, BarcodeListingPatch>> {
  UpdateBarcodeListingUseCase(this._repository);

  final BarcodeListingRepository _repository;

  @override
  Future<BarcodeListing> execute(
    UpdateParams<String, BarcodeListingPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
