import 'package:path/path.dart' as path;

import '../core/context/file_system.dart';
import '../models/generator_config.dart';
import '../plugins/repository/contract/repository_contract_manifest.dart';
import 'method_extractor.dart';
import 'string_utils.dart';

/// Issue #921 — conservative source-interface guard for entity use case
/// generation.
///
/// `zfa make <Entity>` can emit entity use cases whose `execute()` calls
/// action methods that do not exist on the entity's repository/service
/// interface (for example `ToggleTaskUseCase` calling `repository.toggle(...)`
/// when `TaskRepository` was generated by a prior run with a CRUD-only
/// `--methods` set). The use case templates assume the source interface
/// carries the full method vocabulary, so the generated files do not
/// compile, the build step fails, and the make step reports
/// `outcome=regression`.
///
/// The guard filters a requested method set down to the methods actually
/// declared on the source interface file, so every generated use case
/// compiles against the interface as it exists on disk. The repository
/// plugin skips an existing interface file in a non-force run, so the file
/// on disk is authoritative at the time the use case plugin runs
/// (RepositoryPlugin is registered before UseCasePlugin, and ServicePlugin
/// resolves after it through the same registry ordering).
///
/// Fail-open by design: when the interface file does not exist (it will be
/// created by the same generation plan), cannot be parsed, or the class
/// cannot be located, the method set is returned unchanged and current
/// behavior is preserved.
class SourceInterfaceGuard {
  const SourceInterfaceGuard();

  /// Returns the subset of [methods] declared on the entity's source
  /// interface, printing a skip notice for every dropped method.
  ///
  /// Spec 0973: when a **fresh** repository contract manifest exists for
  /// the entity (`.zfa/receipts/repository-<entity>.json`, interface digest
  /// intact), its method set IS the interface contract and wins over a
  /// source parse — one source of truth. Anything else (no manifest,
  /// stale manifest, tampered method table, service interface) falls back
  /// to parsing the interface file exactly as before (issue #921
  /// fail-open behavior).
  Future<List<String>> filterMethods(
    GeneratorConfig config, {
    List<String> methods = const [],
    FileSystem? fileSystem,
  }) async {
    if (methods.isEmpty) return methods;

    final fs = fileSystem ?? const DefaultFileSystem();
    final interface = _resolveInterface(config);
    if (interface == null) return methods;

    final filePath = interface.filePath;
    var className = interface.className;

    // Contract manifest fast path (spec 0973) — repository interfaces only.
    if (!config.hasService) {
      final contract = await _loadFreshContract(config);
      if (contract != null) {
        final declared = contract.methodNames.toSet();
        className = contract.interface.className;
        return _filterAgainst(
          methods,
          declared,
          className,
          config,
        );
      }
    }

    if (!await fs.exists(filePath)) {
      // The source interface will be created by this same generation plan
      // (repository/service plugin active in the plan) or does not exist
      // yet — there is no on-disk contract to filter against.
      return methods;
    }

    final parsed = await MethodExtractor.extractMethodsFromInterface(
      filePath,
      className,
      fileSystem: fs,
    );
    if (parsed.isEmpty) {
      // Unparseable file or the referenced class was not found — fail open
      // rather than silently dropping requested use cases.
      return methods;
    }

    final declared = parsed.map((m) => m.fieldName).toSet();
    return _filterAgainst(methods, declared, className, config);
  }

  List<String> _filterAgainst(
    List<String> methods,
    Set<String> declared,
    String className,
    GeneratorConfig config,
  ) {
    final filtered = <String>[];
    for (final method in methods) {
      if (declared.contains(method)) {
        filtered.add(method);
      } else {
        print(
          "  Skip ${StringUtils.camelToSnake(method)}_${config.nameSnake} "
          "usecase: $className has no '$method' method (issue #921) — pass "
          '--methods to control the usecase set, or add \'$method\' to '
          '$className.',
        );
      }
    }
    return filtered;
  }

  /// Loads the entity's repository contract manifest when it is fresh —
  /// null otherwise (missing, stale, corrupt, or any lookup failure).
  Future<RepositoryContractManifest?> _loadFreshContract(
    GeneratorConfig config,
  ) async {
    try {
      final store = RepositoryContractManifestStore(
        projectRoot: repositoryProjectRootFor(config.outputDir),
      );
      final manifest = await store.loadForEntity(config.name);
      if (manifest == null) return null;
      return store.isFresh(manifest) ? manifest : null;
    } catch (_) {
      return null;
    }
  }

  /// Resolves the source interface the generated use cases will call
  /// through, mirroring `EntityUseCaseGenerator._generateForMethod` (class
  /// name) and the repository/service interface writers (file path).
  _SourceInterface? _resolveInterface(GeneratorConfig config) {
    if (config.hasService) {
      final serviceName = config.effectiveService;
      final serviceSnake = config.serviceSnake;
      if (serviceName == null || serviceSnake == null) return null;
      final fileName = '${serviceSnake}_service.dart';
      final filePath = config.isEntityBased
          ? path.join(
              config.outputDir,
              'domain',
              'services',
              config.effectiveDomain,
              fileName,
            )
          : path.join(config.outputDir, 'domain', 'services', fileName);
      return _SourceInterface(filePath: filePath, className: serviceName);
    }

    final repoName = config.effectiveRepos.isNotEmpty
        ? config.effectiveRepos.first
        : '${config.name}Repository';
    final filePath = path.join(
      config.outputDir,
      'domain',
      'repositories',
      '${config.nameSnake}_repository.dart',
    );
    return _SourceInterface(filePath: filePath, className: repoName);
  }
}

class _SourceInterface {
  final String filePath;
  final String className;

  const _SourceInterface({required this.filePath, required this.className});
}
