// Generated by zfa
// zfa generate Todo --methods=get,getList,watch,watchList,create,update,delete --data --cache=daily

import 'package:zuraffa/zuraffa.dart';
import '../../domain/entities/todo/todo.dart';
import '../../domain/repositories/todo_repository.dart';
import '../data_sources/todo/todo_data_source.dart';
import '../data_sources/todo/todo_local_data_source.dart';

class DataTodoRepository
    with Loggable, FailureHandler
    implements TodoRepository {
  final TodoDataSource _remoteDataSource;
  final TodoLocalDataSource _localDataSource;
  final CachePolicy _cachePolicy;

  DataTodoRepository(
    this._remoteDataSource,
    this._localDataSource,
    this._cachePolicy,
  );

  @override
  Future<Todo> get(QueryParams<Todo> params) async {
    // Check cache validity
    if (await _cachePolicy.isValid('todo_cache')) {
      try {
        return await _localDataSource.get(params);
      } catch (e) {
        logger.severe('Cache miss, fetching from remote');
      }
    }

    // Fetch from remote
    final data = await _remoteDataSource.get(params);

    // Update cache
    await _localDataSource.save(data);
    await _cachePolicy.markFresh('todo_cache');

    return data;
  }

  @override
  Future<List<Todo>> getList(ListQueryParams<Todo> params) async {
    // Include params in cache key for granular caching
    final listCacheKey = 'todo_cache_${params.hashCode}';

    // Check cache validity
    if (await _cachePolicy.isValid(listCacheKey)) {
      try {
        return await _localDataSource.getList(params);
      } catch (e) {
        logger.severe('Cache miss, fetching from remote');
      }
    }

    // Fetch from remote
    final data = await _remoteDataSource.getList(params);

    // Update cache
    await _localDataSource.saveAll(data);
    await _cachePolicy.markFresh(listCacheKey);

    return data;
  }

  @override
  Stream<Todo> watch(QueryParams<Todo> params) {
    // Stream from remote and update cache in background
    return _remoteDataSource.watch(params).map(
      (data) async {
        // Update cache in background when remote data changes
        try {
          await _localDataSource.save(data);
          await _cachePolicy.markFresh('todo_cache');
        } catch (e) {
          logger.warning('Failed to update cache: $e');
        }
        return data;
      },
    ).asyncMap((future) async => await future);
  }

  @override
  Stream<List<Todo>> watchList(ListQueryParams<Todo> params) {
    // Stream from remote and update cache in background
    return _remoteDataSource.watchList(params).map(
      (data) async {
        // Update cache in background when remote data changes
        try {
          await _localDataSource.saveAll(data);
          await _cachePolicy.markFresh('todo_cache');
        } catch (e) {
          logger.warning('Failed to update cache: $e');
        }
        return data;
      },
    ).asyncMap((future) async => await future);
  }

  @override
  Future<Todo> create(Todo todo) async {
    // Create on remote
    final created = await _remoteDataSource.create(todo);

    // Update local cache
    await _localDataSource.save(created);

    // Invalidate list cache since a new item was added
    await _cachePolicy.invalidate('todo_cache');

    return created;
  }

  @override
  Future<Todo> update(UpdateParams<Todo, TodoPatch> params) async {
    // Update on remote
    final updated = await _remoteDataSource.update(params);

    // Update local cache
    await _localDataSource.update(params);

    // Invalidate cache since data was modified
    await _cachePolicy.invalidate('todo_cache');

    return updated;
  }

  @override
  Future<void> delete(DeleteParams<Todo> params) async {
    // Delete from remote
    await _remoteDataSource.delete(params);

    // Delete from local cache
    await _localDataSource.delete(params);

    // Invalidate all cache since data was removed
    await _cachePolicy.invalidate('todo_cache');
  }
}
