// GENERATED - DO NOT EDIT
// Generated by zfa for: Todo
// zfa make Todo --methods=create,get,getList,update,delete,watch,watchList --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/todo/todo.dart';
import '../../domain/repositories/todo_repository.dart';
import '../datasources/todo/todo_datasource.dart';

class DataTodoRepository
    with Loggable, FailureHandler
    implements TodoRepository {
  DataTodoRepository(this._dataSource);

  final TodoDataSource _dataSource;

  @override
  Future<Todo> create(Todo todo) {
    return _dataSource.create(todo);
  }

  @override
  Future<Todo> get(QueryParams<Todo> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<Todo>> getList(ListQueryParams<Todo> params) {
    return _dataSource.getList(params);
  }

  @override
  Future<Todo> update(UpdateParams<int, TodoPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<void> delete(DeleteParams<int> params) {
    return _dataSource.delete(params);
  }

  @override
  Stream<Todo> watch(QueryParams<Todo> params) {
    return _dataSource.watch(params);
  }

  @override
  Stream<List<Todo>> watchList(ListQueryParams<Todo> params) {
    return _dataSource.watchList(params);
  }
}

// END GENERATED
