// Generated by zfa for: Concert
// zfa generate Concert --methods=get,getList,watch,update --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/concert/concert.dart';
import '../../domain/repositories/concert_repository.dart';
import '../datasources/concert/concert_datasource.dart';

class DataConcertRepository
    with Loggable, FailureHandler
    implements ConcertRepository {
  DataConcertRepository(this._dataSource);

  final ConcertDataSource _dataSource;

  @override
  Future<Concert> get(QueryParams<Concert> params) {
    return _dataSource.get(params);
  }

  @override
  Future<List<Concert>> getList(ListQueryParams<Concert> params) {
    return _dataSource.getList(params);
  }

  @override
  Stream<Concert> watch(QueryParams<Concert> params) {
    return _dataSource.watch(params);
  }

  @override
  Future<Concert> update(UpdateParams<String, ConcertPatch> params) {
    return _dataSource.update(params);
  }
}
