// Generated by zfa
// zfa generate Product --methods=get,watch,create,update,delete,getList,watchList --data

import 'package:zuraffa/zuraffa.dart';
import '../../domain/entities/product/product.dart';
import '../../domain/repositories/product_repository.dart';
import '../data_sources/product/product_data_source.dart';

class DataProductRepository with Loggable, FailureHandler implements ProductRepository {
  final ProductDataSource _dataSource;

  DataProductRepository(this._dataSource);

  @override
  Future<Product> get(String id) {
    return _dataSource.get(id);
  }

  @override
  Stream<Product> watch(String id) {
    return _dataSource.watch(id);
  }

  @override
  Future<Product> create(Product product) {
    return _dataSource.create(product);
  }

  @override
  Future<Product> update(UpdateParams<Partial<Product>> params) {
    return _dataSource.update(params);
  }


  @override
  Future<void> delete(DeleteParams<Product> params) {
    return _dataSource.delete(params);
  }

  @override
  Future<List<Product>> getList(ListQueryParams params) {
    return _dataSource.getList(params);
  }

  @override
  Stream<List<Product>> watchList(ListQueryParams params) {
    return _dataSource.watchList(params);
  }
}
