// GENERATED - DO NOT EDIT
// Generated by zfa for: User
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/user/user.dart';
import '../../repositories/user_repository.dart';

class UpdateUserUseCase extends UseCase<User, UpdateParams<String, UserPatch>> {
  UpdateUserUseCase(this._repository);

  final UserRepository _repository;

  @override
  Future<User> execute(
    UpdateParams<String, UserPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
