// GENERATED - DO NOT EDIT
// Generated by zfa for: ExtractedInvoice
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/extracted_invoice/extracted_invoice.dart';
import '../../repositories/extracted_invoice_repository.dart';

class UpdateExtractedInvoiceUseCase
    extends
        UseCase<ExtractedInvoice, UpdateParams<String, ExtractedInvoicePatch>> {
  UpdateExtractedInvoiceUseCase(this._repository);

  final ExtractedInvoiceRepository _repository;

  @override
  Future<ExtractedInvoice> execute(
    UpdateParams<String, ExtractedInvoicePatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
