import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../../../core/ast/append_executor.dart';
import '../../../core/ast/ast_helper.dart';
import '../../../core/ast/augmentation_builder.dart';
import '../../../core/builder/shared/spec_library.dart';
import '../../../core/generator_options.dart';
import '../../../core/plugin_system/discovery_engine.dart';
import '../../../core/context/file_system.dart';
import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/entity_analyzer.dart';
import '../../../utils/package_utils.dart';

/// Generates repository interfaces for the domain layer.
///
/// Builds abstract repository classes with method definitions derived from
/// use cases and data requirements.
class RepositoryInterfaceGenerator {
  final String outputDir;
  final GeneratorOptions options;
  final AppendExecutor appendExecutor;
  final SpecLibrary specLibrary;
  final AugmentationBuilder augmentationBuilder;
  final DiscoveryEngine discovery;
  final FileSystem fileSystem;

  RepositoryInterfaceGenerator({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    this.appendExecutor = const AppendExecutor(),
    this.specLibrary = const SpecLibrary(),
    AugmentationBuilder? augmentationBuilder,
    DiscoveryEngine? discovery,
    FileSystem? fileSystem,
  }) : augmentationBuilder =
           augmentationBuilder ?? AugmentationBuilder(outputDir: outputDir),
       fileSystem = fileSystem ?? FileSystem.create(root: outputDir),
       discovery =
           discovery ??
           DiscoveryEngine(
             projectRoot: outputDir,
             fileSystem: fileSystem ?? FileSystem.create(root: outputDir),
           );

  Future<GeneratedFile> generate(GeneratorConfig config) async {
    final repoName = '${config.name}Repository';
    final fileName = '${config.nameSnake}_repository.dart';
    final filePath = path.join(outputDir, 'domain', 'repositories', fileName);

    final methods = _buildMethods(config);
    final importPaths = _buildImportPaths(config);
    final clazz = Class(
      (b) => b
        ..name = repoName
        ..abstract = true
        ..methods.addAll(methods),
    );

    final output = specLibrary.emitLibrary(
      specLibrary.library(
        specs: [clazz],
        directives: importPaths.toSet().map(Directive.import),
      ),
      leadingComment:
          '// Generated by zfa for: ${config.name}\n// zfa generate ${config.name} --methods=${config.methods.join(',')} --repository',
    );

    if (await fileSystem.exists(filePath) &&
        (config.appendToExisting || !config.force)) {
      if (config.revert) {
        if (!config.appendToExisting) {
          return FileUtils.deleteFile(
            filePath,
            'repository',
            dryRun: options.dryRun,
            verbose: options.verbose,
            fileSystem: fileSystem,
          );
        }

        // Handle Revert for Append (remove methods from augmentation)
        await augmentationBuilder.remove(
          hostPath: filePath,
          className: repoName,
          members: methods,
          dryRun: options.dryRun,
        );

        var source = await fileSystem.read(filePath);
        final augmentFileName = path
            .basename(filePath)
            .replaceFirst('.dart', '.augment.dart');
        source = const AstHelper().removeAugment(
          source: source,
          augmentPath: augmentFileName,
        );

        if (const AstHelper().isClassEmpty(source, repoName)) {
          return FileUtils.deleteFile(
            filePath,
            'repository',
            dryRun: options.dryRun,
            verbose: options.verbose,
            fileSystem: fileSystem,
          );
        }

        return FileUtils.writeFile(
          filePath,
          source,
          'repository',
          force: true,
          dryRun: options.dryRun,
          verbose: options.verbose,
          revert: false,
          fileSystem: fileSystem,
        );
      }

      if (config.appendToExisting) {
        var source = await fileSystem.read(filePath);
        final augmentFileName = path
            .basename(filePath)
            .replaceFirst('.dart', '.augment.dart');

        // 1. Add 'import augment' to host file
        source = const AstHelper().addAugment(
          source: source,
          augmentPath: augmentFileName,
        );

        // 2. Add missing imports to host file
        for (final importPath in importPaths) {
          source = const AstHelper().addImport(
            source: source,
            importPath: importPath,
          );
        }

        await FileUtils.writeFile(
          filePath,
          source,
          'repository',
          force: true,
          dryRun: options.dryRun,
          verbose: options.verbose,
          fileSystem: fileSystem,
        );

        // 3. Generate/Update the augmentation file
        final augmentationFile = await augmentationBuilder.generate(
          hostPath: filePath,
          className: repoName,
          members: methods,
          imports: importPaths,
          dryRun: options.dryRun,
        );

        return GeneratedFile(
          path: augmentationFile.path,
          type: 'repository',
          action: 'updated',
        );
      }

      return GeneratedFile(
        path: filePath,
        type: 'repository',
        action: 'skipped',
      );
    }

    if (config.revert) {
      return FileUtils.deleteFile(
        filePath,
        'repository',
        dryRun: options.dryRun,
        verbose: options.verbose,
        fileSystem: fileSystem,
      );
    }

    return FileUtils.writeFile(
      filePath,
      output,
      'repository',
      force: options.force,
      dryRun: options.dryRun,
      verbose: options.verbose,
      revert: false,
      fileSystem: fileSystem,
    );
  }

  List<String> _buildImportPaths(GeneratorConfig config) {
    final needsZuraffaImport =
        config.methods.any(
          (method) =>
              method == 'get' ||
              method == 'watch' ||
              method == 'getList' ||
              method == 'update' ||
              method == 'delete' ||
              method == 'watchList',
        ) ||
        config.generateInit;

    final imports = <String>[];
    if (needsZuraffaImport) {
      imports.add('package:zuraffa/zuraffa.dart');
    }
    if (config.isEntityBased) {
      final entityName = config.name;
      final entitySnake = config.nameSnake;

      final isEnum = EntityAnalyzer.isEnum(
        entityName,
        outputDir,
        fileSystem: fileSystem,
      );

      if (isEnum) {
        final baseImport = PackageUtils.getBaseImport(
          outputDir,
          fileSystem: fileSystem,
        );
        imports.add('$baseImport/domain/entities/enums/index.dart');
      } else {
        final entityFile = discovery.findFileSync('$entitySnake.dart');
        if (entityFile != null) {
          final repoDir = path.dirname(
            path.join(
              outputDir,
              'domain',
              'repositories',
              '${config.nameSnake}_repository.dart',
            ),
          );
          final relativePath = path.relative(entityFile.path, from: repoDir);
          imports.add(relativePath);
        } else {
          // Fallback to package import
          final baseImport = PackageUtils.getBaseImport(
            outputDir,
            fileSystem: fileSystem,
          );
          imports.add(
            '$baseImport/domain/entities/$entitySnake/$entitySnake.dart',
          );
        }
      }
    }
    return imports;
  }

  List<Method> _buildMethods(GeneratorConfig config) {
    final methods = <Method>[];

    if (config.isCustomUseCase && config.appendToExisting) {
      final methodName = config.getRepoMethodName();
      var returnType = config.returnsType ?? 'void';
      final paramsType = config.paramsType ?? 'NoParams';

      // Wrap in Future/Stream if not already
      if (config.useCaseType == 'stream' ||
          config.useCaseType == 'streamusecase') {
        if (!returnType.startsWith('Stream<')) {
          returnType = 'Stream<$returnType>';
        }
      } else if (config.useCaseType != 'sync' &&
          config.useCaseType != 'syncusecase') {
        if (!returnType.startsWith('Future<')) {
          returnType = 'Future<$returnType>';
        }
      }

      methods.add(
        _buildMethod(
          name: methodName,
          returnType: returnType,
          paramsType: paramsType,
          paramsName: 'params',
        ),
      );
    }

    if (config.generateInit) {
      methods.add(
        Method(
          (b) => b
            ..name = 'isInitialized'
            ..type = MethodType.getter
            ..returns = refer('Stream<bool>'),
        ),
      );
      methods.add(
        Method(
          (b) => b
            ..name = 'initialize'
            ..returns = refer('Future<void>')
            ..requiredParameters.add(
              Parameter(
                (p) => p
                  ..name = 'params'
                  ..type = refer('InitializationParams'),
              ),
            ),
        ),
      );
      methods.add(
        Method(
          (b) => b
            ..name = 'dispose'
            ..returns = refer('Future<void>'),
        ),
      );
    }

    for (final method in config.methods) {
      switch (method) {
        case 'get':
          methods.add(
            _buildMethod(
              name: 'get',
              returnType: 'Future<${config.name}>',
              paramsType: 'QueryParams<${config.name}>',
              paramsName: 'params',
            ),
          );
          break;
        case 'getList':
          methods.add(
            _buildMethod(
              name: 'getList',
              returnType: 'Future<List<${config.name}>>',
              paramsType: 'ListQueryParams<${config.name}>',
              paramsName: 'params',
            ),
          );
          break;
        case 'create':
          methods.add(
            _buildMethod(
              name: 'create',
              returnType: 'Future<${config.name}>',
              paramsType: config.name,
              paramsName: config.nameCamel,
            ),
          );
          break;
        case 'update':
          // Use Patch for entity-based updates by default
          final dataType = '${config.name}Patch';
          methods.add(
            _buildMethod(
              name: 'update',
              returnType: 'Future<${config.name}>',
              paramsType: 'UpdateParams<${config.idFieldType}, $dataType>',
              paramsName: 'params',
            ),
          );
          break;
        case 'delete':
          methods.add(
            _buildMethod(
              name: 'delete',
              returnType: 'Future<void>',
              paramsType: 'DeleteParams<${config.idFieldType}>',
              paramsName: 'params',
            ),
          );
          break;
        case 'watch':
          methods.add(
            _buildMethod(
              name: 'watch',
              returnType: 'Stream<${config.name}>',
              paramsType: 'QueryParams<${config.name}>',
              paramsName: 'params',
            ),
          );
          break;
        case 'watchList':
          methods.add(
            _buildMethod(
              name: 'watchList',
              returnType: 'Stream<List<${config.name}>>',
              paramsType: 'ListQueryParams<${config.name}>',
              paramsName: 'params',
            ),
          );
          break;
      }
    }
    return methods;
  }

  Method _buildMethod({
    required String name,
    required String returnType,
    required String paramsType,
    required String paramsName,
  }) {
    return Method(
      (b) => b
        ..name = name
        ..returns = refer(returnType)
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = paramsName
              ..type = refer(paramsType),
          ),
        ),
    );
  }
}
