@Tags(['regression', 'slow'])
// Regression test for issue #335:
// https://github.com/arrrrny/zuraffa/issues/335
//
// After #334 ("omit detail GoRoute stub when no detail_view"), re-running
// `zfa route create <Entity> --methods=get,getList --force` over the
// smoke-test's pre-existing routes files left a dangling separator comma
// at the end of the returned list literal:
//
//     List<GoRoute> errorLogRoutes() {
//       return [
//         GoRoute(
//           path: ErrorLogRoutes.errorLogList,
//           ...
//         ),
//         ,          // <-- stray comma (separator for the omitted detail route)
//
//       ];
//     }
//
// All 53 generated route files failed to compile with
// "Expected an identifier" and `zfa build` exited 1.
//
// Root cause (#335):
//   The pre-#334 files contained a stray comma BEFORE the (malformed)
//   detail route — leftover from the #331-era bug. #334's cleanup
//   (`removeElementsFromReturnListInFunctionWhere`) removed the detail
//   element plus ITS trailing comma, but left the comma that preceded it,
//   producing `[GoRoute(...), , ];`. DartFormatter then failed on the
//   broken syntax and `_formatSafe` returned the raw source unchanged.
//
// Fix (#335):
//   Rebuild the returned list literal from the surviving elements instead
//   of slicing out removed elements by offset, so no stray separator
//   comma can survive element removal regardless of how mangled the
//   pre-existing file was.
//
// This is the 3rd recurrence of the same defect class (missing import →
// malformed stub → dangling comma), so the test PARSES the generated
// output with the analyzer and asserts zero syntax errors — not just
// substring greps.
import 'dart:io';

import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/diagnostic/diagnostic.dart';
import 'package:test/test.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/models/generator_config.dart';
import 'package:zuraffa/src/plugins/route/builders/route_builder.dart';

/// The post-#334 broken state: detail stub removed, but its separator
/// comma left behind (this is the actual on-disk shape of all 53 route
/// files when issue #335 was filed).
const _issue335RoutesFile = r'''
// GENERATED - DO NOT EDIT
// Generated by zfa for: ErrorLog
import 'package:go_router/go_router.dart';
import 'package:zuraffa/zuraffa.dart';

import '../domain/entities/error_log/error_log.dart';

import '../presentation/pages/error_log/error_log_view.dart';

abstract class ErrorLogRoutes {
  static const String errorLogList = '/error_log';


  static const String errorLogDetail = '/error_log/:id';

}

List<GoRoute> errorLogRoutes() {
  return [
    GoRoute(
      path: ErrorLogRoutes.errorLogList,
      name: 'error_log_list',
      builder: (context, state) {
        return ErrorLogView(errorLog: (state.extra as ErrorLog?));
      },
    ),
    ,
  

];
}

// END GENERATED
''';

/// Pre-#334 state: malformed detail stub preceded by a stray comma (the
/// shape #334's cleanup ran against, whose preceding comma it failed to
/// remove).
const _issue333RoutesFile = r'''
// GENERATED - DO NOT EDIT
import 'package:go_router/go_router.dart';
import 'package:zuraffa/zuraffa.dart';
import '../domain/entities/error_log/error_log.dart';
import '../presentation/pages/error_log/error_log_view.dart';
import '../presentation/pages/error_log/error_log_detail_view.dart';

abstract class ErrorLogRoutes {
  static const String errorLogList = '/error_log';
  static const String errorLogDetail = '/error_log/:id';
}

List<GoRoute> errorLogRoutes() {
  return [
    GoRoute(
      path: ErrorLogRoutes.errorLogList,
      name: 'error_log_list',
      builder: (context, state) {
        return ErrorLogView(errorLog: (state.extra as ErrorLog?));
      },
    ),
    ,
    GoRoute(path: ErrorLogRoutes.errorLogDetail, name: 'error_log_detail',
      builder: (context, state, ) { return  ErrorLogView(id: state.pathParameters  [
'id'
]!, errorLog: (state.extra as ErrorLog?), ); } , ),
  ];
}

// END GENERATED
''';

void main() {
  late Directory tempDir;
  late String outputDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('issue_335_');
    outputDir = Directory('${tempDir.path}/lib/src').path;
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
  });

  Future<String> generateRoutes() async {
    final builder = RouteBuilder(
      outputDir: outputDir,
      options: const GeneratorOptions(
        dryRun: false,
        force: true,
        verbose: false,
      ),
    );

    await builder.generate(
      GeneratorConfig(
        name: 'ErrorLog',
        methods: const ['get', 'getList'],
        generateVpcs: true,
        generateRoute: true,
        outputDir: outputDir,
      ),
    );

    final routesFile = File('$outputDir/routing/error_log_routes.dart');
    expect(routesFile.existsSync(), isTrue, reason: 'routes file must exist');
    return routesFile.readAsStringSync();
  }

  group('issue #335 — dangling separator comma when detail route omitted', () {
    test('FRESH list-only generation (no detail_view) parses with zero syntax '
        'errors', () async {
      final content = await generateRoutes();

      expect(content.contains("name: 'error_log_list'"), isTrue);
      expect(content.contains("name: 'error_log_detail'"), isFalse);

      final errors = syntaxErrors(content);
      expect(
        errors,
        isEmpty,
        reason:
            'list-only routes file must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
      expect(
        RegExp(r',\s*\n\s*,').hasMatch(content),
        isFalse,
        reason: 'stray separator comma detected',
      );
    });

    test('RE-RUN with --force over the #335 broken file (stray trailing comma) '
        'parses with zero syntax errors', () async {
      final routesDir = Directory('$outputDir/routing');
      await routesDir.create(recursive: true);
      await File(
        '${routesDir.path}/error_log_routes.dart',
      ).writeAsString(_issue335RoutesFile);
      await File(
        '${routesDir.path}/index.dart',
      ).writeAsString("import 'error_log_routes.dart';\n");
      await File('${routesDir.path}/app_routes.dart').writeAsString(
        "import './index.dart';\n"
        "class AppRoutes {}\n"
        "extension RouterExtension on AppRoutes {}\n",
      );

      final content = await generateRoutes();

      expect(content.contains("name: 'error_log_list'"), isTrue);
      expect(content.contains("name: 'error_log_detail'"), isFalse);

      final errors = syntaxErrors(content);
      expect(
        errors,
        isEmpty,
        reason:
            'repaired routes file must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
      expect(
        RegExp(r',\s*\n\s*,').hasMatch(content),
        isFalse,
        reason: 'stray separator comma detected',
      );
    });

    test('RE-RUN with --force over the #333 malformed file removes the detail '
        'stub AND its preceding stray comma', () async {
      final routesDir = Directory('$outputDir/routing');
      await routesDir.create(recursive: true);
      await File(
        '${routesDir.path}/error_log_routes.dart',
      ).writeAsString(_issue333RoutesFile);
      await File(
        '${routesDir.path}/index.dart',
      ).writeAsString("import 'error_log_routes.dart';\n");
      await File('${routesDir.path}/app_routes.dart').writeAsString(
        "import './index.dart';\n"
        "class AppRoutes {}\n"
        "extension RouterExtension on AppRoutes {}\n",
      );

      final content = await generateRoutes();

      expect(content.contains('ErrorLogDetailView'), isFalse);
      expect(content.contains("name: 'error_log_detail'"), isFalse);

      final errors = syntaxErrors(content);
      expect(
        errors,
        isEmpty,
        reason:
            'repaired routes file must parse cleanly; got: '
            '${errors.map((e) => e.message).join(', ')}',
      );
      expect(
        RegExp(r',\s*\n\s*,').hasMatch(content),
        isFalse,
        reason: 'stray separator comma detected',
      );
    });

    test(
      'RE-RUN is idempotent — second run parses identically to the first',
      () async {
        final first = await generateRoutes();
        final second = await generateRoutes();

        expect(second, equals(first));
        expect(syntaxErrors(second), isEmpty);
      },
    );
  });
}

/// Parses [source] and returns all syntax (parse) diagnostics. A
/// syntactically valid file yields an empty list — this is the guard that
/// would have caught all three recurrences of this defect class.
List<Diagnostic> syntaxErrors(String source) {
  final result = parseString(content: source, throwIfDiagnostics: false);
  return result.errors.cast<Diagnostic>();
}
