// Spec 0971 / T004 remediation (audit finding F1) — the reverse drift
// direction: a route module that appeared on disk AFTER the receipt was
// written (stale receipt) must fail verification, not pass it.
//
// The verify static check only compared receipt -> disk (every declared
// route still on disk). A receipt whose table predates a newly added
// module (e.g. `order_routes.dart` hand-added or generated without
// re-running `route create`) claimed "healthy" while the ledger row no
// longer described the tree — exactly the drift the #963 ledger exists
// to catch. Driven red-first per /speckit.tdd.verify's remediation
// loop.
library;

import 'dart:async';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/commands/route_command.dart';
import 'package:zuraffa/src/commands/route_verify_command.dart';
import 'package:zuraffa/src/plugins/route/route_plugin.dart';

Future<String> captureOutput(Future<void> Function() body) async {
  final output = <String>[];
  await runZoned(
    body,
    zoneSpecification: ZoneSpecification(
      print: (self, parent, zone, line) {
        output.add(line);
      },
    ),
  );
  return output.join('\n');
}

void main() {
  late Directory tempDir;
  late String projectRoot;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('spec971_f1_');
    projectRoot = tempDir.path;
    await File(p.join(projectRoot, 'pubspec.yaml')).writeAsString('''
name: route_app
dependencies:
  flutter:
    sdk: flutter
''');
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
    exitCode = 0;
  });

  test('a route module added after the receipt (stale receipt) fails '
      'verification with a fix line', () async {
    // Fixture: generate Product routes + receipt, the way the CLI does.
    final create = CommandRunner<void>('zfa', 'test')
      ..addCommand(
        RouteCommand(
          RoutePlugin(
            outputDir: '$projectRoot/lib/src',
            projectRoot: projectRoot,
          ),
          projectRoot: projectRoot,
        ),
      );
    await captureOutput(() => create.run(['route', 'create', 'Product']));

    // Drift: a second module appears on disk AFTER the receipt was
    // written — the receipt's table no longer describes the tree.
    await File(
      p.join(projectRoot, 'lib', 'src', 'routing', 'order_routes.dart'),
    ).writeAsString('''
// GENERATED - DO NOT EDIT
// Generated by zfa for: Order (hand-added, receipt is stale)
abstract class OrderRoutes {
  static const String order = '/order';
}
''');

    exitCode = 0;
    final verify = CommandRunner<void>('zfa', 'test')
      ..addCommand(
        RouteVerifyCommand(
          projectRoot: projectRoot,
          testRunner: (testPath, cwd) async =>
              (exitCode: 0, output: 'all passed'),
        ),
      );
    final out = await captureOutput(() => verify.run(['verify', 'Product']));

    expect(
      exitCode,
      1,
      reason: 'a stale receipt must not verify as healthy\n$out',
    );
    expect(
      out,
      contains('/order'),
      reason: 'the finding must name the unprovenanced disk route',
    );
    expect(out, contains('--> fix:'));
    expect(
      out,
      contains('zfa route create'),
      reason: 'the fix line must point at regeneration',
    );
  });
}
