// GENERATED - DO NOT EDIT
// Generated by zfa for: Customer
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/customer/customer.dart';
import '../../repositories/customer_repository.dart';

class ToggleCustomerUseCase
    extends UseCase<Customer, ToggleParams<String, Field<Customer, dynamic>>> {
  ToggleCustomerUseCase(this._repository);

  final CustomerRepository _repository;

  @override
  Future<Customer> execute(
    ToggleParams<String, Field<Customer, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
