import 'package:path/path.dart' as path;
import '../models/generator_config.dart';
import '../models/generated_file.dart';
import '../utils/file_utils.dart';

class RepositoryGenerator {
  final GeneratorConfig config;
  final String outputDir;
  final bool dryRun;
  final bool force;
  final bool verbose;

  RepositoryGenerator({
    required this.config,
    required this.outputDir,
    this.dryRun = false,
    this.force = false,
    this.verbose = false,
  });

  Future<GeneratedFile> generate() async {
    final repoName = '${config.name}Repository';
    final fileName = '${config.nameSnake}_repository.dart';
    final filePath = path.join(outputDir, 'domain', 'repositories', fileName);

    final methods = <String>[];

    if (config.generateInit) {
      methods.add('  Stream<bool> get isInitialized;');
      methods.add('  Future<void> initialize(InitializationParams params);');
    }

    for (final method in config.methods) {
      switch (method) {
        case 'get':
          if (config.idField == 'null') {
            methods.add('  Future<${config.name}> get();');
          } else {
            methods.add(
                '  Future<${config.name}> get(${config.queryFieldType} ${config.queryField});');
          }
          break;
        case 'getList':
          methods.add(
              '  Future<List<${config.name}>> getList(ListQueryParams params);');
          break;
        case 'create':
          methods.add(
              '  Future<${config.name}> create(${config.name} ${config.nameCamel});');
          break;
        case 'update':
          methods.add(
              '  Future<${config.name}> update(UpdateParams<${config.useMorphy ? "${config.name}Patch" : "Partial<${config.name}>"}> params);');
          break;
        case 'delete':
          methods.add(
              '  Future<void> delete(DeleteParams<${config.name}> params);');
          break;
        case 'watch':
          if (config.idField == 'null') {
            methods.add('  Stream<${config.name}> watch();');
          } else {
            methods.add(
                '  Stream<${config.name}> watch(${config.queryFieldType} ${config.queryField});');
          }
          break;
        case 'watchList':
          methods.add(
              '  Stream<List<${config.name}>> watchList(ListQueryParams params);');
          break;
      }
    }

    // Check if we need zuraffa imports
    final needsZuraffaImport = config.methods.any((method) => 
      method == 'getList' || method == 'update' || method == 'delete' || 
      method == 'watchList') || config.generateInit;

    final imports = <String>[];
    if (needsZuraffaImport) {
      imports.add("import 'package:zuraffa/zuraffa.dart';");
    }
    imports.add("import '../entities/${config.nameSnake}/${config.nameSnake}.dart';");

    final content = '''
// Generated by zfa
// zfa generate ${config.name} --methods=${config.methods.join(',')} --repository

${imports.join('\n')}

abstract class $repoName {
${methods.join('\n')}
}
''';

    return FileUtils.writeFile(
      filePath,
      content,
      'repository',
      force: force,
      dryRun: dryRun,
      verbose: verbose,
    );
  }
}
