// GENERATED - DO NOT EDIT
// Generated by zfa for: ListingOffer
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/listing_offer/listing_offer.dart';
import '../../mock/listing_offer_mock_data.dart';
import 'listing_offer_datasource.dart';

/// Mock data source for ListingOffer
class ListingOfferMockDataSource
    with Loggable, FailureHandler
    implements ListingOfferDataSource {
  ListingOfferMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ListingOffer> get(QueryParams<ListingOffer> params) async {
    logger.info('Getting ListingOffer with params: $params');
    await Future.delayed(_delay);
    final item = ListingOfferMockData.listingOffers.query(params);
    logger.info('Successfully retrieved ListingOffer');
    return item;
  }

  @override
  Future<ListingOffer> update(
    UpdateParams<String, ListingOfferPatch> params,
  ) async {
    logger.info('Updating ListingOffer: ${params.id}');
    await Future.delayed(_delay);
    final existing = ListingOfferMockData.sampleListingOffer;
    logger.info('Successfully updated ListingOffer');
    return existing;
  }

  @override
  Future<ListingOffer> toggle(
    ToggleParams<String, Field<ListingOffer, dynamic>> params,
  ) async {
    logger.info('Toggling ListingOffer: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = ListingOfferMockData.sampleListingOffer;
    logger.info('Successfully toggled ListingOffer');
    return existing;
  }
}

// END GENERATED
