/// MockStubGenerator (spec 043): boundary mocks (FR-003).
///
/// A mock is `class Mock<T> implements T` overriding every public member
/// with a `throw UnimplementedError()` stub — mocktail's shape, chosen so
/// the mock compiles against any interface (abstract or concrete) without
/// knowing constructor signatures. Depth-aware per U31: `full` depth cuts
/// nothing, so no mocks are generated; `existing` strategy defers to the
/// project's own mock (U30).
library;

import 'dart:io';

import 'package:analyzer/dart/ast/ast.dart';
import 'package:path/path.dart' as p;

import '../../../core/ast/file_parser.dart';
import '../../../utils/string_utils.dart';
import '../models/file_graph.dart';
import '../models/slice_boundary.dart';
import '../models/slice_depth.dart';

/// A generated mock file: where it lives in the sandbox and its content.
class GeneratedMock {
  /// Creates the record.
  const GeneratedMock({required this.relativePath, required this.content});

  /// Sandbox-relative path (e.g. `lib/src/mocks/mock_product_repository.dart`).
  final String relativePath;

  /// Full Dart source of the mock file.
  final String content;
}

/// Generates lightweight mocks for boundary interfaces.
class MockStubGenerator {
  /// Creates the generator with an optional [parser].
  MockStubGenerator({FileParser? parser})
    : _parser = parser ?? const FileParser();

  final FileParser _parser;

  /// Generates the mock for [boundary], or null when none should be
  /// generated (mockStrategy `existing`, or `full` depth).
  Future<GeneratedMock?> generate({
    required SliceBoundary boundary,
    required String projectRoot,
    required SliceDepth depth,
    String? sandboxRoot,
  }) async {
    if (depth == SliceDepth.full) return null;
    if (boundary.mockStrategy == 'existing') return null;
    if (boundary.mockStrategy == 'none') return null;

    final targetRoot = sandboxRoot ?? projectRoot;
    // When the concrete interface lives in an excluded layer at this depth, it
    // is not copied into the sandbox; read its source from the project so the
    // mock (with an inline abstract interface) can still be generated (A13/A14).
    final interfaceIncluded = layerAllowedAtDepth(
      classifyLayer(boundary.interfaceFile),
      depth,
    );
    final sourceRoot = interfaceIncluded ? targetRoot : projectRoot;
    final interfacePath = p.canonicalize(
      p.join(sourceRoot, boundary.interfaceFile),
    );
    final file = File(interfacePath);
    if (!await file.exists()) return null;
    final source = await file.readAsString();

    final members = _publicMembers(source, boundary.typeName);
    if (members == null) return null;

    final mockClassName = 'Mock${boundary.typeName}';
    final buffer = StringBuffer();
    buffer.writeln(
      '// Generated by `zfa slice cut` — mock for the boundary interface',
    );
    buffer.writeln(
      '// ${boundary.typeName} (${boundary.interfaceFile}). Modify freely;',
    );
    buffer.writeln('// return realistic values to exercise the slice.');
    buffer.writeln('library;');
    buffer.writeln();

    if (interfaceIncluded) {
      final interfaceImport = p.relative(
        interfacePath,
        from: p.join(targetRoot, 'lib', 'src', 'mocks'),
      );
      buffer.writeln("import '${interfaceImport.replaceAll('\\', '/')}';");
      buffer.writeln();
    } else {
      // The concrete interface lives in an excluded layer at this depth (e.g.
      // the concrete ProductPresenter at `--depth view`). Keep its shape inline
      // so the sandbox stays within the depth and the mock still resolves
      // (A13/A14) without dragging the excluded layer into the sandbox.
      final signatures = _abstractSignatures(source, boundary.typeName);
      if (signatures != null) {
        buffer.writeln(
          '// Inline interface (concrete declaration is outside the slice depth).',
        );
        buffer.writeln('abstract class ${boundary.typeName} {');
        for (final sig in signatures) {
          buffer.writeln('  $sig');
        }
        buffer.writeln('}');
        buffer.writeln();
      }
    }

    buffer.writeln('/// Mock of [${boundary.typeName}].');
    buffer.writeln('class $mockClassName implements ${boundary.typeName} {');
    for (final member in members) {
      buffer.writeln('  @override');
      buffer.writeln('  $member');
    }
    buffer.writeln('}');

    final snake = StringUtils.camelToSnake(boundary.typeName);
    return GeneratedMock(
      relativePath: 'lib/src/mocks/mock_$snake.dart',
      content: buffer.toString(),
    );
  }

  /// Renders every public member of [typeName] as a stubbed override, or
  /// null when the type is not declared in [source].
  List<String>? _publicMembers(String source, String typeName) {
    final result = _parser.parseSource(source);
    final unit = result.unit;
    if (unit == null) return null;
    ClassDeclaration? declaration;
    for (final decl in unit.declarations) {
      if (decl is ClassDeclaration &&
          decl.namePart.typeName.lexeme == typeName) {
        declaration = decl;
        break;
      }
    }
    if (declaration == null) return null;

    final members = <String>[];
    final body = declaration.body;
    if (body is! BlockClassBody) return members;
    for (final member in body.members) {
      if (member is MethodDeclaration) {
        final name = member.name.toString();
        if (name.startsWith('_')) continue;
        members.add(_stubMethod(member));
      } else if (member is FieldDeclaration) {
        for (final variable in member.fields.variables) {
          final name = variable.name.toString();
          if (name.startsWith('_')) continue;
          final type = member.fields.type?.toString() ?? 'dynamic';
          final isFinal = member.fields.isFinal;
          members.add(
            '@override\n  $type get $name => '
            "throw UnimplementedError('$name');",
          );
          if (!isFinal) {
            members.add(
              "@override\n  set $name($type value) => "
              "throw UnimplementedError('$name');",
            );
          }
        }
      }
    }
    return members;
  }

  /// Renders every public member of [typeName] as an abstract signature (no
  /// body), or null when the type is not declared in [source]. Used to keep a
  /// boundary's shape inline when its concrete declaration is outside the cut
  /// depth (so the sandbox does not import an excluded-layer file).
  List<String>? _abstractSignatures(String source, String typeName) {
    final result = _parser.parseSource(source);
    final unit = result.unit;
    if (unit == null) return null;
    ClassDeclaration? declaration;
    for (final decl in unit.declarations) {
      if (decl is ClassDeclaration &&
          decl.namePart.typeName.lexeme == typeName) {
        declaration = decl;
        break;
      }
    }
    if (declaration == null) return null;

    final signatures = <String>[];
    final body = declaration.body;
    if (body is! BlockClassBody) return signatures;
    for (final member in body.members) {
      if (member is MethodDeclaration) {
        final name = member.name.toString();
        if (name.startsWith('_')) continue;
        final returnType = member.returnType?.toString();
        final typeParams = member.typeParameters == null
            ? ''
            : member.typeParameters.toString();
        final params = member.parameters?.toString() ?? '()';
        signatures.add('${returnType ?? 'dynamic'} $name$typeParams$params;');
      } else if (member is FieldDeclaration) {
        for (final variable in member.fields.variables) {
          final name = variable.name.toString();
          if (name.startsWith('_')) continue;
          final type = member.fields.type?.toString() ?? 'dynamic';
          signatures.add('$type get $name;');
          if (!member.fields.isFinal) {
            signatures.add('set $name($type value);');
          }
        }
      }
    }
    return signatures;
  }

  String _stubMethod(MethodDeclaration method) {
    final name = method.name.toString();
    final returnType = method.returnType?.toString();
    final typeParams = method.typeParameters == null
        ? ''
        : method.typeParameters.toString();
    final params = method.parameters?.toString() ?? '';

    final isSetter = method.isSetter;
    final isGetter = method.isGetter;
    final buffer = StringBuffer();
    if (isSetter) {
      buffer.write('set $name$params ');
      buffer.write("{ throw UnimplementedError('$name'); }");
    } else if (isGetter) {
      buffer.write('${returnType ?? 'dynamic'} get $name ');
      buffer.write("=> throw UnimplementedError('$name');");
    } else {
      buffer.write('${returnType ?? 'dynamic'} $name$typeParams$params ');
      buffer.write("=> throw UnimplementedError('$name');");
    }
    return buffer.toString();
  }
}
