/// SandboxBootstrapper (spec 043): main_slice.dart + slice_di.dart (FR-003).
///
/// `main_slice.dart` imports each entry's root view, calls the generated
/// `setupSliceDependencies()`, and wraps the app in a MaterialApp. With one
/// entry it is that view; with several it exposes every root behind a
/// launcher home (U34).
///
/// `slice_di.dart` registers exactly what the slice needs (U33): real
/// wiring is delegated to the project's own (already-included) DI
/// registration functions, and every cut-off boundary is registered to its
/// generated mock.
library;

/// One entry view exposed by the generated entry point.
class EntryView {
  /// Creates the record.
  const EntryView({
    required this.importPath,
    required this.className,
    required this.title,
  });

  /// Import path for the view (package: or relative).
  final String importPath;

  /// Root widget class name.
  final String className;

  /// Human-readable tab/button title.
  final String title;
}

/// A real registration delegated to an included project DI file.
class RealDiCall {
  /// Creates the record.
  const RealDiCall({required this.importPath, required this.functionName});

  /// Import path of the DI file relative to slice_di.dart.
  final String importPath;

  /// Registration function name to call.
  final String functionName;
}

/// A boundary mock registration.
class MockRegistration {
  /// Creates the record.
  const MockRegistration({
    required this.typeName,
    required this.mockClassName,
    required this.mockImportPath,
    required this.interfaceImportPath,
  });

  /// Boundary interface type name.
  final String typeName;

  /// Generated mock class name.
  final String mockClassName;

  /// Import path of the mock relative to slice_di.dart.
  final String mockImportPath;

  /// Import path of the interface relative to slice_di.dart.
  final String interfaceImportPath;
}

/// Generates the sandbox entry point and DI wiring.
class SandboxBootstrapper {
  /// Generates `main_slice.dart`.
  String generateMainSlice({
    required String sliceName,
    required List<EntryView> entryViews,
  }) {
    final buffer = StringBuffer();
    buffer.writeln(
      '// Generated by `zfa slice cut` — runnable entry point for the',
    );
    buffer.writeln('// "$sliceName" slice. Edit the mirrored files, not this',
    );
    buffer.writeln('// harness, unless you really mean it.');
    buffer.writeln('library;');
    buffer.writeln();
    buffer.writeln("import 'package:flutter/material.dart';");
    buffer.writeln();
    for (final view in entryViews) {
      buffer.writeln("import '${view.importPath}';");
    }
    buffer.writeln();
    buffer.writeln("import 'lib/src/di/slice_di.dart';");
    buffer.writeln();
    buffer.writeln('/// Runs the "$sliceName" slice as a standalone app.');
    buffer.writeln('void main() {');
    buffer.writeln('  setupSliceDependencies();');
    buffer.writeln('  runApp(const ${_appClassName(sliceName)}());');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln(
      'class ${_appClassName(sliceName)} extends StatelessWidget {',
    );
    buffer.writeln('  const ${_appClassName(sliceName)}({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) {');
    buffer.writeln('    return MaterialApp(');
    buffer.writeln("      title: '$sliceName slice',");
    buffer.writeln('      home: ${_homeWidget(entryViews)},');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');
    buffer.write(_launcherClass(entryViews));
    return buffer.toString();
  }

  String _appClassName(String sliceName) {
    final parts = sliceName
        .replaceAll(RegExp(r'[^a-zA-Z0-9]+'), ' ')
        .trim()
        .split(RegExp(r'\s+'));
    final camel = parts
        .where((part) => part.isNotEmpty)
        .map(
          (part) =>
              part[0].toUpperCase() + part.substring(1).toLowerCase(),
        )
        .join();
    return '${camel}SliceApp';
  }

  String _homeWidget(List<EntryView> entryViews) {
    if (entryViews.length == 1) {
      return 'const ${entryViews.single.className}()';
    }
    // Multi-entry: a launcher home with one button per entry root (U34).
    return 'const _SliceHome()';
  }

  /// Emits the multi-entry launcher class (generated text, not a real
  /// class — this library is pure Dart with no Flutter dependency).
  String _launcherClass(List<EntryView> entryViews) {
    if (entryViews.length == 1) return '';
    final buffer = StringBuffer();
    buffer.writeln();
    buffer.writeln('class _SliceHome extends StatelessWidget {');
    buffer.writeln('  const _SliceHome({super.key});');
    buffer.writeln();
    buffer.writeln('  @override');
    buffer.writeln('  Widget build(BuildContext context) {');
    buffer.writeln('    return Scaffold(');
    buffer.writeln(
      "      appBar: AppBar(title: const Text('Slice entries')),",
    );
    buffer.writeln('      body: Center(');
    buffer.writeln('        child: Column(');
    buffer.writeln('          mainAxisAlignment: MainAxisAlignment.center,');
    buffer.writeln('          children: [');
    for (final view in entryViews) {
      buffer.writeln('            ElevatedButton(');
      buffer.writeln(
        "              onPressed: () => Navigator.of(context).push(",
      );
      buffer.writeln(
        '                MaterialPageRoute< void>(');
      buffer.writeln(
        '                  builder: (_) => const ${view.className}(),',
      );
      buffer.writeln('                ),');
      buffer.writeln('              ),');
      buffer.writeln("              child: const Text('${view.title}'),");
      buffer.writeln('            ),');
    }
    buffer.writeln('          ],');
    buffer.writeln('        ),');
    buffer.writeln('      ),');
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln('}');
    return buffer.toString();
  }

  /// Generates `lib/src/di/slice_di.dart`.
  String generateSliceDi({
    required String sliceName,
    required List<RealDiCall> realRegistrations,
    required List<MockRegistration> mockRegistrations,
  }) {
    final buffer = StringBuffer();
    buffer.writeln(
      '// Generated by `zfa slice cut` — minimal DI for the "$sliceName"',
    );
    buffer.writeln(
      '// slice. Real wiring delegates to the project\'s own registration',
    );
    buffer.writeln(
      '// functions (included in the slice); cut-off boundaries get mocks.',
    );
    buffer.writeln('library;');
    buffer.writeln();
    if (realRegistrations.isNotEmpty || mockRegistrations.isNotEmpty) {
      buffer.writeln("import 'package:get_it/get_it.dart';");
      for (final real in realRegistrations) {
        buffer.writeln("import '${real.importPath}';");
      }
      for (final mock in mockRegistrations) {
        buffer.writeln("import '${mock.mockImportPath}';");
        buffer.writeln("import '${mock.interfaceImportPath}';");
      }
      buffer.writeln();
    }
    buffer.writeln(
      "final getIt = GetIt.instance;",
    );
    buffer.writeln();
    buffer.writeln(
      '/// Registers exactly the dependencies the "$sliceName" slice needs.',
    );
    buffer.writeln('void setupSliceDependencies() {');
    for (final real in realRegistrations) {
      buffer.writeln('  ${real.functionName}(getIt);');
    }
    for (final mock in mockRegistrations) {
      buffer.writeln(
        '  getIt.registerLazySingleton<${mock.typeName}>(',
      );
      buffer.writeln('    () => ${mock.mockClassName}(),');
      buffer.writeln('  );');
    }
    buffer.writeln('}');
    return buffer.toString();
  }
}
