// GENERATED - DO NOT EDIT
// Generated by zfa for: GroceryPriceComparison
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/grocery_price_comparison/grocery_price_comparison.dart';
import '../../repositories/grocery_price_comparison_repository.dart';

class ToggleGroceryPriceComparisonUseCase
    extends
        UseCase<
          GroceryPriceComparison,
          ToggleParams<String, Field<GroceryPriceComparison, dynamic>>
        > {
  ToggleGroceryPriceComparisonUseCase(this._repository);

  final GroceryPriceComparisonRepository _repository;

  @override
  Future<GroceryPriceComparison> execute(
    ToggleParams<String, Field<GroceryPriceComparison, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
