// GENERATED - DO NOT EDIT
// Generated by zfa for: Listing
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/listing/listing.dart';
import '../../repositories/listing_repository.dart';

class UpdateListingUseCase
    extends UseCase<Listing, UpdateParams<String, ListingPatch>> {
  UpdateListingUseCase(this._repository);

  final ListingRepository _repository;

  @override
  Future<Listing> execute(
    UpdateParams<String, ListingPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
