// Generated by zfa

import 'package:zuraffa/zuraffa.dart';
import '../../entities/product/product.dart';
import '../../repositories/product_repository.dart';

class GetProductUseCase extends UseCase<Product, String> {
  final ProductRepository _repository;

  GetProductUseCase(this._repository);

  @override
  Future<Product> execute(String id, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(id);
  }
}
