import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as p;

import '../../../core/builder/shared/spec_library.dart';

/// Emitter for the zfa app-shell glue files.
///
/// Produces three Dart sources that wire the generated DI tree
/// (`setupDependencies`) and the generated routing tree (`getAllRoutes`)
/// into a runnable Flutter app:
///
///  * `lib/main.dart` — `void main()` → `await setupDependencies()` →
///    `runApp(const MyApp())`.
///  * `<outputDir>/app/my_app.dart` — `MyApp` widget that builds a
///    `MaterialApp.router` configured with [appRouter].
///  * `<outputDir>/routing/app_router.dart` — `final GoRouter appRouter =
///    GoRouter(routes: getAllRoutes());`.
///
/// When `xray: true` is passed (issue #360), `main.dart` additionally
/// starts the X-Ray bridge server in debug mode and invokes
/// `registerAllXRayDecks()` (from the barrel at
/// `<outputDir>/xray/xray_decks.dart`), and `my_app.dart` wraps
/// `MaterialApp.router` in an `XRayScope(viewId: 'App', ...)`. The
/// barrel file is emitted by [buildXRayDecksBarrel] so the import always
/// resolves.
///
/// The `app/` and `routing/` glue files land under the configured output
/// directory (default `lib/src`), and `buildMain` derives its `package:`
/// imports from that same directory so the emitted entrypoint always
/// resolves to the written files.
///
/// All three files are stamped with a `// Generated by zfa` header so
/// subsequent `zfa` runs can identify them. They are *not* wrapped in
/// the AST merge engine's `// GENERATED - DO NOT EDIT` markers — those
/// are reserved for files regenerated by `zfa build` from annotations,
/// and these glue files are emitted by an explicit `zfa app shell`
/// invocation, not by build_runner. `--force` is the explicit opt-in for
/// re-generation when the user wants to refresh them.
class AppShellBuilder {
  final SpecLibrary specLibrary;

  const AppShellBuilder({this.specLibrary = const SpecLibrary()});

  /// Builds `lib/main.dart`.
  ///
  /// [appName] is the Dart package name (from `pubspec.yaml`); used to
  /// import the generated DI barrel at
  /// `package:<appName>/<outputDir>/di/index.dart` (and the MyApp widget
  /// at `package:<appName>/<outputDir>/app/my_app.dart`).
  /// [outputDir] is the project-root-relative directory the `app/` and
  /// `routing/` glue files were written to (default `lib/src`); the
  /// entrypoint always lands at `lib/main.dart`, so the package imports
  /// are derived from [outputDir] relative to `lib/` — this keeps the
  /// emitted imports in sync with a non-default `--output`.
  /// [mockHint] controls whether a `// Mock DI mode` hint comment is
  /// emitted (purely informational — the mock-vs-real decision is made
  /// at DI-generation time via `zfa di <Entity> --use-mock`, and
  /// `setupDependencies()` already wires whatever was generated).
  /// [xray] (issue #360) wires the X-Ray bridge server: emits an
  /// `if (kDebugMode) { await XRayBridgeServer().start();
  /// registerAllXRayDecks(); }` block after `setupDependencies()` and
  /// adds the corresponding imports.
  String buildMain({
    required String appName,
    bool mockHint = false,
    String outputDir = 'lib/src',
    bool xray = false,
  }) {
    // main.dart lives at lib/main.dart, so package: imports must resolve
    // relative to lib/. Map the output dir ("lib/src" -> "src",
    // "lib/custom" -> "custom", "lib" -> "").
    final importBase = _packageImportBase(outputDir);
    final myAppImport = importBase.isEmpty
        ? 'package:$appName/app/my_app.dart'
        : 'package:$appName/$importBase/app/my_app.dart';
    final diImport = importBase.isEmpty
        ? 'package:$appName/di/index.dart'
        : 'package:$appName/$importBase/di/index.dart';
    final xrayDecksImport = importBase.isEmpty
        ? 'package:$appName/xray/xray_decks.dart'
        : 'package:$appName/$importBase/xray/xray_decks.dart';

    final directives = <Directive>[
      Directive.import('package:flutter/widgets.dart'),
      Directive.import(myAppImport),
      Directive.import(diImport),
      if (xray) ...[
        Directive.import('package:flutter/foundation.dart'),
        Directive.import(xrayDecksImport),
      ],
    ];

    final bodyStatements = <Code>[
      refer('setupDependencies').call([]).awaited.statement,
    ];
    if (xray) {
      // Emit:
      //   if (kDebugMode) {
      //     await _startXRayBridge();
      //     registerAllXRayDecks();
      //   }
      bodyStatements.add(
        Code(
          'if (kDebugMode) {\n'
          '  await _startXRayBridge();\n'
          '  registerAllXRayDecks();\n'
          '}',
        ),
      );
    }
    bodyStatements.add(
      refer('runApp')
          .call([CodeExpression(Code('const MyApp()'))])
          .statement,
    );

    final main = Method(
      (m) => m
        ..name = 'main'
        ..returns = refer('void')
        ..modifier = MethodModifier.async
        ..body = Block((b) => b.statements.addAll(bodyStatements)),
    );

    final specs = <Spec>[main];

    final library = specLibrary.library(
      specs: specs,
      directives: directives,
    );

    final leadingParts = <String>['// Generated by zfa'];
    if (mockHint) {
      leadingParts.add(
        '// Mock DI mode: setupDependencies() wires mock datasources\n'
        '// generated via `zfa di <Entity> --use-mock`.',
      );
    }
    if (xray) {
      leadingParts.add(
        '// X-Ray wiring (issue #360): bridge server starts in debug mode,\n'
        '// Control Deck entries are registered via registerAllXRayDecks()\n'
        '// (see <outputDir>/xray/xray_decks.dart, maintained by '
        '`zfa xray deck`).',
      );
    }
    final leading = leadingParts.join('\n');

    var emittedCode = specLibrary.emitLibrary(
      library,
      leadingComment: leading,
      wrapWithGeneratedMarkers: false,
    );

    // Add platform-safe bridge launcher when xray is enabled
    if (xray) {
      // Add conditional import for XRayBridgeServer
      emittedCode = emittedCode.replaceFirst(
        "import 'package:flutter/foundation.dart';",
        "import 'package:flutter/foundation.dart';\n"
        "import 'xray_bridge_launcher_stub.dart'\n"
        "    if (dart.library.io) 'package:zuraffa_flutter/src/presentation/xray/xray_bridge_server.dart';",
      );

      final bridgeLauncher = '''

/// Platform-safe X-Ray bridge launcher.
/// On web: no-op (dart:io unavailable).
/// On other platforms: starts XRayBridgeServer if available.
Future<void> _startXRayBridge() async {
  const hasDartIo = bool.fromEnvironment('dart.library.io', defaultValue: true);
  if (hasDartIo) {
    // Import XRayBridgeServer conditionally (only on non-web platforms)
    await XRayBridgeServer().start();
  }
  // Web: no-op (this function returns immediately)
}
''';
      emittedCode = emittedCode + bridgeLauncher;
    }

    return emittedCode;
  }

  /// Builds `lib/src/app/my_app.dart`.
  ///
  /// Emits a `MyApp` StatelessWidget that returns a `MaterialApp.router`
  /// bound to [appRouter]. The optional [title] is used as the
  /// MaterialApp title. The default theme is the framework light theme
  /// — generated apps are expected to layer their own theme on top, but
  /// the shell must compile and render out of the box.
  ///
  /// When [xray] is true (issue #360), the `MaterialApp.router` is
  /// wrapped in `XRayScope(viewId: 'App', child: ...)` so the bridge
  /// server can serialize the widget tree. `XRayScope` is a no-op
  /// pass-through when X-Ray mode is disabled.
  String buildMyApp({String? title, bool xray = false}) {
    final directives = <Directive>[
      Directive.import('package:flutter/material.dart'),
      Directive.import('package:go_router/go_router.dart'),
      Directive.import('../routing/app_router.dart'),
      if (xray)
        Directive.import('package:zuraffa_flutter/zuraffa_flutter.dart'),
    ];

    final materialApp = refer('MaterialApp').property('router').call([], {
      'title': literalString(title ?? 'Zuraffa App'),
      'routerConfig': refer('appRouter'),
      'debugShowCheckedModeBanner': literalFalse,
    });

    final returnedWidget = xray
        ? refer('XRayScope').call([], {
            'viewId': literalString('App'),
            'child': materialApp,
          })
        : materialApp;

    final myApp = Class(
      (c) => c
        ..name = 'MyApp'
        ..extend = refer('StatelessWidget')
        ..constructors.add(
          Constructor(
            (ctor) => ctor
              ..constant = true
              // A `super.key` *invocation* in the initializer list would
              // emit `const MyApp() : super.key();`, which does not compile
              // — StatelessWidget has no constructor named `key`. Emit a
              // super *parameter* instead (`const MyApp({super.key});`),
              // same pattern as the view template generator.
              ..optionalParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'key'
                    ..type = refer('Key?')
                    ..named = true
                    ..toSuper = true,
                ),
              ),
          ),
        )
        ..methods.add(
          Method(
            (m) => m
              ..name = 'build'
              ..returns = refer('Widget')
              ..annotations.add(refer('override'))
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'context'
                    ..type = refer('BuildContext'),
                ),
              )
              ..body = returnedWidget.returned.statement,
          ),
        ),
    );

    final library = specLibrary.library(
      specs: [myApp],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment: '// Generated by zfa',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Builds `lib/src/routing/app_router.dart`.
  ///
  /// Emits a top-level `final GoRouter appRouter = GoRouter(routes:
  /// getAllRoutes());` wired to the generated `getAllRoutes()` from
  /// `lib/src/routing/index.dart`.
  String buildAppRouter() {
    final directives = [
      Directive.import('package:go_router/go_router.dart'),
      Directive.import('index.dart'),
    ];

    final appRouter = Field(
      (f) => f
        ..name = 'appRouter'
        ..type = refer('GoRouter')
        ..modifier = FieldModifier.final$
        ..assignment = refer('GoRouter').call([], {
          'routes': refer('getAllRoutes').call([]),
        }).code,
    );

    final library = specLibrary.library(
      specs: [appRouter],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment: '// Generated by zfa',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Builds `<outputDir>/xray/xray_decks.dart` — the Control Deck
  /// registration barrel consumed by [buildMain] when `xray: true`.
  ///
  /// Emits a top-level `void registerAllXRayDecks()` that is a no-op in
  /// release mode. `zfa xray deck` appends per-entity
  /// `register<Entity>XRayDeck()` calls (and their imports) into this
  /// file via the AST merge engine, so the barrel always compiles even
  /// before any deck has been generated.
  ///
  /// Pass [existingRegistrations] to preserve calls already present in
  /// an earlier version of the barrel (used by `zfa xray deck` when it
  /// rewrites the barrel). The app-shell command passes an empty list
  /// on first generation.
  String buildXRayDecksBarrel({
    List<String> deckImports = const [],
    List<String> registrationCalls = const [],
  }) {
    final directives = <Directive>[
      Directive.import('package:flutter/foundation.dart'),
      ...deckImports.map((uri) => Directive.import(uri)),
    ];

    final body = StringBuffer();
    body.writeln('  if (kReleaseMode) return;');
    if (registrationCalls.isEmpty) {
      body.writeln(
        '  // Registration calls are appended here by `zfa xray deck`.',
      );
      body.writeln(
        '  // Each `zfa xray deck --entity <Entity>` invocation adds a',
      );
      body.writeln('  // `register<Entity>XRayDeck();` call below.');
    } else {
      for (final call in registrationCalls) {
        body.writeln('  $call');
      }
    }

    final registerAll = Method(
      (m) => m
        ..name = 'registerAllXRayDecks'
        ..returns = refer('void')
        ..body = Code(body.toString()),
    );

    final library = specLibrary.library(
      specs: [registerAll],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment:
          '// Generated by zfa — X-Ray Control Deck registration barrel.\n'
          '// This file is maintained by `zfa xray deck`. Each invocation\n'
          '// appends a `register<Entity>XRayDeck()` call below. Safe to\n'
          '// edit manually — `zfa xray deck` preserves existing calls.',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Returns the Dart package name declared in [pubspecContent] or `null`
  /// if it cannot be parsed. Used by the command to wire imports.
  static String? parseAppName(String pubspecContent) {
    final m = RegExp(
      r'^name:\s*([A-Za-z][A-Za-z0-9_]*)',
      multiLine: true,
    ).firstMatch(pubspecContent);
    return m?.group(1);
  }

  /// Maps a project-root-relative [outputDir] (e.g. `lib/src`, `lib/custom`)
  /// to the package-import base used by main.dart — the path relative to
  /// `lib/` (e.g. `src`, `custom`). Returns `''` when the output dir is
  /// `lib/` itself. The command rejects dirs outside `lib/`, so this never
  /// sees an escaping path in practice.
  static String _packageImportBase(String outputDir) {
    final rel = p.relative(outputDir, from: 'lib');
    return rel == '.' ? '' : rel;
  }
}
