import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as p;

import '../../../core/builder/shared/spec_library.dart';

/// Emitter for the zfa app-shell glue files.
///
/// Produces three Dart sources that wire the generated DI tree
/// (`setupDependencies`) and the generated routing tree (`getAllRoutes`)
/// into a runnable Flutter app:
///
///  * `lib/main.dart` — `void main()` → `setupDependencies(...)` →
///    `runApp(const MyApp())`. The call mirrors the generated DI's
///    `setupDependencies` signature: `setupDependencies(GetIt instance)`
///    for the canonical GetIt-based DI emitted by `zfa di`, or
///    `setupDependencies()` for a no-arg custom entrypoint. When the DI is
///    asynchronous, main becomes `async` and `await`s the call; the canonical
///    synchronous DI is called without `await`. See issue #370.
///  * `<outputDir>/app/my_app.dart` — `MyApp` widget that builds a
///    `MaterialApp.router` configured with [appRouter].
///  * `<outputDir>/routing/app_router.dart` — `final GoRouter appRouter =
///    GoRouter(routes: getAllRoutes());`.
///
/// When `xray: true` is passed (issue #360), `main.dart` additionally
/// starts the X-Ray bridge server in debug mode and invokes
/// `registerAllXRayDecks()` (from the barrel at
/// `<outputDir>/xray/xray_decks.dart`), and `my_app.dart` wraps
/// `MaterialApp.router` in an `XRayScope(viewId: 'App', ...)`. The
/// barrel file is emitted by [buildXRayDecksBarrel] so the import always
/// resolves.
///
/// The `app/` and `routing/` glue files land under the configured output
/// directory (default `lib/src`), and `buildMain` derives its `package:`
/// imports from that same directory so the emitted entrypoint always
/// resolves to the written files.
///
/// All three files are stamped with a `// Generated by zfa` header so
/// subsequent `zfa` runs can identify them. They are *not* wrapped in
/// the AST merge engine's `// GENERATED - DO NOT EDIT` markers — those
/// are reserved for files regenerated by `zfa build` from annotations,
/// and these glue files are emitted by an explicit `zfa app shell`
/// invocation, not by build_runner. `--force` is the explicit opt-in for
/// re-generation when the user wants to refresh them.
class AppShellBuilder {
  final SpecLibrary specLibrary;

  const AppShellBuilder({this.specLibrary = const SpecLibrary()});

  /// Builds `lib/main.dart`.
  ///
  /// [appName] is the Dart package name (from `pubspec.yaml`); used to
  /// import the generated DI barrel at
  /// `package:<appName>/<outputDir>/di/index.dart` (and the MyApp widget
  /// at `package:<appName>/<outputDir>/app/my_app.dart`).
  /// [outputDir] is the project-root-relative directory the `app/` and
  /// `routing/` glue files were written to (default `lib/src`); the
  /// entrypoint always lands at `lib/main.dart`, so the package imports
  /// are derived from [outputDir] relative to `lib/` — this keeps the
  /// emitted imports in sync with a non-default `--output`.
  /// [mockHint] controls whether a `// Mock DI mode` hint comment is
  /// emitted (purely informational — the mock-vs-real decision is made
  /// at DI-generation time via `zfa di <Entity> --use-mock`, and
  /// `setupDependencies(...)` already wires whatever was generated).
  ///
  /// [diTakesGetIt] selects the call signature emitted in `main.dart`.
  /// When `true` (the canonical `zfa di` / `zfa make --with=di` case,
  /// whose DI declares `void setupDependencies(GetIt getIt)`), main.dart
  /// imports `package:zuraffa/zuraffa.dart` — which re-exports `GetIt` —
  /// and passes `GetIt.instance` into `setupDependencies`. When `false`
  /// (a no-arg custom DI entrypoint), it calls `setupDependencies()`.
  ///
  /// [diIsAsync] selects whether main.dart `await`s the call. The canonical
  /// zfa DI declares `void setupDependencies(GetIt getIt)` (synchronous), so
  /// awaiting it is a `use_of_void_result` error; main.dart must call it
  /// synchronously (`void main() { setupDependencies(GetIt.instance); ... }`).
  /// A custom async DI (`Future<void> ... async`) gets an `async` main that
  /// `await`s it so runApp never runs before DI completes. The command
  /// derives both flags from the emitted declaration via
  /// [setupDependenciesTakesGetIt] / [setupDependenciesIsAsync] so the two
  /// generators can never disagree again. See issue #370.
  String buildMain({
    required String appName,
    bool mockHint = false,
    String outputDir = 'lib/src',
    bool diTakesGetIt = false,
    bool diIsAsync = false,
    bool xray = false,
  }) {
    // main.dart lives at lib/main.dart, so package: imports must resolve
    // relative to lib/. Map the output dir ("lib/src" -> "src",
    // "lib/custom" -> "custom", "lib" -> "").
    final importBase = _packageImportBase(outputDir);
    final myAppImport = importBase.isEmpty
        ? 'package:$appName/app/my_app.dart'
        : 'package:$appName/$importBase/app/my_app.dart';
    final diImport = importBase.isEmpty
        ? 'package:$appName/di/index.dart'
        : 'package:$appName/$importBase/di/index.dart';
    final xrayDecksImport = importBase.isEmpty
        ? 'package:$appName/xray/xray_decks.dart'
        : 'package:$appName/$importBase/xray/xray_decks.dart';

    final directives = <Directive>[
      Directive.import('package:flutter/widgets.dart'),
      Directive.import(myAppImport),
      Directive.import(diImport),
      if (xray) ...[
        Directive.import('package:flutter/foundation.dart'),
        Directive.import(xrayDecksImport),
        // Track 4.2 — Spec 036 (issue #181): pure-Dart XRayOverlayState
        // registry that the Flutter painter subscribes to for live
        // bounding-box snapshots. Tree-shaken in release builds because
        // the activate() call below sits inside `if (kDebugMode)`.
        Directive.import(
          'package:zuraffa/src/plugins/xray/xray_overlay.dart',
        ),
      ],
    ];
    if (diTakesGetIt) {
      // `GetIt` is re-exported by `package:zuraffa/zuraffa.dart` (the same
      // import the DI `service_locator.dart` uses), so generated apps —
      // which already depend on `zuraffa` for their DI tree — can resolve
      // it without adding `get_it` as a direct dependency. main.dart needs
      // `GetIt` only to pass `GetIt.instance` into `setupDependencies`.
      directives.add(Directive.import('package:zuraffa/zuraffa.dart'));
    }

    // Mirror the generated DI's `setupDependencies` signature: pass
    // `GetIt.instance` for the canonical GetIt-based DI, or no args for a
    // no-arg custom entrypoint. `await` ONLY when the DI is async —
    // awaiting the canonical `void setupDependencies(GetIt getIt)` is a
    // `use_of_void_result` error. With both flags derived from the emitted
    // declaration, the call always matches the signature, so the mismatch
    // that caused issue #370 is structurally impossible.
    final setupArgs = diTakesGetIt ? [refer('GetIt.instance')] : <Expression>[];
    final setupCall = refer('setupDependencies').call(setupArgs);
    final setupStatement = diIsAsync
        ? setupCall.awaited.statement
        : setupCall.statement;

    // `MethodModifier` has no `sync` value, so only switch to `async` when
    // the DI is actually async — leaving the modifier unset emits a plain
    // `void main() { ... }`, which is correct for the canonical synchronous
    // DI. The modifier must be set inside the builder closure (Method is an
    // immutable built_value, so `main.modifier = ...` after construction is
    // not allowed). When `xray: true`, main also needs `async` for the
    // `await _startXRayBridge()` / `registerAllXRayDecks()` calls.
    final bodyStatements = <Code>[setupStatement];
    if (xray) {
      // Emit:
      //   if (kDebugMode) {
      //     await _startXRayBridge();
      //     registerAllXRayDecks();
      //     XRayOverlayState.instance.activate();
      //   }
      //
      // Track 4.2 — Spec 036 (issue #181): the activate() call boots
      // the pure-Dart overlay registry so the Flutter painter can
      // subscribe to box snapshots on the first paint. Tree-shaken in
      // release builds because it sits inside `if (kDebugMode)`.
      bodyStatements.add(
        Code(
          'if (kDebugMode) {\n'
          '  await _startXRayBridge();\n'
          '  registerAllXRayDecks();\n'
          '  XRayOverlayState.instance.activate();\n'
          '}',
        ),
      );
    }
    bodyStatements.add(
      refer('runApp').call([CodeExpression(Code('const MyApp()'))]).statement,
    );

    final main = Method((m) {
      m
        ..name = 'main'
        ..returns = refer('void')
        ..body = Block((b) => b.statements.addAll(bodyStatements));
      if (diIsAsync || xray) {
        m.modifier = MethodModifier.async;
      }
    });

    final specs = <Spec>[main];

    final leadingParts = <String>['// Generated by zfa'];
    if (mockHint) {
      leadingParts.add(
        '// Mock DI mode: setupDependencies() wires mock datasources\n'
        '// generated via `zfa di <Entity> --use-mock`.',
      );
    }
    if (xray) {
      leadingParts.add(
        '// X-Ray wiring (issue #360): bridge server starts in debug mode,\n'
        '// Control Deck entries are registered via registerAllXRayDecks()\n'
        '// (see <outputDir>/xray/xray_decks.dart, maintained by '
        '`zfa xray deck`).\n'
        '// X-Ray Visual Overlay (issue #181 — Track 4.2, spec 036):\n'
        '// The pure-Dart overlay registry is activated inside the\n'
        '// kDebugMode guard below so the Flutter painter can subscribe\n'
        '// to live bounding-box snapshots. Tree-shaken in release\n'
        '// builds (SC-004).',
      );
    }
    final leading = leadingParts.join('\n');

    final library = specLibrary.library(specs: specs, directives: directives);

    var emittedCode = specLibrary.emitLibrary(
      library,
      leadingComment: leading,
      wrapWithGeneratedMarkers: false,
    );

    // Add platform-safe bridge launcher when xray is enabled
    if (xray) {
      // Add conditional import for XRayBridgeServer
      emittedCode = emittedCode.replaceFirst(
        "import 'package:flutter/foundation.dart';",
        "import 'package:flutter/foundation.dart';\n"
            "import 'xray_bridge_launcher_stub.dart'\n"
            "    if (dart.library.io) 'package:zuraffa_flutter/src/presentation/xray/xray_bridge_server.dart';",
      );

      final bridgeLauncher = '''

/// Platform-safe X-Ray bridge launcher.
/// On web: no-op (dart:io unavailable).
/// On other platforms: starts XRayBridgeServer if available.
Future<void> _startXRayBridge() async {
  const hasDartIo = bool.fromEnvironment('dart.library.io', defaultValue: true);
  if (hasDartIo) {
    // Import XRayBridgeServer conditionally (only on non-web platforms)
    await XRayBridgeServer().start();
  }
  // Web: no-op (this function returns immediately)
}
''';
      emittedCode = emittedCode + bridgeLauncher;
    }

    return emittedCode;
  }

  /// Builds `lib/src/app/my_app.dart`.
  ///
  /// Emits a `MyApp` StatelessWidget that returns a `MaterialApp.router`
  /// bound to [appRouter]. The optional [title] is used as the
  /// MaterialApp title. The default theme is the framework light theme
  /// — generated apps are expected to layer their own theme on top, but
  /// the shell must compile and render out of the box.
  ///
  /// When [xray] is true (issue #360), the `MaterialApp.router` is
  /// wrapped in `XRayScope(viewId: 'App', child: ...)` so the bridge
  /// server can serialize the widget tree. `XRayScope` is a no-op
  /// pass-through when X-Ray mode is disabled.
  String buildMyApp({String? title, bool xray = false}) {
    // No direct go_router import: MyApp never references a go_router
    // symbol (MaterialApp.router comes from material.dart; appRouter
    // arrives via ../routing/app_router.dart, which imports go_router
    // itself). A direct import here is an unused_import — the only
    // analyzer complaint left on a freshly generated shell, and it made
    // `flutter analyze` exit 1 on every generated app (issue #469
    // follow-up). In xray mode the zuraffa_flutter barrel re-exports
    // go_router anyway, so downstream symbols stay reachable.
    final directives = <Directive>[
      Directive.import('package:flutter/material.dart'),
      Directive.import('../routing/app_router.dart'),
      if (xray)
        Directive.import('package:zuraffa_flutter/zuraffa_flutter.dart'),
    ];

    final materialApp = refer('MaterialApp').property('router').call([], {
      'title': literalString(title ?? 'Zuraffa App'),
      'routerConfig': refer('appRouter'),
      'debugShowCheckedModeBanner': literalFalse,
    });

    final returnedWidget = xray
        ? refer(
            'XRayScope',
          ).call([], {'viewId': literalString('App'), 'child': materialApp})
        : materialApp;

    final myApp = Class(
      (c) => c
        ..name = 'MyApp'
        ..extend = refer('StatelessWidget')
        ..constructors.add(
          Constructor(
            (ctor) => ctor
              ..constant = true
              // A `super.key` *invocation* in the initializer list would
              // emit `const MyApp() : super.key();`, which does not compile
              // — StatelessWidget has no constructor named `key`. Emit a
              // super *parameter* instead (`const MyApp({super.key});`),
              // same pattern as the view template generator.
              ..optionalParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'key'
                    ..type = refer('Key?')
                    ..named = true
                    ..toSuper = true,
                ),
              ),
          ),
        )
        ..methods.add(
          Method(
            (m) => m
              ..name = 'build'
              ..returns = refer('Widget')
              ..annotations.add(refer('override'))
              ..requiredParameters.add(
                Parameter(
                  (p) => p
                    ..name = 'context'
                    ..type = refer('BuildContext'),
                ),
              )
              ..body = returnedWidget.returned.statement,
          ),
        ),
    );

    final library = specLibrary.library(specs: [myApp], directives: directives);

    return specLibrary.emitLibrary(
      library,
      leadingComment: '// Generated by zfa',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Builds `lib/src/routing/app_router.dart`.
  ///
  /// Emits a top-level `final GoRouter appRouter = GoRouter(routes:
  /// getAllRoutes());` wired to the generated `getAllRoutes()` from
  /// `lib/src/routing/index.dart`.
  String buildAppRouter() {
    final directives = [
      Directive.import('package:go_router/go_router.dart'),
      Directive.import('index.dart'),
    ];

    final appRouter = Field(
      (f) => f
        ..name = 'appRouter'
        ..type = refer('GoRouter')
        ..modifier = FieldModifier.final$
        ..assignment = refer(
          'GoRouter',
        ).call([], {'routes': refer('getAllRoutes').call([])}).code,
    );

    final library = specLibrary.library(
      specs: [appRouter],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment: '// Generated by zfa',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Returns `true` if [diIndexContent] declares a `setupDependencies`
  /// function (i.e. contains a real `setupDependencies(...)` declaration,
  /// not just a mention in a comment or string).
  ///
  /// Used by the app-shell pre-flight check to fail loudly when the DI
  /// barrel is missing the entrypoint — issue #370 showed the old
  /// substring check accepted a file that only mentioned the name in a
  /// comment, then emitted a non-compiling main.dart. Stripping comments
  /// first means a `// TODO: setupDependencies()` no longer passes the
  /// check. See issue #370.
  static bool hasSetupDependenciesDeclaration(String diIndexContent) {
    return RegExp(
      r'setupDependencies\s*\(',
    ).hasMatch(_stripComments(diIndexContent));
  }

  /// Returns `true` if the `setupDependencies` declaration in
  /// [diIndexContent] declares a `GetIt` parameter — the canonical
  /// signature emitted by `zfa di` / `zfa make --with=di`
  /// (`void setupDependencies(GetIt getIt)`).
  ///
  /// The app-shell command uses this to decide whether `main.dart` must
  /// call `setupDependencies(GetIt.instance)` (canonical GetIt-based DI)
  /// or `setupDependencies()` (a no-arg custom DI entrypoint). Detecting
  /// the actual signature — instead of assuming one — keeps the shell
  /// robust to both signatures. An unrecognized signature falls back to
  /// `setupDependencies()` and may fail during compilation rather than
  /// being rejected as a hard error. See issue #370.
  static bool setupDependenciesTakesGetIt(String diIndexContent) {
    final src = _stripComments(diIndexContent);
    // Match the first `setupDependencies(...)` occurrence. The DI barrel
    // declares the function at top level, so the first match is the
    // declaration (a call site like `setupDependencies(getIt)` inside a
    // body would only appear after the declaration and is never matched).
    // `[^)]*` is sufficient because DI declarations are single-line.
    final match = RegExp(r'setupDependencies\s*\(([^)]*)\)').firstMatch(src);
    if (match == null) return false;
    final params = match.group(1)!.trim();
    if (params.isEmpty) return false; // no-arg: setupDependencies()
    // The canonical DI declares `GetIt getIt`; accept any parameter list
    // referencing `GetIt` (positional or named) so custom DI variants
    // that accept extra options still route to the GetIt.instance call.
    return RegExp(r'\bGetIt\b').hasMatch(params);
  }

  /// Returns `true` if the `setupDependencies` declaration in
  /// [diIndexContent] is asynchronous — i.e. its return type mentions
  /// `Future` or it carries the `async` modifier.
  ///
  /// The canonical zfa DI declares `void setupDependencies(GetIt getIt)`
  /// (synchronous), so main.dart must NOT `await` it (that would be a
  /// `use_of_void_result` error). A custom async DI
  /// (`Future<void> setupDependencies(...) async`) gets an `async` main
  /// that `await`s it so runApp never races the DI setup. See issue #370.
  static bool setupDependenciesIsAsync(String diIndexContent) {
    final src = _stripComments(diIndexContent);
    // Match `<retType> setupDependencies(<params>) [async]` — the top-level
    // DI declaration. `retType` is a single type token (word chars + generic
    // brackets, e.g. `void`, `Future<void>`, `Future`).
    final m = RegExp(
      r'([A-Za-z_][\w<>]*)\s+setupDependencies\s*\(([^)]*)\)\s*(async)?',
    ).firstMatch(src);
    if (m == null) return false;
    final retType = m.group(1) ?? '';
    final asyncKw = m.group(3);
    return asyncKw != null ||
        RegExp(r'\b(Future|FutureOr)\b').hasMatch(retType);
  }

  /// Strips Dart `//` line comments and `/* */` block comments from [src]
  /// so signature detection looks at real code, not doc/TODO text. A
  /// `// TODO: call setupDependencies()` no longer counts as a declaration.
  /// String literals containing the name are an unlikely edge case in a DI
  /// barrel and intentionally not handled (parsing Dart string escapes
  /// here would add far more risk than value).
  static String _stripComments(String src) {
    src = src.replaceAll(RegExp(r'/\*[\s\S]*?\*/'), ''); // block comments
    src = src.replaceAll(RegExp(r'//[^\n]*'), ''); // line comments
    return src;
  }

  /// Builds `<outputDir>/xray/xray_decks.dart` — the Control Deck
  /// registration barrel consumed by [buildMain] when `xray: true`.
  ///
  /// Emits a top-level `void registerAllXRayDecks()` that is a no-op in
  /// release mode. `zfa xray deck` appends per-entity
  /// `register<Entity>XRayDeck()` calls (and their imports) into this
  /// file via the AST merge engine, so the barrel always compiles even
  /// before any deck has been generated.
  ///
  /// Pass [existingRegistrations] to preserve calls already present in
  /// an earlier version of the barrel (used by `zfa xray deck` when it
  /// rewrites the barrel). The app-shell command passes an empty list
  /// on first generation.
  String buildXRayDecksBarrel({
    List<String> deckImports = const [],
    List<String> registrationCalls = const [],
  }) {
    final directives = <Directive>[
      Directive.import('package:flutter/foundation.dart'),
      ...deckImports.map((uri) => Directive.import(uri)),
    ];

    final body = StringBuffer();
    body.writeln('  if (kReleaseMode) return;');
    if (registrationCalls.isEmpty) {
      body.writeln(
        '  // Registration calls are appended here by `zfa xray deck`.',
      );
      body.writeln(
        '  // Each `zfa xray deck --entity <Entity>` invocation adds a',
      );
      body.writeln('  // `register<Entity>XRayDeck();` call below.');
    } else {
      for (final call in registrationCalls) {
        body.writeln('  $call');
      }
    }

    final registerAll = Method(
      (m) => m
        ..name = 'registerAllXRayDecks'
        ..returns = refer('void')
        ..body = Code(body.toString()),
    );

    final library = specLibrary.library(
      specs: [registerAll],
      directives: directives,
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment:
          '// Generated by zfa — X-Ray Control Deck registration barrel.\n'
          '// This file is maintained by `zfa xray deck`. Each invocation\n'
          '// appends a `register<Entity>XRayDeck()` call below. Safe to\n'
          '// edit manually — `zfa xray deck` preserves existing calls.',
      wrapWithGeneratedMarkers: false,
    );
  }

  /// Builds `lib/xray_bridge_launcher_stub.dart` — the web-safe default
  /// branch of the conditional import emitted by [buildMain] when
  /// `xray: true` (issue #469).
  ///
  /// `lib/main.dart` imports this file unconditionally and swaps in the
  /// real bridge server on Dart-VM / Flutter-native builds:
  ///
  /// ```dart
  /// import 'xray_bridge_launcher_stub.dart'
  ///     if (dart.library.io)
  ///       'package:zuraffa_flutter/src/presentation/xray/xray_bridge_server.dart';
  /// ```
  ///
  /// On the web `dart:io` is unavailable, so this stub provides a no-op
  /// stand-in with the same surface as the real `XRayBridgeServer` — the
  /// analyzer resolves both import branches, and `_startXRayBridge()`
  /// stays a no-op at runtime.
  String buildXRayBridgeLauncherStub() {
    return '// Generated by zfa — web-safe X-Ray bridge launcher stub '
        '(issue #469).\n'
        '//\n'
        '// lib/main.dart imports this file as the default branch of a\n'
        '// conditional import; Dart-VM / Flutter-native builds swap in the\n'
        '// real bridge server via `if (dart.library.io)`. On the web\n'
        '// dart:io is unavailable, so the bridge never starts there and\n'
        '// this no-op stand-in keeps the entrypoint compiling.\n'
        '\n'
        '/// No-op stand-in for the X-Ray bridge server on platforms without\n'
        '/// dart:io. Mirrors the real server\'s surface so the conditional\n'
        '/// import resolves identically on every platform.\n'
        'class XRayBridgeServer {\n'
        '  /// Starts the bridge. No-op on the web; returns 0 to match the\n'
        '  /// real server\'s port result shape.\n'
        '  Future<int> start() async => 0;\n'
        '}\n';
  }

  /// Returns the Dart package name declared in [pubspecContent] or `null`
  /// if it cannot be parsed. Used by the command to wire imports.
  static String? parseAppName(String pubspecContent) {
    final m = RegExp(
      r'^name:\s*([A-Za-z][A-Za-z0-9_]*)',
      multiLine: true,
    ).firstMatch(pubspecContent);
    return m?.group(1);
  }

  /// Maps a project-root-relative [outputDir] (e.g. `lib/src`, `lib/custom`)
  /// to the package-import base used by main.dart — the path relative to
  /// `lib/` (e.g. `src`, `custom`). Returns `''` when the output dir is
  /// `lib/` itself. The command rejects dirs outside `lib/`, so this never
  /// sees an escaping path in practice.
  static String _packageImportBase(String outputDir) {
    final rel = p.relative(outputDir, from: 'lib');
    return rel == '.' ? '' : rel;
  }
}
