// GENERATED - DO NOT EDIT
// Generated by zfa for: ChatSession
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/chat_session/chat_session.dart';
import '../../repositories/chat_session_repository.dart';

class ToggleChatSessionUseCase
    extends
        UseCase<
          ChatSession,
          ToggleParams<String, Field<ChatSession, dynamic>>
        > {
  ToggleChatSessionUseCase(this._repository);

  final ChatSessionRepository _repository;

  @override
  Future<ChatSession> execute(
    ToggleParams<String, Field<ChatSession, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
