// GENERATED - DO NOT EDIT
// Generated by zfa for: UrlListing
// zfa make UrlListing --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/url_listing/url_listing.dart';
import '../../domain/repositories/url_listing_repository.dart';
import '../datasources/url_listing/url_listing_datasource.dart';

class DataUrlListingRepository
    with Loggable, FailureHandler
    implements UrlListingRepository {
  DataUrlListingRepository(this._dataSource);

  final UrlListingDataSource _dataSource;

  @override
  Future<UrlListing> get(QueryParams<UrlListing> params) {
    return _dataSource.get(params);
  }

  @override
  Future<UrlListing> update(UpdateParams<String, UrlListingPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<UrlListing> toggle(
    ToggleParams<String, Field<UrlListing, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
