// GENERATED - DO NOT EDIT
// Generated by zfa for: TextSpark
// zfa make TextSpark --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/text_spark/text_spark.dart';
import '../../domain/repositories/text_spark_repository.dart';
import '../datasources/text_spark/text_spark_datasource.dart';

class DataTextSparkRepository
    with Loggable, FailureHandler
    implements TextSparkRepository {
  DataTextSparkRepository(this._dataSource);

  final TextSparkDataSource _dataSource;

  @override
  Future<TextSpark> get(QueryParams<TextSpark> params) {
    return _dataSource.get(params);
  }

  @override
  Future<TextSpark> update(UpdateParams<String, TextSparkPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<TextSpark> toggle(
    ToggleParams<String, Field<TextSpark, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
