// GENERATED - DO NOT EDIT
// Generated by zfa for: Walkthrough
// zfa make Walkthrough --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/walkthrough/walkthrough.dart';
import '../../domain/repositories/walkthrough_repository.dart';
import '../datasources/walkthrough/walkthrough_datasource.dart';

class DataWalkthroughRepository
    with Loggable, FailureHandler
    implements WalkthroughRepository {
  DataWalkthroughRepository(this._dataSource);

  final WalkthroughDataSource _dataSource;

  @override
  Future<Walkthrough> get(QueryParams<Walkthrough> params) {
    return _dataSource.get(params);
  }

  @override
  Future<Walkthrough> update(UpdateParams<String, WalkthroughPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<Walkthrough> toggle(
    ToggleParams<String, Field<Walkthrough, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
