// GENERATED - DO NOT EDIT
// Generated by zfa for: FormOption
// zfa make FormOption --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/form_option/form_option.dart';
import '../../domain/repositories/form_option_repository.dart';
import '../datasources/form_option/form_option_datasource.dart';

class DataFormOptionRepository
    with Loggable, FailureHandler
    implements FormOptionRepository {
  DataFormOptionRepository(this._dataSource);

  final FormOptionDataSource _dataSource;

  @override
  Future<FormOption> get(QueryParams<FormOption> params) {
    return _dataSource.get(params);
  }

  @override
  Future<FormOption> update(UpdateParams<String, FormOptionPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<FormOption> toggle(
    ToggleParams<String, Field<FormOption, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
