// GENERATED - DO NOT EDIT
// Generated by zfa for: GroceryProduct
// zfa make GroceryProduct --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/grocery_product/grocery_product.dart';
import '../../domain/repositories/grocery_product_repository.dart';
import '../datasources/grocery_product/grocery_product_datasource.dart';

class DataGroceryProductRepository
    with Loggable, FailureHandler
    implements GroceryProductRepository {
  DataGroceryProductRepository(this._dataSource);

  final GroceryProductDataSource _dataSource;

  @override
  Future<GroceryProduct> get(QueryParams<GroceryProduct> params) {
    return _dataSource.get(params);
  }

  @override
  Future<GroceryProduct> update(
    UpdateParams<String, GroceryProductPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<GroceryProduct> toggle(
    ToggleParams<String, Field<GroceryProduct, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
