// GENERATED - DO NOT EDIT
// Generated by zfa for: MetricDetail
// zfa make MetricDetail --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/metric_detail/metric_detail.dart';
import '../../domain/repositories/metric_detail_repository.dart';
import '../datasources/metric_detail/metric_detail_datasource.dart';

class DataMetricDetailRepository
    with Loggable, FailureHandler
    implements MetricDetailRepository {
  DataMetricDetailRepository(this._dataSource);

  final MetricDetailDataSource _dataSource;

  @override
  Future<MetricDetail> get(QueryParams<MetricDetail> params) {
    return _dataSource.get(params);
  }

  @override
  Future<MetricDetail> update(UpdateParams<String, MetricDetailPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<MetricDetail> toggle(
    ToggleParams<String, Field<MetricDetail, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
