// GENERATED - DO NOT EDIT
// Generated by zfa for: WalkthroughView
// zfa make WalkthroughView --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/walkthrough_view/walkthrough_view.dart';
import '../../domain/repositories/walkthrough_view_repository.dart';
import '../datasources/walkthrough_view/walkthrough_view_datasource.dart';

class DataWalkthroughViewRepository
    with Loggable, FailureHandler
    implements WalkthroughViewRepository {
  DataWalkthroughViewRepository(this._dataSource);

  final WalkthroughViewDataSource _dataSource;

  @override
  Future<WalkthroughView> get(QueryParams<WalkthroughView> params) {
    return _dataSource.get(params);
  }

  @override
  Future<WalkthroughView> update(
    UpdateParams<String, WalkthroughViewPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<WalkthroughView> toggle(
    ToggleParams<String, Field<WalkthroughView, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
