// GENERATED - DO NOT EDIT
// Generated by zfa for: ChatSession
// zfa make ChatSession --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/chat_session/chat_session.dart';
import '../../domain/repositories/chat_session_repository.dart';
import '../datasources/chat_session/chat_session_datasource.dart';

class DataChatSessionRepository
    with Loggable, FailureHandler
    implements ChatSessionRepository {
  DataChatSessionRepository(this._dataSource);

  final ChatSessionDataSource _dataSource;

  @override
  Future<ChatSession> get(QueryParams<ChatSession> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ChatSession> update(UpdateParams<String, ChatSessionPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<ChatSession> toggle(
    ToggleParams<String, Field<ChatSession, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
