// GENERATED - DO NOT EDIT
// Generated by zfa for: TelemetryEvent
// zfa make TelemetryEvent --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/telemetry_event/telemetry_event.dart';
import '../../domain/repositories/telemetry_event_repository.dart';
import '../datasources/telemetry_event/telemetry_event_datasource.dart';

class DataTelemetryEventRepository
    with Loggable, FailureHandler
    implements TelemetryEventRepository {
  DataTelemetryEventRepository(this._dataSource);

  final TelemetryEventDataSource _dataSource;

  @override
  Future<TelemetryEvent> get(QueryParams<TelemetryEvent> params) {
    return _dataSource.get(params);
  }

  @override
  Future<TelemetryEvent> update(
    UpdateParams<String, TelemetryEventPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<TelemetryEvent> toggle(
    ToggleParams<String, Field<TelemetryEvent, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
