// GENERATED - DO NOT EDIT
// Generated by zfa for: ListingOffer
// zfa make ListingOffer --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/listing_offer/listing_offer.dart';
import '../../domain/repositories/listing_offer_repository.dart';
import '../datasources/listing_offer/listing_offer_datasource.dart';

class DataListingOfferRepository
    with Loggable, FailureHandler
    implements ListingOfferRepository {
  DataListingOfferRepository(this._dataSource);

  final ListingOfferDataSource _dataSource;

  @override
  Future<ListingOffer> get(QueryParams<ListingOffer> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ListingOffer> update(UpdateParams<String, ListingOfferPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<ListingOffer> toggle(
    ToggleParams<String, Field<ListingOffer, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
