// GENERATED - DO NOT EDIT
// Generated by zfa for: ChatMessage
// zfa make ChatMessage --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/chat_message/chat_message.dart';
import '../../domain/repositories/chat_message_repository.dart';
import '../datasources/chat_message/chat_message_datasource.dart';

class DataChatMessageRepository
    with Loggable, FailureHandler
    implements ChatMessageRepository {
  DataChatMessageRepository(this._dataSource);

  final ChatMessageDataSource _dataSource;

  @override
  Future<ChatMessage> get(QueryParams<ChatMessage> params) {
    return _dataSource.get(params);
  }

  @override
  Future<ChatMessage> update(UpdateParams<String, ChatMessagePatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<ChatMessage> toggle(
    ToggleParams<String, Field<ChatMessage, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
