// GENERATED - DO NOT EDIT
// Generated by zfa for: Listing
// zfa make Listing --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/listing/listing.dart';
import '../../domain/repositories/listing_repository.dart';
import '../datasources/listing/listing_datasource.dart';

class DataListingRepository
    with Loggable, FailureHandler
    implements ListingRepository {
  DataListingRepository(this._dataSource);

  final ListingDataSource _dataSource;

  @override
  Future<Listing> get(QueryParams<Listing> params) {
    return _dataSource.get(params);
  }

  @override
  Future<Listing> update(UpdateParams<String, ListingPatch> params) {
    return _dataSource.update(params);
  }

  @override
  Future<Listing> toggle(ToggleParams<String, Field<Listing, dynamic>> params) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
