// GENERATED - DO NOT EDIT
// Generated by zfa for: GrocerySubVariety
// zfa make GrocerySubVariety --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../../domain/entities/grocery_sub_variety/grocery_sub_variety.dart';
import '../../domain/repositories/grocery_sub_variety_repository.dart';
import '../datasources/grocery_sub_variety/grocery_sub_variety_datasource.dart';

class DataGrocerySubVarietyRepository
    with Loggable, FailureHandler
    implements GrocerySubVarietyRepository {
  DataGrocerySubVarietyRepository(this._dataSource);

  final GrocerySubVarietyDataSource _dataSource;

  @override
  Future<GrocerySubVariety> get(QueryParams<GrocerySubVariety> params) {
    return _dataSource.get(params);
  }

  @override
  Future<GrocerySubVariety> update(
    UpdateParams<String, GrocerySubVarietyPatch> params,
  ) {
    return _dataSource.update(params);
  }

  @override
  Future<GrocerySubVariety> toggle(
    ToggleParams<String, Field<GrocerySubVariety, dynamic>> params,
  ) {
    return _dataSource.toggle(params);
  }
}

// END GENERATED
