import 'package:path/path.dart' as path;

import '../../../config/zfa_config.dart';
import '../../../core/context/file_system.dart';
import '../../../core/generator_options.dart';
import '../../../core/planning/preset_registry.dart';
import '../../../core/plugin_system/plugin_context.dart';
import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';

class AdaptiveLayoutScaffoldBuilder {
  final String outputDir;
  final GeneratorOptions options;
  final FileSystem fileSystem;

  const AdaptiveLayoutScaffoldBuilder({
    required this.outputDir,
    required this.options,
    required this.fileSystem,
  });

  Future<List<GeneratedFile>> generate(
    GeneratorConfig config, {
    required String viewName,
    required String domainSnake,
    required String controllerName,
    required String presenterName,
    required bool withState,
    PluginContext? context,
  }) async {
    if (!_isAdaptiveEnabled(config, context)) {
      return const <GeneratedFile>[];
    }

    final targets = _resolveTargets(config, context);
    final layoutDir = path.join(
      outputDir,
      'presentation',
      'pages',
      domainSnake,
      'layouts',
    );
    final controllerSnake = StringUtils.camelToSnake(
      controllerName.replaceAll('Controller', ''),
    );
    final presenterSnake = StringUtils.camelToSnake(
      presenterName.replaceAll('Presenter', ''),
    );
    final stateSnake = config.nameSnake;
    final baseName = StringUtils.camelToSnake(viewName.replaceAll('View', ''));
    final layoutPrefix = viewName.replaceAll('View', '');

    final files = <GeneratedFile>[];
    for (final target in targets) {
      final layoutClassName =
          '$layoutPrefix${_targetClassSuffix(target)}Layout';
      final filePath = path.join(
        layoutDir,
        '${baseName}_${target}_layout.dart',
      );
      final shellClass = _shellClassForTarget(target);
      final content = _buildLayoutContent(
        title: viewName,
        layoutClassName: layoutClassName,
        controllerName: controllerName,
        controllerSnake: controllerSnake,
        presenterSnake: presenterSnake,
        stateSnake: stateSnake,
        withState: withState,
        shellClass: shellClass,
        target: target,
      );
      files.add(
        await FileUtils.writeFile(
          filePath,
          content,
          'view_layout',
          force: options.force,
          dryRun: options.dryRun,
          verbose: options.verbose,
          revert: config.revert,
          skipRevertIfExisted: true,
          fileSystem: fileSystem,
        ),
      );
    }

    final exports = targets
        .map((target) => "export '${baseName}_${target}_layout.dart';")
        .join('\n');
    files.add(
      await FileUtils.writeFile(
        path.join(layoutDir, '${baseName}_layouts.dart'),
        '// Generated by zfa for: ${config.name}\n$exports\n',
        'view_layout',
        force: options.force,
        dryRun: options.dryRun,
        verbose: options.verbose,
        revert: config.revert,
        skipRevertIfExisted: true,
        fileSystem: fileSystem,
      ),
    );

    return files;
  }

  bool _isAdaptiveEnabled(GeneratorConfig config, PluginContext? context) {
    final data = context?.data ?? const <String, dynamic>{};
    if (data['adaptive-layouts'] == true ||
        data['adaptive_layouts'] == true ||
        data['platform-layouts'] == true ||
        data['platform_layouts'] == true) {
      return true;
    }

    final preset = data['preset']?.toString();
    if (PresetRegistry.isAdaptivePreset(preset)) {
      return true;
    }

    final loadedConfig = ZfaConfig.load(
      projectRoot: _resolveProjectRoot(config),
    );
    return loadedConfig?.adaptiveLayoutsByDefault == true;
  }

  List<String> _resolveTargets(GeneratorConfig config, PluginContext? context) {
    final data = context?.data ?? const <String, dynamic>{};
    final dynamic rawTargets =
        data['layout-targets'] ?? data['layout_targets'] ?? data['layouts'];
    if (rawTargets is List) {
      final targets = rawTargets
          .map((value) => value.toString().trim().toLowerCase())
          .where((value) => value.isNotEmpty)
          .toList(growable: false);
      if (targets.isNotEmpty) {
        return targets;
      }
    }

    final loadedConfig = ZfaConfig.load(
      projectRoot: _resolveProjectRoot(config),
    );
    return loadedConfig?.adaptiveLayoutTargets ??
        ZfaConfig.defaultAdaptiveLayoutTargets;
  }

  String _resolveProjectRoot(GeneratorConfig config) {
    final normalized = path.normalize(config.outputDir);
    final parts = path.split(normalized);
    if (parts.length >= 2 &&
        parts[parts.length - 2] == 'lib' &&
        parts.last == 'src') {
      return path.joinAll(parts.sublist(0, parts.length - 2));
    }
    return path.dirname(normalized);
  }

  String _targetClassSuffix(String target) => switch (target) {
    'mobile' => 'Mobile',
    'tablet' => 'Tablet',
    'desktop' => 'Desktop',
    'macos' => 'Macos',
    _ => StringUtils.capitalize(target),
  };

  String _shellClassForTarget(String target) => switch (target) {
    'mobile' => 'MobileAppShell',
    'tablet' => 'TabletAppShell',
    'desktop' => 'DesktopAppShell',
    'macos' => 'MacosAppShell',
    _ => 'MobileAppShell',
  };

  String _buildLayoutContent({
    required String title,
    required String layoutClassName,
    required String controllerName,
    required String controllerSnake,
    required String presenterSnake,
    required String stateSnake,
    required bool withState,
    required String shellClass,
    required String target,
  }) {
    final stateReference = withState ? " and ../${stateSnake}_state.dart" : '';
    return '''// Generated by zfa adaptive layout scaffold.
import 'package:flutter/material.dart';
import 'package:zuraffa/zuraffa.dart';

import '../${controllerSnake}_controller.dart';

// Shared logic stays in ../${presenterSnake}_presenter.dart, ../${controllerSnake}_controller.dart$stateReference.
class $layoutClassName extends StatelessWidget {
  final $controllerName controller;

  const $layoutClassName({
    super.key,
    required this.controller,
  });

  @override
  Widget build(BuildContext context) {
    return $shellClass(
      title: '$title',
      body: KeyedSubtree(
        key: ValueKey('${target}_layout_
$controllerName'),
        child: ControlledWidgetBuilder<$controllerName>(
          builder: (context, _) {
            return Center(
              child: Text(
                'TODO: Implement $title $target layout',
                textAlign: TextAlign.center,
              ),
            );
          },
        ),
      ),
    );
  }
}
''';
  }
}
