// GENERATED - DO NOT EDIT
import 'package:zuraffa/zuraffa.dart';

import 'ai_conversation_remote_datasource_di.dart';
import 'app_config_remote_datasource_di.dart';
import 'app_notification_remote_datasource_di.dart';
import 'authentication_remote_datasource_di.dart';
import 'barcode_listing_remote_datasource_di.dart';
import 'barcode_spark_remote_datasource_di.dart';
import 'category_remote_datasource_di.dart';
import 'chat_message_remote_datasource_di.dart';
import 'chat_session_remote_datasource_di.dart';
import 'connected_account_remote_datasource_di.dart';
import 'customer_address_remote_datasource_di.dart';
import 'customer_remote_datasource_di.dart';
import 'deal_remote_datasource_di.dart';
import 'device_info_remote_datasource_di.dart';
import 'device_remote_datasource_di.dart';
import 'dynamic_form_field_remote_datasource_di.dart';
import 'dynamic_form_remote_datasource_di.dart';
import 'error_log_remote_datasource_di.dart';
import 'extracted_invoice_remote_datasource_di.dart';
import 'feedback_remote_datasource_di.dart';
import 'form_option_remote_datasource_di.dart';
import 'form_submission_remote_datasource_di.dart';
import 'grocery_item_remote_datasource_di.dart';
import 'grocery_price_comparison_remote_datasource_di.dart';
import 'grocery_product_remote_datasource_di.dart';
import 'grocery_store_remote_datasource_di.dart';
import 'grocery_sub_variety_remote_datasource_di.dart';
import 'listing_offer_remote_datasource_di.dart';
import 'listing_remote_datasource_di.dart';
import 'locale_remote_datasource_di.dart';
import 'nearby_grocery_store_remote_datasource_di.dart';
import 'price_alert_remote_datasource_di.dart';
import 'price_check_invoice_remote_datasource_di.dart';
import 'price_drop_notification_remote_datasource_di.dart';
import 'store_price_remote_datasource_di.dart';
import 'subscription_remote_datasource_di.dart';
import 'telemetry_event_remote_datasource_di.dart';
import 'text_listing_remote_datasource_di.dart';
import 'text_spark_remote_datasource_di.dart';
import 'url_listing_remote_datasource_di.dart';
import 'url_spark_remote_datasource_di.dart';
import 'user_remote_datasource_di.dart';
import 'walkthrough_remote_datasource_di.dart';
import 'walkthrough_step_remote_datasource_di.dart';
import 'walkthrough_view_remote_datasource_di.dart';
import 'zik_zak_config_remote_datasource_di.dart';
import 'zik_zak_remote_datasource_di.dart';
import 'zik_zak_score_remote_datasource_di.dart';

void registerAllDataSources(GetIt getIt) {
  registerAiConversationRemoteDataSource(getIt);
  registerAppConfigRemoteDataSource(getIt);
  registerAppNotificationRemoteDataSource(getIt);
  registerAuthenticationRemoteDataSource(getIt);
  registerBarcodeListingRemoteDataSource(getIt);
  registerBarcodeSparkRemoteDataSource(getIt);
  registerCategoryRemoteDataSource(getIt);
  registerChatMessageRemoteDataSource(getIt);
  registerChatSessionRemoteDataSource(getIt);
  registerConnectedAccountRemoteDataSource(getIt);
  registerCustomerAddressRemoteDataSource(getIt);
  registerCustomerRemoteDataSource(getIt);
  registerDealRemoteDataSource(getIt);
  registerDeviceInfoRemoteDataSource(getIt);
  registerDeviceRemoteDataSource(getIt);
  registerDynamicFormFieldRemoteDataSource(getIt);
  registerDynamicFormRemoteDataSource(getIt);
  registerErrorLogRemoteDataSource(getIt);
  registerExtractedInvoiceRemoteDataSource(getIt);
  registerFeedbackRemoteDataSource(getIt);
  registerFormOptionRemoteDataSource(getIt);
  registerFormSubmissionRemoteDataSource(getIt);
  registerGroceryItemRemoteDataSource(getIt);
  registerGroceryPriceComparisonRemoteDataSource(getIt);
  registerGroceryProductRemoteDataSource(getIt);
  registerGroceryStoreRemoteDataSource(getIt);
  registerGrocerySubVarietyRemoteDataSource(getIt);
  registerListingOfferRemoteDataSource(getIt);
  registerListingRemoteDataSource(getIt);
  registerLocaleRemoteDataSource(getIt);
  registerNearbyGroceryStoreRemoteDataSource(getIt);
  registerPriceAlertRemoteDataSource(getIt);
  registerPriceCheckInvoiceRemoteDataSource(getIt);
  registerPriceDropNotificationRemoteDataSource(getIt);
  registerStorePriceRemoteDataSource(getIt);
  registerSubscriptionRemoteDataSource(getIt);
  registerTelemetryEventRemoteDataSource(getIt);
  registerTextListingRemoteDataSource(getIt);
  registerTextSparkRemoteDataSource(getIt);
  registerUrlListingRemoteDataSource(getIt);
  registerUrlSparkRemoteDataSource(getIt);
  registerUserRemoteDataSource(getIt);
  registerWalkthroughRemoteDataSource(getIt);
  registerWalkthroughStepRemoteDataSource(getIt);
  registerWalkthroughViewRemoteDataSource(getIt);
  registerZikZakConfigRemoteDataSource(getIt);
  registerZikZakRemoteDataSource(getIt);
  registerZikZakScoreRemoteDataSource(getIt);
}

// END GENERATED
