// Auto-generated by Zorphy
// Generated at: 2026-08-13T13:37:40.261810

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../store_price/store_price.dart';

part 'grocery_product.zorphy.dart';
part 'grocery_product.g.dart';

/// GroceryProduct entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $GroceryProduct {
  String get id;
  String get title;
  String? get brand;
  String? get imageUrl;
  String? get volumeOrWeight;
  List<String> get categories;
  String get mainCategory;
  String? get menuCategory;
  List<$StorePrice> get storePrices;
}
