// Generated by zfa

import 'package:zuraffa/zuraffa.dart';
import '../../entities/todo/todo.dart';
import '../../repositories/todo_repository.dart';

class GetTodoListUseCase extends UseCase<List<Todo>, ListQueryParams> {
  final TodoRepository _repository;

  GetTodoListUseCase(this._repository);

  @override
  Future<List<Todo>> execute(ListQueryParams params, CancelToken? cancelToken) async {
    cancelToken?.throwIfCancelled();
    return _repository.getList(params);
  }
}
