// Generated by zfa

import 'package:zuraffa/zuraffa.dart';
import '../../entities/todo/todo.dart';
import '../../repositories/todo_repository.dart';

class WatchTodoUseCase extends StreamUseCase<Todo, QueryParams<Todo>> {
  final TodoRepository _repository;

  WatchTodoUseCase(this._repository);

  @override
  Stream<Todo> execute(QueryParams<Todo> params, CancelToken? cancelToken) {
    cancelToken?.throwIfCancelled();
    return _repository.watch(params);
  }
}
