// Generated by zfa

import 'package:zuraffa/zuraffa.dart';
import '../../entities/todo/todo.dart';
import '../../repositories/todo_repository.dart';

class WatchTodoListUseCase extends StreamUseCase<List<Todo>, ListQueryParams> {
  final TodoRepository _repository;

  WatchTodoListUseCase(this._repository);

  @override
  Stream<List<Todo>> execute(ListQueryParams params, CancelToken? cancelToken) {
    cancelToken?.throwIfCancelled();
    return _repository.watchList(params);
  }
}
