import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/app_shell/builders/app_shell_builder.dart';

/// Regression test for issue #404.
///
/// A bad merge between the X-Ray feature (#367) and the leading/mockHint
/// change left `buildMain` in a broken state:
///   1. `xray` was referenced but not in the parameter list.
///   2. `library` was referenced but never declared as a local.
///   3. `leading` was declared twice (mockHint version + xray-aware version).
///
/// These tests ensure the parameter list, local declarations, and combined
/// flag behaviour stay consistent so a repeat merge cannot break `buildMain`
/// without failing this suite.
void main() {
  const builder = AppShellBuilder();

  group('issue #404 regression: buildMain parameter & local consistency', () {
    test('buildMain accepts xray parameter without error', () {
      expect(
        () => builder.buildMain(appName: 'my_app', xray: true),
        returnsNormally,
      );
    });

    test('buildMain xray=true emits async main', () {
      final src = builder.buildMain(appName: 'my_app', xray: true);
      // code_builder emits the modifier after the return type: "void main() async"
      expect(src, contains('void main() async'));
    });

    test(
      'buildMain xray=true emits kDebugMode guard wrapping registerAllXRayDecks '
      'and _startXRayBridge',
      () {
        final src = builder.buildMain(appName: 'my_app', xray: true);
        // Structural check: the X-Ray calls must live *inside* the
        // `if (kDebugMode) { ... }` block, not merely appear somewhere in the
        // file. A substring/contains check alone would pass even if a bad merge
        // hoisted these calls above the guard and ran debug instrumentation in
        // release mode.
        final guardOpen = src.indexOf('if (kDebugMode) {');
        expect(guardOpen, greaterThan(-1), reason: 'kDebugMode guard missing');
        // The guard body has no nested braces, so the first `}` after the
        // guard opener is its closing brace — the structural boundary.
        final guardClose = src.indexOf('}', guardOpen);
        expect(guardClose, greaterThan(guardOpen),
            reason: 'kDebugMode guard is not closed');

        // registerAllXRayDecks() must be between the guard open and close.
        // Match the *call* (trailing semicolon); the X-Ray header comment
        // also mentions registerAllXRayDecks() in prose and must not match.
        final registerCall = src.indexOf('registerAllXRayDecks();');
        expect(
          registerCall > guardOpen && registerCall < guardClose,
          isTrue,
          reason: 'registerAllXRayDecks() is not inside the kDebugMode guard',
        );

        // The `_startXRayBridge()` *call* (not the file-scope definition) must
        // also be between the guard open and close.
        final bridgeCall = src.indexOf('await _startXRayBridge();');
        expect(
          bridgeCall > guardOpen && bridgeCall < guardClose,
          isTrue,
          reason: 'await _startXRayBridge() is not inside the kDebugMode guard',
        );
      },
    );

    test('buildMain xray=false suppresses all X-Ray instrumentation', () {
      final src = builder.buildMain(appName: 'my_app', xray: false);
      // A regression that unconditionally emits X-Ray code (the kDebugMode
      // guard, the registration call, the bridge launcher, or the header note)
      // would not be caught by the xray=true assertions above.
      expect(src, isNot(contains('if (kDebugMode)')),
          reason: 'xray=false must not emit a kDebugMode guard');
      expect(src, isNot(contains('registerAllXRayDecks()')),
          reason: 'xray=false must not emit registerAllXRayDecks()');
      expect(src, isNot(contains('_startXRayBridge')),
          reason: 'xray=false must not emit the X-Ray bridge launcher');
      expect(src, isNot(contains('X-Ray wiring')),
          reason: 'xray=false must not emit the X-Ray header note');
    });

    test('buildMain emits exactly one leading comment block', () {
      for (final xray in [false, true]) {
        for (final mockHint in [false, true]) {
          final src = builder.buildMain(
            appName: 'my_app',
            xray: xray,
            mockHint: mockHint,
          );
          final headerCount = '// Generated by zfa'.allMatches(src).length;
          expect(
            headerCount,
            equals(1),
            reason: 'expected exactly one zfa header with xray=$xray, mockHint=$mockHint',
          );
        }
      }
    });

    test('buildMain mockHint + xray combined emits both header notes', () {
      final src = builder.buildMain(
        appName: 'my_app',
        mockHint: true,
        xray: true,
      );
      expect(src, contains('Mock DI mode'));
      expect(src, contains('X-Ray wiring (issue #360)'));
    });

    test('buildMain xray=true with diTakesGetIt + diIsAsync runs without error', () {
      expect(
        () => builder.buildMain(
          appName: 'my_app',
          xray: true,
          mockHint: true,
          diTakesGetIt: true,
          diIsAsync: true,
          outputDir: 'lib/custom',
        ),
        returnsNormally,
      );
    });

    test('buildMain all-flags output contains expected structure', () {
      final src = builder.buildMain(
        appName: 'my_app',
        xray: true,
        mockHint: true,
        diTakesGetIt: true,
        diIsAsync: true,
        outputDir: 'lib/src',
      );
      expect(src, contains('void main() async'));
      expect(src, contains('GetIt.instance'));
      expect(src, contains('await setupDependencies('));
      expect(src, contains('registerAllXRayDecks()'));
      expect(src, contains('// Generated by zfa'));
    });
  });
}
