import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/app_shell/builders/app_shell_builder.dart';

/// Regression test for issue #404 — "development is red:
/// app_shell_builder.dart buildMain references undefined xray/library
/// and declares leading twice".
///
/// Issue #404 reported that `AppShellBuilder.buildMain` (as of development
/// @ f793e17) was in a broken merged state after a bad merge between the
/// X-Ray feature (#367) and the leading/mockHint refactor:
///
///   1. `buildMain` referenced `xray` (lines 106, 173, 190) but had no
///      `xray` parameter in its signature — every `if (xray) ...` branch
///      referenced an undefined getter.
///   2. `buildMain` referenced `library` (line 184) but never declared a
///      `library` local — `buildMyApp` and `buildAppRouter` each declared
///      their own, but `buildMain` did not.
///   3. `buildMain` declared `leading` twice (the mockHint version at
///      lines 162-164 and the xray-aware version at lines 166-181) — a
///      "Previous declaration of 'leading'" compile error.
///
/// The fix landed in master commit 03b90b4 ("restore xray param +
/// buildXRayDecksBarrel in AppShellBuilder, fix format") and was merged
/// into development via 835c9eb. The fix:
///   - Restored `bool xray = false` to the parameter list.
///   - Added `final library = specLibrary.library(specs: specs, ...);`
///     so `library` is declared locally.
///   - Consolidated the two `leading` declarations into a single
///     `leadingParts.join('\n')` computation that accounts for both
///     `mockHint` and `xray`.
///
/// This test locks in the fix so the bad merge cannot recur. It focuses
/// on the *merged* state (`mockHint: true` + `xray: true`) — the exact
/// combination the bad merge broke — which is not exercised by the
/// existing `app_shell_builder_test.dart` or `app_shell_xray_test.dart`
/// suites (those cover the two flags in isolation).
void main() {
  const builder = AppShellBuilder();

  group('issue #404 — AppShellBuilder.buildMain merged state', () {
    // Concern 1: buildMain must accept an `xray` parameter so the X-Ray
    // wiring can be threaded from the `app shell` command. The original
    // bad merge dropped the parameter, leaving every `if (xray) ...`
    // branch referencing an undefined getter.
    test('accepts an `xray` parameter (default false)', () {
      // Calling buildMain with xray explicitly set must not throw.
      final srcOff = builder.buildMain(appName: 'my_app', xray: false);
      final srcOn = builder.buildMain(appName: 'my_app', xray: true);
      expect(srcOff, isNotEmpty);
      expect(srcOn, isNotEmpty);
      // Default value must be false — without xray, no X-Ray imports.
      final srcDefault = builder.buildMain(appName: 'my_app');
      expect(srcDefault, isNot(contains('registerAllXRayDecks')));
      // And enabling xray must produce strictly more output (the bridge
      // imports + kDebugMode block).
      expect(srcOn.length, greaterThan(srcOff.length));
    });

    // Concern 2: buildMain must declare a `library` local so the
    // `specLibrary.emitLibrary(library, ...)` call resolves. The original
    // bad merge referenced `library` without declaring it, producing
    // "The getter 'library' isn't defined for the type 'AppShellBuilder'".
    // We can't reflect on local variables, but if `library` were
    // undeclared the call would throw at runtime — so simply producing
    // non-empty output proves the local is wired correctly.
    test('emits a library — proves the `library` local is declared', () {
      final src = builder.buildMain(appName: 'my_app');
      // If `library` were undeclared, buildMain would throw before
      // returning any string.
      expect(src, isNotEmpty);
      // The emitted library output always begins with the leading
      // comment (the zfa header) — proving the `leadingComment: leading`
      // argument resolved to a real String, which is only possible if
      // `library` was declared and passed to `emitLibrary`.
      expect(src.startsWith('// Generated by zfa'), isTrue);
      // A real `Library` spec always emits at least one directive + the
      // main() entrypoint.
      expect(src, contains("import 'package:flutter/widgets.dart';"));
      expect(src, contains('void main('));
    });

    // Concern 3: `leading` must be declared once and account for both
    // `mockHint` and `xray`. The original bad merge had two `leading`
    // declarations ("Previous declaration of 'leading'" compile error).
    // The consolidated `leadingParts.join('\n')` form produces a single
    // header block whose lines are stitched in order: zfa header, mock
    // hint (when mockHint), xray wiring (when xray).
    test('produces a single leading comment block (no duplicate `leading`)', () {
      // Both flags on — the merged state the bad merge broke.
      final src = builder.buildMain(
        appName: 'my_app',
        mockHint: true,
        xray: true,
      );
      // The zfa header is always present (first line).
      expect(src.startsWith('// Generated by zfa'), isTrue);
      // The mock hint is present exactly once.
      final mockHintCount =
          '// Mock DI mode: setupDependencies() wires mock datasources'
              .allMatches(src)
              .length;
      expect(mockHintCount, 1);
      // The X-Ray wiring header is present exactly once.
      final xrayHeaderCount =
          'X-Ray wiring (issue #360)'.allMatches(src).length;
      expect(xrayHeaderCount, 1);
      // The mock hint MUST come before the X-Ray header — the
      // leadingParts list order is [zfaHeader, mockHint?, xray?].
      final mockIdx = src.indexOf('// Mock DI mode');
      final xrayIdx = src.indexOf('X-Ray wiring (issue #360)');
      expect(mockIdx, greaterThan(0));
      expect(xrayIdx, greaterThan(mockIdx));
    });

    test('compiles the merged state (mockHint + xray) without exceptions', () {
      // The bad merge left buildMain unable to emit ANY output when both
      // flags were on. This test ensures the call returns non-empty
      // output containing all three pieces: setupDependencies, the
      // kDebugMode-guarded X-Ray bridge start, and runApp.
      final src = builder.buildMain(
        appName: 'my_app',
        mockHint: true,
        xray: true,
      );
      expect(src, contains('setupDependencies'));
      expect(src, contains('if (kDebugMode)'));
      expect(src, contains('await _startXRayBridge();'));
      expect(src, contains('registerAllXRayDecks();'));
      expect(src, contains('runApp(const MyApp())'));
    });

    test('emits the mock hint only when mockHint is true', () {
      // Regression guard: the consolidated `leading` computation must
      // only include the mock-mode hint when `mockHint: true`. The bad
      // merge had a `mockHint ? ... : '// Generated by zfa'` form that
      // would have clobbered the zfa header when mockHint was false.
      final withMock = builder.buildMain(
        appName: 'my_app',
        mockHint: true,
      );
      final withoutMock = builder.buildMain(
        appName: 'my_app',
        mockHint: false,
      );
      // Both must start with the zfa header.
      expect(withMock.startsWith('// Generated by zfa'), isTrue);
      expect(withoutMock.startsWith('// Generated by zfa'), isTrue);
      // Only the mockHint variant includes the mock DI mode hint.
      expect(withMock, contains('// Mock DI mode'));
      expect(withoutMock, isNot(contains('// Mock DI mode')));
    });
  });
}
