import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/app_shell/builders/app_shell_builder.dart';

void main() {
  group('AppShellBuilder', () {
    const builder = AppShellBuilder();

    group('buildMain', () {
      test('emits a `void main()` async entrypoint', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        // MethodModifier.async produces `void main() async { ... }`.
        expect(src, contains('void main() async'));
      });

      test('awaits setupDependencies()', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(src, contains('await setupDependencies()'));
      });

      test('runs MyApp', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(src, contains('runApp(const MyApp())'));
      });

      test('imports the generated DI barrel via the app package name', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(
          src,
          contains("import 'package:my_app/src/di/index.dart';"),
        );
      });

      test('imports MyApp from the app package', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(
          src,
          contains("import 'package:my_app/src/app/my_app.dart';"),
        );
      });

      test('imports flutter widgets for runApp', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(src, contains("import 'package:flutter/widgets.dart';"));
      });

      test('stamps the file with the zfa header', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(src.startsWith('// Generated by zfa'), isTrue);
      });

      test('adds the mock-mode hint when mockHint is true', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: true);
        expect(src, contains('Mock DI mode'));
        expect(src, contains('zfa di <Entity> --use-mock'));
      });

      test('does NOT add the mock hint when mockHint is false', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        expect(src.contains('Mock DI mode'), isFalse);
      });

      test('is not wrapped in // GENERATED - DO NOT EDIT markers', () {
        final src = builder.buildMain(appName: 'my_app', mockHint: false);
        // main.dart is user-editable glue — it should not be auto-replaced
        // by the AST merge engine on every `zfa build`.
        expect(src.contains('GENERATED - DO NOT EDIT'), isFalse);
      });
    });

    group('buildMyApp', () {
      test('emits a StatelessWidget named MyApp', () {
        final src = builder.buildMyApp();
        expect(src, contains('class MyApp extends StatelessWidget'));
      });

      test('has a const constructor', () {
        final src = builder.buildMyApp();
        expect(src, contains('const MyApp'));
      });

      test('returns MaterialApp.router', () {
        final src = builder.buildMyApp();
        expect(src, contains('MaterialApp.router('));
      });

      test('wires routerConfig to appRouter', () {
        final src = builder.buildMyApp();
        expect(src, contains('routerConfig: appRouter'));
      });

      test('uses the provided title', () {
        final src = builder.buildMyApp(title: 'Hello World');
        expect(src, contains("title: 'Hello World'"));
      });

      test('falls back to "Zuraffa App" title when none provided', () {
        final src = builder.buildMyApp();
        expect(src, contains("title: 'Zuraffa App'"));
      });

      test('hides the debug banner', () {
        final src = builder.buildMyApp();
        expect(src, contains('debugShowCheckedModeBanner: false'));
      });

      test('imports go_router and the app_router glue', () {
        final src = builder.buildMyApp();
        expect(src, contains("import 'package:go_router/go_router.dart';"));
        expect(src, contains("import '../routing/app_router.dart';"));
      });

      test('imports flutter material', () {
        final src = builder.buildMyApp();
        expect(src, contains("import 'package:flutter/material.dart';"));
      });

      test('stamps the file with the zfa header', () {
        final src = builder.buildMyApp();
        expect(src.startsWith('// Generated by zfa'), isTrue);
      });
    });

    group('buildAppRouter', () {
      test('declares a final GoRouter appRouter', () {
        final src = builder.buildAppRouter();
        expect(src, contains('final GoRouter appRouter'));
      });

      test('constructs GoRouter with getAllRoutes()', () {
        final src = builder.buildAppRouter();
        expect(src, contains('GoRouter('));
        expect(src, contains('routes: getAllRoutes()'));
      });

      test('imports go_router', () {
        final src = builder.buildAppRouter();
        expect(src, contains("import 'package:go_router/go_router.dart';"));
      });

      test('imports the routing index (getAllRoutes source)', () {
        final src = builder.buildAppRouter();
        expect(src, contains("import 'index.dart';"));
      });

      test('stamps the file with the zfa header', () {
        final src = builder.buildAppRouter();
        expect(src.startsWith('// Generated by zfa'), isTrue);
      });
    });

    group('parseAppName', () {
      test('parses the name field from a pubspec', () {
        const pubspec = '''
name: my_app
description: A test app.
environment:
  sdk: ^3.11.0
''';
        expect(AppShellBuilder.parseAppName(pubspec), 'my_app');
      });

      test('parses the name field even when other fields precede it', () {
        const pubspec = '''
description: A test app.
name: my_app
environment:
  sdk: ^3.11.0
''';
        expect(AppShellBuilder.parseAppName(pubspec), 'my_app');
      });

      test('returns null when no name field is present', () {
        const pubspec = '''
description: no name here
environment:
  sdk: ^3.11.0
''';
        expect(AppShellBuilder.parseAppName(pubspec), isNull);
      });

      test('rejects names starting with a digit', () {
        // The regex requires [A-Za-z] as the first character, so a name
        // starting with a digit returns null even though YAML would
        // technically accept it as a string. This matches the Dart
        // package-name convention.
        const pubspec = 'name: 1bad\n';
        expect(AppShellBuilder.parseAppName(pubspec), isNull);
      });
    });
  });
}
