import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/app_shell/builders/app_shell_builder.dart';

/// Regression test for issue #404.
///
/// A bad merge between the X-Ray feature (#367) and the leading/mockHint
/// change left `buildMain` in a broken state:
///   1. `xray` was referenced but not in the parameter list.
///   2. `library` was referenced but never declared as a local.
///   3. `leading` was declared twice (mockHint version + xray-aware version).
///
/// These tests ensure the parameter list, local declarations, and combined
/// flag behaviour stay consistent so a repeat merge cannot break `buildMain`
/// without failing this suite.
void main() {
  const builder = AppShellBuilder();

  group('issue #404 regression: buildMain parameter & local consistency', () {
    test('buildMain accepts xray parameter without error', () {
      expect(
        () => builder.buildMain(appName: 'my_app', xray: true),
        returnsNormally,
      );
    });

    test('buildMain xray=true emits async main', () {
      final src = builder.buildMain(appName: 'my_app', xray: true);
      // code_builder emits the modifier after the return type: "void main() async"
      expect(src, contains('void main() async'));
    });

    test('buildMain xray=true emits kDebugMode guard + registerAllXRayDecks', () {
      final src = builder.buildMain(appName: 'my_app', xray: true);
      expect(src, contains('if (kDebugMode)'));
      expect(src, contains('registerAllXRayDecks()'));
    });

    test('buildMain emits exactly one leading comment block', () {
      for (final xray in [false, true]) {
        for (final mockHint in [false, true]) {
          final src = builder.buildMain(
            appName: 'my_app',
            xray: xray,
            mockHint: mockHint,
          );
          final headerCount = '// Generated by zfa'.allMatches(src).length;
          expect(
            headerCount,
            equals(1),
            reason: 'expected exactly one zfa header with xray=$xray, mockHint=$mockHint',
          );
        }
      }
    });

    test('buildMain mockHint + xray combined emits both header notes', () {
      final src = builder.buildMain(
        appName: 'my_app',
        mockHint: true,
        xray: true,
      );
      expect(src, contains('Mock DI mode'));
      expect(src, contains('X-Ray wiring (issue #360)'));
    });

    test('buildMain xray=true with diTakesGetIt + diIsAsync runs without error', () {
      expect(
        () => builder.buildMain(
          appName: 'my_app',
          xray: true,
          mockHint: true,
          diTakesGetIt: true,
          diIsAsync: true,
          outputDir: 'lib/custom',
        ),
        returnsNormally,
      );
    });

    test('buildMain all-flags output contains expected structure', () {
      final src = builder.buildMain(
        appName: 'my_app',
        xray: true,
        mockHint: true,
        diTakesGetIt: true,
        diIsAsync: true,
        outputDir: 'lib/src',
      );
      expect(src, contains('void main() async'));
      expect(src, contains('GetIt.instance'));
      expect(src, contains('await setupDependencies('));
      expect(src, contains('registerAllXRayDecks()'));
      expect(src, contains('// Generated by zfa'));
    });
  });
}
