// BUG 1260 — `zfa app shell` emits the raw shell + MaterialApp.router, never the
// certified shell (issue #1260, remediation 3).
//
// ZuraffaApp is "the certified app shell of the skin lane" (route
// observer + audit bus + violation chrome mounted in one place), but the
// generated app shell cannot use it: the emitted shell file builds a
// raw `MaterialApp.router`. The certified surface must be REACHABLE from
// the pipeline: `zfa app shell --zuraffa-app` emits a shell widget that mounts
// `ZuraffaApp` and keeps the generated GoRouter tree functional beneath
// it (`Router.withConfig(config: appRouter)` — GoRouter implements
// RouterConfig<Object?>).
//
// Fix contract pinned here:
//   - `--zuraffa-app` emits the certified import + shell, no
//     MaterialApp.router;
//   - a project whose pubspec does not declare `zuraffa_ui` is refused
//     BEFORE any file is written (the #938/#1260 errors-are-an-API
//     discipline) with an actionable `flutter pub add zuraffa_ui` line;
//   - `--zuraffa-app --skin-audit` composes: SkinAuditChrome rides the
//     certified shell's builder, the SkinRouteContractObserver stays on
//     the GoRouter;
//   - `--zuraffa-app --xray` composes: XRayScope wraps the routed home;
//   - without the flag the emission is byte-compatible with pre-1260
//     (MaterialApp.router) — no regression.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

const String kZuraffaUiImport = "import 'package:zuraffa_ui/zuraffa_ui.dart';";

void main() {
  group('bug 1260: zfa app shell --zuraffa-app mounts the certified shell', () {
    late Directory workspace;

    setUp(() async {
      workspace = await Directory.systemTemp.createTemp('bug1260_shell_');
      await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: my_test_app
description: bug 1260 fixture
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
''');
      final diDir = Directory(p.join(workspace.path, 'lib', 'src', 'di'))
        ..createSync(recursive: true);
      await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:get_it/get_it.dart';
void setupDependencies(GetIt getIt) {}
''');
      final routingDir = Directory(
        p.join(workspace.path, 'lib', 'src', 'routing'),
      )..createSync(recursive: true);
      await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');
    });

    tearDown(() async {
      if (workspace.existsSync()) {
        workspace.deleteSync(recursive: true);
      }
    });

    /// Adds zuraffa_ui to the fixture pubspec's dependencies.
    Future<void> withCertifiedDependency() async {
      final pubspec = File(p.join(workspace.path, 'pubspec.yaml'));
      await pubspec.writeAsString('''
name: my_test_app
description: bug 1260 fixture
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
  zuraffa_ui: ^0.1.0
''');
    }

    Future<String> runShell([List<String> extra = const []]) async {
      final runner = CliRunner(exitOnCompletion: false);
      return runner.runCapturing([
        'app',
        'shell',
        '--root',
        workspace.path,
        '--force',
        ...extra,
      ]);
    }

    String myAppSrc() => File(
      p.join(workspace.path, 'lib', 'src', 'app', 'my_test_app.dart'),
    ).readAsStringSync();

    test(
      '--zuraffa-app: the shell file mounts ZuraffaApp over the GoRouter tree',
      () async {
        await withCertifiedDependency();
        final out = await runShell(['--zuraffa-app']);

        expect(exitCode, 0, reason: out);
        final src = myAppSrc();
        expect(
          src,
          contains('ZuraffaApp('),
          reason:
              'issue #1260 remediation 3: the generated app shell must '
              'match the certified surface (route observer + audit bus + '
              'violation chrome in one place)',
        );
        expect(src, contains(kZuraffaUiImport));
        expect(
          src,
          contains('Router.withConfig'),
          reason:
              'the generated GoRouter tree stays functional under the '
              'certified shell',
        );
        expect(
          src,
          isNot(contains('MaterialApp.router(')),
          reason: 'the certified flag replaces the raw engine shell',
        );
        // main.dart is unchanged: runApp(const MyTestApp()).
        final mainSrc = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        expect(mainSrc, contains('runApp(const MyTestApp())'));
      },
    );

    test('project without zuraffa_ui: refused BEFORE writing, with the exact '
        'remedy', () async {
      final out = await runShell(['--zuraffa-app']);

      expect(
        exitCode,
        isNot(0),
        reason:
            'a certified shell the target cannot resolve must be a '
            'refusal, not a broken app (got:\n$out)',
      );
      expect(out, contains('zuraffa_ui'));
      expect(out, contains('flutter pub add zuraffa_ui'));
      expect(
        File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
        isFalse,
        reason: 'a refused shell writes no artifacts',
      );
    });

    test(
      'pure-Dart project validates --zuraffa-app before being skipped',
      () async {
        await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: my_test_app
description: pure Dart fixture
environment:
  sdk: ^3.11.0
dependencies:
  path: ^1.9.0
''');

        final out = await runShell(['--zuraffa-app']);

        expect(exitCode, isNot(0), reason: out);
        expect(out, contains('flutter pub add zuraffa_ui'));
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
          reason: 'the rejected command must not write app-shell artifacts',
        );
      },
    );

    test('--zuraffa-app --skin-audit: chrome composes, observer stays on the '
        'GoRouter', () async {
      await withCertifiedDependency();
      final out = await runShell(['--zuraffa-app', '--skin-audit']);

      expect(exitCode, 0, reason: out);
      final src = myAppSrc();
      expect(src, contains('ZuraffaApp('));
      expect(
        src,
        contains('SkinAuditChrome'),
        reason:
            'the violation-banner mount rides the certified shell '
            'builder (MaterialApp.builder no longer exists to hang it on)',
      );
      final routerSrc = File(
        p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
      ).readAsStringSync();
      expect(
        routerSrc,
        contains('SkinRouteContractObserver'),
        reason:
            'the route contract observer stays mounted on the '
            'GoRouter where pushes actually happen',
      );
    });

    test('--zuraffa-app --xray: XRayScope wraps the routed home', () async {
      await withCertifiedDependency();
      final out = await runShell(['--zuraffa-app', '--xray']);

      expect(exitCode, 0, reason: out);
      final src = myAppSrc();
      expect(src, contains('ZuraffaApp('));
      expect(src, contains('XRayScope'));
    });

    test('without the flag: MaterialApp.router emission is preserved '
        '(no regression)', () async {
      final out = await runShell();

      expect(exitCode, 0, reason: out);
      final src = myAppSrc();
      expect(src, contains('MaterialApp.router('));
      expect(src, isNot(contains('ZuraffaApp(')));
    });
  });
}
