// GENERATED BY `zfa api Product` — DO NOT EDIT BY HAND
// Regenerate with: zfa api Product (--force to overwrite)

import 'dart:convert';
import 'dart:developer' as developer;

import 'package:zuraffa/zuraffa.dart';

import '../../domain/usecases/product/get_product_usecase.dart';

import '../../domain/entities/product/product.dart';

final getIt = GetIt.instance;

/// Registers all Product UseCase extensions with [ZuraffaApiBridge].
///
/// Prerequisites: call [ZuraffaApiBridge.init] first, configure DI,
/// then call this function before `runApp()`.
void registerProductApiBridge() {
  if (const bool.fromEnvironment('dart.vm.product')) return;
  if (const bool.fromEnvironment('dart.vm.profile') &&
      !Zuraffa.enableApiInProfile)
    return;

  ZuraffaApiBridge.registerEndpoint(
    endpoint: const ApiEndpoint(
      method: 'ext.zuraffa.product.getProduct',
      domain: 'product',
      usecase: 'getProduct',
      params: {},
      returns: 'Product',
      isStream: false,
    ),
    handler: _handleGetProduct,
  );
}

// GENERATED - DO NOT EDIT
Future<developer.ServiceExtensionResponse> _handleGetProduct(
  String method,
  Map<String, String> args,
) async {
  try {
    final useCase = getIt<GetProductUseCase>();
    final result = await useCase(const NoParams());
    return ZuraffaApiBridge.serializeResult(
      result,
      (v) => _toJsonForGetProduct(v),
    );
  } catch (e, st) {
    developer.log(
      'Bridge error: ext.zuraffa.product.getProduct',
      error: e,
      stackTrace: st,
      name: 'ZuraffaApiBridge',
    );
    return ZuraffaApiBridge.errorResponse('unknown', e.toString());
  }
}

// END GENERATED

Map<String, dynamic> _toJsonForGetProduct(Product v) => v.toJson();
