// Generated by zfa
// zfa generate Product --methods=create --test

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:example/src/domain/entities/product/product.dart';
import 'package:example/src/domain/repositories/product_repository.dart';
import 'package:example/src/domain/usecases/product/create_product_usecase.dart';

class MockProductRepository extends Mock implements ProductRepository {}

class MockProduct extends Mock implements Product {}

void main() {
  late CreateProductUseCase useCase;
  late MockProductRepository mockRepository;

  setUp(() {
    registerFallbackValue(MockProduct());
    mockRepository = MockProductRepository();
    useCase = CreateProductUseCase(mockRepository);
  });

  group('CreateProductUseCase', () {
    final tProduct = MockProduct();

    test('should call repository.create and return result', () async {
      // Arrange
      when(
        () => mockRepository.create(any()),
      ).thenAnswer((_) async => tProduct);

      // Act
      final result = await useCase(tProduct);

      // Assert
      verify(() => mockRepository.create(any())).called(1);
      expect(result.isSuccess, true);
      expect(result.getOrElse(() => throw Exception()), equals(tProduct));
    });

    test('should return Failure when repository throws', () async {
      // Arrange
      final exception = Exception('Error');
      when(() => mockRepository.create(any())).thenThrow(exception);

      // Act
      final result = await useCase(tProduct);

      // Assert
      verify(() => mockRepository.create(any())).called(1);
      expect(result.isFailure, true);
    });
  });
}
