// Generated by zfa
// zfa generate Product --methods=getList --test

import 'package:flutter_test/flutter_test.dart';
import 'package:mocktail/mocktail.dart';
import 'package:zuraffa/zuraffa.dart';
import 'package:example/src/domain/entities/product/product.dart';
import 'package:example/src/domain/repositories/product_repository.dart';
import 'package:example/src/domain/usecases/product/get_product_list_usecase.dart';

class MockProductRepository extends Mock implements ProductRepository {}

class MockProduct extends Mock implements Product {}

void main() {
  late GetProductListUseCase useCase;
  late MockProductRepository mockRepository;

  setUp(() {
    registerFallbackValue(const ListQueryParams<dynamic>());

    mockRepository = MockProductRepository();
    useCase = GetProductListUseCase(mockRepository);
  });

  group('GetProductListUseCase', () {
    final tProduct = MockProduct();

    final tProductList = [tProduct];

    test('should call repository.getList and return result', () async {
      // Arrange
      when(() => mockRepository.getList(any()))
          .thenAnswer((_) async => tProductList);

      // Act
      final result = await useCase(const ListQueryParams<Product>());

      // Assert
      verify(() => mockRepository.getList(any())).called(1);
      expect(result.isSuccess, true);
      expect(result.getOrElse(() => throw Exception()), equals(tProductList));
    });

    test('should return Failure when repository throws', () async {
      // Arrange
      final exception = Exception('Error');
      when(() => mockRepository.getList(any())).thenThrow(exception);

      // Act
      final result = await useCase(const ListQueryParams<Product>());

      // Assert
      verify(() => mockRepository.getList(any())).called(1);
      expect(result.isFailure, true);
    });
  });
}
