// Generated by zfa
// zfa generate Product --methods=get,getList,watch,watchList,create,update,delete --vpc

import 'package:zuraffa/zuraffa.dart';
import 'product_presenter.dart';
import '../../../domain/entities/product/product.dart';

class ProductController extends Controller {
  final ProductPresenter _presenter;

  ProductController(this._presenter);

  Future<void> getProduct(String id) async {
    final result = await _presenter.getProduct(id);

    result.fold(
      (entity) {},
      (failure) {},
    );
  }

  Future<void> getProductList(
      [ListQueryParams<Product> params = const ListQueryParams()]) async {
    final result = await _presenter.getProductList(params);

    result.fold(
      (list) {},
      (failure) {},
    );
  }

  void watchProduct(String id) {
    _presenter.watchProduct(id).listen(
      (result) {
        result.fold(
          (entity) {},
          (failure) {},
        );
      },
    );
  }

  void watchProductList(
      [ListQueryParams<Product> params = const ListQueryParams()]) {
    _presenter.watchProductList(params).listen(
      (result) {
        result.fold(
          (list) {},
          (failure) {},
        );
      },
    );
  }

  Future<void> createProduct(Product product) async {
    final result = await _presenter.createProduct(product);

    result.fold(
      (created) {},
      (failure) {},
    );
  }

  Future<void> updateProduct(String id, Partial<Product> data) async {
    final result = await _presenter.updateProduct(id, data);

    result.fold(
      (updated) {},
      (failure) {},
    );
  }

  Future<void> deleteProduct(String id) async {
    final result = await _presenter.deleteProduct(id);

    result.fold(
      (_) {},
      (failure) {},
    );
  }

  @override
  void onDisposed() {
    _presenter.dispose();
    super.onDisposed();
  }
}
