// GENERATED - DO NOT EDIT
// Generated by zfa for: ZikZak
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/zik_zak/zik_zak.dart';
import '../../mock/zik_zak_mock_data.dart';
import 'zik_zak_datasource.dart';

/// Mock data source for ZikZak
class ZikZakMockDataSource
    with Loggable, FailureHandler
    implements ZikZakDataSource {
  ZikZakMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ZikZak> get(QueryParams<ZikZak> params) async {
    logger.info('Getting ZikZak with params: $params');
    await Future.delayed(_delay);
    final item = ZikZakMockData.zikZaks.query(params);
    logger.info('Successfully retrieved ZikZak');
    return item;
  }

  @override
  Future<ZikZak> update(UpdateParams<String, ZikZakPatch> params) async {
    logger.info('Updating ZikZak: ${params.id}');
    await Future.delayed(_delay);
    final existing = ZikZakMockData.sampleZikZak;
    logger.info('Successfully updated ZikZak');
    return existing;
  }

  @override
  Future<ZikZak> toggle(
    ToggleParams<String, Field<ZikZak, dynamic>> params,
  ) async {
    logger.info('Toggling ZikZak: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = ZikZakMockData.sampleZikZak;
    logger.info('Successfully toggled ZikZak');
    return existing;
  }
}

// END GENERATED
