// Generated by zfa for: GroceryProduct
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import '../../../data/mock/grocery_product_mock_data.dart';
import '../../../domain/entities/grocery_product/grocery_product.dart';
import 'grocery_product_controller.dart';
import 'grocery_product_presenter.dart';
import 'grocery_product_state.dart';

class GroceryProductView extends CleanView {
  const GroceryProductView({
    super.key,
    super.routeObserver,
    this.groceryProduct,
  });

  final GroceryProduct? groceryProduct;

  @override
  State<GroceryProductView> createState() {
    return _GroceryProductViewState(
      GroceryProductController(
        GroceryProductPresenter(),
        initialGroceryProduct: groceryProduct,
      ),
    );
  }
}

class _GroceryProductViewState
    extends
        CleanViewState<
          GroceryProductView,
          GroceryProductController,
          GroceryProductState
        > {
  _GroceryProductViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('GroceryProduct')),
      body: ControlledWidgetBuilder<GroceryProductController>(
        builder: (context, controller) {
          return ListView.builder(
            itemCount: GroceryProductMockData.sampleList.length,
            itemBuilder: (context, index) => ListTile(
              title: Text(GroceryProductMockData.sampleList[index].toString()),
              subtitle: Text('Mock #${index + 1}'),
            ),
          );
        },
      ),
    );
  }
}
