// Auto-generated by Zorphy
// Generated at: 2026-08-15T03:05:19.310123

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'customer_profile.zorphy.dart';
part 'customer_profile.g.dart';

/// CustomerProfile entity
@Zorphy(
  kind: ZorphyKind.valueObject,
  generateJson: true,
  generateCompareTo: true,
)
abstract class $CustomerProfile {
  int? get yearOfBirth;
  Gender? get gender;
  String? get shoppingStyle;
  String? get shoeSize;
}
