/// Unit behaviors U7–U10 for spec 066-zfa-replay: gen replay with the
/// path-stable tree compare, verify replay against the recorded exit,
/// report shaping, and the NDJSON event log.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import 'package:zuraffa/src/plugins/tdd/services/replay_events.dart';
import 'package:zuraffa/src/plugins/tdd/services/replay_history.dart';
import 'package:zuraffa/src/plugins/tdd/services/replay_runner.dart';
import 'package:zuraffa/src/plugins/tdd/services/replay_sandbox.dart';

import '../helpers/replay_fixture.dart';

void main() {
  group('ReplayRunner gen stage (U7)', () {
    test('U7: identical trees when the recorded gen reproduces', () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.writeFakeZfa();
      await fx.appendCycle(
        '066-b1',
        marker: 'm1',
        genSteps: [genStep(fx.genCommandOf('066-b1'))],
      );
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runGen(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
        zfaBin: fx.fakeZfaPath,
      );

      expect(result.status, ReplayStepStatus.identical);
      expect(result.paths, isEmpty);
      expect(result.ok, isTrue);
      // The recorded step really ran, argv-substituted with the fake bin.
      final log = await File(fx.fakeZfaLogPath).readAsString();
      expect(log, contains('tdd gen 066-b1'));
    });

    test('U7: drift is reported path-stably with classifications',
        () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.writeFakeZfa();
      // The recorded artifact on disk carries the OLD template; the
      // generator (fake zfa) now regenerates a DIFFERENT test body.
      await fx.writeDriftConfig(
        '066-b1',
        'test/066_b1_test.dart',
        '// test for 066-b1 — regenerated by a newer template\n',
      );
      await fx.appendCycle(
        '066-b1',
        marker: 'm1',
        genSteps: [genStep(fx.genCommandOf('066-b1'))],
      );
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runGen(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
        zfaBin: fx.fakeZfaPath,
      );

      expect(result.status, ReplayStepStatus.drift);
      expect(result.ok, isFalse);
      expect(result.paths, ['test/066_b1_test.dart']);
      // Path-stable: the sandbox root never leaks into the report.
      expect(result.paths.where((path) => path.startsWith('/')), isEmpty);
      // The real tree is untouched by the drift (it happened in the
      // sandbox).
      expect(
        await File(fx.testPathOf('066-b1')).readAsString(),
        contains('// test for 066-b1'),
      );
    });

    test('U7: added files are classified as drift too', () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.writeFakeZfa();
      await fx.writeDriftConfig(
        '066-b1',
        'lib/extra_artifact.dart',
        '// regenerated extra\n',
      );
      await fx.appendCycle(
        '066-b1',
        marker: 'm1',
        genSteps: [genStep(fx.genCommandOf('066-b1'))],
      );
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runGen(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
        zfaBin: fx.fakeZfaPath,
      );

      expect(result.status, ReplayStepStatus.drift);
      expect(result.paths, ['lib/extra_artifact.dart']);
    });

    test('U7: a failing gen step is a runner-error divergence', () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.writeFakeZfa();
      await fx.appendCycle(
        '066-b1',
        marker: 'm1',
        genSteps: [genStep('zfa-binary-that-does-not-exist tdd gen 066-b1')],
      );
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runGen(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
      );

      expect(result.status, ReplayStepStatus.diverged);
      expect(result.reason, contains('runner-error'));
    });
  });

  group('ReplayRunner verify stage (U8)', () {
    test('U8: a passing recorded command is green in the sandbox cwd',
        () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.appendCycle('066-b1', marker: 'OK-marker');
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runVerify(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
      );

      expect(result.status, ReplayStepStatus.green);
      expect(result.ok, isTrue);
    });

    test('U8: a broken subject diverges with expected/actual', () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.appendCycle('066-b1', marker: 'OK-marker');
      // Break the subject in the real project AFTER recording: the sandbox
      // copy inherits the breakage, the check script fails.
      await fx.writeSubject('066-b1', 'BROKEN');
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runVerify(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
      );

      expect(result.status, ReplayStepStatus.diverged);
      expect(result.ok, isFalse);
      expect(result.expected, 0);
      expect(result.actual, 1);
      expect(result.reason, contains('verify-exit-mismatch'));
    });

    test('U8: an unspawnable recorded command is a runner error',
        () async {
      final fx = await ReplayFixture.create();
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.appendCycle(
        '066-b1',
        marker: 'm1',
        greenCommand: 'definitely-not-a-real-binary-066 --version',
      );
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runVerify(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
      );

      expect(result.status, ReplayStepStatus.diverged);
      expect(result.reason, contains('runner-error'));
    });

    test('U8: an unresolved project skips verify (FR-011)', () async {
      final fx = await ReplayFixture.create(withPackageConfig: false);
      addTearDown(() => fx.root.delete(recursive: true));
      await fx.appendCycle('066-b1', marker: 'm1');
      final sandbox = await ReplaySandbox.create(
        projectRoot: fx.root.path,
        feature: fx.featureName,
      );
      addTearDown(sandbox.delete);

      final b = (await ReplayHistory.load(fx.featureDir)).single;
      final result = await ReplayRunner.runVerify(
        b,
        sandboxPath: sandbox.path,
        projectRoot: fx.root.path,
      );

      expect(result.status, ReplayStepStatus.skipped);
      expect(result.reason, contains('package resolution'));
    });
  });

  group('ReplayReport (U9)', () {
    test('U9: any divergence aggregates to divergent/1', () {
      final report = ReplayReport.build(
        feature: '066-f',
        steps: {
          '066-b1': [
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.integrity,
              status: ReplayStepStatus.verified,
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.gen,
              status: ReplayStepStatus.identical,
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.verify,
              status: ReplayStepStatus.green,
            ),
          ],
          '066-b2': [
            const ReplayStepResult(
              behavior: '066-b2',
              stage: ReplayStage.integrity,
              status: ReplayStepStatus.diverged,
              reason: 'chain mismatch',
              entry: 'green',
            ),
          ],
        },
      );

      expect(report.result, 'divergent');
      expect(report.exit, 1);
      expect(report.replayed, 1);
      expect(report.skipped, 0);
      expect(report.diverged, 1);
    });

    test('U9: zero replayed behaviors aggregate to partial/2', () {
      final report = ReplayReport.build(
        feature: '066-f',
        steps: {
          '066-b1': [
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.integrity,
              status: ReplayStepStatus.verified,
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.gen,
              status: ReplayStepStatus.skipped,
              reason: 'no generation block',
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.verify,
              status: ReplayStepStatus.skipped,
              reason: 'no green command',
            ),
          ],
        },
      );

      expect(report.result, 'partial');
      expect(report.exit, 2);
      expect(report.replayed, 0);
      expect(report.skipped, 1);
      expect(report.diverged, 0);
    });

    test('U9: all-replayed-without-divergence aggregates to clean/0', () {
      final report = ReplayReport.build(
        feature: '066-f',
        steps: {
          '066-b1': [
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.integrity,
              status: ReplayStepStatus.verified,
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.gen,
              status: ReplayStepStatus.identical,
            ),
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.verify,
              status: ReplayStepStatus.green,
            ),
          ],
        },
      );

      expect(report.result, 'clean');
      expect(report.exit, 0);
      expect(report.replayed, 1);
      expect(report.skipped, 0);
      expect(report.diverged, 0);
    });

    test('U9: the summary line carries the contract fields', () {
      final report = ReplayReport.build(
        feature: '066-f',
        steps: {
          '066-b1': [
            const ReplayStepResult(
              behavior: '066-b1',
              stage: ReplayStage.gen,
              status: ReplayStepStatus.identical,
            ),
          ],
        },
      );

      expect(
        report.summaryLine,
        'replay: feature=066-f result=clean replayed=1 skipped=0 diverged=0',
      );
    });
  });

  group('ReplayEvents (U10)', () {
    test('U10: events are NDJSON and end with the exit', () async {
      final tmp = await Directory.systemTemp.createTemp('replay_events_');
      addTearDown(() => tmp.delete(recursive: true));
      final eventsPath = p.join(tmp.path, 'events.ndjson');

      final events = await ReplayEvents.start(eventsPath);
      events.runStart(feature: '066-f', behaviors: const ['066-b1']);
      events.stepStart(behavior: '066-b1', step: ReplayStage.gen);
      events.stepEnd(
        const ReplayStepResult(
          behavior: '066-b1',
          stage: ReplayStage.gen,
          status: ReplayStepStatus.identical,
        ),
      );
      events.stepEnd(
        const ReplayStepResult(
          behavior: '066-b1',
          stage: ReplayStage.verify,
          status: ReplayStepStatus.diverged,
          reason: 'verify-exit-mismatch',
          expected: 0,
          actual: 1,
        ),
      );
      await events.runEnd(
        result: 'divergent',
        replayed: 1,
        skipped: 0,
        diverged: 1,
        exit: 1,
      );

      final lines = (await File(eventsPath).readAsString())
          .split('\n')
          .where((line) => line.trim().isNotEmpty)
          .toList();
      final decoded =
          lines.map((line) => jsonDecode(line) as Map<String, dynamic>).toList();
      expect(decoded.first['event'], 'replay.start');
      expect(decoded.first['feature'], '066-f');
      expect(decoded[1]['event'], 'step.start');
      final genEnd = decoded
          .firstWhere((e) => e['event'] == 'step.end' && e['step'] == 'gen');
      expect(genEnd['status'], 'identical');
      final verifyEnd = decoded.lastWhere(
        (e) => e['event'] == 'step.end' && e['step'] == 'verify',
      );
      expect(verifyEnd['status'], 'diverged');
      expect(verifyEnd['expected'], 0);
      expect(verifyEnd['actual'], 1);
      final end = decoded.last;
      expect(end['event'], 'replay.end');
      expect(end['exit'], 1);
      expect(end['result'], 'divergent');
    });
  });
}
