// Issue #1196 (part of #908 P0) — the coverage tracker's honesty
// guard: the committed sweep evidence
// (corpus/zik_zak/sweep.json, written by
// `dart run tool/sweep_zikzak_corpus.dart --plan`) must agree with a
// FRESH parse-level sweep of the committed corpus. If the parser or
// the corpus drifts, this test fails — the evidence can never silently
// go stale (the same philosophy as the traceability hash, bug #846).
//
// The plan half of the evidence (120 real `zfa tdd plan` runs) is
// asserted structurally: every recorded row is internally consistent,
// the exit classes sum to the spec count, and the headline invariants
// (crashed == 0, every non-clean plan exit is an honest class) hold.
// The full plan sweep is regenerated by the tool, never re-run per
// test (it is minutes, not seconds).
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/tdd/services/spec_corpus_sweeper.dart';

import '../../../helpers/project_root.dart' as pr;

Future<void> main() async {
  late final Directory corpusRoot;
  late final Map<String, dynamic> evidence;

  setUpAll(() async {
    final root = await pr.findProjectRoot();
    corpusRoot = Directory(p.join(root, 'corpus', 'zik_zak'));
    evidence =
        jsonDecode(
              File(p.join(corpusRoot.path, 'sweep.json')).readAsStringSync(),
            )
            as Map<String, dynamic>;
  });

  test('the committed evidence is the zikzak-sweep.v1 schema over 120', () {
    expect(evidence['schema'], 'zikzak-sweep.v1');
    expect(evidence['specs'], 120);
    expect(evidence['corpus'], 'corpus/zik_zak');
  });

  test('the parse half of the evidence matches a fresh sweep', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    final parse = evidence['parse'] as Map<String, dynamic>;
    expect(
      parse['clean'],
      sweep.cleanCount,
      reason:
          'committed evidence is stale — regenerate with '
          '`dart run tool/sweep_zikzak_corpus.dart --plan`',
    );
    expect(parse['refused'], sweep.refusedCount);
    expect(parse['crashed'], sweep.crashedCount);
    expect(parse['crashed'], 0, reason: 'the hardened parser never crashes');
    // The per-spec outcomes agree row for row.
    final rows = evidence['specRows'] as List<dynamic>;
    final byFeature = {
      for (final row in rows.cast<Map<String, dynamic>>())
        row['feature'] as String: row['parse'] as String,
    };
    for (final r in sweep.records) {
      expect(
        byFeature[r.feature],
        r.outcome.name,
        reason:
            '${r.feature}: committed outcome drifted from the fresh '
            'sweep — regenerate the evidence',
      );
    }
  });

  test('the plan half of the evidence is internally consistent', () {
    final plan = evidence['plan'] as Map<String, dynamic>;
    final rows = evidence['planRows'] as List<dynamic>;
    final clean = plan['clean'] as int;
    final refused = plan['refused'] as int;
    expect(clean + refused, 120, reason: 'every spec planned or refused');
    expect(rows.length, 120);

    var declared = 0;
    var fallback = 0;
    var cleanRows = 0;
    for (final row in rows.cast<Map<String, dynamic>>()) {
      final exit = row['planExit'] as int;
      if (exit == 0) cleanRows++;
      declared += row['declaredRoutes'] as int;
      fallback += row['fallbackRoutes'] as int;
      // A spec that never planned wrote no route lines.
      if (exit != 0) {
        expect(
          row['declaredRoutes'],
          0,
          reason: '${row['feature']}: refused plan must not route',
        );
        expect(
          row['fallbackRoutes'],
          0,
          reason: '${row['feature']}: refused plan must not route',
        );
      }
    }
    expect(cleanRows, clean);
    expect(declared, plan['declaredRoutes']);
    expect(fallback, plan['fallbackRoutes']);
    // The #1186 tracker: the fallback window is COUNTED, and the
    // number can only shrink honestly from here.
    expect(
      fallback,
      greaterThanOrEqualTo(0),
      reason: 'fallback routes are tracked (issue #1186: shrink to zero)',
    );
  });

  test('the headline numbers are the issue #1196 coverage tracker', () {
    final plan = evidence['plan'] as Map<String, dynamic>;
    final parse = evidence['parse'] as Map<String, dynamic>;
    // The honest headline: X of 120 plan cleanly; Y behaviors route
    // via the labeled fallback (see #1186 — shrinks toward zero).
    expect(
      plan['fallbackRoutes'],
      isA<int>(),
      reason: 'tracked: ${plan['fallbackRoutes']} fallback behaviors',
    );
    expect(parse['crashed'], 0);
    expect(plan['clean'], isA<int>());
  });
}
