// Issue #1196 (part of #908 P0) — the 120-format sweep: the spec
// parser must SURVIVE every spec shape the ZikZak corpus will contain,
// and every refusal must name the offending spec line (the #1186
// actionable-refusal contract). This suite sweeps the committed corpus
// (corpus/zik_zak — 120 specs generated by
// tool/generate_zikzak_corpus.dart, deterministic) through the FULL
// declaration-parse surface and asserts per-shape expectations from
// the committed oracle (corpus/zik_zak/corpus-shapes.txt).
//
// The properties under test (the #1196 contract):
//  P1 no crash:        no spec in the corpus crashes the parser
//                      (a lineless StateError is a crashed honesty
//                      contract, not a refusal);
//  P2 honest refusal:  every refusal names `spec line N`;
//  P3 no silent drop:  a shape that declares scenarios/contracts/
//                      dependencies/lanes shows them in the facts —
//                      a section silently skipped is a silent misroute.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/tdd/services/spec_corpus_sweeper.dart';

import '../../../helpers/project_root.dart' as pr;

/// The committed corpus root — resolved in setUpAll via the shared
/// project_root helper (the test kernel lives in /tmp, so
/// Platform.script walks are unreliable; Isolate.resolvePackageUri is
/// CWD-independent).
late final Directory corpusRoot;

/// The committed shape oracle: `<slug> <shape-id>` per line.
late final Map<String, String> oracle;

Map<String, String> _readOracle() {
  final file = File(p.join(corpusRoot.path, 'corpus-shapes.txt'));
  final map = <String, String>{};
  for (final line in file.readAsStringSync().split('\n')) {
    final parts = line.trim().split(RegExp(r'\s+'));
    if (parts.length == 2) map[parts[0]] = parts[1];
  }
  return map;
}

/// The per-shape fact expectations (the "no silent misroute" oracle):
/// what the parser MUST derive from each shape class.
const Map<String, (int, int, int, int, int)> shapeFacts = {
  // shape => (behaviors, acceptance, units, layerContracts, lanes)
  'modern': (5, 3, 2, 2, 3),
  'modern-no-lanes': (5, 3, 2, 2, 0),
  'modern-undeclared': (5, 3, 2, 2, 3),
  'legacy-002': (3, 3, 0, 0, 0),
  'crlf': (5, 3, 2, 2, 3),
  'html-entities': (3, 1, 2, 1, 0),
  'non-english': (4, 2, 2, 0, 0),
  'fr-table': (3, 1, 2, 1, 0),
  'nested-ac': (6, 4, 2, 0, 0),
  'inline-prose': (5, 3, 2, 0, 0),
  'epic-contracts': (2, 1, 1, 2, 0),
  'manual': (3, 2, 1, 0, 0),
};

Future<void> main() async {
  setUpAll(() async {
    final root = await pr.findProjectRoot();
    corpusRoot = Directory(p.join(root, 'corpus', 'zik_zak'));
    oracle = _readOracle();
  });

  test('the committed corpus is present: 120 specs + oracle', () async {
    expect(oracle.length, 120, reason: 'corpus-shapes.txt carries 120 rows');
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    expect(sweep.records.length, 120, reason: 'every spec.md swept');
  });

  test('P1: no spec in the corpus crashes the parser', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    final crashed = sweep.records.where((r) => r.isCrashed).toList();
    expect(
      crashed.map((r) => '${r.feature}: ${r.error}').join('\n'),
      '',
      reason:
          'crashed=${sweep.crashedCount} — the parser must survive every '
          'shape (issue #1196); a lineless refusal is a crash of the '
          'honesty contract',
    );
  }, timeout: const Timeout(Duration(minutes: 2)));

  test('P2: every refusal names the offending spec line', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    for (final r in sweep.records) {
      if (r.outcome == SweepOutcome.refused) {
        expect(
          r.refusal,
          contains(RegExp(r'(?:spec )?line \d+')),
          reason: '${r.feature} refused without a line address',
        );
      }
    }
  });

  test(
    'P3: no silent misroute — every shape derives its declared facts',
    () async {
      final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
      for (final r in sweep.records) {
        final shape = oracle[r.feature];
        if (shape == null || shape == 'pathological') continue;
        final expected = shapeFacts[shape];
        if (expected == null) continue;
        final facts = r.facts;
        expect(
          facts,
          isNotNull,
          reason:
              '${r.feature} ($shape) left no facts — the surface must '
              'complete cleanly for every non-pathological shape',
        );
        final (behaviors, acceptance, units, contracts, lanes) = expected;
        expect(
          facts!.behaviorCount,
          behaviors,
          reason:
              '${r.feature} ($shape): behaviors silently dropped or '
              'miscounted',
        );
        expect(
          facts.acceptanceCount,
          acceptance,
          reason: '${r.feature} ($shape): acceptance scenarios lost',
        );
        expect(
          facts.unitCount,
          units,
          reason: '${r.feature} ($shape): unit behaviors lost',
        );
        expect(
          facts.layerContractCount,
          contracts,
          reason:
              '${r.feature} ($shape): Layer Contracts section silently '
              'skipped (silent misroute)',
        );
        expect(
          facts.laneCount,
          lanes,
          reason: '${r.feature} ($shape): Lanes section silently skipped',
        );
      }
    },
    timeout: const Timeout(Duration(minutes: 2)),
  );

  test('the BOM pathological spec still pins its template version', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    // The BOM is detected from the RAW BYTES: Dart's UTF-8 decoder
    // strips it on readAsString, so the string-level check would never
    // find it — the sweep asserts the parser survives the file anyway.
    final bom = sweep.records.where((r) {
      if (oracle[r.feature] != 'pathological') return false;
      final bytes = File(
        p.join(corpusRoot.path, r.feature, 'spec.md'),
      ).readAsBytesSync();
      return bytes.length >= 3 &&
          bytes[0] == 0xEF &&
          bytes[1] == 0xBB &&
          bytes[2] == 0xBF;
    }).single;
    expect(
      bom.facts?.templateVersion,
      'zuraffa-1.0',
      reason: 'a BOM before the treaty pin must not hide the pin',
    );
  });

  test('the unknown-version pathological spec reports its version', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    final unknown = sweep.records.where((r) {
      if (oracle[r.feature] != 'pathological') return false;
      final spec = File(
        p.join(corpusRoot.path, r.feature, 'spec.md'),
      ).readAsStringSync();
      return spec.contains('zuraffa-99.0');
    }).single;
    expect(unknown.facts?.templateVersion, 'zuraffa-99.0');
    expect(unknown.outcome, SweepOutcome.clean);
  });

  test('the honest summary line counts the corpus (the coverage tracker '
      'headline)', () async {
    final sweep = await const SpecCorpusSweeper().sweep(corpusRoot);
    expect(
      sweep.summaryLine,
      matches(
        RegExp(
          r'zikzak sweep: specs=120 parse-clean=\d+ '
          r'parse-refused\(line\)=[0-9]+ crashed=0',
        ),
      ),
      reason: 'crashed must be zero on the hardened parser',
    );
  });
}
