/// EngineChecker (spec 1002, deliverable 2): the `zfa engine check`
/// verification core.
///
/// Resolves every `getIt<T>()` call in the generated engine against
/// generated classes: a lookup resolves when either a DI registration
/// file exists for the type (`<snake>_di.dart` under `lib/src/di/`) or a
/// top-level declaration of the type exists anywhere under `lib/`. Any
/// dangling reference fails the check with an actionable `--> fix:`
/// hint. The check also enforces the engine purity exit criterion —
/// zero `package:flutter` imports in the slice's lib files and test
/// tree — and the per-method mock certification.
library;

import 'dart:io';

import 'package:path/path.dart' as p;

import '../plugins/slice/engine/service_locator_analyzer.dart';
import 'engine_models.dart';
import 'mock_certifier.dart';
export 'engine_models.dart';

/// Runs the engine-slice verification for one entity.
class EngineChecker {
  /// Checks the engine slice of [entity] in [projectRoot].
  ///
  /// When [methods] is provided, per-method mock certification is part of
  /// the check; when null, certification is skipped (the caller may not
  /// know the requested method set, e.g. an engine slice generated by an
  /// older run without a receipt).
  static Future<EngineCheckResult> check({
    required String entity,
    required String projectRoot,
    List<String>? methods,
  }) async {
    final serviceLocatorAnalyzer = ServiceLocatorAnalyzer();
    final failures = <EngineCheckFailure>[];
    final slice = EngineSlicePaths(entity: entity, projectRoot: projectRoot);

    // 1. The entity source must exist — everything else hangs off it.
    final entityAbs = File(p.join(projectRoot, slice.entityFile));
    if (!entityAbs.existsSync()) {
      failures.add(
        EngineCheckFailure(
          code: EngineFindingCode.missingEntity,
          typeName: entity,
          message:
              'Entity source file ${slice.entityFile} was not found for '
              'the engine slice of "$entity".\n'
              '   --> fix: run `zfa make engine $entity` (it creates the '
              'entity when missing) or `zfa entity create -n $entity`.',
        ),
      );
    }

    // 2. Index every top-level type declaration under lib/ so getIt<T>()
    // lookups can resolve against generated classes.
    final typeIndex = <String, String>{};
    final libDir = Directory(p.join(projectRoot, 'lib'));
    if (libDir.existsSync()) {
      for (final entry in libDir.listSync(recursive: true)) {
        if (entry is! File || !entry.path.endsWith('.dart')) continue;
        final rel = p.relative(entry.path, from: projectRoot);
        for (final name in declaredTopLevelNames(entry.readAsStringSync())) {
          typeIndex.putIfAbsent(name, () => rel);
        }
      }
    }

    // 3. Resolve every getIt<T>() in the entity's DI wiring.
    final resolutions = <EngineGetItResolution>[];
    final seenTypes = <String>{};
    for (final file in slice.entityDiFiles()) {
      final rel = p.relative(file.path, from: projectRoot);
      final source = file.readAsStringSync();
      for (final typeName in serviceLocatorAnalyzer.extractServiceLocatorTypes(
        source,
      )) {
        if (!seenTypes.add(typeName)) continue;
        final diFile = serviceLocatorAnalyzer.diRegistrationFileFor(
          typeName,
          projectRoot,
        );
        final declaringFile = typeIndex[typeName];
        resolutions.add(
          EngineGetItResolution(
            typeName: typeName,
            sourceFile: rel,
            diRegistrationFile: diFile == null
                ? null
                : p.relative(diFile, from: projectRoot),
            declaringFile: declaringFile,
          ),
        );
        if (diFile == null && declaringFile == null) {
          failures.add(
            EngineCheckFailure(
              code: EngineFindingCode.danglingGetIt,
              typeName: typeName,
              file: rel,
              message:
                  'Dangling getIt reference: `getIt<$typeName>()` in '
                  '$rel resolves to no generated class and no DI '
                  'registration file.\n'
                  '   --> fix: generate the missing slice for $typeName '
                  '(e.g. `zfa make engine $typeName`) or remove the '
                  '`getIt<$typeName>()` call from $rel.',
            ),
          );
        }
      }
    }

    // 4. Engine purity: zero package:flutter imports in the slice's lib
    //    files and test tree (exit criterion).
    for (final file in [...slice.sliceLibFiles(), ...slice.sliceTestFiles()]) {
      final rel = p.relative(file.path, from: projectRoot);
      final source = file.readAsStringSync();
      if (_flutterImportPattern.hasMatch(source)) {
        failures.add(
          EngineCheckFailure(
            code: EngineFindingCode.flutterImport,
            file: rel,
            message:
                'Flutter import in the engine slice: $rel imports '
                'package:flutter — engine slices must stay pure Dart.\n'
                '   --> fix: remove the Flutter import from $rel or move '
                'the UI dependency behind an engine-side interface.',
          ),
        );
      }
    }

    // 5. Per-method mock certification (when the method set is known).
    MockCertificationResult? certification;
    if (methods != null) {
      certification = MockCertifier.certify(
        entity: entity,
        methods: methods,
        projectRoot: projectRoot,
      );
      for (final method in methods) {
        if (certification.methods[method] != true) {
          failures.add(
            EngineCheckFailure(
              code: EngineFindingCode.uncertifiedMock,
              typeName: method,
              file: certification.mockDatasourcePath,
              message:
                  'Uncertified mock: method "$method" is not fully '
                  'implemented on the mock datasource of "$entity" '
                  '(missing member or missing seeded mock data).\n'
                  '   --> fix: regenerate the certified mock: '
                  '`zfa mock create $entity --methods=${methods.join(",")} '
                  '--certify`.',
            ),
          );
        }
      }
    }

    return EngineCheckResult(
      entity: entity,
      projectRoot: projectRoot,
      resolutions: resolutions,
      failures: failures,
      mockCertification: certification,
    );
  }

  /// `import '<anything>flutter<anything>'` — matches package:flutter,
  /// package:flutter_test, and flutter sub-packages.
  static final RegExp _flutterImportPattern = RegExp(
    r'''^\s*import\s+['"][^'"]*flutter[^'"]*['"]''',
    multiLine: true,
  );
}
