/// EngineChecker (spec 1002, deliverable 2): the `zfa engine check`
/// verification core.
///
/// Resolves every `getIt<T>()` call in the generated engine against
/// generated classes: a lookup resolves when either a DI registration
/// file exists for the type (`<snake>_di.dart` under `lib/src/di/`) or a
/// top-level declaration of the type exists anywhere under `lib/`. Any
/// dangling reference fails the check with an actionable `--> fix:`
/// hint. The check also enforces the engine purity exit criterion —
/// zero `package:flutter` imports in the slice's lib files and test
/// tree — and the per-method mock certification.
library;

import 'dart:io';

import 'package:path/path.dart' as p;

import '../plugins/slice/engine/service_locator_analyzer.dart';
import 'engine_receipt_writer.dart';
import 'mock_certifier.dart';
export 'engine_models.dart';

/// Runs the engine-slice verification for one entity.
class EngineChecker {
  /// Test seam (the MockCertifier.gate pattern): when non-null, used
  /// instead of the real analyze subprocess. Static per-isolate — `dart
  /// test` runs each file in its own isolate, so the override never leaks
  /// across files.
  static EngineAnalyzeRunner? analyzeRunnerOverride;

  /// Checks the engine slice of [entity] in [projectRoot].
  ///
  /// When [methods] is provided, per-method mock certification is part of
  /// the check; when null, certification is skipped (the caller may not
  /// know the requested method set, e.g. an engine slice generated by an
  /// older run without a receipt).
  ///
  /// Issue #1109 adds two opt-in legs used by `zfa engine check`:
  ///   - [verifyReceipt]: the v2 engine receipt must exist at
  ///     `specs/<feature>/tdd/engine.receipt.json` and record no
  ///     `mock_certified: false`; a missing receipt is a failure.
  ///   - [runStaticAnalysis]: `dart analyze` scoped to the entity's
  ///     slice files must exit clean. Skipped (not failed) when the
  ///     project has no package config — a workspace that never ran
  ///     `dart pub get` cannot resolve imports, and that is not an
  ///     engine-slice defect. The `zfa make engine` tail leaves both
  ///     off; the standalone check command turns both on.
  static Future<EngineCheckResult> check({
    required String entity,
    required String projectRoot,
    List<String>? methods,
    String? feature,
    bool verifyReceipt = false,
    bool runStaticAnalysis = false,
    EngineAnalyzeRunner? analyzeRunner,
  }) async {
    final serviceLocatorAnalyzer = ServiceLocatorAnalyzer();
    final failures = <EngineCheckFailure>[];
    final slice = EngineSlicePaths(entity: entity, projectRoot: projectRoot);

    // 1. The entity source must exist — everything else hangs off it.
    final entityAbs = File(p.join(projectRoot, slice.entityFile));
    if (!entityAbs.existsSync()) {
      failures.add(
        EngineCheckFailure(
          code: EngineFindingCode.missingEntity,
          typeName: entity,
          message:
              'Entity source file ${slice.entityFile} was not found for '
              'the engine slice of "$entity".\n'
              '   --> fix: run `zfa make engine $entity` (it creates the '
              'entity when missing) or `zfa entity create -n $entity`.',
        ),
      );
    }

    // 2. Index every top-level type declaration under lib/ so getIt<T>()
    // lookups can resolve against generated classes.
    final typeIndex = <String, String>{};
    final libDir = Directory(p.join(projectRoot, 'lib'));
    if (libDir.existsSync()) {
      for (final entry in libDir.listSync(recursive: true)) {
        if (entry is! File || !entry.path.endsWith('.dart')) continue;
        final rel = p.relative(entry.path, from: projectRoot);
        for (final name in declaredTopLevelNames(entry.readAsStringSync())) {
          typeIndex.putIfAbsent(name, () => rel);
        }
      }
    }

    // 3. Resolve every getIt<T>() in the entity's DI wiring.
    final resolutions = <EngineGetItResolution>[];
    final seenTypes = <String>{};
    for (final file in slice.entityDiFiles()) {
      final rel = p.relative(file.path, from: projectRoot);
      final source = file.readAsStringSync();
      for (final typeName in serviceLocatorAnalyzer.extractServiceLocatorTypes(
        source,
      )) {
        if (!seenTypes.add(typeName)) continue;
        final diFile = serviceLocatorAnalyzer.diRegistrationFileFor(
          typeName,
          projectRoot,
        );
        final declaringFile = typeIndex[typeName];
        resolutions.add(
          EngineGetItResolution(
            typeName: typeName,
            sourceFile: rel,
            diRegistrationFile: diFile == null
                ? null
                : p.relative(diFile, from: projectRoot),
            declaringFile: declaringFile,
          ),
        );
        if (diFile == null && declaringFile == null) {
          failures.add(
            EngineCheckFailure(
              code: EngineFindingCode.danglingGetIt,
              typeName: typeName,
              file: rel,
              message:
                  'Dangling getIt reference: `getIt<$typeName>()` in '
                  '$rel resolves to no generated class and no DI '
                  'registration file.\n'
                  '   --> fix: generate the missing slice for $typeName '
                  '(e.g. `zfa make engine $typeName`) or remove the '
                  '`getIt<$typeName>()` call from $rel.',
            ),
          );
        }
      }
    }

    // 4. Engine purity: zero package:flutter imports in the slice's lib
    //    files and test tree (exit criterion).
    for (final file in [...slice.sliceLibFiles(), ...slice.sliceTestFiles()]) {
      final rel = p.relative(file.path, from: projectRoot);
      final source = file.readAsStringSync();
      if (_flutterImportPattern.hasMatch(source)) {
        failures.add(
          EngineCheckFailure(
            code: EngineFindingCode.flutterImport,
            file: rel,
            message:
                'Flutter import in the engine slice: $rel imports '
                'package:flutter — engine slices must stay pure Dart.\n'
                '   --> fix: remove the Flutter import from $rel or move '
                'the UI dependency behind an engine-side interface.',
          ),
        );
      }
    }

    // 5. Per-method mock certification (when the method set is known —
    //    supplied by the caller, or resolved from the receipt in step 6).
    MockCertificationResult? certification;
    if (methods != null) {
      certification = _certifyMethods(
        entity: entity,
        methods: methods,
        projectRoot: projectRoot,
        failures: failures,
      );
    }

    // 6. Issue #1109, receipt leg: the v2 engine receipt must exist and
    //    record no uncertified method (the #1014/CERT-GATE signal).
    if (verifyReceipt) {
      final receipt = EngineReceiptWriter.loadV2Receipt(
        projectRoot,
        feature: feature,
        entity: entity,
      );
      if (receipt == null) {
        failures.add(
          EngineCheckFailure(
            code: EngineFindingCode.missingReceipt,
            typeName: entity,
            message:
                'Missing engine receipt: no engine.receipt.json for '
                '"$entity" under specs/<feature>/tdd/.\n'
                '   --> fix: run `zfa make engine $entity` first (it '
                'writes the receipt), or pass --feature <id> when the '
                'receipt lives in a non-default feature directory.',
          ),
        );
      } else {
        final recorded = (receipt['methods'] as List? ?? const [])
            .map(EngineReceiptMethod.fromJson)
            .whereType<EngineReceiptMethod>()
            .toList();
        for (final method in recorded.where((m) => !m.mockCertified)) {
          // When live certification already ran and failed this method,
          // its uncertifiedMock failure is the actionable finding —
          // don't double-report the same root cause. A live PASS against
          // a false record is kept: the receipt is stale and CERT-GATE
          // still reads the false.
          if (certification?.methods[method.name] == false) continue;
          failures.add(
            EngineCheckFailure(
              code: EngineFindingCode.receiptUncertified,
              typeName: method.name,
              message:
                  'Uncertified method in the engine receipt: '
                  '"${method.name}" is recorded with mock_certified: false '
                  'for "$entity".\n'
                  '   --> fix: regenerate the certified slice: '
                  '`zfa make engine $entity` (the certifier must pass for '
                  'every method before the receipt records true).',
            ),
          );
        }
        // The receipt's method set feeds live certification when the
        // caller did not supply one (the check command path).
        final methodSet = methods ?? recorded.map((m) => m.name).toList();
        if (methodSet.isNotEmpty && certification == null) {
          certification = _certifyMethods(
            entity: entity,
            methods: methodSet,
            projectRoot: projectRoot,
            failures: failures,
          );
        }
      }
    }

    // 7. Issue #1109, static-analysis leg: `dart analyze` scoped to the
    //    entity's slice files. Skipped (no failure) when there are no
    //    slice files or no package config to resolve imports against.
    final analyzedFiles = <String>[];
    if (runStaticAnalysis) {
      final sliceFiles = [...slice.sliceLibFiles(), ...slice.sliceTestFiles()];
      final hasPackageConfig = File(
        p.join(projectRoot, '.dart_tool', 'package_config.json'),
      ).existsSync();
      if (sliceFiles.isEmpty || !hasPackageConfig) {
        // Nothing to analyze (or nothing analyzable) — not a failure.
      } else {
        analyzedFiles.addAll(
          sliceFiles
              .map((file) => p.relative(file.path, from: projectRoot))
              .toList(),
        );
        final runner =
            analyzeRunner ?? analyzeRunnerOverride ?? _defaultAnalyzeRunner;
        final result = await runner(analyzedFiles, projectRoot);
        if (result.exitCode != 0) {
          failures.addAll(_analyzeFailures(result.output));
        }
      }
    }

    return EngineCheckResult(
      entity: entity,
      projectRoot: projectRoot,
      resolutions: resolutions,
      failures: failures,
      mockCertification: certification,
      analyzedFiles: analyzedFiles,
    );
  }

  /// Runs the live per-method mock certification and appends an
  /// [EngineFindingCode.uncertifiedMock] failure per uncertified method.
  static MockCertificationResult _certifyMethods({
    required String entity,
    required List<String> methods,
    required String projectRoot,
    required List<EngineCheckFailure> failures,
  }) {
    final certification = MockCertifier.certify(
      entity: entity,
      methods: methods,
      projectRoot: projectRoot,
    );
    for (final method in methods) {
      if (certification.methods[method] != true) {
        failures.add(
          EngineCheckFailure(
            code: EngineFindingCode.uncertifiedMock,
            typeName: method,
            file: certification.mockDatasourcePath,
            message:
                'Uncertified mock: method "$method" is not fully '
                'implemented on the mock datasource of "$entity" '
                '(missing member or missing seeded mock data).\n'
                '   --> fix: regenerate the certified mock: '
                '`zfa mock create $entity --methods=${methods.join(",")} '
                '--certify`.',
          ),
        );
      }
    }
    return certification;
  }

  /// `import '<anything>flutter<anything>'` — matches package:flutter,
  /// package:flutter_test, and flutter sub-packages.
  static final RegExp _flutterImportPattern = RegExp(
    r'''^\s*import\s+['"][^'"]*flutter[^'"]*['"]''',
    multiLine: true,
  );

  /// The production analyze runner: `dart analyze <files>` with the
  /// project root as the working directory so package imports resolve
  /// against the target project's package config.
  static Future<({int exitCode, String output})> _defaultAnalyzeRunner(
    List<String> files,
    String workingDirectory,
  ) async {
    final result = await Process.run('dart', [
      'analyze',
      '--no-fatal-warnings',
      ...files,
    ], workingDirectory: workingDirectory);
    return (
      exitCode: result.exitCode,
      output: '${result.stdout}${result.stderr}',
    );
  }

  /// Maps `dart analyze` output to failures. The analyzer's line shape
  /// is `  severity - file:line:col - message - code`; unparsed non-zero
  /// output degrades to one generic failure carrying the raw output
  /// tail, so the finding is never silently dropped.
  static List<EngineCheckFailure> _analyzeFailures(String output) {
    final failures = <EngineCheckFailure>[];
    final pattern = RegExp(
      r'^\s*(error|warning) - (.+?):\d+:\d+ - (.+?) - \S+$',
      multiLine: true,
    );
    for (final match in pattern.allMatches(output)) {
      final severity = match.group(1)!;
      final file = match.group(2)!.trim();
      final message = match.group(3)!.trim();
      failures.add(
        EngineCheckFailure(
          code: EngineFindingCode.staticAnalysis,
          file: file,
          message:
              'Analyzer $severity in the engine tree: $message ($file).\n'
              '   --> fix: address the finding in $file, then re-run '
              '`zfa engine check`.',
        ),
      );
    }
    if (failures.isEmpty) {
      final tail = output.trim();
      failures.add(
        EngineCheckFailure(
          code: EngineFindingCode.staticAnalysis,
          message:
              'Static analysis of the engine tree failed with no parsable '
              'findings.\n'
              '   --> fix: run `dart analyze` in the project to see the '
              'raw output. Tail:\n'
              '${tail.length > 800 ? tail.substring(tail.length - 800) : tail}',
        ),
      );
    }
    return failures;
  }
}

/// The scoped `dart analyze` runner for the engine check leg: (files,
/// workingDirectory) → (exitCode, output). Production spawns the real
/// subprocess; the fast test tier injects a deterministic fake through
/// [EngineChecker.analyzeRunnerOverride].
typedef EngineAnalyzeRunner =
    Future<({int exitCode, String output})> Function(
      List<String> files,
      String workingDirectory,
    );
