// GENERATED - DO NOT EDIT
// Generated by zfa for: ExtractedInvoice
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/extracted_invoice/extracted_invoice.dart';
import '../../mock/extracted_invoice_mock_data.dart';
import 'extracted_invoice_datasource.dart';

/// Mock data source for ExtractedInvoice
class ExtractedInvoiceMockDataSource
    with Loggable, FailureHandler
    implements ExtractedInvoiceDataSource {
  ExtractedInvoiceMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<ExtractedInvoice> get(QueryParams<ExtractedInvoice> params) async {
    logger.info('Getting ExtractedInvoice with params: $params');
    await Future.delayed(_delay);
    final item = ExtractedInvoiceMockData.extractedInvoices.query(params);
    logger.info('Successfully retrieved ExtractedInvoice');
    return item;
  }

  @override
  Future<ExtractedInvoice> update(
    UpdateParams<String, ExtractedInvoicePatch> params,
  ) async {
    logger.info('Updating ExtractedInvoice: ${params.id}');
    await Future.delayed(_delay);
    final existing = ExtractedInvoiceMockData.sampleExtractedInvoice;
    logger.info('Successfully updated ExtractedInvoice');
    return existing;
  }

  @override
  Future<ExtractedInvoice> toggle(
    ToggleParams<String, Field<ExtractedInvoice, dynamic>> params,
  ) async {
    logger.info(
      'Toggling ExtractedInvoice: ${params.id} on field ${params.field}',
    );
    await Future.delayed(_delay);
    final existing = ExtractedInvoiceMockData.sampleExtractedInvoice;
    logger.info('Successfully toggled ExtractedInvoice');
    return existing;
  }
}

// END GENERATED
