// GENERATED - DO NOT EDIT
// Generated by zfa for: UrlListing
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/url_listing/url_listing.dart';
import '../../repositories/url_listing_repository.dart';

class GetUrlListingUseCase
    extends UseCase<UrlListing, QueryParams<UrlListing>> {
  GetUrlListingUseCase(this._repository);

  final UrlListingRepository _repository;

  @override
  Future<UrlListing> execute(
    QueryParams<UrlListing> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
