// Tests for the day-zero app-surface writers (issue #626).
//
// `AppModuleWriter` emits `lib/app.dart` — the minimal zfa-generated app
// module whose DI container symbol derives from the app name. The
// bootstrap DI/routing index writers emit the empty-graph barrels that
// let `zfa app shell` run (and upgrade the minimal shell) before the
// first entity exists.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/writers/tdd/app_module_writer.dart';
import 'package:zuraffa/src/plugins/app_shell/builders/app_shell_builder.dart';

void main() {
  late Directory tmpDir;

  setUp(() {
    tmpDir = Directory.systemTemp.createTempSync('app_module_writer_test_');
  });

  tearDown(() {
    if (tmpDir.existsSync()) tmpDir.deleteSync(recursive: true);
  });

  group('AppModuleWriter', () {
    test('container symbol derives from the app name (issue #626)', () {
      // Maintainer decision on #626: `zfa setup zik_zak_tdd` emits
      // `ZikZakTddContainer` (PascalCase of the app name + Container).
      expect(
        AppModuleWriter.containerSymbolFor('zik_zak_tdd'),
        'ZikZakTddContainer',
      );
      expect(AppModuleWriter.containerSymbolFor('myapp'), 'MyappContainer');
      expect(
        AppModuleWriter.containerSymbolFor('day_zero_app'),
        'DayZeroAppContainer',
      );
    });

    test('renders a zfa-attributable Flutter app module', () {
      final rendered = const AppModuleWriter(
        isFlutter: true,
      ).render('zik_zak_tdd');
      expect(rendered, contains('Generated by zfa'));
      expect(rendered, contains('class ZikZakTddContainer'));
      expect(
        rendered,
        contains("import 'package:zuraffa_flutter/zuraffa_flutter.dart';"),
      );
      expect(rendered, contains('final GetIt di = GetIt.instance;'));
      // Bootstrap DI: an empty graph — registering nothing day zero.
      expect(rendered, contains('void bootstrap() {}'));
    });

    test('renders the zuraffa import for pure-Dart projects', () {
      final rendered = const AppModuleWriter(isFlutter: false).render('mylib');
      expect(rendered, contains("import 'package:zuraffa/zuraffa.dart';"));
      expect(rendered, contains('class MylibContainer'));
      expect(rendered, isNot(contains('zuraffa_flutter')));
    });

    test('writes lib/app.dart into the project', () async {
      final path = await const AppModuleWriter().write(tmpDir.path, 'myapp');
      expect(path, isNotNull);
      final file = File(p.join(tmpDir.path, 'lib/app.dart'));
      expect(file.existsSync(), isTrue);
      expect(file.readAsStringSync(), contains('class MyappContainer'));
    });

    test('is idempotent — never overwrites existing app content', () async {
      final writer = const AppModuleWriter();
      await writer.write(tmpDir.path, 'myapp');
      final file = File(p.join(tmpDir.path, 'lib/app.dart'));
      await file.writeAsString('// Hand-written app module\n');
      final result = await writer.write(tmpDir.path, 'myapp');
      expect(
        result,
        isNull,
        reason: 'skip-if-exists: user content is never clobbered',
      );
      expect(file.readAsStringSync(), '// Hand-written app module\n');
    });

    test('dry-run reports the path without writing', () async {
      final path = await const AppModuleWriter().write(
        tmpDir.path,
        'myapp',
        dryRun: true,
      );
      expect(path, isNotNull);
      expect(File(p.join(tmpDir.path, 'lib/app.dart')).existsSync(), isFalse);
    });
  });

  group('BootstrapDiIndexWriter', () {
    test('emits an empty setupDependencies the app shell accepts', () {
      final content = const BootstrapDiIndexWriter().render();
      expect(content, contains('Generated by zfa'));
      // The app-shell preflight (issue #370 hardening) strips comments
      // before matching — the bootstrap barrel must carry a real
      // declaration, not just a mention.
      expect(AppShellBuilder.hasSetupDependenciesDeclaration(content), isTrue);
      // The canonical GetIt-based signature, so main.dart calls
      // setupDependencies(GetIt.instance) and later `zfa di` runs append
      // into the same shape.
      expect(AppShellBuilder.setupDependenciesTakesGetIt(content), isTrue);
      expect(AppShellBuilder.setupDependenciesIsAsync(content), isFalse);
      expect(content, contains('void setupDependencies(GetIt getIt) {}'));
    });

    test(
      'writes lib/src/di/index.dart, skip-if-exists, dry-run aware',
      () async {
        final writer = const BootstrapDiIndexWriter();
        final path = await writer.write(tmpDir.path);
        expect(path, isNotNull);
        expect(
          File(p.join(tmpDir.path, 'lib/src/di/index.dart')).existsSync(),
          isTrue,
        );

        // Never clobber real generated DI content on a re-setup.
        final index = File(p.join(tmpDir.path, 'lib/src/di/index.dart'));
        await index.writeAsString('// real generated DI\n');
        expect(await writer.write(tmpDir.path), isNull);
        expect(index.readAsStringSync(), '// real generated DI\n');

        expect(await writer.write(tmpDir.path, dryRun: true), isNotNull);
      },
    );
  });

  group('BootstrapRoutingIndexWriter', () {
    test('emits an empty getAllRoutes barrel', () {
      final content = const BootstrapRoutingIndexWriter().render();
      expect(content, contains('Generated by zfa'));
      // The app-shell preflight checks the barrel mentions getAllRoutes.
      expect(content, contains('List<RouteBase> getAllRoutes()'));
      expect(content, contains("import 'package:go_router/go_router.dart';"));
    });

    test('writes lib/src/routing/index.dart, skip-if-exists', () async {
      final writer = const BootstrapRoutingIndexWriter();
      final path = await writer.write(tmpDir.path);
      expect(path, isNotNull);
      expect(
        File(p.join(tmpDir.path, 'lib/src/routing/index.dart')).existsSync(),
        isTrue,
      );

      final index = File(p.join(tmpDir.path, 'lib/src/routing/index.dart'));
      await index.writeAsString('// real generated routes\n');
      expect(await writer.write(tmpDir.path), isNull);
      expect(index.readAsStringSync(), '// real generated routes\n');
    });
  });

  group('AppShellBuilder.isFlutterCreateHelloWorldStub', () {
    test('detects the flutter create --empty Hello-World boilerplate', () {
      const stub = '''
import 'package:flutter/material.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: Scaffold(body: Center(child: Text('Hello World!'))),
    );
  }
}
''';
      expect(AppShellBuilder.isFlutterCreateHelloWorldStub(stub), isTrue);
    });

    test('does not match the zfa shell main.dart', () {
      final shellMain = const AppShellBuilder().buildMain(
        appName: 'my_app',
        diTakesGetIt: true,
      );
      expect(AppShellBuilder.isFlutterCreateHelloWorldStub(shellMain), isFalse);
    });

    test('does not match a customized user main', () {
      const custom = '''
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(home: Scaffold(body: Text('Welcome home')));
  }
}
''';
      expect(AppShellBuilder.isFlutterCreateHelloWorldStub(custom), isFalse);
    });
  });
}
