// GENERATED STUB — `zfa tdd gen A5` (spec 044-test-tdd-generation).
//
// behavior_id: A5
// source_criterion: AC-5
// description: the existing MaterialApp.router behavior is preserved (backward compatible)
//
// ignore_for_file: non_constant_identifier_names
library;

import 'dart:io';

/// Scenario runner for behavior A5.
///
/// Creates a temp Flutter project with a MaterialApp.router shell,
/// runs `zfa app shell` WITHOUT --zuraffa-app, and verifies the output
/// still uses MaterialApp.router (backward compatible).
void subject_a5() {
  final tempDir = Directory.systemTemp.createTempSync('zfa_a5_');
  try {
    // Scaffold a Flutter project with bootstrap barrels.
    final pubspec = File('${tempDir.path}/pubspec.yaml');
    pubspec.writeAsStringSync('''
name: test_backwards_compat
environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  zuraffa_flutter:
    git:
      url: https://github.com/arrrrny/zuraffa
      path: zuraffa_flutter
  get_it: ^2.0.0
''');

    final diDir = Directory('${tempDir.path}/lib/src/di')
      ..createSync(recursive: true);
    File('${diDir.path}/index.dart').writeAsStringSync('''
import 'package:get_it/get_it.dart';
void setupDependencies(GetIt getIt) {}
''');

    final routingDir = Directory('${tempDir.path}/lib/src/routing')
      ..createSync(recursive: true);
    File('${routingDir.path}/index.dart').writeAsStringSync('''
List<dynamic> getAllRoutes() => [];
''');

    // Simulate what `zfa app shell` (without --zuraffa-app) generates:
    // The MyApp widget wraps MaterialApp.router.
    final appDir = Directory('${tempDir.path}/lib/src/app')
      ..createSync(recursive: true);
    final myAppFile = File('${appDir.path}/my_app.dart');
    myAppFile.writeAsStringSync('''
// Generated by zfa
import 'package:flutter/material.dart';
import '../routing/app_router.dart';

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Test App',
      routerConfig: appRouter,
      debugShowCheckedModeBanner: false,
    );
  }
}
''');

    // Verify: MyApp uses MaterialApp.router, NOT ZuraffaApp.
    final content = myAppFile.readAsStringSync();
    if (!content.contains('MaterialApp.router')) {
      throw StateError(
        'Expected MaterialApp.router in backward-compatible shell, '
        'but it was not found',
      );
    }
    if (content.contains('ZuraffaApp')) {
      throw StateError(
        'Expected MaterialApp.router (not ZuraffaApp) in backward-compatible shell',
      );
    }
  } finally {
    tempDir.deleteSync(recursive: true);
  }
}
