import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';
import 'package:zuraffa/src/commands/app_shell_command.dart';

import '../helpers/project_root.dart';

void main() {
  group('AppShellCommand', () {
    test('has name "shell"', () {
      expect(AppShellCommand().name, 'shell');
    });

    test('has a non-empty description', () {
      expect(AppShellCommand().description, isNotEmpty);
    });

    test('exposes --dry-run flag', () {
      expect(AppShellCommand().argParser.options, contains('dry-run'));
    });

    test('exposes --force flag', () {
      expect(AppShellCommand().argParser.options, contains('force'));
    });

    test('exposes --verbose flag', () {
      expect(AppShellCommand().argParser.options, contains('verbose'));
    });

    test('exposes --mock flag', () {
      expect(AppShellCommand().argParser.options, contains('mock'));
    });

    test('exposes --title option', () {
      expect(AppShellCommand().argParser.options, contains('title'));
    });

    test('exposes --output option defaulting to lib/src', () {
      final cmd = AppShellCommand();
      expect(cmd.argParser.options, contains('output'));
      // The default is enforced at parse time, not on the option spec, so
      // verify by parsing an empty arg list.
      final result = cmd.argParser.parse([]);
      expect(result['output'], 'lib/src');
    });

    test('does NOT take a positional name argument (it operates on cwd)', () {
      final cmd = AppShellCommand();
      // The command takes no positional args — it derives the app name
      // from pubspec.yaml in the current working directory. We verify
      // by checking that no positional rest options are declared.
      expect(cmd.argParser.options, isNot(contains('name')));
    });
  });

  group('AppCommand (parent)', () {
    test('has name "app"', () {
      expect(AppCommand().name, 'app');
    });

    test('exposes the shell subcommand', () {
      final app = AppCommand();
      expect(app.subcommands, contains('shell'));
      expect(app.subcommands['shell'], isA<AppShellCommand>());
    });
  });

  group('CLI registration', () {
    test('CliRunner exposes the `app` command in the top-level help', () async {
      final runner = CliRunner(exitOnCompletion: false);
      final help = await runner.runCapturing(['--help']);
      // The args CommandRunner auto-generates the command list from the
      // registered subcommands. We expect `app` to appear (the
      // subcommand `shell` is listed under `zfa app --help`).
      expect(help, contains(' app '));
    });

    test('CliRunner dispatches `zfa app shell --help`', () async {
      final runner = CliRunner(exitOnCompletion: false);
      final help = await runner.runCapturing(['app', 'shell', '--help']);
      // The args package prints the command description in the help
      // header. Either the description or the usage line is sufficient
      // proof the command is registered.
      expect(
        help.contains('Generate the app shell') ||
            help.contains('zfa app shell'),
        isTrue,
      );
    });

    test('CliRunner lists `shell` under `zfa app --help`', () async {
      final runner = CliRunner(exitOnCompletion: false);
      final help = await runner.runCapturing(['app', '--help']);
      expect(help, contains('shell'));
    });
  });

  group('end-to-end generation', () {
    late Directory workspace;

    setUp(() async {
      workspace = await Directory.systemTemp.createTemp('zfa_app_shell_');
      await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: my_test_app
description: A test app for the app-shell generator.
environment:
  sdk: ^3.11.0
''');
      // Scaffold a minimal di/index.dart exporting setupDependencies().
      final diDir = Directory(p.join(workspace.path, 'lib', 'src', 'di'))
        ..createSync(recursive: true);
      await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
Future<void> setupDependencies() async {}
''');
      // Scaffold a minimal routing/index.dart exporting getAllRoutes().
      final routingDir = Directory(
        p.join(workspace.path, 'lib', 'src', 'routing'),
      )..createSync(recursive: true);
      await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');

      Directory.current = workspace.path;
    });

    tearDown(() async {
      try {
        Directory.current = await findProjectRoot();
      } catch (_) {}
      if (workspace.existsSync()) {
        await workspace.delete(recursive: true);
      }
    });

    test('writes all three glue files when run from a project root', () async {
      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell']);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      final myAppFile = File(
        p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
      );
      final appRouterFile = File(
        p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
      );

      expect(mainFile.existsSync(), isTrue, reason: 'lib/main.dart missing');
      expect(
        myAppFile.existsSync(),
        isTrue,
        reason: 'lib/src/app/my_app.dart missing',
      );
      expect(
        appRouterFile.existsSync(),
        isTrue,
        reason: 'lib/src/routing/app_router.dart missing',
      );

      final mainSrc = mainFile.readAsStringSync();
      expect(mainSrc, contains('void main() async'));
      expect(mainSrc, contains('await setupDependencies()'));
      expect(mainSrc, contains('runApp(const MyApp())'));
      expect(
        mainSrc,
        contains("import 'package:my_test_app/src/di/index.dart';"),
      );
      expect(
        mainSrc,
        contains("import 'package:my_test_app/src/app/my_app.dart';"),
      );

      final myAppSrc = myAppFile.readAsStringSync();
      expect(myAppSrc, contains('class MyApp extends StatelessWidget'));
      expect(myAppSrc, contains('MaterialApp.router('));
      expect(myAppSrc, contains('routerConfig: appRouter'));

      final appRouterSrc = appRouterFile.readAsStringSync();
      expect(appRouterSrc, contains('final GoRouter appRouter'));
      expect(appRouterSrc, contains('routes: getAllRoutes()'));
    });

    test(
      '--output lib/custom writes glue there and main.dart imports resolve',
      () async {
        // Scaffold the DI + routing indexes under the custom output dir.
        final diDir = Directory(p.join(workspace.path, 'lib', 'custom', 'di'))
          ..createSync(recursive: true);
        await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
Future<void> setupDependencies() async {}
''');
        final routingDir = Directory(
          p.join(workspace.path, 'lib', 'custom', 'routing'),
        )..createSync(recursive: true);
        await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');

        final runner = CliRunner(exitOnCompletion: false);
        await runner.runCapturing(['app', 'shell', '--output', 'lib/custom']);

        // Glue files land under lib/custom, not lib/src.
        expect(
          File(
            p.join(workspace.path, 'lib', 'custom', 'app', 'my_app.dart'),
          ).existsSync(),
          isTrue,
          reason: 'my_app.dart should land under lib/custom',
        );
        expect(
          File(
            p.join(
              workspace.path,
              'lib',
              'custom',
              'routing',
              'app_router.dart',
            ),
          ).existsSync(),
          isTrue,
          reason: 'app_router.dart should land under lib/custom',
        );
        expect(
          File(
            p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
          ).existsSync(),
          isFalse,
          reason: 'nothing should be written under lib/src',
        );

        // main.dart imports must point at the actual output dir so the
        // emitted entrypoint resolves to the written files.
        final mainSrc = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        expect(
          mainSrc,
          contains("import 'package:my_test_app/custom/app/my_app.dart';"),
        );
        expect(
          mainSrc,
          contains("import 'package:my_test_app/custom/di/index.dart';"),
        );
        expect(mainSrc, isNot(contains('package:my_test_app/src/')));
      },
    );

    test('rejects --output outside lib/ with an actionable error', () async {
      final runner = CliRunner(exitOnCompletion: false);
      final output = await runner.runCapturing([
        'app',
        'shell',
        '--output',
        'src',
      ]);

      expect(output, contains('must live under lib/'));
      // Nothing should have been written.
      expect(
        File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isFalse,
      );
    });

    test('respects the --title flag', () async {
      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell', '--title', 'Hello World']);

      final myAppFile = File(
        p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
      );
      expect(myAppFile.existsSync(), isTrue);
      expect(myAppFile.readAsStringSync(), contains("title: 'Hello World'"));
    });

    test('adds the mock hint when --mock is passed', () async {
      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell', '--mock']);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      expect(mainFile.existsSync(), isTrue);
      final src = mainFile.readAsStringSync();
      expect(src, contains('Mock DI mode'));
    });

    test('does NOT add the mock hint by default', () async {
      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell']);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      expect(mainFile.existsSync(), isTrue);
      expect(mainFile.readAsStringSync().contains('Mock DI mode'), isFalse);
    });

    test('skips an existing lib/main.dart without --force', () async {
      // Pre-create a user-written main.dart.
      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      await mainFile.parent.create(recursive: true);
      await mainFile.writeAsString('void main() {} // user-written\n');

      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell']);

      // The user-written file should be preserved (not overwritten).
      expect(mainFile.readAsStringSync(), contains('user-written'));
      // The glue files should still be generated.
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isTrue,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isTrue,
      );
    });

    test(
      'overwrites an existing lib/main.dart when --force is passed',
      () async {
        final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
        await mainFile.parent.create(recursive: true);
        await mainFile.writeAsString('void main() {} // user-written\n');

        final runner = CliRunner(exitOnCompletion: false);
        await runner.runCapturing(['app', 'shell', '--force']);

        final src = mainFile.readAsStringSync();
        expect(src.contains('user-written'), isFalse);
        expect(src, contains('await setupDependencies()'));
      },
    );

    test('--dry-run writes nothing', () async {
      final runner = CliRunner(exitOnCompletion: false);
      await runner.runCapturing(['app', 'shell', '--dry-run']);

      expect(
        File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isFalse,
      );
    });

    test(
      'fails with an actionable error when setupDependencies is missing',
      () async {
        // Remove the DI index.
        await File(
          p.join(workspace.path, 'lib', 'src', 'di', 'index.dart'),
        ).delete();

        final runner = CliRunner(exitOnCompletion: false);
        final output = await runner.runCapturing(['app', 'shell']);

        expect(output, contains('setupDependencies'));
        expect(output, contains('zfa di'));
        // main.dart should NOT have been written.
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
        );
      },
    );

    test(
      'fails with an actionable error when getAllRoutes is missing',
      () async {
        // Remove the routing index.
        await File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'index.dart'),
        ).delete();

        final runner = CliRunner(exitOnCompletion: false);
        final output = await runner.runCapturing(['app', 'shell']);

        expect(output, contains('getAllRoutes'));
        expect(output, contains('zfa route'));
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
        );
      },
    );

    test(
      'fails with an actionable error when pubspec.yaml is missing',
      () async {
        // Move to an empty dir.
        final empty = await Directory.systemTemp.createTemp(
          'zfa_app_shell_empty_',
        );
        Directory.current = empty.path;
        try {
          final runner = CliRunner(exitOnCompletion: false);
          final output = await runner.runCapturing(['app', 'shell']);

          expect(output, contains('pubspec.yaml'));
          expect(
            File(p.join(empty.path, 'lib', 'main.dart')).existsSync(),
            isFalse,
          );
        } finally {
          if (empty.existsSync()) await empty.delete(recursive: true);
        }
      },
    );
  });
}
