import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/commands/app_shell_command.dart';

import '../helpers/run_zfa_source.dart';

void main() {
  setUpAll(() async {
    await initZfaSourceBin();
  });

  group('AppShellCommand', () {
    test('has name "shell"', () {
      expect(AppShellCommand().name, 'shell');
    });

    test('has a non-empty description', () {
      expect(AppShellCommand().description, isNotEmpty);
    });

    test('exposes --dry-run flag', () {
      expect(AppShellCommand().argParser.options, contains('dry-run'));
    });

    test('exposes --force flag', () {
      expect(AppShellCommand().argParser.options, contains('force'));
    });

    test('exposes --verbose flag', () {
      expect(AppShellCommand().argParser.options, contains('verbose'));
    });

    test('exposes --mock flag', () {
      expect(AppShellCommand().argParser.options, contains('mock'));
    });

    test('exposes --title option', () {
      expect(AppShellCommand().argParser.options, contains('title'));
    });

    test('exposes --output option defaulting to lib/src', () {
      final cmd = AppShellCommand();
      expect(cmd.argParser.options, contains('output'));
      // The default is enforced at parse time, not on the option spec, so
      // verify by parsing an empty arg list.
      final result = cmd.argParser.parse([]);
      expect(result['output'], 'lib/src');
    });

    test('does NOT take a positional name argument (it operates on cwd)', () {
      final cmd = AppShellCommand();
      // The command takes no positional args — it derives the app name
      // from pubspec.yaml in the current working directory. We verify
      // by checking that no positional rest options are declared.
      expect(cmd.argParser.options, isNot(contains('name')));
    });
  });

  group('AppCommand (parent)', () {
    test('has name "app"', () {
      expect(AppCommand().name, 'app');
    });

    test('exposes the shell subcommand', () {
      final app = AppCommand();
      expect(app.subcommands, contains('shell'));
      expect(app.subcommands['shell'], isA<AppShellCommand>());
    });
  });

  group('CLI registration', timeout: const Timeout(Duration(minutes: 2)), () {
    test('CliRunner exposes the `app` command in the top-level help', () async {
      final result = await runZfaSource([
        '--help',
      ], workingDirectory: zfaProjectRoot);
      // The args CommandRunner auto-generates the command list from the
      // registered subcommands. We expect `app` to appear (the
      // subcommand `shell` is listed under `zfa app --help`).
      expect(combinedOutput(result), contains(' app '));
    });

    test('CliRunner dispatches `zfa app shell --help`', () async {
      final result = await runZfaSource([
        'app',
        'shell',
        '--help',
      ], workingDirectory: zfaProjectRoot);
      final help = combinedOutput(result);
      // The args package prints the command description in the help
      // header. Either the description or the usage line is sufficient
      // proof the command is registered.
      expect(
        help.contains('Generate the app shell') ||
            help.contains('zfa app shell'),
        isTrue,
      );
    });

    test('CliRunner lists `shell` under `zfa app --help`', () async {
      final result = await runZfaSource([
        'app',
        '--help',
      ], workingDirectory: zfaProjectRoot);
      expect(combinedOutput(result), contains('shell'));
    });
  });

  group('end-to-end generation', timeout: const Timeout(Duration(minutes: 2)), () {
    late Directory workspace;

    setUp(() async {
      workspace = await Directory.systemTemp.createTemp('zfa_app_shell_');
      await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: my_test_app
description: A test app for the app-shell generator.
environment:
  sdk: ^3.11.0
''');
      // Scaffold the canonical zfa-generated DI barrel — `void
      // setupDependencies(GetIt getIt)` (the signature emitted by
      // `zfa di` / `zfa make --with=di` via registration_builder.dart).
      // The shell must detect this signature and emit a matching
      // `setupDependencies(GetIt.instance)` call. See issue #370.
      final diDir = Directory(p.join(workspace.path, 'lib', 'src', 'di'))
        ..createSync(recursive: true);
      await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:get_it/get_it.dart';
void setupDependencies(GetIt getIt) {}
''');
      // Scaffold a minimal routing/index.dart exporting getAllRoutes().
      final routingDir = Directory(
        p.join(workspace.path, 'lib', 'src', 'routing'),
      )..createSync(recursive: true);
      await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');
    });

    tearDown(() async {
      if (workspace.existsSync()) {
        await workspace.delete(recursive: true);
      }
    });

    test('writes all three glue files when run from a project root', () async {
      await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
      ], workingDirectory: zfaProjectRoot);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      final myAppFile = File(
        p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
      );
      final appRouterFile = File(
        p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
      );

      expect(mainFile.existsSync(), isTrue, reason: 'lib/main.dart missing');
      expect(
        myAppFile.existsSync(),
        isTrue,
        reason: 'lib/src/app/my_app.dart missing',
      );
      expect(
        appRouterFile.existsSync(),
        isTrue,
        reason: 'lib/src/routing/app_router.dart missing',
      );

      final mainSrc = mainFile.readAsStringSync();
      expect(mainSrc, contains('void main() {'));
      // Canonical DI is synchronous void — main must NOT await it.
      expect(mainSrc, isNot(contains('void main() async')));
      expect(mainSrc, contains('setupDependencies(GetIt.instance);'));
      expect(mainSrc, isNot(contains('await setupDependencies')));
      expect(mainSrc, contains("import 'package:zuraffa/zuraffa.dart';"));
      expect(
        mainSrc,
        contains("import 'package:my_test_app/src/di/index.dart';"),
      );
      expect(
        mainSrc,
        contains("import 'package:my_test_app/src/app/my_app.dart';"),
      );

      final myAppSrc = myAppFile.readAsStringSync();
      expect(myAppSrc, contains('class MyApp extends StatelessWidget'));
      expect(myAppSrc, contains('MaterialApp.router('));
      expect(myAppSrc, contains('routerConfig: appRouter'));

      final appRouterSrc = appRouterFile.readAsStringSync();
      expect(appRouterSrc, contains('final GoRouter appRouter'));
      expect(appRouterSrc, contains('routes: getAllRoutes()'));
    });

    test(
      '--output lib/custom writes glue there and main.dart imports resolve',
      () async {
        // Scaffold the DI + routing indexes under the custom output dir.
        final diDir = Directory(p.join(workspace.path, 'lib', 'custom', 'di'))
          ..createSync(recursive: true);
        await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:get_it/get_it.dart';
void setupDependencies(GetIt getIt) {}
''');
        final routingDir = Directory(
          p.join(workspace.path, 'lib', 'custom', 'routing'),
        )..createSync(recursive: true);
        await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');

        await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
          '--output',
          'lib/custom',
        ], workingDirectory: zfaProjectRoot);

        // Glue files land under lib/custom, not lib/src.
        expect(
          File(
            p.join(workspace.path, 'lib', 'custom', 'app', 'my_app.dart'),
          ).existsSync(),
          isTrue,
          reason: 'my_app.dart should land under lib/custom',
        );
        expect(
          File(
            p.join(
              workspace.path,
              'lib',
              'custom',
              'routing',
              'app_router.dart',
            ),
          ).existsSync(),
          isTrue,
          reason: 'app_router.dart should land under lib/custom',
        );
        expect(
          File(
            p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
          ).existsSync(),
          isFalse,
          reason: 'nothing should be written under lib/src',
        );

        // main.dart imports must point at the actual output dir so the
        // emitted entrypoint resolves to the written files.
        final mainSrc = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        expect(
          mainSrc,
          contains("import 'package:my_test_app/custom/app/my_app.dart';"),
        );
        expect(
          mainSrc,
          contains("import 'package:my_test_app/custom/di/index.dart';"),
        );
        expect(mainSrc, isNot(contains('package:my_test_app/src/')));
      },
    );

    test('rejects --output outside lib/ with an actionable error', () async {
      final result = await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
        '--output',
        'src',
      ], workingDirectory: zfaProjectRoot);

      final output = combinedOutput(result);
      expect(output, contains('must live under lib/'));
      // Nothing should have been written.
      expect(
        File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isFalse,
      );
    });

    test('respects the --title flag', () async {
      await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
        '--title',
        'Hello World',
      ], workingDirectory: zfaProjectRoot);

      final myAppFile = File(
        p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
      );
      expect(myAppFile.existsSync(), isTrue);
      expect(myAppFile.readAsStringSync(), contains("title: 'Hello World'"));
    });

    test('adds the mock hint when --mock is passed', () async {
      await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
        '--mock',
      ], workingDirectory: zfaProjectRoot);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      expect(mainFile.existsSync(), isTrue);
      final src = mainFile.readAsStringSync();
      expect(src, contains('Mock DI mode'));
    });

    test('does NOT add the mock hint by default', () async {
      await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
      ], workingDirectory: zfaProjectRoot);

      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      expect(mainFile.existsSync(), isTrue);
      expect(mainFile.readAsStringSync().contains('Mock DI mode'), isFalse);
    });

    test('skips an existing lib/main.dart without --force', () async {
      // Pre-create a user-written main.dart.
      final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
      await mainFile.parent.create(recursive: true);
      await mainFile.writeAsString('void main() {} // user-written\n');

      await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
      ], workingDirectory: zfaProjectRoot);

      // The user-written file should be preserved (not overwritten).
      expect(mainFile.readAsStringSync(), contains('user-written'));
      // The glue files should still be generated.
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isTrue,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isTrue,
      );
    });

    test(
      'overwrites an existing lib/main.dart when --force is passed',
      () async {
        final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
        await mainFile.parent.create(recursive: true);
        await mainFile.writeAsString('void main() {} // user-written\n');

        await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
          '--force',
        ], workingDirectory: zfaProjectRoot);

        final src = mainFile.readAsStringSync();
        expect(src.contains('user-written'), isFalse);
        expect(src, contains('setupDependencies(GetIt.instance);'));
      },
    );

    test('--dry-run writes nothing', () async {
      final result = await runZfaSource([
        'app',
        'shell',
        '--root',
        workspace.path,
        '--dry-run',
      ], workingDirectory: zfaProjectRoot);

      expect(result.exitCode, 0, reason: 'dry-run must exit successfully');

      expect(
        File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'app', 'my_app.dart'),
        ).existsSync(),
        isFalse,
      );
      expect(
        File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'app_router.dart'),
        ).existsSync(),
        isFalse,
      );
    });

    test(
      'fails with an actionable error when setupDependencies is missing',
      () async {
        // Remove the DI index.
        await File(
          p.join(workspace.path, 'lib', 'src', 'di', 'index.dart'),
        ).delete();

        final result = await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
        ], workingDirectory: zfaProjectRoot);

        final output = combinedOutput(result);
        expect(output, contains('setupDependencies'));
        expect(output, contains('zfa di'));
        // main.dart should NOT have been written.
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
        );
      },
    );

    // Regression for issue #370: the old pre-flight only checked that
    // di/index.dart CONTAINED the substring `setupDependencies`, so a file
    // that mentioned the name only in a comment (no real declaration) passed
    // the check and then produced a non-compiling main.dart. The hardened
    // check requires an actual `setupDependencies(` declaration.
    test(
      'fails when di/index.dart mentions setupDependencies only in a comment',
      () async {
        await File(
          p.join(workspace.path, 'lib', 'src', 'di', 'index.dart'),
        ).writeAsString('''
// TODO: call setupDependencies() once DI is generated
void unrelated() {}
''');

        final result = await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
        ], workingDirectory: zfaProjectRoot);

        final output = combinedOutput(result);
        expect(output, contains('does not declare setupDependencies'));
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
        );
      },
    );

    // Regression for issue #370: a no-arg synchronous custom DI entrypoint
    // (`void setupDependencies() {}`) must still produce a compiling
    // main.dart — `setupDependencies();` with no await and no GetIt import.
    // This guards the backward-compatible branch of the signature detection.
    test(
      '#370 no-arg DI: emits setupDependencies() with no await and no GetIt import',
      () async {
        await File(
          p.join(workspace.path, 'lib', 'src', 'di', 'index.dart'),
        ).writeAsString('''
// Generated by zfa
void setupDependencies() {}
''');

        await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
          '--force',
        ], workingDirectory: zfaProjectRoot);

        final src = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        expect(src, contains('void main() {'));
        expect(src, isNot(contains('void main() async')));
        expect(src, contains('setupDependencies();'));
        expect(src, isNot(contains('await setupDependencies')));
        // No GetIt param -> no zuraffa import needed.
        expect(src, isNot(contains('package:zuraffa/zuraffa.dart')));
      },
    );

    // Regression for issue #370: the canonical `zfa di` / `zfa make --with=di`
    // flow emits `void setupDependencies(GetIt getIt)`. main.dart MUST call
    // `setupDependencies(GetIt.instance)` (passing GetIt.instance), MUST NOT
    // await it (synchronous void), and MUST import zuraffa for GetIt. This is
    // the exact mismatch that crashed main.dart before the fix.
    test(
      '#370 canonical GetIt DI: main.dart calls setupDependencies(GetIt.instance) and compiles',
      () async {
        // The setUp scaffold already writes the canonical GetIt signature,
        // so just run the shell and assert the generated main.dart.
        await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
          '--force',
        ], workingDirectory: zfaProjectRoot);

        final src = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        // The two errors from the issue must both be gone:
        //  - not_enough_positional_arguments -> GetIt.instance is passed.
        //  - use_of_void_result -> no await on the synchronous void call.
        expect(src, contains('setupDependencies(GetIt.instance);'));
        expect(src, isNot(contains('await setupDependencies')));
        expect(src, contains("import 'package:zuraffa/zuraffa.dart';"));
        expect(src, contains('void main() {'));
      },
    );

    test(
      '#370 async GetIt DI: main.dart awaits setupDependencies(GetIt.instance)',
      () async {
        await File(
          p.join(workspace.path, 'lib', 'src', 'di', 'index.dart'),
        ).writeAsString('''
// Generated by zfa
import 'package:get_it/get_it.dart';
Future<void> setupDependencies(GetIt getIt) async {}
''');

        await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
          '--force',
        ], workingDirectory: zfaProjectRoot);

        final src = File(
          p.join(workspace.path, 'lib', 'main.dart'),
        ).readAsStringSync();
        expect(src, contains('void main() async'));
        expect(src, contains('await setupDependencies(GetIt.instance);'));
        expect(src, contains("import 'package:zuraffa/zuraffa.dart';"));
      },
    );

    test(
      'fails with an actionable error when getAllRoutes is missing',
      () async {
        // Remove the routing index.
        await File(
          p.join(workspace.path, 'lib', 'src', 'routing', 'index.dart'),
        ).delete();

        final result = await runZfaSource([
          'app',
          'shell',
          '--root',
          workspace.path,
        ], workingDirectory: zfaProjectRoot);

        final output = combinedOutput(result);
        expect(output, contains('getAllRoutes'));
        expect(output, contains('zfa route'));
        expect(
          File(p.join(workspace.path, 'lib', 'main.dart')).existsSync(),
          isFalse,
        );
      },
    );

    test(
      'fails with an actionable error when pubspec.yaml is missing',
      () async {
        // Run against an empty dir via --root (no CWD mutation).
        final empty = await Directory.systemTemp.createTemp(
          'zfa_app_shell_empty_',
        );
        try {
          final result = await runZfaSource([
            'app',
            'shell',
            '--root',
            empty.path,
          ], workingDirectory: empty.path);

          final output = combinedOutput(result);
          expect(output, contains('pubspec.yaml'));
          expect(
            File(p.join(empty.path, 'lib', 'main.dart')).existsSync(),
            isFalse,
          );
        } finally {
          if (empty.existsSync()) await empty.delete(recursive: true);
        }
      },
    );
  });
}
