// Bug 1675 defect 3 — the `zfa build` analyze gate's ownership classifier
// (`BuildCommand.analyzeGateRemedyLines` → `_isGeneratedPath`).
//
// The gate's remedy follows the offenders' OWNERSHIP: files `zfa make` just
// wrote must be attributed to the generator (the original #1675 misdirection
// was the reverse — fresh make output labeled "hand-authored", telling the
// user to hand-patch files the next regeneration clobbers), while code
// outside the generator's tree must stay honestly hand-authored.
//
// The make-owned directory conventions (`domain`/`data`/`di`/`routing`/
// `presentation`/`cache`) are therefore matched *under the output dir*
// (`lib/src` by default) only — a `test/data/…` or `lib/data/…` path is not
// make output. What remains is a deliberate, documented trade-off:
// hand-authored code inside an owned segment *under* the output dir is
// indistinguishable from make output by path alone and is attributed to the
// generator. That trade-off is pinned below so changing it means changing
// the intended semantics, not just the heuristic.
//
// Pure and process-free (no `dart analyze` spawn), so this file runs in the
// default fast lane; the same classifier's slower pins live in
// `test/commands/build_command_unit_test.dart` and
// `test/fixes/bug_1675_make_crud_vpc_route_compile_test.dart`.
import 'package:test/test.dart';
import 'package:zuraffa/src/commands/build_command.dart';

void main() {
  /// One `dart analyze` excerpt in the single-line format the remedy
  /// classifier parses: `   error - path:line:col - message - code`.
  String analyzeOutput(List<String> paths) => [
    'Analyzing lib/...',
    for (final path in paths)
      '   error - $path:1:1 - Something is wrong. - some_code',
    '${paths.length} issue(s) found.',
  ].join('\n');

  const generatorRemedy =
      'Fix the generator or run with --no-analyze to skip this check.';
  const fixTheFilesRemedy =
      'Fix the named files, or run with --no-analyze to skip this check.';

  group('analyze-gate ownership classifier — output-dir anchoring (1675)', () {
    test('make-owned segments under the output dir are generator output', () {
      for (final path in const [
        'lib/src/domain/usecases/todo/get_todo_usecase.dart',
        'lib/src/data/repositories/data_todo_repository.dart',
        'lib/src/di/index.dart',
        'lib/src/routing/todo_routes.dart',
        'lib/src/presentation/pages/todo/todo_state.dart',
        'lib/src/cache/todo_cache.dart',
      ]) {
        expect(
          BuildCommand.analyzeGateRemedyLines(analyzeOutput([path])),
          [generatorRemedy],
          reason:
              'make output must never be labeled hand-authored (#1675) — '
              'offender: $path',
        );
      }
    });

    test('owned-segment names outside the output dir stay hand-authored', () {
      const outside = [
        'test/data/migrator_test.dart',
        'lib/data/legacy/migrator.dart',
        'lib/src/datax/migrator.dart',
      ];
      expect(BuildCommand.analyzeGateRemedyLines(analyzeOutput(outside)), [
        'hand-authored offending (not generator output): ${outside.join(', ')}',
        fixTheFilesRemedy,
      ]);
    });

    test('generated-name suffixes are generator output in any directory', () {
      const suffixed = [
        'lib/src/models/user.zorphy.dart',
        'test/support/fixtures.g.dart',
      ];
      expect(BuildCommand.analyzeGateRemedyLines(analyzeOutput(suffixed)), [
        generatorRemedy,
      ]);
    });

    test('an explicit output dir re-anchors the segment check', () {
      expect(
        BuildCommand.analyzeGateRemedyLines(
          analyzeOutput(const [
            'lib/features/data/todo_repository.dart',
            'lib/src/data/legacy/migrator.dart',
          ]),
          outputDir: 'lib/features',
        ),
        [
          'generator output offending (generated by zfa): '
              'lib/features/data/todo_repository.dart',
          'hand-authored offending (not generator output): '
              'lib/src/data/legacy/migrator.dart',
          fixTheFilesRemedy,
        ],
      );
    });

    test('hand-authored code inside a make-owned segment UNDER the output dir '
        'is attributed to the generator — the deliberate over-attribution '
        'trade-off, pinned', () {
      expect(
        BuildCommand.analyzeGateRemedyLines(
          analyzeOutput(const ['lib/src/data/legacy/migrator.dart']),
        ),
        [generatorRemedy],
        reason:
            'pinned trade-off: a pure path classifier cannot tell a '
            'hand-authored file inside `lib/src/data/` from make output. '
            'v5 fixes that layout (the domain root and the sibling make '
            'dirs are generator territory), and over-attributing keeps the '
            'remedy on regeneration — the reverse is the #1675 '
            'misdirection. Changing this pin means changing the intended '
            'semantics; exact per-file provenance would need the '
            '`.zfa/receipts` run records.',
      );
    });
  });
}
