/// U6 for spec 0806-zfa-replay: `zfa entity create` is a convergent fixed
/// point — when the target entity file already exists on disk (the tree the
/// recorded generation step already produced), the command is a no-op with
/// exit 0 and the file's bytes stay untouched.
///
/// This is the precondition for replaying `examples/todo_tdd`'s recorded A1/A2
/// chains (`entity create -n Todo` → `tdd wire` → `build`): re-running the
/// chain against the tree it produced must converge, not clobber the
/// field-bearing entity back to an empty scaffold.
///
/// Driven through a real subprocess ([runZfaSource]) — the entity command
/// calls `exit()` on its paths (issue #506 hermetic pattern).
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../helpers/run_zfa_source.dart';

void main() {
  setUpAll(initZfaSourceBin);

  late Directory workspace;

  setUp(() async {
    workspace = await Directory.systemTemp.createTemp('zfa_entity_conv_');
    await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: zfa_entity_convergent_test
environment:
  sdk: ^3.11.0
dependencies:
  zorphy_annotation: any
dev_dependencies:
  build_runner: any
''');
  });

  tearDown(() {
    if (workspace.existsSync()) {
      try {
        workspace.deleteSync(recursive: true);
      } on PathNotFoundException {
        // Already gone.
      }
    }
  });

  test(
    'U6: an existing entity file is skipped (exit 0, bytes untouched)',
    () async {
      final entityPath = p.join(
        workspace.path,
        'lib',
        'src',
        'domain',
        'entities',
        'todo',
        'todo.dart',
      );
      const existing = '''
// Auto-generated by Zorphy
// Generated at: 2026-09-02T09:39:25.004203

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'todo.zorphy.dart';
part 'todo.g.dart';

/// Todo entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class \$Todo {
  String get id;
  String get title;
}
''';
      await File(entityPath).create(recursive: true);
      await File(entityPath).writeAsString(existing);

      final result = await runZfaSource([
        'entity',
        'create',
        '-n',
        'Todo',
      ], workingDirectory: workspace.path);

      expect(result.exitCode, 0, reason: 'stdout=${result.stdout}');
      expect(
        result.stdout,
        contains('already exists'),
        reason: 'the convergent skip is reported, not silent',
      );
      expect(await File(entityPath).readAsString(), existing);
      // No receipt for a no-op: nothing was generated, so there is nothing
      // to prove (the .zfa/receipts/ directory is not created).
      expect(Directory(p.join(workspace.path, '.zfa')).existsSync(), isFalse);
    },
  );

  test(
    'U6: a fresh create still writes the entity (the loop contract)',
    () async {
      final result = await runZfaSource([
        'entity',
        'create',
        '-n',
        'Product',
        '--fields',
        'name:String',
      ], workingDirectory: workspace.path);

      expect(result.exitCode, 0, reason: 'stdout=${result.stdout}');
      expect(result.stdout, contains('✓ Created entity'));
      expect(
        File(
          p.join(
            workspace.path,
            'lib',
            'src',
            'domain',
            'entities',
            'product',
            'product.dart',
          ),
        ).existsSync(),
        isTrue,
      );
    },
  );
}
