@Tags(['e2e'])
library;

import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:crypto/crypto.dart' as crypto;
import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/commands/app_shell_command.dart';
import 'package:zuraffa/src/core/project/receipt_store.dart';
import 'package:zuraffa/src/plugins/skin/commands/skin_command.dart';
import 'package:zuraffa/src/plugins/skin/skin_plugin.dart';

import '../helpers/exit_span_mutex.dart';

/// SPEC 1132 / EPIC 1 lane 3 — receipts on the LAST two standalone
/// generation paths that still ship no proof (the 2026-09-17 audit):
///
///   * `zfa app shell` writes `lib/main.dart` + the shell glue and exits
///     0 with NO receipt;
///   * `zfa skin kit` writes `skin/skin_contract_auditor.dart` and exits
///     0 with NO receipt.
///
/// Every other generation verb audited already either leaves a proof.v1
/// receipt on success or refuses honestly (non-zero, no receipt). This
/// suite pins the #996/#1138 provenance contract
/// `{plugin, capability, entity, hash, files, receipt_version: 1}` on
/// the two stragglers, and pins the #769 negative: a run that changes
/// nothing ships no receipt.
void main() {
  late Directory workspace;

  setUp(() async {
    workspace = await Directory.systemTemp.createTemp('receipts_1132_');
  });

  tearDown(() async {
    if (workspace.existsSync()) {
      try {
        await workspace.delete(recursive: true);
      } on FileSystemException {
        // Best-effort cleanup.
      }
    }
  });

  Future<List<ReceiptRecord>> receipts() =>
      ReceiptStore(projectRoot: workspace.path).loadAll();

  /// The full machine contract every standalone receipt must satisfy
  /// (issue #1138): {plugin, capability, entity, hash, files,
  /// receipt_version: 1} — the same assertions
  /// standalone_invocation_receipts_test.dart applies to the #1138 verbs.
  void expectProofV1Contract(
    ReceiptRecord record, {
    required String label,
    required String plugin,
    required String capability,
    required String entity,
  }) {
    final receipt = record.receipt;
    expect(receipt.plugin, plugin, reason: '`$label` receipt plugin');
    expect(receipt.capability, capability, reason: '`$label` capability');
    expect(receipt.entity, entity, reason: '`$label` entity');
    expect(
      receipt.files,
      isNotEmpty,
      reason: '`$label` receipt must bind the generated files',
    );
    for (final entry in receipt.files) {
      final file = File(p.join(workspace.path, entry.path));
      expect(
        file.existsSync(),
        isTrue,
        reason: '`$label` receipted artifact must exist: ${entry.path}',
      );
      expect(
        entry.sha256,
        matches(RegExp(r'^[0-9a-f]{64}$')),
        reason: '`$label` per-file digest',
      );
      final diskDigest = crypto.sha256
          .convert(file.readAsBytesSync())
          .toString();
      expect(
        entry.sha256,
        diskDigest,
        reason:
            '`$label` digest must match the CURRENT disk bytes '
            '(${entry.path}) — zfa proof check re-derives exactly this',
      );
    }
    expect(
      receipt.runHash,
      allOf(isNotNull, matches(RegExp(r'^[0-9a-f]{64}$'))),
      reason: '`$label` run hash (issue #996)',
    );
    expect(
      receipt.methodset,
      isNotNull,
      reason: '`$label` methodset must be present (machine readers)',
    );
    expect(receipt.receiptVersion, 1, reason: '`$label` receipt_version');
  }

  group('SPEC 1132 L3 — zfa app shell ships a proof.v1 receipt', () {
    setUp(() async {
      await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: my_test_app
environment:
  sdk: ^3.11.0
dependencies:
  flutter:
    sdk: flutter
''');
      final diDir = Directory(p.join(workspace.path, 'lib', 'src', 'di'))
        ..createSync(recursive: true);
      await File(p.join(diDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:get_it/get_it.dart';
void setupDependencies(GetIt getIt) {}
''');
      final routingDir = Directory(
        p.join(workspace.path, 'lib', 'src', 'routing'),
      )..createSync(recursive: true);
      await File(p.join(routingDir.path, 'index.dart')).writeAsString('''
// Generated by zfa
import 'package:go_router/go_router.dart';
List<GoRoute> getAllRoutes() => [];
''');
    });

    test(
      'app shell writes the shell artifacts AND a receipt covering them',
      () async {
        await ExitSpanMutex.acquire();
        try {
          exitCode = 0;
          final runner = CommandRunner<void>('zfa', 'test')
            ..addCommand(
              // A process runner that always fails: the pubspec auto-add
              // post-pass degrades to its diagnostic instead of spawning a
              // network-dependent `flutter pub add` (hermetic test).
              AppShellCommand(
                // ignore: avoid_ignoring_return_values
                processRunner: (_, _, _) async =>
                    ProcessResult(0, 1, '', 'fixture: pub add disabled'),
              ),
            );
          await runner.run(['shell', '--root', workspace.path]);
        } finally {
          ExitSpanMutex.release();
        }

        final mainFile = File(p.join(workspace.path, 'lib', 'main.dart'));
        expect(mainFile.existsSync(), isTrue, reason: 'lib/main.dart written');
        expect(
          File(
            p.join(workspace.path, 'lib', 'src', 'app', 'my_test_app.dart'),
          ).existsSync(),
          isTrue,
          reason: 'the shell widget is written',
        );

        final records = await receipts();
        expect(
          records,
          isNotEmpty,
          reason:
              '`zfa app shell` must persist a proof.v1 receipt (EPIC 1 '
              'lane 3: every generation path ships proof before reporting '
              'success) — the audit found .zfa/receipts/ empty after a '
              'green app-shell run.',
        );
        final record = records.lastWhere(
          (r) => r.receipt.plugin == 'app',
          orElse: () => throw StateError('no plugin=app receipt: $records'),
        );
        expectProofV1Contract(
          record,
          label: 'zfa app shell',
          plugin: 'app',
          capability: 'shell',
          entity: 'my_test_app',
        );
        expect(
          record.receipt.files.map((f) => f.path),
          containsAll([
            'lib/main.dart',
            'lib/src/app/my_test_app.dart',
            'lib/src/routing/app_router.dart',
          ]),
          reason: 'the receipt must bind the shell glue the run wrote',
        );
        expect(
          record.fileName,
          startsWith('app-shell-my_test_app-'),
          reason: 'receipt key follows the <plugin>-<capability>-<entity> form',
        );
      },
    );
  });

  group('SPEC 1132 L3 — zfa skin kit ships a proof.v1 receipt', () {
    test('skin kit writes the auditor kit AND a receipt covering it', () async {
      await ExitSpanMutex.acquire();
      try {
        exitCode = 0;
        final runner = CommandRunner<void>('zfa', 'test')
          ..addCommand(
            SkinCommand(
              SkinPlugin(outputDir: p.join(workspace.path, 'lib', 'src')),
              projectRoot: workspace.path,
            ),
          );
        await runner.run(['skin', 'kit']);
      } finally {
        ExitSpanMutex.release();
      }

      final kitFile = File(
        p.join(
          workspace.path,
          'lib',
          'src',
          'skin',
          'skin_contract_auditor.dart',
        ),
      );
      expect(kitFile.existsSync(), isTrue, reason: 'the skin kit is written');

      final records = await receipts();
      expect(
        records,
        isNotEmpty,
        reason:
            '`zfa skin kit` must persist a proof.v1 receipt (EPIC 1 '
            'lane 3) — the audit found .zfa/receipts/ empty after a '
            'green skin-kit run.',
      );
      final record = records.lastWhere(
        (r) => r.receipt.plugin == 'skin',
        orElse: () => throw StateError('no plugin=skin receipt: $records'),
      );
      expectProofV1Contract(
        record,
        label: 'zfa skin kit',
        plugin: 'skin',
        capability: 'kit',
        entity: 'kit',
      );
      expect(
        record.receipt.files.map((f) => f.path),
        contains('lib/src/skin/skin_contract_auditor.dart'),
        reason: 'the receipt binds the kit file the run wrote',
      );
    });

    test(
      'a skipped kit (exists, no --force) ships NO receipt (#769)',
      () async {
        // First run writes the kit (and, post-fix, its receipt).
        await ExitSpanMutex.acquire();
        try {
          exitCode = 0;
          final runner = CommandRunner<void>('zfa', 'test')
            ..addCommand(
              SkinCommand(
                SkinPlugin(outputDir: p.join(workspace.path, 'lib', 'src')),
                projectRoot: workspace.path,
              ),
            );
          await runner.run(['skin', 'kit']);
        } finally {
          ExitSpanMutex.release();
        }
        final afterFirst = await receipts();

        // Second run: the kit exists and no --force — nothing changes.
        await ExitSpanMutex.acquire();
        try {
          exitCode = 0;
          final runner = CommandRunner<void>('zfa', 'test')
            ..addCommand(
              SkinCommand(
                SkinPlugin(outputDir: p.join(workspace.path, 'lib', 'src')),
                projectRoot: workspace.path,
              ),
            );
          await runner.run(['skin', 'kit']);
        } finally {
          ExitSpanMutex.release();
        }
        final afterSecond = await receipts();

        expect(
          afterSecond.length,
          afterFirst.length,
          reason:
              'a run that changes nothing writes no receipt (issue #769: '
              'no artifact, no receipt) — receipts:\n'
              'first=${afterFirst.map((r) => r.fileName)}\n'
              'second=${afterSecond.map((r) => r.fileName)}',
        );
      },
    );
  });
}
