import 'dart:io';

import 'package:test/test.dart';
import 'package:zuraffa/src/zfa_cli.dart';

/// Integration tests for `zfa xray deck`.
///
/// The sandbox root is passed via `--root` so the tests never mutate the
/// process working directory (which is shared across concurrently-running
/// test files under `dart test`). All source/yaml/output paths are absolute,
/// so the command is fully hermetic.
void main() {
  late Directory tempDir;

  setUp(() async {
    tempDir = await Directory.systemTemp.createTemp('xray_deck_cli_');
  });

  tearDown(() async {
    if (tempDir.existsSync()) {
      await tempDir.delete(recursive: true);
    }
  });

  group('zfa xray deck CLI integration', () {
    test('generates registration from YAML source', () async {
      // Create a YAML file.
      final yamlDir = Directory('${tempDir.path}/assets/mocks');
      yamlDir.createSync(recursive: true);
      final yamlFile = File('${yamlDir.path}/barcodes.yaml');
      yamlFile.writeAsStringSync('''- name: Valid Product A
  payload: "123456789"
  type: valid
- name: Invalid Barcode
  payload: "000000"
  type: error
  description: Triggers validation failure
''');

      final outputFile = '${tempDir.path}/barcodes_xray_deck.dart';

      final output = await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--yaml=${yamlFile.path}',
        '--output=$outputFile',
        '--usecase-name=ScanBarcode',
        '--force',
      ]);

      expect(output, contains('Generated 2 mock entries'));
      expect(output, contains('ScanBarcode'));

      // Verify the generated file.
      final generated = File(outputFile);
      expect(generated.existsSync(), isTrue);
      final content = generated.readAsStringSync();

      expect(content, contains('GENERATED BY zfa xray deck'));
      expect(content, contains('ScanBarcode'));
      expect(content, contains("name: 'Valid Product A'"));
      expect(content, contains("payload: '123456789'"));
      expect(content, contains('XRayMockType.valid'));
      expect(content, contains("name: 'Invalid Barcode'"));
      expect(content, contains('XRayMockType.error'));
      expect(content, contains("description: 'Triggers validation failure'"));
      expect(content, contains('registerScanBarcodeXRayDeck'));
      expect(content, contains('XRayControlDeckRegistry.registerEntries'));
    });

    test('generates registration from annotated source', () async {
      // Create a source file with annotations.
      final sourceFile = File('${tempDir.path}/scan_barcode_usecase.dart');
      sourceFile.writeAsStringSync(
        '''@XRayMock(name: 'Valid Product A', payload: '123456789', type: 'valid')
@XRayMock(name: 'Bad Scan', payload: 'err', type: 'error')
class ScanBarcodeUseCase {}
''',
      );

      final outputFile = '${tempDir.path}/scan_barcode_xray_deck.dart';

      final output = await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--source=${sourceFile.path}',
        '--output=$outputFile',
        '--usecase-name=ScanBarcode',
        '--force',
      ]);

      expect(output, contains('Generated 2 mock entries'));

      final content = File(outputFile).readAsStringSync();
      expect(content, contains("name: 'Valid Product A'"));
      expect(content, contains("name: 'Bad Scan'"));
      expect(content, contains('XRayMockType.error'));
    });

    test('combines annotations and YAML', () async {
      final sourceFile = File('${tempDir.path}/process_usecase.dart');
      sourceFile.writeAsStringSync(
        '''@XRayMock(name: 'FromAnnotation', payload: 'ann', type: 'valid')
class ProcessUseCase {}
''',
      );

      final yamlFile = File('${tempDir.path}/extra.yaml');
      yamlFile.writeAsStringSync('''- name: FromYaml
  payload: "yaml_data"
  type: valid
''');

      final outputFile = '${tempDir.path}/process_xray_deck.dart';

      final output = await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--source=${sourceFile.path}',
        '--yaml=${yamlFile.path}',
        '--output=$outputFile',
        '--force',
      ]);

      expect(output, contains('Generated 2 mock entries'));

      final content = File(outputFile).readAsStringSync();
      expect(content, contains("name: 'FromAnnotation'"));
      expect(content, contains("name: 'FromYaml'"));
    });

    test('no source and no yaml shows error', () async {
      final output = await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
      ]);
      expect(output, contains('provide --source and/or --yaml'));
    });

    test('re-running with updated YAML reflects changes', () async {
      final yamlFile = File('${tempDir.path}/scenarios.yaml');
      yamlFile.writeAsStringSync('''- name: V1
  payload: "a"
  type: valid
''');

      final outputFile = '${tempDir.path}/scenarios_xray_deck.dart';

      // First run.
      await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--yaml=${yamlFile.path}',
        '--output=$outputFile',
        '--usecase-name=ScenariosTest',
        '--force',
      ]);

      var content = File(outputFile).readAsStringSync();
      expect(content, contains("name: 'V1'"));
      expect(content, isNot(contains("name: 'V2'")));

      // Update YAML and re-run.
      yamlFile.writeAsStringSync('''- name: V1
  payload: "a"
  type: valid
- name: V2
  payload: "b"
  type: error
- name: V3
  payload: "c"
''');

      await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--yaml=${yamlFile.path}',
        '--output=$outputFile',
        '--usecase-name=ScenariosTest',
        '--force',
      ]);

      content = File(outputFile).readAsStringSync();
      expect(content, contains("name: 'V1'"));
      expect(content, contains("name: 'V2'"));
      expect(content, contains("name: 'V3'"));
      expect(content, contains('XRayMockType.unknown')); // V3 has no type
    });

    test('auto-detected usecase name preserves UseCase casing', () async {
      final sourceFile = File('${tempDir.path}/scan_barcode_usecase.dart');
      sourceFile.writeAsStringSync(
        '''@XRayMock(name: 'Test', payload: 'data', type: 'valid')
class ScanBarcodeUseCase {}
''',
      );

      final outputFile = '${tempDir.path}/scan_barcode_xray_deck.dart';

      // Don't provide --usecase-name, let it auto-detect
      final output = await runCapturing([
        'xray',
        'deck',
        '--root=${tempDir.path}',
        '--source=${sourceFile.path}',
        '--output=$outputFile',
        '--force',
      ]);

      expect(output, contains('ScanBarcodeUseCase'));

      final content = File(outputFile).readAsStringSync();
      expect(content, contains('registerScanBarcodeUseCaseXRayDeck'));
      expect(content, contains("'ScanBarcodeUseCase'"));
    });
  });
}
