// Generated by zfa for: TextSpark
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'text_spark_controller.dart';
import 'text_spark_presenter.dart';

class TextSparkView extends CleanView {
  const TextSparkView({super.key, super.routeObserver});

  @override
  State<TextSparkView> createState() {
    return _TextSparkViewState(TextSparkController(TextSparkPresenter()));
  }
}

class _TextSparkViewState
    extends CleanViewState<TextSparkView, TextSparkController, void> {
  _TextSparkViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('TextSpark')),
      body: ControlledWidgetBuilder<TextSparkController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
