// Generated by zfa
// zfa generate Todo --methods=get,getList,create,update,delete,watch --data

import 'package:zuraffa/zuraffa.dart';
import '../../../domain/entities/todo/todo.dart';

abstract class TodoDataSource with Loggable, FailureHandler {
  Future<Todo> get(String id);
  Future<List<Todo>> getList(ListQueryParams params);
  Future<Todo> create(Todo todo);
  Future<Todo> update(UpdateParams<Partial<Todo>> params);
  Future<void> delete(DeleteParams<Todo> params);
  Stream<Todo> watch(String? id);
}
