// Generated by zfa for: Authentication
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'authentication_controller.dart';
import 'authentication_presenter.dart';

class AuthenticationView extends CleanView {
  const AuthenticationView({super.key, super.routeObserver});

  @override
  State<AuthenticationView> createState() {
    return _AuthenticationViewState(
      AuthenticationController(AuthenticationPresenter()),
    );
  }
}

class _AuthenticationViewState
    extends CleanViewState<AuthenticationView, AuthenticationController, void> {
  _AuthenticationViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('Authentication')),
      body: ControlledWidgetBuilder<AuthenticationController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
