// Generated by zfa for: PriceCheckInvoice
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'price_check_invoice_controller.dart';
import 'price_check_invoice_presenter.dart';

class PriceCheckInvoiceView extends CleanView {
  const PriceCheckInvoiceView({super.key, super.routeObserver});

  @override
  State<PriceCheckInvoiceView> createState() {
    return _PriceCheckInvoiceViewState(
      PriceCheckInvoiceController(PriceCheckInvoicePresenter()),
    );
  }
}

class _PriceCheckInvoiceViewState
    extends
        CleanViewState<
          PriceCheckInvoiceView,
          PriceCheckInvoiceController,
          void
        > {
  _PriceCheckInvoiceViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('PriceCheckInvoice')),
      body: ControlledWidgetBuilder<PriceCheckInvoiceController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
