// GENERATED - DO NOT EDIT
// Generated by zfa for: Subscription
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/subscription/subscription.dart';
import '../../mock/subscription_mock_data.dart';
import 'subscription_datasource.dart';

/// Mock data source for Subscription
class SubscriptionMockDataSource
    with Loggable, FailureHandler
    implements SubscriptionDataSource {
  SubscriptionMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Subscription> get(QueryParams<Subscription> params) async {
    logger.info('Getting Subscription with params: $params');
    await Future.delayed(_delay);
    final item = SubscriptionMockData.subscriptions.query(params);
    logger.info('Successfully retrieved Subscription');
    return item;
  }

  @override
  Future<Subscription> update(
    UpdateParams<String, SubscriptionPatch> params,
  ) async {
    logger.info('Updating Subscription: ${params.id}');
    await Future.delayed(_delay);
    final existing = SubscriptionMockData.sampleSubscription;
    logger.info('Successfully updated Subscription');
    return existing;
  }

  @override
  Future<Subscription> toggle(
    ToggleParams<String, Field<Subscription, dynamic>> params,
  ) async {
    logger.info('Toggling Subscription: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = SubscriptionMockData.sampleSubscription;
    logger.info('Successfully toggled Subscription');
    return existing;
  }
}

// END GENERATED
