/// Composite component scaffolding — `zfa make <Name> --ui` (spec 024
/// FR-002 / FR-007).
///
/// Generates a first-class vocabulary entry consisting of:
/// 1. the node entity — `lib/src/ui/nodes/<name>_node.dart`
/// 2. the renderer extension — `lib/src/ui/renderers/<name>_renderer.dart`
/// 3. the schema registration — `.zfa/ui/components/<name>.json`
///
/// Reserved built-in names are rejected with the reserved list; existing
/// registrations/renderers are conflicts rejected at scaffold time unless
/// [force] is set.
library;

import 'dart:convert';
import 'dart:io';

import 'ui_node_registry.dart';

class CompositeScaffoldException implements Exception {
  CompositeScaffoldException(this.message);
  final String message;

  @override
  String toString() => 'CompositeScaffoldException: $message';
}

class CompositeScaffoldResult {
  const CompositeScaffoldResult(this.writtenFiles);

  /// Absolute paths of every artifact written.
  final List<String> writtenFiles;
}

class CompositeScaffolder {
  static const int _defaultMaxChildren = 8;

  /// Scaffolds the composite component [name] (PascalCase, e.g.
  /// `OfferCard`) into the project at [projectRoot].
  Future<CompositeScaffoldResult> scaffold(
    String name, {
    required String projectRoot,
    required NodeRegistry registry,
    bool force = false,
  }) async {
    final validName = RegExp(r'^[A-Z][A-Za-z0-9]*$');
    if (!validName.hasMatch(name)) {
      throw CompositeScaffoldException(
        'Invalid composite name "$name" — use PascalCase '
        '(e.g. OfferCard).',
      );
    }

    final snakeName = _snake(name);
    final vocabularyName = snakeName;

    // FR-007: reserved built-in names are rejected with the list.
    if (registry.reservedNames.contains(vocabularyName) ||
        registry.reservedNames.contains(name.toLowerCase())) {
      throw CompositeScaffoldException(
        '"$name" collides with a reserved built-in component name. '
        'Reserved names: ${registry.builtInNames.join(", ")}.',
      );
    }

    final registrationFile = File(
      '$projectRoot/.zfa/ui/components/$vocabularyName.json',
    );
    final entityFile = File(
      '$projectRoot/lib/src/ui/nodes/${snakeName}_node.dart',
    );
    final rendererFile = File(
      '$projectRoot/lib/src/ui/renderers/${snakeName}_renderer.dart',
    );

    // Edge case: existing registration / renderer conflict.
    if (!force) {
      final conflicts = <String>[];
      if (registrationFile.existsSync()) {
        conflicts.add(registrationFile.path);
      }
      if (rendererFile.existsSync()) {
        conflicts.add(rendererFile.path);
      }
      if (conflicts.isNotEmpty) {
        throw CompositeScaffoldException(
          'A composite named "$name" already exists (conflicting files: '
          '${conflicts.join(", ")}). Remove them or pass --force to '
          'overwrite.',
        );
      }
    }

    final written = <String>[];

    // 1. Node entity.
    await entityFile.parent.create(recursive: true);
    await entityFile.writeAsString(_nodeEntitySource(name, snakeName));
    written.add(entityFile.path);

    // 2. Renderer extension.
    await rendererFile.parent.create(recursive: true);
    await rendererFile.writeAsString(_rendererSource(name, snakeName));
    written.add(rendererFile.path);

    // 3. Schema registration.
    await registrationFile.parent.create(recursive: true);
    await registrationFile.writeAsString(
      '${const JsonEncoder.withIndent('  ').convert({
        'name': vocabularyName,
        'category': 'composite',
        'props': {
          'title': {'type': 'string'},
        },
        'children': {'min': 0, 'max': _defaultMaxChildren},
      })}\n',
    );
    written.add(registrationFile.path);

    return CompositeScaffoldResult(written);
  }

  String _nodeEntitySource(String name, String snakeName) =>
      '''
import 'package:zuraffa/zuraffa.dart';

/// `$name` composite node (generated by `zfa make $name --ui`).
///
/// A first-class UI vocabulary entry: referenced by type `$snakeName` in
/// payloads, rendered by the `$name` renderer extension.
class ${name}Node {
  const ${name}Node({this.title});

  /// Card title.
  final String? title;

  /// Converts the typed entity into a renderable vocabulary [UiNode].
  UiNode toNode({List<UiNode> children = const [], String? styleToken}) {
    return UiNode(
      type: '$snakeName',
      props: {
        if (title != null) 'title': title,
      },
      children: children,
      styleToken: styleToken,
    );
  }
}
''';

  String _rendererSource(String name, String snakeName) =>
      '''
/// `$name` renderer extension (generated by `zfa make $name --ui`).
///
/// Registers how the `$snakeName` vocabulary node renders. The Flutter
/// widget tree lives in the app package; this extension binds the node
/// type to its builder in the renderer registry.
class ${name}Renderer {
  /// The vocabulary node type this renderer handles.
  static const String nodeType = '$snakeName';

  /// Registers this renderer against the node registry at app start.
  static void register() {
    // Renderer registration hook — wired by the app's UI bootstrap:
    //   rendererRegistry.register(nodeType, build$name);
  }
}
''';

  static String _snake(String name) {
    final buffer = StringBuffer();
    for (var i = 0; i < name.length; i++) {
      final char = name[i];
      if (char.toUpperCase() == char && i > 0) {
        buffer.write('_');
      }
      buffer.write(char.toLowerCase());
    }
    return buffer.toString();
  }
}
