// Generated by zfa for: ListingOffer
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'listing_offer_controller.dart';
import 'listing_offer_presenter.dart';

class ListingOfferView extends CleanView {
  const ListingOfferView({super.key, super.routeObserver});

  @override
  State<ListingOfferView> createState() {
    return _ListingOfferViewState(
      ListingOfferController(ListingOfferPresenter()),
    );
  }
}

class _ListingOfferViewState
    extends CleanViewState<ListingOfferView, ListingOfferController, void> {
  _ListingOfferViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('ListingOffer')),
      body: ControlledWidgetBuilder<ListingOfferController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
