import '../../mcp/sse_server.dart';
import 'di_container.dart';
import 'mcp_stdio_server.dart';
import 'mcp_tool.dart';
import 'mcp_tool_registry.dart';
import 'route_builder.dart';
import 'zuraffa_plugin.dart';

/// Runtime [ZuraffaPlugin] that exposes the host app's [McpTool]s
/// over the Model Context Protocol.
///
/// ## What it does
///
/// During the engine's bootstrap phase, [registerDependencies]
/// populates a [McpToolRegistry] (registered as a singleton in the
/// DI container) with every tool passed to the plugin's constructor.
/// [onInit] then captures the [ZuraffaDIContainer] for later use
/// by [serveStdio] / [serveSse] / [listTools].
///
/// ## Usage (typical generated app)
///
/// Generated by `zfa plugin mcp`, the host `lib/main.dart` becomes:
///
/// ```dart
/// import 'package:zuraffa/zuraffa.dart';
/// import 'package:my_app/src/plugin/mcp_server_plugin.dart';
/// import 'package:my_app/src/mcp/tools.dart';
///
/// void main() async {
///   final engine = ZuraffaEngine()
///     ..register(McpServerPlugin(tools: myMcpTools));
///   await engine.bootstrap();
///
///   // Run the stdio MCP server. Blocks forever.
///   await engine['mcp']!.serveStdio();
/// }
/// ```
///
/// ## Design notes
///
/// - The plugin does NOT auto-start any server by default. The host
///   app decides when to start the loop (typically at the end of
///   `main()` after `engine.bootstrap()` completes). Pass
///   `autoStartStdio: true` to start the loop in [onInit].
/// - The `routes` getter returns an empty map — the MCP plugin does
///   not contribute to the host app's route table.
/// - `pluginId` defaults to `'mcp'`; pass a custom id if you need
///   multiple MCP server plugins in the same engine (rare).
class McpServerPlugin extends ZuraffaPlugin {
  @override
  final String pluginId;

  /// The tools this plugin exposes. Held immutably — the
  /// [McpToolRegistry] in DI is the live source of truth after
  /// bootstrap.
  final List<McpTool> tools;

  /// If `true`, [onInit] automatically starts the stdio server.
  /// Useful for bin-only apps that exist solely to serve MCP.
  final bool autoStartStdio;

  /// If non-null, [onInit] automatically starts the SSE server on
  /// the given port. Pair with [sseAuthToken] for remote agents.
  final int? autoStartSsePort;

  /// Bearer token for the auto-started SSE server. Ignored unless
  /// [autoStartSsePort] is set.
  final String? sseAuthToken;

  /// Captured during [onInit] for later use by [serveStdio] /
  /// [serveSse] / [listTools]. `null` before bootstrap completes.
  ZuraffaDIContainer? _di;

  McpServerPlugin({
    this.pluginId = 'mcp',
    List<McpTool>? tools,
    this.autoStartStdio = false,
    this.autoStartSsePort,
    this.sseAuthToken,
  }) : tools = List<McpTool>.unmodifiable(tools ?? const []);

  @override
  void registerDependencies(ZuraffaDIContainer di) {
    final registry = McpToolRegistry();
    for (final tool in tools) {
      registry.register(tool);
    }
    // The runtime ZuraffaPlugin contract is sync (void), so we
    // bypass the async override path in ZuraffaDIContainer.registerSingleton
    // and manipulate GetIt directly. In production the type is never
    // registered yet; in tests with a shared GetIt.instance the prior
    // registration is removed synchronously before re-registering.
    final getIt = di.getIt;
    if (getIt.isRegistered<McpToolRegistry>()) {
      // unregister's side effect is synchronous; the returned Future
      // is for onDispose callbacks we don't use.
      getIt.unregister<McpToolRegistry>();
    }
    getIt.registerSingleton<McpToolRegistry>(registry);
  }

  @override
  Future<void> onInit(ZuraffaDIContainer di) async {
    _di = di;
    if (autoStartStdio) {
      await serveStdio();
    } else if (autoStartSsePort != null) {
      await serveSse(
        port: autoStartSsePort!,
        authToken: sseAuthToken,
      );
    }
  }

  @override
  Map<String, ZuraffaRouteHandler> get routes => const {};

  /// Returns the live [McpToolRegistry] from the DI container.
  ///
  /// Throws [StateError] if called before [onInit] has run (i.e.
  /// before the engine has bootstrapped). Pre-bootstrap callers
  /// can inspect the static [tools] list instead.
  McpToolRegistry get registry {
    final di = _di;
    if (di == null) {
      throw StateError(
        'McpServerPlugin cannot resolve its registry before the '
        'engine has bootstrapped (onInit has not run yet).',
      );
    }
    return di.get<McpToolRegistry>();
  }

  /// Lists the tools currently registered. Pre-bootstrap, returns
  /// the static [tools] list; post-bootstrap, returns the live
  /// registry contents (which may differ if the host app added
  /// tools via `registry.register(...)` after bootstrap).
  List<McpTool> listTools() {
    if (_di == null) return List<McpTool>.unmodifiable(tools);
    return registry.allTools;
  }

  /// Starts the stdio MCP server. Blocks forever in production
  /// (stdin is held open); in tests with an injected stream it
  /// returns when the stream ends.
  ///
  /// Throws [StateError] if called before bootstrap.
  Future<void> serveStdio({
    String serverName = 'zuraffa-app-mcp',
    String serverVersion = '1.0.0',
  }) async {
    final di = _requireDi();
    final reg = di.get<McpToolRegistry>();
    final server = McpStdioServer(
      registry: reg,
      serverName: serverName,
      serverVersion: serverVersion,
    );
    await server.run();
  }

  /// Starts an SSE MCP server on [port]. Returns when the server
  /// is shut down (typically never).
  ///
  /// [authToken] gates remote connections; loopback connections
  /// are always allowed. When `null`, any client can connect.
  ///
  /// Throws [StateError] if called before bootstrap.
  Future<void> serveSse({
    int port = 8372,
    String? authToken,
    String serverName = 'zuraffa-app-mcp',
    String serverVersion = '1.0.0',
  }) async {
    final di = _requireDi();
    final reg = di.get<McpToolRegistry>();
    final sse = McpSseServer(
      registry: reg,
      serverName: serverName,
      serverVersion: serverVersion,
      authToken: authToken,
    );
    await sse.start(port: port);
  }

  ZuraffaDIContainer _requireDi() {
    final di = _di;
    if (di == null) {
      throw StateError(
        'McpServerPlugin cannot serve before the engine has '
        'bootstrapped (onInit has not run yet).',
      );
    }
    return di;
  }
}
