import 'di_container.dart';
import 'mcp_tool.dart';
import 'zuraffa_plugin.dart';
import '../../version.dart';

/// Runtime module contract for Zuraffa-native packages (spec 025,
/// FR-006/FR-007).
///
/// A [PackageModule] is the lifecycle entry point a reusable package
/// exposes to consuming apps. It follows the standard engine lifecycle —
/// no separate lifecycle model is introduced:
///
/// 1. **register** — `ZuraffaEngine.register` / `registerPackage` accepts
///    the module (registerPackage additionally validates the package's
///    zuraffa SDK constraint against the running version, FR-015).
/// 2. **bootstrap** — `registerDependencies` runs (the generated package
///    registrar wires datasources/repositories/usecases into the consuming
///    app's container — FR-005), then `onInit`.
/// 3. **ready** — `ZuraffaEngine.ready()` awaits [onReady] for every
///    module, in registration order.
/// 4. **dispose** — `ZuraffaEngine.shutdown()` awaits [onDispose] for
///    every module, in reverse registration order.
///
/// Example (generated by `zfa package create`):
///
/// ```dart
/// class MyPkgPackageModule extends PackageModule {
///   @override
///   String get pluginId => 'my_pkg';
///
///   @override
///   void registerDependencies(ZuraffaDIContainer di) =>
///       registerMyPkgPackage(di); // from di/my_pkg_package_registrar.dart
///
///   @override
///   Map<String, ZuraffaRouteHandler> get routes => const {};
/// }
/// ```
abstract class PackageModule extends ZuraffaPlugin {
  /// The package identity used to namespace contributed agent tools
  /// (FR-008: `<package>.<usecase>`).
  ///
  /// Defaults to [pluginId] — the scaffolded module's id IS the package
  /// name, and the id is the engine's stable discoverable identifier
  /// (FR-007).
  String get packageName => pluginId;

  /// The zuraffa SDK constraint this package was generated against.
  ///
  /// `ZuraffaEngine.registerPackage` validates it against the running
  /// zuraffa version and rejects incompatible (major-mismatched) modules
  /// with a clear error (FR-015). Defaults to a caret constraint on the
  /// running version; the scaffold stamps the constraint it wrote into the
  /// package's pubspec.yaml.
  String get zuraffaSdkConstraint => '^$version';

  /// Agent tools contributed by this package (FR-008), built against
  /// the consuming app's [di] container once it is wired.
  ///
  /// Tool names are **un-namespaced** usecase names; registering them via
  /// `PackageAgentTools.registerInto` applies the `"$packageName.<tool>"`
  /// namespace, so tools from different packages never collide (FR-009).
  /// Default: no tools. Build tools with [PackageUseCaseTool] so they
  /// resolve their usecase from the container (the package's own
  /// dependency context).
  List<McpTool> buildAgentTools(ZuraffaDIContainer di) => const [];
}
