// GENERATED - DO NOT EDIT
// Generated by zfa for: Device
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/device/device.dart';
import '../../mock/device_mock_data.dart';
import 'device_datasource.dart';

/// Mock data source for Device
class DeviceMockDataSource
    with Loggable, FailureHandler
    implements DeviceDataSource {
  DeviceMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Device> get(QueryParams<Device> params) async {
    logger.info('Getting Device with params: $params');
    await Future.delayed(_delay);
    final item = DeviceMockData.devices.query(params);
    logger.info('Successfully retrieved Device');
    return item;
  }

  @override
  Future<Device> update(UpdateParams<String, DevicePatch> params) async {
    logger.info('Updating Device: ${params.id}');
    await Future.delayed(_delay);
    final existing = DeviceMockData.sampleDevice;
    logger.info('Successfully updated Device');
    return existing;
  }

  @override
  Future<Device> toggle(
    ToggleParams<String, Field<Device, dynamic>> params,
  ) async {
    logger.info('Toggling Device: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = DeviceMockData.sampleDevice;
    logger.info('Successfully toggled Device');
    return existing;
  }
}

// END GENERATED
