// Generated by zfa for: DynamicFormField
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'dynamic_form_field_controller.dart';
import 'dynamic_form_field_presenter.dart';

class DynamicFormFieldView extends CleanView {
  const DynamicFormFieldView({super.key, super.routeObserver});

  @override
  State<DynamicFormFieldView> createState() {
    return _DynamicFormFieldViewState(
      DynamicFormFieldController(DynamicFormFieldPresenter()),
    );
  }
}

class _DynamicFormFieldViewState
    extends
        CleanViewState<DynamicFormFieldView, DynamicFormFieldController, void> {
  _DynamicFormFieldViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('DynamicFormField')),
      body: ControlledWidgetBuilder<DynamicFormFieldController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
