import 'json_parser.dart';

/// Generates test files for entities
///
/// Tests:
/// - fromJson() deserialization
/// - toJson() serialization
/// - Required 'id' field
class EntityTestGenerator {
  /// Generate entity test file
  String generateEntityTest(String entityName, EntitySchema schema) {
    final buffer = StringBuffer();

    // Header
    buffer.writeln('// Generated by Zuraffa on ${DateTime.now().toIso8601String()}');
    buffer.writeln('// DO NOT EDIT - Regenerate with: zuraffa generate $entityName');
    buffer.writeln();

    // Imports
    buffer.writeln("import 'package:test/test.dart';");
    buffer.writeln("import 'package:${_getPackageName()}/src/domain/entities/${_toSnakeCase(entityName)}.dart';");
    buffer.writeln();

    // Test group
    buffer.writeln("void main() {");
    buffer.writeln("  group('$entityName', () {");
    buffer.writeln();

    // Sample JSON fixture
    buffer.writeln("    final sampleJson = {");
    for (final field in schema.fields) {
      final value = _getSampleValue(field);
      buffer.writeln("      '${field.jsonKey}': $value,");
    }
    buffer.writeln("    };");
    buffer.writeln();

    // Test fromJson
    buffer.writeln("    test('fromJson creates valid $entityName', () {");
    buffer.writeln("      final entity = $entityName.fromJson(sampleJson);");
    buffer.writeln();
    buffer.writeln("      expect(entity.id, isNotNull);");
    for (final field in schema.fields) {
      if (field.name != 'id') {
        buffer.writeln("      expect(entity.${field.name}, ${_getExpectedValue(field)});");
      }
    }
    buffer.writeln("    });");
    buffer.writeln();

    // Test toJson
    buffer.writeln("    test('toJson serializes correctly', () {");
    buffer.writeln("      final entity = $entityName.fromJson(sampleJson);");
    buffer.writeln("      final json = entity.toJson();");
    buffer.writeln();
    for (final field in schema.fields) {
      buffer.writeln("      expect(json['${field.jsonKey}'], entity.${field.name});");
    }
    buffer.writeln("    });");
    buffer.writeln();

    // Test roundtrip
    buffer.writeln("    test('fromJson -> toJson roundtrip preserves data', () {");
    buffer.writeln("      final entity = $entityName.fromJson(sampleJson);");
    buffer.writeln("      final json = entity.toJson();");
    buffer.writeln("      final entity2 = $entityName.fromJson(json);");
    buffer.writeln();
    buffer.writeln("      expect(entity2.toJson(), equals(entity.toJson()));");
    buffer.writeln("    });");
    buffer.writeln();

    // Test required id field
    buffer.writeln("    test('has required id field', () {");
    buffer.writeln("      final entity = $entityName.fromJson(sampleJson);");
    buffer.writeln("      expect(entity.id, isA<String>());");
    buffer.writeln("      expect(entity.id.isNotEmpty, true);");
    buffer.writeln("    });");

    buffer.writeln("  });");
    buffer.writeln("}");

    return buffer.toString();
  }

  /// Get file path for entity test
  String getFilePath(String entityName) {
    return 'test/domain/entities/${_toSnakeCase(entityName)}_test.dart';
  }

  /// Get sample value for field type
  String _getSampleValue(FieldSchema field) {
    if (field.type.startsWith('List<')) {
      final innerType = field.type.substring(5, field.type.length - 1);
      if (innerType.startsWith(r'$')) {
        // List of entities
        return '[]';
      } else {
        // List of primitives
        return switch (innerType) {
          'String' => "['test1', 'test2']",
          'int' => '[1, 2, 3]',
          'double' => '[1.5, 2.5]',
          'bool' => '[true, false]',
          _ => '[]',
        };
      }
    } else if (field.type.startsWith(r'$')) {
      // Nested entity - return simple object
      return "{'id': 'nested-1'}";
    } else {
      // Primitive
      return switch (field.type) {
        'String' => field.name == 'id' ? "'test-id-123'" : "'test ${field.name}'",
        'int' => '42',
        'double' => '3.14',
        'bool' => 'true',
        _ => 'null',
      };
    }
  }

  /// Get expected value for assertion
  String _getExpectedValue(FieldSchema field) {
    if (field.type.startsWith('List<')) {
      return 'isA<List>()';
    } else if (field.type.startsWith(r'$')) {
      return 'isNotNull';
    } else {
      return switch (field.type) {
        'String' => 'isA<String>()',
        'int' => 'equals(42)',
        'double' => 'equals(3.14)',
        'bool' => 'equals(true)',
        _ => 'isNotNull',
      };
    }
  }

  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'[A-Z]'),
          (match) => '_${match.group(0)!.toLowerCase()}',
        )
        .substring(1);
  }

  String _getPackageName() {
    // This will be the consuming project's package name
    // We'll need to pass this from the generator
    return 'app'; // Default placeholder
  }
}
