import 'usecase_generator.dart';
import 'json_parser.dart';

/// Generates test files for usecases
///
/// Tests:
/// - All usecase types (Get, GetProducts, Create, Update, Delete)
/// - Mocked repository
/// - Result handling (Success/Failure)
class UseCaseTestGenerator {
  /// Generate usecase test
  String generateUseCaseTest(String entityName, UseCaseType type, String packageName, EntitySchema schema) {
    final useCaseName = _inferUseCaseName(entityName, type);
    final buffer = StringBuffer();

    buffer.writeln('// Generated by Zuraffa on ${DateTime.now().toIso8601String()}');
    buffer.writeln('// DO NOT EDIT - Regenerate with: zuraffa generate $entityName');
    buffer.writeln();

    buffer.writeln("import 'package:test/test.dart';");
    buffer.writeln("import 'package:mocktail/mocktail.dart';");
    buffer.writeln("import 'package:zuraffa/zuraffa.dart';");
    buffer.writeln("import 'package:$packageName/src/domain/entities/${_toSnakeCase(entityName)}.dart';");
    buffer.writeln("import 'package:$packageName/src/domain/repositories/${_toSnakeCase(entityName)}_repository.dart';");
    if (type == UseCaseType.getAll) {
      buffer.writeln("import 'package:$packageName/src/domain/usecases/${_toSnakeCase(entityName)}_filter.dart';");
    }
    buffer.writeln("import 'package:$packageName/src/domain/usecases/${_toSnakeCase(useCaseName)}.dart';");
    buffer.writeln();

    buffer.writeln("class Mock${entityName}Repository extends Mock implements ${entityName}Repository {}");
    buffer.writeln();

    buffer.writeln("void main() {");
    if (type == UseCaseType.getAll) {
      buffer.writeln("  setUpAll(() {");
      buffer.writeln("    // Register fallback values for mocktail");
      buffer.writeln("    registerFallbackValue(${entityName}Filter());");
      buffer.writeln("  });");
      buffer.writeln();
    }
    buffer.writeln("  group('$useCaseName', () {");
    buffer.writeln("    late Mock${entityName}Repository mockRepository;");
    buffer.writeln("    late $useCaseName useCase;");
    buffer.writeln();

    buffer.writeln("    setUp(() {");
    buffer.writeln("      mockRepository = Mock${entityName}Repository();");
    buffer.writeln("      useCase = $useCaseName(mockRepository);");
    buffer.writeln("    });");
    buffer.writeln();

    // Generate specific tests based on type
    switch (type) {
      case UseCaseType.get:
        _generateGetTests(buffer, entityName, schema);
        break;
      case UseCaseType.getAll:
        _generateGetAllTests(buffer, entityName, schema);
        break;
      case UseCaseType.create:
        _generateCreateTests(buffer, entityName, schema);
        break;
      case UseCaseType.update:
        _generateUpdateTests(buffer, entityName, schema);
        break;
      case UseCaseType.delete:
        _generateDeleteTests(buffer, entityName);
        break;
    }

    buffer.writeln("  });");
    buffer.writeln("}");

    return buffer.toString();
  }

  void _generateGetTests(StringBuffer buffer, String entityName, EntitySchema schema) {
    final sampleJson = _generateSampleJson(schema);
    buffer.writeln("    test('returns Success when repository succeeds', () async {");
    buffer.writeln("      final entity = $entityName.fromJson($sampleJson);");
    buffer.writeln("      when(() => mockRepository.getById(any()))");
    buffer.writeln("          .thenAnswer((_) async => Success(entity));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute('test-1');");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Success<$entityName, AppFailure>>());");
    buffer.writeln("      result.fold(");
    buffer.writeln("        (failure) => fail('Should not fail'),");
    buffer.writeln("        (data) => expect(data.id, 'test-1'),");
    buffer.writeln("      );");
    buffer.writeln("      verify(() => mockRepository.getById('test-1')).called(1);");
    buffer.writeln("    });");
    buffer.writeln();

    buffer.writeln("    test('returns Failure when repository fails', () async {");
    buffer.writeln("      when(() => mockRepository.getById(any()))");
    buffer.writeln("          .thenAnswer((_) async => Failure(NetworkFailure('Network error')));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute('test-1');");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Failure<$entityName, AppFailure>>());");
    buffer.writeln("    });");
  }

  void _generateGetAllTests(StringBuffer buffer, String entityName, EntitySchema schema) {
    final sampleJson = _generateSampleJson(schema);
    final sampleJson2 = _generateSampleJson(schema, idSuffix: '2');
    buffer.writeln("    test('returns Success with list when repository succeeds', () async {");
    buffer.writeln("      final entities = [");
    buffer.writeln("        $entityName.fromJson($sampleJson),");
    buffer.writeln("        $entityName.fromJson($sampleJson2),");
    buffer.writeln("      ];");
    buffer.writeln("      final filter = ${entityName}Filter();");
    buffer.writeln("      when(() => mockRepository.getAll(any()))");
    buffer.writeln("          .thenAnswer((_) async => Success(entities));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(filter);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Success<List<$entityName>, AppFailure>>());");
    buffer.writeln("      result.fold(");
    buffer.writeln("        (failure) => fail('Should not fail'),");
    buffer.writeln("        (data) => expect(data.length, 2),");
    buffer.writeln("      );");
    buffer.writeln("    });");
    buffer.writeln();

    buffer.writeln("    test('returns Failure when repository fails', () async {");
    buffer.writeln("      final filter = ${entityName}Filter();");
    buffer.writeln("      when(() => mockRepository.getAll(any()))");
    buffer.writeln("          .thenAnswer((_) async => Failure(NetworkFailure('Network error')));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(filter);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Failure<List<$entityName>, AppFailure>>());");
    buffer.writeln("    });");
  }

  void _generateCreateTests(StringBuffer buffer, String entityName, EntitySchema schema) {
    final sampleJson = _generateSampleJson(schema);
    buffer.writeln("    test('returns Success when repository creates successfully', () async {");
    buffer.writeln("      final entity = $entityName.fromJson($sampleJson);");
    buffer.writeln("      when(() => mockRepository.create(any()))");
    buffer.writeln("          .thenAnswer((_) async => Success(entity));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(entity);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Success<$entityName, AppFailure>>());");
    buffer.writeln("      verify(() => mockRepository.create(entity)).called(1);");
    buffer.writeln("    });");
    buffer.writeln();

    buffer.writeln("    test('returns Failure when repository fails', () async {");
    buffer.writeln("      final entity = $entityName.fromJson($sampleJson);");
    buffer.writeln("      when(() => mockRepository.create(any()))");
    buffer.writeln("          .thenAnswer((_) async => Failure(ServerFailure('Server error')));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(entity);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Failure<$entityName, AppFailure>>());");
    buffer.writeln("    });");
  }

  void _generateUpdateTests(StringBuffer buffer, String entityName, EntitySchema schema) {
    final sampleJson = _generateSampleJson(schema);
    buffer.writeln("    test('returns Success when repository updates successfully', () async {");
    buffer.writeln("      final entity = $entityName.fromJson($sampleJson);");
    buffer.writeln("      when(() => mockRepository.update(any()))");
    buffer.writeln("          .thenAnswer((_) async => Success(entity));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(entity);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Success<$entityName, AppFailure>>());");
    buffer.writeln("      verify(() => mockRepository.update(entity)).called(1);");
    buffer.writeln("    });");
    buffer.writeln();

    buffer.writeln("    test('returns Failure when repository fails', () async {");
    buffer.writeln("      final entity = $entityName.fromJson($sampleJson);");
    buffer.writeln("      when(() => mockRepository.update(any()))");
    buffer.writeln("          .thenAnswer((_) async => Failure(ServerFailure('Server error')));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute(entity);");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Failure<$entityName, AppFailure>>());");
    buffer.writeln("    });");
  }

  void _generateDeleteTests(StringBuffer buffer, String entityName) {
    buffer.writeln("    test('returns Success when repository deletes successfully', () async {");
    buffer.writeln("      when(() => mockRepository.delete(any()))");
    buffer.writeln("          .thenAnswer((_) async => const Success(null));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute('test-1');");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Success<void, AppFailure>>());");
    buffer.writeln("      verify(() => mockRepository.delete('test-1')).called(1);");
    buffer.writeln("    });");
    buffer.writeln();

    buffer.writeln("    test('returns Failure when repository fails', () async {");
    buffer.writeln("      when(() => mockRepository.delete(any()))");
    buffer.writeln("          .thenAnswer((_) async => Failure(ServerFailure('Server error')));");
    buffer.writeln();
    buffer.writeln("      final result = await useCase.execute('test-1');");
    buffer.writeln();
    buffer.writeln("      expect(result, isA<Failure<void, AppFailure>>());");
    buffer.writeln("    });");
  }

  /// Get file path for usecase test
  String getFilePath(String entityName, UseCaseType type) {
    final useCaseName = _inferUseCaseName(entityName, type);
    return 'test/domain/usecases/${_toSnakeCase(useCaseName)}_test.dart';
  }

  String _inferUseCaseName(String entityName, UseCaseType type) {
    return switch (type) {
      UseCaseType.get => 'Get${entityName}UseCase',
      UseCaseType.getAll => 'Get${entityName}ListUseCase',
      UseCaseType.create => 'Create${entityName}UseCase',
      UseCaseType.update => 'Update${entityName}UseCase',
      UseCaseType.delete => 'Delete${entityName}UseCase',
    };
  }

  /// Generate sample JSON for testing based on EntitySchema
  String _generateSampleJson(EntitySchema schema, {String idSuffix = '1'}) {
    final buffer = StringBuffer();
    buffer.write('{');

    final fields = <String>[];
    for (final field in schema.fields) {
      final value = _getSampleValue(field, schema, idSuffix: idSuffix);
      fields.add("'${field.name}': $value");
    }

    buffer.write(fields.join(', '));
    buffer.write('}');
    return buffer.toString();
  }

  /// Get sample value for field type
  String _getSampleValue(FieldSchema field, EntitySchema parentSchema, {String idSuffix = '1'}) {
    if (field.type.startsWith('List<')) {
      final innerType = field.type.substring(5, field.type.length - 1);
      if (innerType.startsWith(r'$')) {
        // List of nested entities
        final entityName = innerType.substring(1);
        final nestedSchema = parentSchema.nestedEntities.firstWhere(
          (e) => e.name == entityName,
          orElse: () => EntitySchema(name: entityName, fields: [], nestedEntities: []),
        );
        if (nestedSchema.fields.isEmpty) return "[{}]";
        return '[${_generateNestedJson(nestedSchema, idSuffix: idSuffix)}]';
      } else {
        // List of primitives
        return switch (innerType) {
          'String' => "['test$idSuffix']",
          'int' => '[$idSuffix]',
          'double' => '[$idSuffix.5]',
          'bool' => '[true]',
          _ => '[]',
        };
      }
    } else if (field.type.startsWith(r'$')) {
      // Nested entity
      final entityName = field.type.substring(1);
      final nestedSchema = parentSchema.nestedEntities.firstWhere(
        (e) => e.name == entityName,
        orElse: () => EntitySchema(name: entityName, fields: [], nestedEntities: []),
      );
      if (nestedSchema.fields.isEmpty) return "{}";
      return _generateNestedJson(nestedSchema, idSuffix: idSuffix);
    } else {
      // Primitive
      return switch (field.type) {
        'String' => field.name == 'id' ? "'test-$idSuffix'" : "'test ${field.name} $idSuffix'",
        'int' => field.name == 'id' ? idSuffix : '42',
        'double' => '3.14',
        'bool' => 'true',
        _ => 'null',
      };
    }
  }

  /// Generate JSON for nested entity
  String _generateNestedJson(EntitySchema schema, {String idSuffix = '1'}) {
    final buffer = StringBuffer();
    buffer.write('{');

    final fields = <String>[];
    for (final field in schema.fields) {
      final value = _getSampleValue(field, schema, idSuffix: idSuffix);
      fields.add("'${field.name}': $value");
    }

    buffer.write(fields.join(', '));
    buffer.write('}');
    return buffer.toString();
  }

  String _toSnakeCase(String input) {
    return input
        .replaceAllMapped(
          RegExp(r'[A-Z]'),
          (match) => '_${match.group(0)!.toLowerCase()}',
        )
        .substring(1);
  }
}
