// GENERATED - DO NOT EDIT
// Generated by zfa for: AppNotification
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/app_notification/app_notification.dart';
import '../../repositories/app_notification_repository.dart';

class GetAppNotificationUseCase
    extends UseCase<AppNotification, QueryParams<AppNotification>> {
  GetAppNotificationUseCase(this._repository);

  final AppNotificationRepository _repository;

  @override
  Future<AppNotification> execute(
    QueryParams<AppNotification> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
