// Generated by zfa for: GrocerySubVariety
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'grocery_sub_variety_controller.dart';
import 'grocery_sub_variety_presenter.dart';

class GrocerySubVarietyView extends CleanView {
  const GrocerySubVarietyView({super.key, super.routeObserver});

  @override
  State<GrocerySubVarietyView> createState() {
    return _GrocerySubVarietyViewState(
      GrocerySubVarietyController(GrocerySubVarietyPresenter()),
    );
  }
}

class _GrocerySubVarietyViewState
    extends
        CleanViewState<
          GrocerySubVarietyView,
          GrocerySubVarietyController,
          void
        > {
  _GrocerySubVarietyViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('GrocerySubVariety')),
      body: ControlledWidgetBuilder<GrocerySubVarietyController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
