// Generated by zfa for: UrlListing
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'url_listing_controller.dart';
import 'url_listing_presenter.dart';

class UrlListingView extends CleanView {
  const UrlListingView({super.key, super.routeObserver});

  @override
  State<UrlListingView> createState() {
    return _UrlListingViewState(UrlListingController(UrlListingPresenter()));
  }
}

class _UrlListingViewState
    extends CleanViewState<UrlListingView, UrlListingController, void> {
  _UrlListingViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('UrlListing')),
      body: ControlledWidgetBuilder<UrlListingController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
