// GENERATED - DO NOT EDIT
// Generated by zfa for: Subscription
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/subscription/subscription.dart';
import '../../repositories/subscription_repository.dart';

class UpdateSubscriptionUseCase
    extends UseCase<Subscription, UpdateParams<String, SubscriptionPatch>> {
  UpdateSubscriptionUseCase(this._repository);

  final SubscriptionRepository _repository;

  @override
  Future<Subscription> execute(
    UpdateParams<String, SubscriptionPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
