// Generated by zfa for: TelemetryEvent
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'telemetry_event_controller.dart';
import 'telemetry_event_presenter.dart';

class TelemetryEventView extends CleanView {
  const TelemetryEventView({super.key, super.routeObserver});

  @override
  State<TelemetryEventView> createState() {
    return _TelemetryEventViewState(
      TelemetryEventController(TelemetryEventPresenter()),
    );
  }
}

class _TelemetryEventViewState
    extends CleanViewState<TelemetryEventView, TelemetryEventController, void> {
  _TelemetryEventViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('TelemetryEvent')),
      body: ControlledWidgetBuilder<TelemetryEventController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
