// GENERATED - DO NOT EDIT
// Generated by zfa for: Deal
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/deal/deal.dart';
import '../../mock/deal_mock_data.dart';
import 'deal_datasource.dart';

/// Mock data source for Deal
class DealMockDataSource
    with Loggable, FailureHandler
    implements DealDataSource {
  DealMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Deal> get(QueryParams<Deal> params) async {
    logger.info('Getting Deal with params: $params');
    await Future.delayed(_delay);
    final item = DealMockData.deals.query(params);
    logger.info('Successfully retrieved Deal');
    return item;
  }

  @override
  Future<Deal> update(UpdateParams<String, DealPatch> params) async {
    logger.info('Updating Deal: ${params.id}');
    await Future.delayed(_delay);
    final existing = DealMockData.sampleDeal;
    logger.info('Successfully updated Deal');
    return existing;
  }

  @override
  Future<Deal> toggle(ToggleParams<String, Field<Deal, dynamic>> params) async {
    logger.info('Toggling Deal: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = DealMockData.sampleDeal;
    logger.info('Successfully toggled Deal');
    return existing;
  }
}

// END GENERATED
