/// Generates real working-slice entity source (042, FR-001).
///
/// Entities carry final typed fields parsed from the spec, a const
/// constructor, a type-coercing `fromJson` factory with required-field
/// guards, `toJson`, `copyWith`, and a top-level `validate<E>` function that
/// flags blank required String fields. Field-less entities keep the same
/// shape with vacuous validation (US1.AC4).
library;

import '../models/bone.dart';

/// Generates a working-slice entity file for [stub].
class EntityStubBuilder {
  /// A sample value expression per supported type (used by mocks and tests).
  static String sampleValue(EntityField field) {
    if (field.nullable) return 'null';
    switch (field.type) {
      case 'String':
        return "'sample'";
      case 'int':
        return '1';
      case 'double':
        return '1.5';
      case 'num':
        return '1';
      case 'bool':
        return 'true';
      case 'List<String>':
        return "const <String>['sample']";
      case 'Map<String, dynamic>':
        return "const <String, dynamic>{'sample': true}";
      case 'DateTime':
        return 'DateTime.utc(2026, 1, 1)';
    }
    throw ArgumentError('unsupported field type: ${field.type}');
  }

  /// An edit value expression per supported type (used by copyWith demos).
  static String editValue(EntityField field) {
    switch (field.type) {
      case 'String':
        return "'Edited by bone page'";
      case 'int':
        return '42';
      case 'double':
        return '4.2';
      case 'num':
        return '42';
      case 'bool':
        return 'true';
      case 'List<String>':
        return "const <String>['edited']";
      case 'Map<String, dynamic>':
        return "const <String, dynamic>{'edited': true}";
      case 'DateTime':
        return 'DateTime.utc(2027, 1, 1)';
    }
    throw ArgumentError('unsupported field type: ${field.type}');
  }

  /// Returns the generated Dart source for [stub].
  String build(EntityStub stub) {
    final buffer = StringBuffer();
    _writeClass(buffer, stub);
    _writeValidate(buffer, stub);
    return buffer.toString();
  }

  void _writeClass(StringBuffer buffer, EntityStub stub) {
    final name = stub.name;
    final fields = stub.fields;

    buffer.writeln('/// The $name entity of this feature working slice.');
    buffer.writeln('///');
    buffer.writeln(
      '/// Generated by `zfa bone generate` from the feature spec.',
    );
    buffer.writeln('class $name {');

    // Constructor.
    if (fields.isEmpty) {
      buffer.writeln('  const $name();');
    } else {
      buffer.writeln('  const $name({');
      for (final field in fields) {
        buffer.write('    ');
        if (!field.nullable) buffer.write('required ');
        buffer.writeln('this.${field.name},');
      }
      buffer.writeln('  });');
    }
    buffer.writeln();

    // Fields.
    if (fields.isEmpty) {
      buffer.writeln('  // This entity declares no fields in the source spec.');
    } else {
      for (final field in fields) {
        buffer.writeln(
          '  final ${field.type}${field.nullable ? '?' : ''} ${field.name};',
        );
      }
    }
    buffer.writeln();

    // fromJson.
    buffer.writeln(
      '  /// Builds a [$name] from decoded JSON, rejecting missing required '
      'fields.',
    );
    if (fields.isEmpty) {
      buffer.writeln(
        '  factory $name.fromJson(Map<String, dynamic> json) => '
        'const $name();',
      );
    } else {
      buffer.writeln('  factory $name.fromJson(Map<String, dynamic> json) {');
      for (final field in fields.where((f) => !f.nullable)) {
        buffer.writeln("    _requireKey(json, '${field.name}', '$name');");
      }
      buffer.writeln('    return $name(');
      for (final field in fields) {
        buffer.writeln('      ${field.name}: ${_fromJsonExpr(field)},');
      }
      buffer.writeln('    );');
      buffer.writeln('  }');
      buffer.writeln();
      buffer.writeln(
        '  static void _requireKey(Map<String, dynamic> json, String key, '
        'String entity) {',
      );
      buffer.writeln("    if (!json.containsKey(key) || json[key] == null) {");
      buffer.writeln(
        "      throw FormatException("
        "'\$entity.fromJson: missing required field \"\$key\".');",
      );
      buffer.writeln('    }');
      buffer.writeln('  }');
    }
    buffer.writeln();

    // toJson.
    buffer.writeln('  /// Serializes this instance to decoded JSON.');
    if (fields.isEmpty) {
      buffer.writeln(
        '  Map<String, dynamic> toJson() => const <String, dynamic>{};',
      );
    } else {
      buffer.writeln('  Map<String, dynamic> toJson() => <String, dynamic>{');
      for (final field in fields) {
        if (field.nullable) {
          if (field.type == 'DateTime') {
            buffer.writeln(
              "    if (${field.name} != null) "
              "'${field.name}': ${field.name}!.toIso8601String(),",
            );
            continue;
          }
          buffer.writeln(
            "    if (${field.name} != null) '${field.name}': ${field.name},",
          );
        } else if (field.type == 'DateTime') {
          buffer.writeln(
            "    '${field.name}': ${field.name}.toIso8601String(),",
          );
        } else {
          buffer.writeln("    '${field.name}': ${field.name},");
        }
      }
      buffer.writeln('  };');
    }
    buffer.writeln();

    // copyWith.
    buffer.writeln('  /// Returns a copy with the provided fields overridden.');
    if (fields.isEmpty) {
      buffer.writeln('  $name copyWith() => const $name();');
    } else {
      buffer.writeln('  $name copyWith({');
      for (final field in fields) {
        buffer.writeln('    ${field.type}? ${field.name},');
      }
      buffer.writeln('  }) =>');
      buffer.writeln('      $name(');
      for (final field in fields) {
        buffer.writeln(
          '        ${field.name}: ${field.name} ?? this.${field.name},',
        );
      }
      buffer.writeln('      );');
    }
    buffer.writeln('}');
  }

  String _fromJsonExpr(EntityField field) {
    final key = "json['${field.name}']";
    final nullable = field.nullable ? '?' : '';
    switch (field.type) {
      case 'String':
        return '$key as String$nullable';
      case 'int':
        return field.nullable
            ? '($key as num?)?.toInt()'
            : '($key as num).toInt()';
      case 'double':
        return field.nullable
            ? '($key as num?)?.toDouble()'
            : '($key as num).toDouble()';
      case 'num':
        return '$key as num$nullable';
      case 'bool':
        return '$key as bool$nullable';
      case 'List<String>':
        return field.nullable
            ? '($key as List<dynamic>?)'
                  '?.whereType<String>().toList()'
            : '($key as List<dynamic>)'
                  '.whereType<String>().toList()';
      case 'Map<String, dynamic>':
        return field.nullable
            ? '$key == null ? null : Map<String, dynamic>.from('
                  '$key as Map<dynamic, dynamic>)'
            : 'Map<String, dynamic>.from($key as Map<dynamic, dynamic>)';
      case 'DateTime':
        return field.nullable
            ? '($key == null ? null : DateTime.parse($key as String))'
            : 'DateTime.parse($key as String)';
    }
    throw ArgumentError('unsupported field type: ${field.type}');
  }

  void _writeValidate(StringBuffer buffer, EntityStub stub) {
    final name = stub.name;
    final requiredStrings = stub.fields
        .where((f) => !f.nullable && f.type == 'String')
        .toList();

    buffer.writeln();
    buffer.writeln(
      '/// Validates [instance]: every required String field must be '
      'non-blank.',
    );
    if (requiredStrings.isEmpty) {
      buffer.writeln(
        'List<String> validate$name($name instance) => '
        'const <String>[];',
      );
      return;
    }
    buffer.writeln('List<String> validate$name($name instance) {');
    buffer.writeln('  final errors = <String>[];');
    for (final field in requiredStrings) {
      buffer.writeln("  if (instance.${field.name}.trim().isEmpty) {");
      buffer.writeln("    errors.add('${field.name} must not be blank');");
      buffer.writeln('  }');
    }
    buffer.writeln('  return errors;');
    buffer.writeln('}');
  }
}
