// GENERATED - DO NOT EDIT
// Generated by zfa for: Feedback
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/feedback/feedback.dart';
import '../../mock/feedback_mock_data.dart';
import 'feedback_datasource.dart';

/// Mock data source for Feedback
class FeedbackMockDataSource
    with Loggable, FailureHandler
    implements FeedbackDataSource {
  FeedbackMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Feedback> get(QueryParams<Feedback> params) async {
    logger.info('Getting Feedback with params: $params');
    await Future.delayed(_delay);
    final item = FeedbackMockData.feedbacks.query(params);
    logger.info('Successfully retrieved Feedback');
    return item;
  }

  @override
  Future<Feedback> update(UpdateParams<String, FeedbackPatch> params) async {
    logger.info('Updating Feedback: ${params.id}');
    await Future.delayed(_delay);
    final existing = FeedbackMockData.sampleFeedback;
    logger.info('Successfully updated Feedback');
    return existing;
  }

  @override
  Future<Feedback> toggle(
    ToggleParams<String, Field<Feedback, dynamic>> params,
  ) async {
    logger.info('Toggling Feedback: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = FeedbackMockData.sampleFeedback;
    logger.info('Successfully toggled Feedback');
    return existing;
  }
}

// END GENERATED
