// Generated by zfa for: Category
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'category_controller.dart';
import 'category_presenter.dart';

class CategoryView extends CleanView {
  const CategoryView({super.key, super.routeObserver});

  @override
  State<CategoryView> createState() {
    return _CategoryViewState(CategoryController(CategoryPresenter()));
  }
}

class _CategoryViewState
    extends CleanViewState<CategoryView, CategoryController, void> {
  _CategoryViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('Category')),
      body: ControlledWidgetBuilder<CategoryController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
