// Issue #1383 — generates `docs/openwiki/cli.md` from the LIVE command
// registry (the CLI's own --help output), so the per-command docs cannot
// drift from the dispatcher: every command's usage, description, and
// subcommands are captured from `zfa <command> --help`.
//
// SPEC 1132 / EPIC 1 lane 4: the command-list parser moved to
// `lib/src/docs/openwiki_cli_docs.dart` (shared with the tests) because
// the inline line-anchored regex stopped at the first WRAPPED command
// description (descriptions grew past the 120-column kUsageLineLength)
// and the tool generated a 12-command doc, silently clobbering the
// committed fleet file.
//
// Regenerate after any command-surface change:
//   dart run tool/generate_openwiki_cli_docs.dart
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:zuraffa/src/cli/zfa_executable.dart';
import 'package:zuraffa/src/docs/openwiki_cli_docs.dart';

Future<void> main() async {
  final help = await _zfa(['--help']);

  // The "Available commands:" block — wrapped descriptions included
  // (the shared parser consumes continuation lines).
  final names = parseCommandNames(help);
  if (names.length < 20) {
    // The fleet floor: a parse that sees fewer than 20 commands is a
    // parser regression (the #1132 audit found 12) — refuse to write a
    // silently-truncated doc over the committed fleet file.
    stderr.writeln(
      'only ${names.length} commands parsed from --help — refusing to '
      'write a truncated fleet doc (parser regression?)',
    );
    exit(1);
  }

  final buf = StringBuffer()
    ..writeln('# Openwiki CLI — the command fleet')
    ..writeln()
    ..writeln(
      '<!-- GENERATED by `tool/generate_openwiki_cli_docs.dart` '
      'from the live dispatcher — regenerate, never hand-edit. -->',
    )
    ..writeln()
    ..writeln(
      '- Registry: **${names.length} commands** (as of this '
      'generation — the count is re-emitted on every regeneration, '
      'never pinned by hand).',
    )
    ..writeln(
      '- Exit codes (SPEC 917): `0` success, `1` failure/drift, '
      '`2` usage error. Every non-zero exit ends with a machine-'
      'actionable `--> fix:` line.',
    )
    ..writeln(
      '- Machine envelopes: `--json` emits the '
      '`zuraffa.verdict.v1` document; generated artifacts carry '
      '`proof.v1` receipts under `.zfa/receipts/`.',
    )
    ..writeln();

  for (final name in names) {
    final cmdHelp = await _zfa([name, '--help']);
    buf
      ..writeln('## `zfa $name`')
      ..writeln()
      ..writeln('```');
    // Trim the trailing usage repetition: keep the whole help body —
    // it IS the contract (usage + options + subcommands).
    buf.writeln(cmdHelp.trimRight());
    buf
      ..writeln('```')
      ..writeln();
  }

  final out = File('docs/openwiki/cli.md');
  await out.parent.create(recursive: true);
  await out.writeAsString(buf.toString());
  stdout.writeln('wrote ${out.path} (${names.length} commands)');
}

Future<String> _zfa(List<String> args) async {
  // The no-JIT rule (AGENTS.md / issue #531): every zfa child is a
  // COMPILED binary. The pre-1132 shape spawned `dart run bin/zfa.dart`
  // per command — 59 JIT compiles at ~10s each, which also made the
  // regeneration time out. Resolve the shared AOT artifact through
  // ZfaExecutable.ensureCompiled and shape the argv with commandFor.
  final exe = await ZfaExecutable.ensureCompiled(
    p.join(Directory.current.path, 'bin', 'zfa.dart'),
  );
  final argv = ZfaExecutable.commandFor(exe, args);
  final result = await Process.run(
    argv.first,
    argv.skip(1).toList(),
    stdoutEncoding: utf8,
    stderrEncoding: utf8,
  );
  if (result.exitCode != 0) {
    stderr.writeln('zfa ${args.join(" ")} failed: ${result.stderr}');
    exit(1);
  }
  return result.stdout as String;
}
