// Auto-generated by Zorphy
// Generated at: 2026-08-13T15:57:48.492980

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../enums/index.dart';

part 'feedback.zorphy.dart';
part 'feedback.g.dart';

/// Feedback entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $Feedback {
  String? get id;
  String get message;
  FeedbackType get type;
  String? get imageUrl;
  DateTime? get createdAt;
}
