name: zuraffa_pure_dart_example
description: Example pure Dart server/CLI using zuraffa without Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  zuraffa:
    path: ../../
  logging: any

dependency_overrides:
  zuraffa:
    path: ../..
  zuraffa_flutter:
    path: ../../zuraffa_flutter
  zorphy:
    path: ../../../zorphy/zorphy
  zorphy_annotation:
    path: ../../../zorphy/zorphy_annotation
