part of 'custom_usecase_generator.dart';

extension CustomUseCaseGeneratorGenerate on CustomUseCaseGenerator {
  Future<GeneratedFile> generate(GeneratorConfig config) async {
    // 1. Check for required Domain for non-entity usecases
    if (config.useCaseType != 'entity' && config.domain == null) {
      throw ArgumentError(
        'For non-entity usecases (like ${config.useCaseType}), you must specify a domain using --domain.',
      );
    }

    // 2. Check for required dependencies for specific types
    if (!config.revert &&
        config.useCaseType != 'sync' &&
        !config.hasRepo &&
        !config.hasService) {
      throw ArgumentError(
        'For ${config.useCaseType} usecases, you must specify a repository or service using --repo or --service. Only --type=sync allows no dependencies.',
      );
    }

    final baseName = config.name.endsWith('UseCase')
        ? config.name.substring(0, config.name.length - 7)
        : config.name;
    final className = '${baseName}UseCase';
    final classSnake = StringUtils.camelToSnake(baseName);
    final fileName = '${classSnake}_usecase.dart';
    final usecaseDirPath = path.join(
      outputDir,
      'domain',
      'usecases',
      config.effectiveDomain,
    );
    final filePath = path.join(usecaseDirPath, fileName);

    final paramsType = config.hasMultipleParams
        ? '${baseName}Params'
        : (config.paramsType ?? 'NoParams');
    final returnsType = config.returnsType ?? 'void';
    // Users may pass an already-Future return type (e.g. `--returns Future<void>`).
    // The usecase type already wraps the inner type in a Future, so strip a leading
    // `Future<...>` to avoid `Future<Future<void>>` and bogus entity imports (#419).
    final innerReturnsType = _stripFutureReturns(returnsType);

    final baseClass = _baseClass(config, paramsType, innerReturnsType);
    final imports = _buildImports(config, paramsType, innerReturnsType);
    final fields = _buildDependencyFields(config);
    final constructorParams = _buildDependencyParams(fields);
    final methods = _buildMethods(config, paramsType, innerReturnsType, fields);

    final spec = UseCaseClassSpec(
      className: className,
      baseClass: baseClass,
      fields: fields,
      constructors: constructorParams.isEmpty
          ? const []
          : [
              Constructor(
                (b) => b..requiredParameters.addAll(constructorParams),
              ),
            ],
      methods: methods,
      imports: imports,
    );

    var content = classBuilder.build(
      spec,
      leadingComment: '// Generated by zfa for: ${config.name}',
    );

    if (config.hasMultipleParams) {
      final paramsClass = Class(
        (b) => b
          ..name = paramsType
          ..fields.addAll(
            config.multipleParams.map(
              (p) => Field(
                (f) => f
                  ..name = p.name
                  ..type = refer(p.type)
                  ..modifier = FieldModifier.final$,
              ),
            ),
          )
          ..constructors.add(
            Constructor(
              (c) => c
                ..constant = true
                ..optionalParameters.addAll(
                  config.multipleParams.map(
                    (p) => Parameter(
                      (pp) => pp
                        ..name = p.name
                        ..toThis = true
                        ..named = true
                        ..required = true,
                    ),
                  ),
                ),
            ),
          ),
      );
      final emitter = DartEmitter(
        allocator: Allocator.simplePrefixing(),
        orderDirectives: true,
      );
      content += '\n\n${paramsClass.accept(emitter)}';
    }

    return _writeOrAppend(
      config: config,
      filePath: filePath,
      className: className,
      methodSources: _methodSourcesForAppend(
        config,
        paramsType,
        innerReturnsType,
        fields,
      ),
      content: content,
    );
  }
}

/// Strips a leading `Future<...>` (or bare `Future`) wrapper from a return type
/// so it can be used as the inner type when the usecase type already wraps it.
///
/// Examples: `Future<void>` -> `void`, `Future<List<Item>>` -> `List<Item>`,
/// `Future` -> `void`, `List<Item>` -> `List<Item>` (unchanged).
String _stripFutureReturns(String type) {
  final trimmed = type.trim();
  if (trimmed.startsWith('Future<') && trimmed.endsWith('>')) {
    return trimmed.substring('Future<'.length, trimmed.length - 1);
  }
  if (trimmed == 'Future' || trimmed == 'Future?') {
    return 'void';
  }
  return trimmed;
}
