part of 'custom_usecase_generator.dart';

extension CustomUseCaseGeneratorGenerate on CustomUseCaseGenerator {
  Future<GeneratedFile> generate(GeneratorConfig config) async {
    // 1. Check for required Domain for non-entity usecases
    if (config.useCaseType != 'entity' && config.domain == null) {
      throw ArgumentError(
        'For non-entity usecases (like ${config.useCaseType}), you must specify a domain using --domain.',
      );
    }

    // 2. Check for required dependencies for specific types
    if (!config.revert &&
        config.useCaseType != 'sync' &&
        !config.hasRepo &&
        !config.hasService) {
      throw ArgumentError(
        'For ${config.useCaseType} usecases, you must specify a repository or service using --repo or --service. Only --type=sync allows no dependencies.',
      );
    }

    final baseName = config.name.endsWith('UseCase')
        ? config.name.substring(0, config.name.length - 7)
        : config.name;
    final className = '${baseName}UseCase';
    final classSnake = StringUtils.camelToSnake(baseName);
    final fileName = '${classSnake}_usecase.dart';
    final usecaseDirPath = path.join(
      outputDir,
      'domain',
      'usecases',
      config.effectiveDomain,
    );
    final filePath = path.join(usecaseDirPath, fileName);

    final paramsType = config.paramsType ?? 'NoParams';
    final returnsType = config.returnsType ?? 'void';

    final baseClass = _baseClass(config, paramsType, returnsType);
    final imports = _buildImports(config, paramsType, returnsType);
    final fields = _buildDependencyFields(config);
    final constructorParams = _buildDependencyParams(fields);
    final methods = _buildMethods(config, paramsType, returnsType, fields);

    final spec = UseCaseClassSpec(
      className: className,
      baseClass: baseClass,
      fields: fields,
      constructors: constructorParams.isEmpty
          ? const []
          : [
              Constructor(
                (b) => b..requiredParameters.addAll(constructorParams),
              ),
            ],
      methods: methods,
      imports: imports,
    );

    final content = classBuilder.build(
      spec,
      leadingComment: '// Generated by zfa for: ${config.name}',
    );
    return _writeOrAppend(
      config: config,
      filePath: filePath,
      className: className,
      methodSources: _methodSourcesForAppend(
        config,
        paramsType,
        returnsType,
        fields,
      ),
      content: content,
    );
  }
}
