// Generated by zfa
// zfa generate Product --methods=get,getList,watch,watchList,create,update,delete --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/product/product.dart';

abstract class ProductRepository {
  Future<Product> get(QueryParams<Product> params);
  Future<List<Product>> getList(ListQueryParams<Product> params);
  Stream<Product> watch(QueryParams<Product> params);
  Stream<List<Product>> watchList(ListQueryParams<Product> params);
  Future<Product> create(Product product);
  Future<Product> update(UpdateParams<Product, Map<String, dynamic>> params);
  Future<void> delete(DeleteParams<Product> params);
}
