// Generated by zfa
// zfa generate Product --methods=get,getList,create,watch,update,delete,watchList --repository

import 'package:zuraffa/zuraffa.dart';
import '../entities/product/product.dart';

abstract class ProductRepository {
  Stream<bool> get isInitialized;
  Future<void> initialize(InitializationParams params);
  Future<Product> get(String id);
  Future<List<Product>> getList(ListQueryParams params);
  Future<Product> create(Product product);
  Stream<Product> watch(String id);
  Future<Product> update(UpdateParams<Partial<Product>> params);
  Future<void> delete(DeleteParams<Product> params);
  Stream<List<Product>> watchList(ListQueryParams params);
}
