import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../../../core/builder/shared/spec_library.dart';
import '../../../core/generator_options.dart';
import '../../../core/context/file_system.dart';
import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';

/// Generates the `Sync<Entity>UseCase` for manual sync triggering (FR-007, T030).
///
/// Produces `domain/usecases/{domain}/{entity_snake}_sync_usecase.dart`:
///
/// ```dart
/// class SyncProductUseCase extends UseCase<void, NoParams> {
///   final ProductRepository _repository;
///
///   SyncProductUseCase(this._repository);
///
///   @override
///   Future<void> execute(NoParams params, CancelToken? cancelToken) async {
///     cancelToken?.throwIfCancelled();
///     await _repository.syncPending(cancelToken: cancelToken);
///   }
/// }
/// ```
///
/// The use case mirrors the existing entity use case generators: it depends on
/// the abstract `{Entity}Repository` (proper dependency inversion) and delegates
/// the actual sync work to [repository.syncPending]. The sync-enabled repository
/// interface declares `syncPending`/`pullRemote`, so this compiles cleanly.
class SyncEntityUseCaseGenerator {
  final String outputDir;
  final GeneratorOptions options;
  final SpecLibrary specLibrary;
  final FileSystem fileSystem;

  SyncEntityUseCaseGenerator({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    SpecLibrary? specLibrary,
    FileSystem? fileSystem,
  }) : specLibrary = specLibrary ?? const SpecLibrary(),
       fileSystem = fileSystem ?? FileSystem.create();

  /// Generates the `Sync<Entity>UseCase` source file for [config].
  Future<GeneratedFile> generate(GeneratorConfig config) async {
    final entityName = config.name;
    final entitySnake = config.nameSnake;
    final className = 'Sync${entityName}UseCase';
    final fileName = '${entitySnake}_sync_usecase.dart';

    final usecaseDirPath = path.join(
      outputDir,
      'domain',
      'usecases',
      config.effectiveDomain,
    );
    final filePath = path.join(usecaseDirPath, fileName);

    final repositoryType = '${entityName}Repository';

    final repositoryField = Field(
      (f) => f
        ..modifier = FieldModifier.final$
        ..type = refer(repositoryType)
        ..name = '_repository',
    );

    final constructor = Constructor(
      (c) => c
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = '_repository'
              ..toThis = true,
          ),
        ),
    );

    final executeMethod = Method(
      (m) => m
        ..name = 'execute'
        ..annotations.add(refer('override'))
        ..returns = _futureVoidType()
        ..modifier = MethodModifier.async
        ..requiredParameters.addAll([
          Parameter(
            (p) => p
              ..name = 'params'
              ..type = refer('NoParams'),
          ),
          Parameter(
            (p) => p
              ..name = 'cancelToken'
              ..type = TypeReference(
                (t) => t
                  ..symbol = 'CancelToken'
                  ..isNullable = true,
              ),
          ),
        ])
        ..body = Block(
          (b) => b
            ..statements.add(Code('cancelToken?.throwIfCancelled();'))
            ..statements.add(
              refer('_repository')
                  .property('syncPending')
                  .call([], {'cancelToken': refer('cancelToken')})
                  .awaited
                  .statement,
            ),
        ),
    );

    final useCaseClass = Class(
      (c) => c
        ..name = className
        ..extend = TypeReference(
          (t) => t
            ..symbol = 'UseCase'
            ..types.addAll([refer('void'), refer('NoParams')]),
        )
        ..fields.add(repositoryField)
        ..constructors.add(constructor)
        ..methods.add(executeMethod),
    );

    final directives = [
      Directive.import('package:zuraffa/zuraffa.dart'),
      Directive.import(
        '../../../repositories/${StringUtils.camelToSnake(entityName)}_repository.dart',
      ),
    ];

    final content = specLibrary.emitLibrary(
      specLibrary.library(specs: [useCaseClass], directives: directives),
      leadingComment: '// Generated by zfa for: ${config.name}',
    );

    return FileUtils.writeFile(
      filePath,
      content,
      'sync_usecase',
      force: config.force,
      dryRun: config.dryRun,
      verbose: config.verbose,
      revert: config.revert,
      fileSystem: fileSystem,
    );
  }

  /// Returns `Future<void>` type reference.
  TypeReference _futureVoidType() {
    return TypeReference(
      (b) => b
        ..symbol = 'Future'
        ..types.add(refer('void')),
    );
  }
}
