import 'package:code_builder/code_builder.dart';

import '../../../core/builder/shared/spec_library.dart';
import '../../../package/package_names.dart';

/// A DI category contributed to a package registrar: the `di/` folder
/// (e.g. `usecases`) and its `registerAll*` label (e.g. `UseCases` →
/// `registerAllUseCases`).
typedef RegistrarCategory = ({String folder, String label});

/// Builds the package registrar emitted by the DI plugin in package mode
/// (spec 025, FR-004/FR-012).
///
/// The registrar is the package-level registration unit a consuming app
/// merges into its dependency container via the package's
/// `PackageModule.registerDependencies` — replacing the app-context
/// `service_locator.dart` + `di/index.dart` (`setupDependencies`) pair.
class PackageRegistrarBuilder {
  final SpecLibrary specLibrary;

  const PackageRegistrarBuilder({this.specLibrary = const SpecLibrary()});

  /// Builds the registrar source for [packageName] (snake_case) covering
  /// [categories] — the DI directories whose `index.dart` files expose
  /// `registerAll*` functions.
  String build({
    required String packageName,
    required List<RegistrarCategory> categories,
  }) {
    final pascal = PackageNames.pascalFor(packageName);
    final functionName = PackageNames.registrarFunctionFor(packageName);

    final importPaths = <String>[
      'package:zuraffa/zuraffa.dart',
      ...categories.map((c) => '${c.folder}/index.dart'),
    ];

    final registerMethod = Method(
      (m) => m
        ..name = functionName
        ..returns = refer('void')
        ..docs.add('''
/// Registers every contributed datasource/repository/usecase of package
/// `$packageName` into the consuming app's [di] container.
///
/// Generated by `zfa make ... --di` in package mode and called by the
/// package's `${pascal}PackageModule.registerDependencies`, so
/// registration is strictly import-scoped (spec 025, FR-005).
///''')
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = 'di'
              ..type = refer('ZuraffaDIContainer'),
          ),
        )
        ..body = Block(
          (b) => b
            ..statements.add(
              declareFinal(
                'getIt',
                type: refer('GetIt'),
              ).assign(refer('di').property('getIt')).statement,
            )
            ..statements.addAll(
              categories.map(
                (c) => refer(
                  _registerAllName(c.label),
                ).call([refer('getIt')]).statement,
              ),
            ),
        ),
    );

    final library = specLibrary.library(
      specs: [registerMethod],
      directives: importPaths.map(Directive.import).toList(),
    );

    return specLibrary.emitLibrary(
      library,
      leadingComment:
          '// Generated by zfa — package registrar for $packageName '
          '(spec 025, FR-004).',
    );
  }

  static String _registerAllName(String label) => 'registerAll$label';
}
