/// Generated simulation DI bindings (spec 893, T002).
///
/// The simulation binding is GENERATED, not hand-wired (FR-002): both
/// `zfa make --di` and `zfa mock create` emit
/// `di/simulation/<entity>_simulation_datasource_di.dart`, which binds the
/// entity's production datasource interface to its generated mock behind
/// the single `--dart-define=SIMULATION=true` flavor switch (FR-001,
/// FR-003, FR-013). Simulation bindings are distinguishable from
/// hand-written bindings by their dedicated `di/simulation/` location and
/// the `SIMULATION BINDING` generated-file markers (FR-011, SC-006).
///
/// Issue #1031: in service mode the mock lane generates
/// `<Name>Service` + `<Name>MockProvider` and no datasource pair, so the
/// simulation binding follows the service shape instead:
/// `di/simulation/<name>_simulation_service_di.dart` binds
/// `<Name>Service` -> `<Name>MockProvider` behind the same flavor switch.
library;

import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../../../core/ast/append_executor.dart';
import '../../../core/ast/strategies/append_strategy.dart';
import '../../../core/builder/shared/spec_library.dart';
import '../../../core/context/file_system.dart';
import '../../../core/generator_options.dart';
import '../../../models/generated_file.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';
import '../detectors/registration_detector.dart';

const String simulationDiFolder = 'simulation';

/// One simulation binding registration discovered on disk or pending.
class SimulationBindingRegistration {
  final String fileName;
  final String functionName;

  const SimulationBindingRegistration({
    required this.fileName,
    required this.functionName,
  });
}

/// Pure builder for the per-entity simulation binding file.
class SimulationBindingBuilder {
  const SimulationBindingBuilder();

  static const String bindingMarker =
      '// spec 893 — SIMULATION BINDING: generated by '
      '`zfa make --di` / `zfa mock create`.\n'
      '// Do not hand-edit — regenerate with the zfa CLI. Simulation\n'
      '// bindings live in di/simulation/ and are the only generated\n'
      '// bindings that switch on the SIMULATION flavor define.';

  /// Emits `register<Entity>SimulationDataSource(GetIt getIt)`, which
  /// binds `<Entity>DataSource` (the production interface) to
  /// `<Entity>MockDataSource` and no-ops unless the app was compiled with
  /// `--dart-define=SIMULATION=true`.
  String buildBindingFile({
    required String entityName,
    required String entitySnake,
  }) {
    final method = _registrationFunction(
      functionName: 'register${entityName}SimulationDataSource',
      interfaceName: '${entityName}DataSource',
      mockName: '${entityName}MockDataSource',
    );

    final directives = _simulationDirectives([
      '../../data/datasources/$entitySnake/${entitySnake}_datasource.dart',
      '../../data/datasources/$entitySnake/${entitySnake}_mock_datasource.dart',
    ]);

    return _wrapBinding(
      const SpecLibrary().emitLibrary(
        const SpecLibrary().library(specs: [method], directives: directives),
        wrapWithGeneratedMarkers: false,
      ),
    );
  }

  /// Issue #1031: emits `register<Name>SimulationService(GetIt getIt)`,
  /// which binds `<Name>Service` (the production service interface the
  /// mock lane actually generated) to `<Name>MockProvider` behind the same
  /// single `--dart-define=SIMULATION=true` flavor switch — the
  /// service-mode counterpart of [buildBindingFile]. The datasource shape
  /// must never be emitted in service mode: its imports would reference a
  /// datasource pair that was never generated.
  String buildServiceBindingFile({
    required String serviceName,
    required String mockProviderName,
    required List<String> relativeImports,
  }) {
    final baseName = stripServiceSuffix(serviceName);
    final method = _registrationFunction(
      functionName: 'register${baseName}SimulationService',
      interfaceName: serviceName,
      mockName: mockProviderName,
    );

    final directives = _simulationDirectives(relativeImports);

    return _wrapBinding(
      const SpecLibrary().emitLibrary(
        const SpecLibrary().library(specs: [method], directives: directives),
        wrapWithGeneratedMarkers: false,
      ),
    );
  }

  /// The flavor-guarded `registerLazySingleton<interface>(() => mock)`
  /// registration shared by both binding shapes (FR-001).
  static Method _registrationFunction({
    required String functionName,
    required String interfaceName,
    required String mockName,
  }) {
    return Method(
      (m) => m
        ..name = functionName
        ..returns = refer('void')
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = 'getIt'
              ..type = refer('GetIt'),
          ),
        )
        ..body = Block(
          (b) => b
            ..statements.addAll([
              // Single --dart-define flavor switch (FR-001): the binding is
              // inert in the real flavor and dead-code-eliminated in AOT.
              Code('if (!kSimulationMode) return;'),
              refer('getIt')
                  .property('registerLazySingleton')
                  .call(
                    [
                      Method(
                        (m) => m
                          ..lambda = true
                          ..body = refer(mockName).call([]).code,
                      ).closure,
                    ],
                    {},
                    [refer(interfaceName)],
                  )
                  .statement,
            ]),
        ),
    );
  }

  static List<Directive> _simulationDirectives(List<String> relativeImports) =>
      [
        Directive.import('package:zuraffa/zuraffa.dart'),
        Directive.import('package:zuraffa/simulation.dart'),
        ...relativeImports.map(Directive.import),
      ];

  static String _wrapBinding(String body) =>
      '// GENERATED - DO NOT EDIT\n'
      '$bindingMarker\n'
      '$body\n\n'
      '// END GENERATED';

  /// `AuthService` -> `Auth` (the `<Name>` of `<Name>Service ->
  /// <Name>MockProvider` binding names).
  static String stripServiceSuffix(String serviceName) =>
      serviceName.endsWith('Service')
      ? serviceName.substring(0, serviceName.length - 7)
      : serviceName;

  /// Emits `di/simulation/index.dart` exposing
  /// `registerSimulationBindings(GetIt getIt)`, which runs the FR-012
  /// flag-conflict gate first and then registers every entity binding
  /// discovered under `di/simulation/`.
  String buildIndexFile({
    required List<SimulationBindingRegistration> registrations,
  }) {
    final specLibrary = const SpecLibrary();

    final method = Method(
      (m) => m
        ..name = 'registerSimulationBindings'
        ..returns = refer('void')
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = 'getIt'
              ..type = refer('GetIt'),
          ),
        )
        ..body = Block(
          (b) => b
            ..statements.addAll([
              // FR-012: an incoherent build-time flag set fails loudly
              // before any binding is registered — never a silent
              // fall-through to real network access.
              refer(
                'SimulationFlavor',
              ).property('checkFlagConflicts').call([]).statement,
              ...registrations.map(
                (r) => refer(r.functionName).call([refer('getIt')]).statement,
              ),
            ]),
        ),
    );

    final directives = [
      Directive.import('package:zuraffa/zuraffa.dart'),
      Directive.import('package:zuraffa/simulation.dart'),
      ...registrations.map((r) => Directive.import(r.fileName)),
    ];

    return specLibrary.emitLibrary(
      specLibrary.library(specs: [method], directives: directives),
    );
  }
}

/// File-writing facade shared by `DiPlugin` (`zfa make --di`) and
/// `MockPlugin` (`zfa mock create`): emits the per-entity binding file and
/// keeps `di/simulation/index.dart` in sync with the RegistrationDetector
/// used by every other DI category index.
class SimulationBindingEmitter {
  SimulationBindingEmitter({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    FileSystem? fileSystem,
  }) : fileSystem = fileSystem ?? const DefaultFileSystem();

  final String outputDir;
  final GeneratorOptions options;
  final FileSystem fileSystem;

  static const RegistrationDetector _detector = RegistrationDetector();
  static const SimulationBindingBuilder builder = SimulationBindingBuilder();
  static const AppendExecutor _appendExecutor = AppendExecutor();

  String get simulationDir => path.join(outputDir, 'di', simulationDiFolder);

  String entityNameFor({String? repo, required String name}) =>
      repo?.replaceAll('Repository', '') ?? name;

  /// Writes `di/simulation/<entity>_simulation_datasource_di.dart`.
  Future<GeneratedFile> emitBinding({
    required String entityName,
    GeneratedFile? pendingBinding,
  }) async {
    final entitySnake = StringUtils.camelToSnake(entityName);
    final fileName = '${entitySnake}_simulation_datasource_di.dart';
    final bindingPath = path.join(simulationDir, fileName);

    return FileUtils.writeFile(
      bindingPath,
      builder.buildBindingFile(
        entityName: entityName,
        entitySnake: entitySnake,
      ),
      'di_simulation_binding',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// Issue #1031: writes
  /// `di/simulation/<name>_simulation_service_di.dart` — the service-mode
  /// counterpart of [emitBinding], binding the service interface the mock
  /// lane actually generated (`<Name>Service`) to its mock provider.
  Future<GeneratedFile> emitServiceBinding({
    required String serviceName,
    required String mockProviderName,
    required String serviceImport,
    required String mockProviderImport,
  }) async {
    final baseSnake = StringUtils.camelToSnake(
      SimulationBindingBuilder.stripServiceSuffix(serviceName),
    );
    final fileName = '${baseSnake}_simulation_service_di.dart';
    final bindingPath = path.join(simulationDir, fileName);

    return FileUtils.writeFile(
      bindingPath,
      builder.buildServiceBindingFile(
        serviceName: serviceName,
        mockProviderName: mockProviderName,
        relativeImports: [serviceImport, mockProviderImport],
      ),
      'di_simulation_binding',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// Regenerates `di/simulation/index.dart` from the `_di.dart` files on
  /// disk plus [pendingFiles].
  Future<GeneratedFile?> regenerateIndex({
    List<GeneratedFile> pendingFiles = const [],
  }) async {
    final detected = await _detector.detectRegistrations(
      simulationDir,
      pendingFiles: pendingFiles,
      fileSystem: fileSystem,
    );
    if (detected.isEmpty) return null;

    final registrations = detected
        .map(
          (r) => SimulationBindingRegistration(
            fileName: r.fileName,
            functionName: r.functionName,
          ),
        )
        .toList();

    final indexPath = path.join(simulationDir, 'index.dart');
    return FileUtils.writeFile(
      indexPath,
      builder.buildIndexFile(registrations: registrations),
      'di_simulation_index',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// Ensures the app-level `di/index.dart` calls
  /// `registerSimulationBindings(getIt)` from `setupDependencies` so the
  /// generated flavor switch is wired with zero manual steps. Idempotent:
  /// the append strategies no-op when the call or import already exists.
  Future<GeneratedFile?> syncMainIndex() async {
    final mainIndexPath = path.join(outputDir, 'di', 'index.dart');
    if (!await fileSystem.exists(mainIndexPath)) return null;
    if (options.dryRun || options.revert) return null;

    var content = await fileSystem.read(mainIndexPath);
    final importResult = _appendExecutor.execute(
      AppendRequest.import(
        source: content,
        importPath: '$simulationDiFolder/index.dart',
      ),
    );
    content = importResult.source;
    final callResult = _appendExecutor.execute(
      AppendRequest.functionStatement(
        source: content,
        functionName: 'setupDependencies',
        memberSource: 'registerSimulationBindings(getIt);',
      ),
    );
    content = callResult.source;
    if (!importResult.changed && !callResult.changed) return null;

    return FileUtils.writeFile(
      mainIndexPath,
      content,
      'di_main_index',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }
}
