/// Generated simulation DI bindings (spec 893, T002).
///
/// The simulation binding is GENERATED, not hand-wired (FR-002): both
/// `zfa make --di` and `zfa mock create` emit
/// `di/simulation/<entity>_simulation_datasource_di.dart`, which binds the
/// entity's production datasource interface to its generated mock behind
/// the single `--dart-define=SIMULATION=true` flavor switch (FR-001,
/// FR-003, FR-013). Simulation bindings are distinguishable from
/// hand-written bindings by their dedicated `di/simulation/` location and
/// the `SIMULATION BINDING` generated-file markers (FR-011, SC-006).
library;

import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../../../core/ast/append_executor.dart';
import '../../../core/ast/strategies/append_strategy.dart';
import '../../../core/builder/shared/spec_library.dart';
import '../../../core/context/file_system.dart';
import '../../../core/generator_options.dart';
import '../../../models/generated_file.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';
import '../detectors/registration_detector.dart';

const String simulationDiFolder = 'simulation';

/// One simulation binding registration discovered on disk or pending.
class SimulationBindingRegistration {
  final String fileName;
  final String functionName;

  const SimulationBindingRegistration({
    required this.fileName,
    required this.functionName,
  });
}

/// Pure builder for the per-entity simulation binding file.
class SimulationBindingBuilder {
  const SimulationBindingBuilder();

  static const String bindingMarker =
      '// spec 893 — SIMULATION BINDING: generated by '
      '`zfa make --di` / `zfa mock create`.\n'
      '// Do not hand-edit — regenerate with the zfa CLI. Simulation\n'
      '// bindings live in di/simulation/ and are the only generated\n'
      '// bindings that switch on the SIMULATION flavor define.';

  /// Emits the per-entity simulation binding file.
  ///
  /// Datasource mode (default): emits
  /// `register<Entity>SimulationDataSource(GetIt getIt)`, which binds
  /// `<Entity>DataSource` (the production interface) to
  /// `<Entity>MockDataSource` and no-ops unless the app was compiled with
  /// `--dart-define=SIMULATION=true`.
  ///
  /// Service mode (#1031): when [serviceInterfaceName] is non-null, emits
  /// `register<Name>SimulationService(GetIt getIt)` instead, binding
  /// `<Name>Service` (the production interface) to `<Name>MockProvider` —
  /// the mock surface the service lane actually generates. The datasource
  /// names/classes do not exist in service mode, so a datasource-shaped
  /// binding there is a guaranteed `uri_does_not_exist`. [entityName] and
  /// [entitySnake] are ignored by the service branch; [serviceImportPath]
  /// and [mockProviderImportPath] carry the fs-resolved import paths the
  /// emitter derived from where the service lane writes its files.
  String buildBindingFile({
    required String entityName,
    required String entitySnake,
    String? serviceInterfaceName,
    String? serviceMockProviderName,
    String? serviceImportPath,
    String? mockProviderImportPath,
  }) {
    if (serviceInterfaceName != null) {
      // #1031: service-mode branch. The interface name is the normalized
      // `<Name>Service`; the generated registration mirrors the datasource
      // lane's `register<Entity>SimulationDataSource`.
      final baseName = serviceInterfaceName.endsWith('Service')
          ? serviceInterfaceName.substring(
              0,
              serviceInterfaceName.length - 'Service'.length,
            )
          : serviceInterfaceName;
      return _buildBindingFile(
        functionName: 'register${baseName}SimulationService',
        interfaceName: serviceInterfaceName,
        mockName: serviceMockProviderName ?? '${baseName}MockProvider',
        interfaceImport: serviceImportPath!,
        mockImport: mockProviderImportPath!,
      );
    }
    return _buildBindingFile(
      functionName: 'register${entityName}SimulationDataSource',
      interfaceName: '${entityName}DataSource',
      mockName: '${entityName}MockDataSource',
      interfaceImport:
          '../../data/datasources/$entitySnake/${entitySnake}_datasource.dart',
      mockImport:
          '../../data/datasources/$entitySnake/${entitySnake}_mock_datasource.dart',
    );
  }

  /// Shared emitter for both shapes: a single flavor-guarded
  /// `registerLazySingleton<Interface>(() => Mock())` registration with the
  /// generated-file markers. Only the names and imports differ per lane.
  String _buildBindingFile({
    required String functionName,
    required String interfaceName,
    required String mockName,
    required String interfaceImport,
    required String mockImport,
  }) {
    final specLibrary = const SpecLibrary();

    final method = Method(
      (m) => m
        ..name = functionName
        ..returns = refer('void')
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = 'getIt'
              ..type = refer('GetIt'),
          ),
        )
        ..body = Block(
          (b) => b
            ..statements.addAll([
              // Single --dart-define flavor switch (FR-001): the binding is
              // inert in the real flavor and dead-code-eliminated in AOT.
              Code('if (!kSimulationMode) return;'),
              refer('getIt')
                  .property('registerLazySingleton')
                  .call(
                    [
                      Method(
                        (m) => m
                          ..lambda = true
                          ..body = refer(mockName).call([]).code,
                      ).closure,
                    ],
                    {},
                    [refer(interfaceName)],
                  )
                  .statement,
            ]),
        ),
    );

    final directives = [
      Directive.import('package:zuraffa/zuraffa.dart'),
      Directive.import('package:zuraffa/simulation.dart'),
      Directive.import(interfaceImport),
      Directive.import(mockImport),
    ];

    final body = specLibrary.emitLibrary(
      specLibrary.library(specs: [method], directives: directives),
      wrapWithGeneratedMarkers: false,
    );

    return '// GENERATED - DO NOT EDIT\n'
        '$bindingMarker\n'
        '$body\n\n'
        '// END GENERATED';
  }

  /// Emits `di/simulation/index.dart` exposing
  /// `registerSimulationBindings(GetIt getIt)`, which runs the FR-012
  /// flag-conflict gate first and then registers every entity binding
  /// discovered under `di/simulation/`.
  String buildIndexFile({
    required List<SimulationBindingRegistration> registrations,
  }) {
    final specLibrary = const SpecLibrary();

    final method = Method(
      (m) => m
        ..name = 'registerSimulationBindings'
        ..returns = refer('void')
        ..requiredParameters.add(
          Parameter(
            (p) => p
              ..name = 'getIt'
              ..type = refer('GetIt'),
          ),
        )
        ..body = Block(
          (b) => b
            ..statements.addAll([
              // FR-012: an incoherent build-time flag set fails loudly
              // before any binding is registered — never a silent
              // fall-through to real network access.
              refer(
                'SimulationFlavor',
              ).property('checkFlagConflicts').call([]).statement,
              ...registrations.map(
                (r) => refer(r.functionName).call([refer('getIt')]).statement,
              ),
            ]),
        ),
    );

    final directives = [
      Directive.import('package:zuraffa/zuraffa.dart'),
      Directive.import('package:zuraffa/simulation.dart'),
      ...registrations.map((r) => Directive.import(r.fileName)),
    ];

    return specLibrary.emitLibrary(
      specLibrary.library(specs: [method], directives: directives),
    );
  }
}

/// File-writing facade shared by `DiPlugin` (`zfa make --di`) and
/// `MockPlugin` (`zfa mock create`): emits the per-entity binding file and
/// keeps `di/simulation/index.dart` in sync with the RegistrationDetector
/// used by every other DI category index.
class SimulationBindingEmitter {
  SimulationBindingEmitter({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    FileSystem? fileSystem,
  }) : fileSystem = fileSystem ?? const DefaultFileSystem();

  final String outputDir;
  final GeneratorOptions options;
  final FileSystem fileSystem;

  static const RegistrationDetector _detector = RegistrationDetector();
  static const SimulationBindingBuilder builder = SimulationBindingBuilder();
  static const AppendExecutor _appendExecutor = AppendExecutor();

  String get simulationDir => path.join(outputDir, 'di', simulationDiFolder);

  String entityNameFor({String? repo, required String name}) =>
      repo?.replaceAll('Repository', '') ?? name;

  /// Writes `di/simulation/<entity>_simulation_datasource_di.dart`, or —
  /// in service mode (#1031) —
  /// `di/simulation/<service>_simulation_service_di.dart`.
  ///
  /// Service mode is selected by passing [serviceInterfaceName] (the
  /// normalized `<Name>Service`): the emitter resolves the service
  /// interface and mock provider imports from where the service lane
  /// actually writes those files before delegating to the builder's
  /// service branch.
  Future<GeneratedFile> emitBinding({
    required String entityName,
    GeneratedFile? pendingBinding,
    String? serviceInterfaceName,
    String? serviceMockProviderName,
    String? serviceSnake,
    String? serviceDomain,
  }) async {
    if (serviceInterfaceName != null) {
      return _emitServiceBinding(
        serviceInterfaceName: serviceInterfaceName,
        serviceMockProviderName: serviceMockProviderName,
        serviceSnake: serviceSnake,
        serviceDomain: serviceDomain,
      );
    }

    final entitySnake = StringUtils.camelToSnake(entityName);
    final fileName = '${entitySnake}_simulation_datasource_di.dart';
    final bindingPath = path.join(simulationDir, fileName);

    return FileUtils.writeFile(
      bindingPath,
      builder.buildBindingFile(
        entityName: entityName,
        entitySnake: entitySnake,
      ),
      'di_simulation_binding',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// #1031 service-mode emission: mirrors how the service lane lays out its
  /// files so the generated binding imports classes that really exist —
  ///
  ///   * interface: `domain/services/<serviceSnake>_service.dart` (custom
  ///     services, flat) or `domain/services/<domain>/<serviceSnake>_service.dart`
  ///     (entity-based services) — resolved from disk exactly like
  ///     `DiPlugin._generateServiceDI`;
  ///   * mock: `data/providers/<effectiveDomain>/<mockSnake>.dart`, the same
  ///     path `MockProviderBuilder.generateMockProvider` writes, where
  ///     `effectiveDomain = domain ?? <name snake>` (GeneratorConfig).
  Future<GeneratedFile> _emitServiceBinding({
    required String serviceInterfaceName,
    String? serviceMockProviderName,
    String? serviceSnake,
    String? serviceDomain,
  }) async {
    final baseName = serviceInterfaceName.endsWith('Service')
        ? serviceInterfaceName.substring(
            0,
            serviceInterfaceName.length - 'Service'.length,
          )
        : serviceInterfaceName;
    final snake = serviceSnake ?? StringUtils.camelToSnake(baseName);
    final mockName = serviceMockProviderName ?? '${baseName}MockProvider';
    final fileName = '${snake}_simulation_service_di.dart';
    final bindingPath = path.join(simulationDir, fileName);

    final domainScopedServiceFile = serviceDomain == null
        ? null
        : path.join(
            outputDir,
            'domain',
            'services',
            serviceDomain,
            '${snake}_service.dart',
          );
    final serviceImportPath =
        domainScopedServiceFile != null &&
            await fileSystem.exists(domainScopedServiceFile)
        ? '../../domain/services/$serviceDomain/${snake}_service.dart'
        : '../../domain/services/${snake}_service.dart';

    final providerDomain = serviceDomain ?? snake;
    final mockProviderImportPath =
        '../../data/providers/$providerDomain/${StringUtils.camelToSnake(mockName)}.dart';

    return FileUtils.writeFile(
      bindingPath,
      builder.buildBindingFile(
        entityName: serviceInterfaceName,
        entitySnake: snake,
        serviceInterfaceName: serviceInterfaceName,
        serviceMockProviderName: mockName,
        serviceImportPath: serviceImportPath,
        mockProviderImportPath: mockProviderImportPath,
      ),
      'di_simulation_binding',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// Regenerates `di/simulation/index.dart` from the `_di.dart` files on
  /// disk plus [pendingFiles].
  Future<GeneratedFile?> regenerateIndex({
    List<GeneratedFile> pendingFiles = const [],
  }) async {
    final detected = await _detector.detectRegistrations(
      simulationDir,
      pendingFiles: pendingFiles,
      fileSystem: fileSystem,
    );
    if (detected.isEmpty) return null;

    final registrations = detected
        .map(
          (r) => SimulationBindingRegistration(
            fileName: r.fileName,
            functionName: r.functionName,
          ),
        )
        .toList();

    final indexPath = path.join(simulationDir, 'index.dart');
    return FileUtils.writeFile(
      indexPath,
      builder.buildIndexFile(registrations: registrations),
      'di_simulation_index',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }

  /// Ensures the app-level `di/index.dart` calls
  /// `registerSimulationBindings(getIt)` from `setupDependencies` so the
  /// generated flavor switch is wired with zero manual steps. Idempotent:
  /// the append strategies no-op when the call or import already exists.
  Future<GeneratedFile?> syncMainIndex() async {
    final mainIndexPath = path.join(outputDir, 'di', 'index.dart');
    if (!await fileSystem.exists(mainIndexPath)) return null;
    if (options.dryRun || options.revert) return null;

    var content = await fileSystem.read(mainIndexPath);
    final importResult = _appendExecutor.execute(
      AppendRequest.import(
        source: content,
        importPath: '$simulationDiFolder/index.dart',
      ),
    );
    content = importResult.source;
    final callResult = _appendExecutor.execute(
      AppendRequest.functionStatement(
        source: content,
        functionName: 'setupDependencies',
        memberSource: 'registerSimulationBindings(getIt);',
      ),
    );
    content = callResult.source;
    if (!importResult.changed && !callResult.changed) return null;

    return FileUtils.writeFile(
      mainIndexPath,
      content,
      'di_main_index',
      force: true,
      dryRun: options.dryRun,
      verbose: options.verbose,
      fileSystem: fileSystem,
    );
  }
}
