// GENERATED - DO NOT EDIT
// Generated by zfa for: ErrorLog
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/error_log/error_log.dart';
import '../../repositories/error_log_repository.dart';

class GetErrorLogUseCase extends UseCase<ErrorLog, QueryParams<ErrorLog>> {
  GetErrorLogUseCase(this._repository);

  final ErrorLogRepository _repository;

  @override
  Future<ErrorLog> execute(
    QueryParams<ErrorLog> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
