// GENERATED - DO NOT EDIT
// Generated by zfa for: Deal
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/deal/deal.dart';
import '../../repositories/deal_repository.dart';

class ToggleDealUseCase
    extends UseCase<Deal, ToggleParams<String, Field<Deal, dynamic>>> {
  ToggleDealUseCase(this._repository);

  final DealRepository _repository;

  @override
  Future<Deal> execute(
    ToggleParams<String, Field<Deal, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
