import 'package:zuraffa/zuraffa.dart';

import 'src/di/index.dart' as di;
import 'src/presentation/todo_controller.dart';
import 'src/presentation/todo_presenter.dart';

/// Application bootstrap.
///
/// HAND-WRITTEN (spec 031 US4): wires the CLI-generated DI layer into
/// get_it and builds the hand-written presenter/controller pair.
///
/// `di.setupDependencies` was generated by `zfa make --preset=crud` and
/// registers the datasource, repository, and all seven use cases.
Future<TodoController> setup() async {
  final getIt = GetIt.I;
  di.setupDependencies(getIt);

  final presenter = TodoPresenter(getIt: getIt);
  return TodoController(presenter);
}
