// Spec #972 — the append path for `zfa usecase create` (FR-6,
// stream-append).
//
// When the per-method usecase file already exists, the generator does
// not rewrite it wholesale: the append executor adds the missing
// `execute` member to the existing class. The --json verdict for that
// path is `appended` (the file was modified in place), `skipped` when
// the method is already present, and `created` for a brand-new file.
// Stream methods (watch / watchList) must flow through the same
// machinery as their Future counterparts.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

void main() {
  late Directory workspace;
  late CliRunner runner;

  setUp(() async {
    workspace = await Directory.systemTemp.createTemp('zfa_usecase_app_');
    await File(p.join(workspace.path, 'pubspec.yaml')).writeAsString('''
name: usecase_append_test
environment:
  sdk: ^3.11.0
''');
    runner = CliRunner(exitOnCompletion: false);
    exitCode = 0;
  });

  tearDown(() {
    exitCode = 0;
    if (workspace.existsSync()) {
      try {
        workspace.deleteSync(recursive: true);
      } on PathNotFoundException {
        // Already gone.
      }
    }
  });

  test('an existing class gains the execute method — verdict is appended, '
      'not created', () async {
    await _scaffoldEntity(workspace.path, 'Product');

    // A prior partial generation left the class shell without `execute`.
    final usecaseDir = Directory(
      p.join(workspace.path, 'lib', 'src', 'domain', 'usecases', 'product'),
    );
    await usecaseDir.create(recursive: true);
    await File(
      p.join(usecaseDir.path, 'get_product_usecase.dart'),
    ).writeAsString('''
// Generated by zfa for: Product
import 'package:zuraffa/zuraffa.dart';

class GetProductUseCase extends UseCase<Product, QueryParams<Product>> {
  GetProductUseCase();
}
''');

    final output = await runner.runCapturing([
      '-C',
      workspace.path,
      'usecase',
      'create',
      'Product',
      '--methods=get',
      '--json',
    ]);

    final envelope = jsonDecode(output.trim()) as Map<String, dynamic>;
    final methods = (envelope['methods'] as List).cast<Map<String, dynamic>>();
    expect(methods, hasLength(1));
    expect(methods.single['name'], 'get');
    expect(
      methods.single['action'],
      'appended',
      reason: 'the class existed; execute was appended in place: $methods',
    );

    // The file now carries the execute method AND keeps its class shell.
    final source = await File(
      p.join(usecaseDir.path, 'get_product_usecase.dart'),
    ).readAsString();
    expect(source, contains('class GetProductUseCase'));
    expect(source, contains('Future<Product> execute('));
  });

  test('a stream method (watch) is created on first request and skipped as '
      'already-present on re-run', () async {
    await _scaffoldEntity(workspace.path, 'Stock');

    final first = await runner.runCapturing([
      '-C',
      workspace.path,
      'usecase',
      'create',
      'Stock',
      '--methods=watch',
      '--json',
    ]);
    final firstEnvelope = jsonDecode(first.trim()) as Map<String, dynamic>;
    final firstVerdicts = (firstEnvelope['methods'] as List)
        .cast<Map<String, dynamic>>();
    expect(firstVerdicts, hasLength(1));
    expect(firstVerdicts.single['name'], 'watch');
    expect(firstVerdicts.single['action'], 'created');

    final watchFile = File(
      p.join(
        workspace.path,
        'lib',
        'src',
        'domain',
        'usecases',
        'stock',
        'watch_stock_usecase.dart',
      ),
    );
    expect(watchFile.existsSync(), isTrue);
    final source = await watchFile.readAsString();
    expect(source, contains('StreamUseCase<Stock'));
    expect(source, contains('Stream<Stock> execute('));

    // Re-run: the stream method's execute is already present — honest
    // skip, never a silent re-append.
    final second = await runner.runCapturing([
      '-C',
      workspace.path,
      'usecase',
      'create',
      'Stock',
      '--methods=watch',
      '--json',
    ]);
    final secondEnvelope = jsonDecode(second.trim()) as Map<String, dynamic>;
    final secondVerdicts = (secondEnvelope['methods'] as List)
        .cast<Map<String, dynamic>>();
    expect(secondVerdicts.single['name'], 'watch');
    expect(
      secondVerdicts.single['action'],
      'skipped',
      reason: 'second run must not claim creation: $secondVerdicts',
    );
  });
}

Future<void> _scaffoldEntity(String projectRoot, String entityName) async {
  final snake = _camelToSnake(entityName);
  final dir = Directory(
    p.join(projectRoot, 'lib', 'src', 'domain', 'entities', snake),
  );
  await dir.create(recursive: true);
  await File(p.join(dir.path, '$snake.dart')).writeAsString('''
class $entityName {
  final String id;

  const $entityName({required this.id});
}
''');
}

String _camelToSnake(String input) => input
    .replaceAllMapped(RegExp(r'[A-Z]'), (m) => '_${m.group(0)!.toLowerCase()}')
    .replaceFirst(RegExp(r'^_'), '');
