// GENERATED - DO NOT EDIT
import 'package:zuraffa/zuraffa.dart';

import 'ai_conversation_repository_di.dart';
import 'app_config_repository_di.dart';
import 'app_notification_repository_di.dart';
import 'auth_request_repository_di.dart';
import 'authentication_repository_di.dart';
import 'barcode_listing_repository_di.dart';
import 'barcode_repository_di.dart';
import 'barcode_spark_repository_di.dart';
import 'category_repository_di.dart';
import 'chat_message_repository_di.dart';
import 'chat_session_repository_di.dart';
import 'connected_account_repository_di.dart';
import 'customer_address_repository_di.dart';
import 'customer_repository_di.dart';
import 'deal_repository_di.dart';
import 'device_info_repository_di.dart';
import 'device_repository_di.dart';
import 'dynamic_form_field_repository_di.dart';
import 'dynamic_form_repository_di.dart';
import 'error_log_repository_di.dart';
import 'extracted_invoice_repository_di.dart';
import 'feedback_repository_di.dart';
import 'form_option_repository_di.dart';
import 'form_submission_repository_di.dart';
import 'grocery_item_repository_di.dart';
import 'grocery_price_comparison_repository_di.dart';
import 'grocery_price_result_repository_di.dart';
import 'grocery_product_repository_di.dart';
import 'grocery_store_repository_di.dart';
import 'grocery_sub_variety_repository_di.dart';
import 'listing_offer_repository_di.dart';
import 'listing_repository_di.dart';
import 'locale_repository_di.dart';
import 'metric_detail_repository_di.dart';
import 'nearby_grocery_store_repository_di.dart';
import 'price_alert_repository_di.dart';
import 'price_check_invoice_repository_di.dart';
import 'price_drop_notification_repository_di.dart';
import 'store_price_repository_di.dart';
import 'subscription_repository_di.dart';
import 'telemetry_event_repository_di.dart';
import 'text_listing_repository_di.dart';
import 'text_spark_repository_di.dart';
import 'url_listing_repository_di.dart';
import 'url_spark_repository_di.dart';
import 'user_repository_di.dart';
import 'walkthrough_repository_di.dart';
import 'walkthrough_step_repository_di.dart';
import 'walkthrough_view_repository_di.dart';
import 'zik_zak_config_repository_di.dart';
import 'zik_zak_repository_di.dart';
import 'zik_zak_score_repository_di.dart';

void registerAllRepositories(GetIt getIt) {
  registerAiConversationRepository(getIt);
  registerAppConfigRepository(getIt);
  registerAppNotificationRepository(getIt);
  registerAuthRequestRepository(getIt);
  registerAuthenticationRepository(getIt);
  registerBarcodeListingRepository(getIt);
  registerBarcodeRepository(getIt);
  registerBarcodeSparkRepository(getIt);
  registerCategoryRepository(getIt);
  registerChatMessageRepository(getIt);
  registerChatSessionRepository(getIt);
  registerConnectedAccountRepository(getIt);
  registerCustomerAddressRepository(getIt);
  registerCustomerRepository(getIt);
  registerDealRepository(getIt);
  registerDeviceInfoRepository(getIt);
  registerDeviceRepository(getIt);
  registerDynamicFormFieldRepository(getIt);
  registerDynamicFormRepository(getIt);
  registerErrorLogRepository(getIt);
  registerExtractedInvoiceRepository(getIt);
  registerFeedbackRepository(getIt);
  registerFormOptionRepository(getIt);
  registerFormSubmissionRepository(getIt);
  registerGroceryItemRepository(getIt);
  registerGroceryPriceComparisonRepository(getIt);
  registerGroceryPriceResultRepository(getIt);
  registerGroceryProductRepository(getIt);
  registerGroceryStoreRepository(getIt);
  registerGrocerySubVarietyRepository(getIt);
  registerListingOfferRepository(getIt);
  registerListingRepository(getIt);
  registerLocaleRepository(getIt);
  registerMetricDetailRepository(getIt);
  registerNearbyGroceryStoreRepository(getIt);
  registerPriceAlertRepository(getIt);
  registerPriceCheckInvoiceRepository(getIt);
  registerPriceDropNotificationRepository(getIt);
  registerStorePriceRepository(getIt);
  registerSubscriptionRepository(getIt);
  registerTelemetryEventRepository(getIt);
  registerTextListingRepository(getIt);
  registerTextSparkRepository(getIt);
  registerUrlListingRepository(getIt);
  registerUrlSparkRepository(getIt);
  registerUserRepository(getIt);
  registerWalkthroughRepository(getIt);
  registerWalkthroughStepRepository(getIt);
  registerWalkthroughViewRepository(getIt);
  registerZikZakConfigRepository(getIt);
  registerZikZakRepository(getIt);
  registerZikZakScoreRepository(getIt);
}

// END GENERATED
