// GENERATED - DO NOT EDIT
// Generated by zfa for: Customer
import '../../domain/entities/customer/customer.dart';
import 'customer_address_mock_data.dart';
import 'customer_profile_mock_data.dart';
import 'device_mock_data.dart';
import 'locale_mock_data.dart';

/// Mock data for Customer
class CustomerMockData {
  static final List<Customer> customers = [
    Customer(
      id: 'id 1',
      userId: 'userId 1',
      firstName: 'firstName 1',
      lastName: 'lastName 1',
      email: 'email 1',
      profile: CustomerProfileMockData.sampleCustomerProfile,
      device: DeviceMockData.sampleDevice,
      addresses: [
        CustomerAddressMockData.customerAddresss[1],
        CustomerAddressMockData.customerAddresss[2],
        CustomerAddressMockData.customerAddresss[0],
      ],
      defaultAddressId: 'defaultAddressId 1',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 30)),
      locale: LocaleMockData.sampleLocale,
      isAnonymousAuth: true,
      latitude: 10.5,
      longitude: 10.5,
    ),
    Customer(
      id: 'id 2',
      userId: 'userId 2',
      firstName: 'firstName 2',
      lastName: 'lastName 2',
      email: 'email 2',
      profile: CustomerProfileMockData.sampleCustomerProfile,
      device: DeviceMockData.sampleDevice,
      addresses: [
        CustomerAddressMockData.customerAddresss[2],
        CustomerAddressMockData.customerAddresss[0],
        CustomerAddressMockData.customerAddresss[1],
      ],
      defaultAddressId: 'defaultAddressId 2',
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
      updatedAt: DateTime.now().subtract(const Duration(days: 60)),
      locale: LocaleMockData.sampleLocale,
      isAnonymousAuth: false,
      latitude: 21.0,
      longitude: 21.0,
    ),
    Customer(
      id: 'id 3',
      userId: 'userId 3',
      firstName: null,
      lastName: null,
      email: null,
      profile: null,
      device: null,
      addresses: null,
      defaultAddressId: null,
      createdAt: null,
      updatedAt: null,
      locale: null,
      isAnonymousAuth: null,
      latitude: null,
      longitude: null,
    ),
  ];

  static Customer get sampleCustomer => customers.first;

  static List<Customer> get sampleList => customers;

  static List<Customer> get emptyList => <Customer>[];

  static List<Customer> get largeCustomerList =>
      List.generate(100, (index) => _createCustomer(index + 1000));

  static Customer _createCustomer(int seed) {
    return Customer(
      id: 'id $seed',
      userId: 'userId $seed',
      firstName: seed % 3 == 0 ? null : 'firstName $seed',
      lastName: seed % 3 == 0 ? null : 'lastName $seed',
      email: seed % 3 == 0 ? null : 'email $seed',
      profile: seed % 3 == 0
          ? null
          : CustomerProfileMockData.sampleCustomerProfile,
      device: seed % 3 == 0 ? null : DeviceMockData.sampleDevice,
      addresses: seed % 3 == 0
          ? null
          : [
              CustomerAddressMockData.customerAddresss[seed % 3],
              CustomerAddressMockData.customerAddresss[seed + 1 % 3],
              CustomerAddressMockData.customerAddresss[seed + 2 % 3],
            ],
      defaultAddressId: seed % 3 == 0 ? null : 'defaultAddressId $seed',
      createdAt: seed % 3 == 0
          ? null
          : DateTime.now().subtract(Duration(days: seed * 30)),
      updatedAt: seed % 3 == 0
          ? null
          : DateTime.now().subtract(Duration(days: seed * 30)),
      locale: seed % 3 == 0 ? null : LocaleMockData.sampleLocale,
      isAnonymousAuth: seed % 3 == 0 ? null : seed % 2 == 1,
      latitude: seed % 3 == 0 ? null : seed * 10.5,
      longitude: seed % 3 == 0 ? null : seed * 10.5,
    );
  }
}

// END GENERATED
