// GENERATED - DO NOT EDIT
// Generated by zfa for: Deal
import '../../domain/entities/deal/deal.dart';
import 'listing_mock_data.dart';

/// Mock data for Deal
class DealMockData {
  static final List<Deal> deals = [
    Deal(
      id: 'id 1',
      listing: ListingMockData.sampleListing,
      badges: ['item 2', 'item 3', 'item 4'],
      discountRate: 10.5,
      likeCount: 1,
      dislikeCount: 1,
      shareCount: 1,
      manLikeCount: 1,
      womanLikeCount: 1,
      manDislikeCount: 1,
      womanDislikeCount: 1,
      ratingScore: 10.5,
      reviewCount: 1,
      aiReasoning: 'aiReasoning 1',
    ),
    Deal(
      id: 'id 2',
      listing: ListingMockData.sampleListing,
      badges: ['item 3', 'item 4', 'item 5'],
      discountRate: 21.0,
      likeCount: 2,
      dislikeCount: 2,
      shareCount: 2,
      manLikeCount: 2,
      womanLikeCount: 2,
      manDislikeCount: 2,
      womanDislikeCount: 2,
      ratingScore: 21.0,
      reviewCount: 2,
      aiReasoning: 'aiReasoning 2',
    ),
    Deal(
      id: 'id 3',
      listing: ListingMockData.sampleListing,
      badges: null,
      discountRate: null,
      likeCount: 3,
      dislikeCount: 3,
      shareCount: 3,
      manLikeCount: 3,
      womanLikeCount: 3,
      manDislikeCount: 3,
      womanDislikeCount: 3,
      ratingScore: null,
      reviewCount: null,
      aiReasoning: null,
    ),
  ];

  static Deal get sampleDeal => deals.first;

  static List<Deal> get sampleList => deals;

  static List<Deal> get emptyList => <Deal>[];

  static List<Deal> get largeDealList =>
      List.generate(100, (index) => _createDeal(index + 1000));

  static Deal _createDeal(int seed) {
    return Deal(
      id: 'id $seed',
      listing: ListingMockData.sampleListing,
      badges: seed % 3 == 0 ? null : ['item $seed', 'item $seed'],
      discountRate: seed % 3 == 0 ? null : seed * 10.5,
      likeCount: seed * 10,
      dislikeCount: seed * 10,
      shareCount: seed * 10,
      manLikeCount: seed * 10,
      womanLikeCount: seed * 10,
      manDislikeCount: seed * 10,
      womanDislikeCount: seed * 10,
      ratingScore: seed % 3 == 0 ? null : seed * 10.5,
      reviewCount: seed % 3 == 0 ? null : seed * 10,
      aiReasoning: seed % 3 == 0 ? null : 'aiReasoning $seed',
    );
  }
}

// END GENERATED
