// GENERATED - DO NOT EDIT
// Generated by zfa for: DeviceInfo
import '../../domain/entities/device_info/device_info.dart';
import '../../domain/entities/enums/index.dart';

/// Mock data for DeviceInfo
class DeviceInfoMockData {
  static final List<DeviceInfo> deviceInfos = [
    DeviceInfo(
      systemName: 'systemName 1',
      deviceModel: 'deviceModel 1',
      systemVersion: 'systemVersion 1',
      deviceId: 'deviceId 1',
      brand: 'brand 1',
      manufacturer: 'manufacturer 1',
      isPhysicalDevice: true,
      additionalProperties: {
        'key1 2': 'value1 1',
        'key2 3': 'value2 2',
        'key3 4': 'value3 3',
      },
      os: OperatingSystem.values[1 % OperatingSystem.values.length],
    ),
    DeviceInfo(
      systemName: 'systemName 2',
      deviceModel: 'deviceModel 2',
      systemVersion: 'systemVersion 2',
      deviceId: 'deviceId 2',
      brand: 'brand 2',
      manufacturer: 'manufacturer 2',
      isPhysicalDevice: false,
      additionalProperties: {
        'key1 3': 'value1 2',
        'key2 4': 'value2 3',
        'key3 5': 'value3 4',
      },
      os: OperatingSystem.values[2 % OperatingSystem.values.length],
    ),
    DeviceInfo(
      systemName: null,
      deviceModel: null,
      systemVersion: null,
      deviceId: null,
      brand: null,
      manufacturer: null,
      isPhysicalDevice: null,
      additionalProperties: null,
      os: OperatingSystem.values[3 % OperatingSystem.values.length],
    ),
  ];

  static DeviceInfo get sampleDeviceInfo => deviceInfos.first;

  static List<DeviceInfo> get sampleList => deviceInfos;

  static List<DeviceInfo> get emptyList => <DeviceInfo>[];

  static List<DeviceInfo> get largeDeviceInfoList =>
      List.generate(100, (index) => _createDeviceInfo(index + 1000));

  static DeviceInfo _createDeviceInfo(int seed) {
    return DeviceInfo(
      systemName: seed % 3 == 0 ? null : 'systemName $seed',
      deviceModel: seed % 3 == 0 ? null : 'deviceModel $seed',
      systemVersion: seed % 3 == 0 ? null : 'systemVersion $seed',
      deviceId: seed % 3 == 0 ? null : 'deviceId $seed',
      brand: seed % 3 == 0 ? null : 'brand $seed',
      manufacturer: seed % 3 == 0 ? null : 'manufacturer $seed',
      isPhysicalDevice: seed % 3 == 0 ? null : seed % 2 == 1,
      additionalProperties: seed % 3 == 0
          ? null
          : {'key $seed': 'value $seed', 'key2 $seed': 'value2 $seed'},
      os: OperatingSystem.values[seed % OperatingSystem.values.length],
    );
  }
}

// END GENERATED
