// GENERATED - DO NOT EDIT
// Generated by zfa for: ExtractedInvoice
import '../../domain/entities/extracted_invoice/extracted_invoice.dart';

/// Mock data for ExtractedInvoice
class ExtractedInvoiceMockData {
  static final List<ExtractedInvoice> extractedInvoices = [
    ExtractedInvoice(
      id: 'id 1',
      storeName: 'storeName 1',
      total: 10.5,
      currencyCode: 'currencyCode 1',
      items: ['item 2', 'item 3', 'item 4'],
      purchaseDate: DateTime.now().subtract(const Duration(days: 30)),
    ),
    ExtractedInvoice(
      id: 'id 2',
      storeName: 'storeName 2',
      total: 21.0,
      currencyCode: 'currencyCode 2',
      items: ['item 3', 'item 4', 'item 5'],
      purchaseDate: DateTime.now().subtract(const Duration(days: 60)),
    ),
    ExtractedInvoice(
      id: null,
      storeName: null,
      total: null,
      currencyCode: null,
      items: null,
      purchaseDate: null,
    ),
  ];

  static ExtractedInvoice get sampleExtractedInvoice => extractedInvoices.first;

  static List<ExtractedInvoice> get sampleList => extractedInvoices;

  static List<ExtractedInvoice> get emptyList => <ExtractedInvoice>[];

  static List<ExtractedInvoice> get largeExtractedInvoiceList =>
      List.generate(100, (index) => _createExtractedInvoice(index + 1000));

  static ExtractedInvoice _createExtractedInvoice(int seed) {
    return ExtractedInvoice(
      id: seed % 3 == 0 ? null : 'id $seed',
      storeName: seed % 3 == 0 ? null : 'storeName $seed',
      total: seed % 3 == 0 ? null : seed * 10.5,
      currencyCode: seed % 3 == 0 ? null : 'currencyCode $seed',
      items: seed % 3 == 0 ? null : ['item $seed', 'item $seed'],
      purchaseDate: seed % 3 == 0
          ? null
          : DateTime.now().subtract(Duration(days: seed * 30)),
    );
  }
}

// END GENERATED
