// GENERATED - DO NOT EDIT
// Generated by zfa for: Feedback
import '../../domain/entities/enums/index.dart';
import '../../domain/entities/feedback/feedback.dart';

/// Mock data for Feedback
class FeedbackMockData {
  static final List<Feedback> feedbacks = [
    Feedback(
      id: 'id 1',
      message: 'message 1',
      type: FeedbackType.values[1 % FeedbackType.values.length],
      imageUrl: 'imageUrl 1',
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    Feedback(
      id: 'id 2',
      message: 'message 2',
      type: FeedbackType.values[2 % FeedbackType.values.length],
      imageUrl: 'imageUrl 2',
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    Feedback(
      id: null,
      message: 'message 3',
      type: FeedbackType.values[3 % FeedbackType.values.length],
      imageUrl: null,
      createdAt: null,
    ),
  ];

  static Feedback get sampleFeedback => feedbacks.first;

  static List<Feedback> get sampleList => feedbacks;

  static List<Feedback> get emptyList => <Feedback>[];

  static List<Feedback> get largeFeedbackList =>
      List.generate(100, (index) => _createFeedback(index + 1000));

  static Feedback _createFeedback(int seed) {
    return Feedback(
      id: seed % 3 == 0 ? null : 'id $seed',
      message: 'message $seed',
      type: FeedbackType.values[seed % FeedbackType.values.length],
      imageUrl: seed % 3 == 0 ? null : 'imageUrl $seed',
      createdAt: seed % 3 == 0
          ? null
          : DateTime.now().subtract(Duration(days: seed * 30)),
    );
  }
}

// END GENERATED
