// GENERATED - DO NOT EDIT
// Generated by zfa for: ListingOffer
import '../../domain/entities/listing_offer/listing_offer.dart';

/// Mock data for ListingOffer
class ListingOfferMockData {
  static final List<ListingOffer> listingOffers = [
    ListingOffer(
      id: 'id 1',
      code: 'code 1',
      price: 10.5,
      originalPrice: 10.5,
      unitPrice: 10.5,
      unitPriceText: 'unitPriceText 1',
      url: 'url 1',
      website: 'website 1',
      seller: 'seller 1',
      sellerId: 'sellerId 1',
      title: 'title 1',
      sellerScore: 10.5,
      availability: 'availability 1',
      shippingCost: 10.5,
      shippingInfo: 'shippingInfo 1',
      sellerIcon: 'sellerIcon 1',
      badges: ['item 2', 'item 3', 'item 4'],
      brand: 'brand 1',
      sku: 'sku 1',
      imageUrl: 'imageUrl 1',
      images: ['item 2', 'item 3', 'item 4'],
      ratingScore: 10.5,
      reviewCount: 1,
      productId: 'productId 1',
    ),
    ListingOffer(
      id: 'id 2',
      code: 'code 2',
      price: 21.0,
      originalPrice: 21.0,
      unitPrice: 21.0,
      unitPriceText: 'unitPriceText 2',
      url: 'url 2',
      website: 'website 2',
      seller: 'seller 2',
      sellerId: 'sellerId 2',
      title: 'title 2',
      sellerScore: 21.0,
      availability: 'availability 2',
      shippingCost: 21.0,
      shippingInfo: 'shippingInfo 2',
      sellerIcon: 'sellerIcon 2',
      badges: ['item 3', 'item 4', 'item 5'],
      brand: 'brand 2',
      sku: 'sku 2',
      imageUrl: 'imageUrl 2',
      images: ['item 3', 'item 4', 'item 5'],
      ratingScore: 21.0,
      reviewCount: 2,
      productId: 'productId 2',
    ),
    ListingOffer(
      id: null,
      code: null,
      price: null,
      originalPrice: null,
      unitPrice: null,
      unitPriceText: null,
      url: null,
      website: null,
      seller: null,
      sellerId: null,
      title: null,
      sellerScore: null,
      availability: null,
      shippingCost: null,
      shippingInfo: null,
      sellerIcon: null,
      badges: null,
      brand: null,
      sku: null,
      imageUrl: null,
      images: null,
      ratingScore: null,
      reviewCount: null,
      productId: null,
    ),
  ];

  static ListingOffer get sampleListingOffer => listingOffers.first;

  static List<ListingOffer> get sampleList => listingOffers;

  static List<ListingOffer> get emptyList => <ListingOffer>[];

  static List<ListingOffer> get largeListingOfferList =>
      List.generate(100, (index) => _createListingOffer(index + 1000));

  static ListingOffer _createListingOffer(int seed) {
    return ListingOffer(
      id: seed % 3 == 0 ? null : 'id $seed',
      code: seed % 3 == 0 ? null : 'code $seed',
      price: seed % 3 == 0 ? null : seed * 10.5,
      originalPrice: seed % 3 == 0 ? null : seed * 10.5,
      unitPrice: seed % 3 == 0 ? null : seed * 10.5,
      unitPriceText: seed % 3 == 0 ? null : 'unitPriceText $seed',
      url: seed % 3 == 0 ? null : 'url $seed',
      website: seed % 3 == 0 ? null : 'website $seed',
      seller: seed % 3 == 0 ? null : 'seller $seed',
      sellerId: seed % 3 == 0 ? null : 'sellerId $seed',
      title: seed % 3 == 0 ? null : 'title $seed',
      sellerScore: seed % 3 == 0 ? null : seed * 10.5,
      availability: seed % 3 == 0 ? null : 'availability $seed',
      shippingCost: seed % 3 == 0 ? null : seed * 10.5,
      shippingInfo: seed % 3 == 0 ? null : 'shippingInfo $seed',
      sellerIcon: seed % 3 == 0 ? null : 'sellerIcon $seed',
      badges: seed % 3 == 0 ? null : ['item $seed', 'item $seed'],
      brand: seed % 3 == 0 ? null : 'brand $seed',
      sku: seed % 3 == 0 ? null : 'sku $seed',
      imageUrl: seed % 3 == 0 ? null : 'imageUrl $seed',
      images: seed % 3 == 0 ? null : ['item $seed', 'item $seed'],
      ratingScore: seed % 3 == 0 ? null : seed * 10.5,
      reviewCount: seed % 3 == 0 ? null : seed * 10,
      productId: seed % 3 == 0 ? null : 'productId $seed',
    );
  }
}

// END GENERATED
