// GENERATED - DO NOT EDIT
// Generated by zfa for: Locale
import '../../domain/entities/locale/locale.dart';

/// Mock data for Locale
class LocaleMockData {
  static final List<Locale> locales = [
    Locale(
      id: 'id 1',
      languageCode: 'languageCode 1',
      countryCode: 'countryCode 1',
    ),
    Locale(
      id: 'id 2',
      languageCode: 'languageCode 2',
      countryCode: 'countryCode 2',
    ),
    Locale(
      id: 'id 3',
      languageCode: 'languageCode 3',
      countryCode: 'countryCode 3',
    ),
  ];

  static Locale get sampleLocale => locales.first;

  static List<Locale> get sampleList => locales;

  static List<Locale> get emptyList => <Locale>[];

  static List<Locale> get largeLocaleList =>
      List.generate(100, (index) => _createLocale(index + 1000));

  static Locale _createLocale(int seed) {
    return Locale(
      id: 'id $seed',
      languageCode: 'languageCode $seed',
      countryCode: 'countryCode $seed',
    );
  }
}

// END GENERATED
