// GENERATED - DO NOT EDIT
// Generated by zfa for: TelemetryEvent
import '../../domain/entities/enums/index.dart';
import '../../domain/entities/telemetry_event/telemetry_event.dart';

/// Mock data for TelemetryEvent
class TelemetryEventMockData {
  static final List<TelemetryEvent> telemetryEvents = [
    TelemetryEvent(
      id: 'id 1',
      type: TelemetryEventType.values[1 % TelemetryEventType.values.length],
      value: 'value 1',
      context: {
        'key1 2': 'value1 1',
        'key2 3': 'value2 2',
        'key3 4': 'value3 3',
      },
    ),
    TelemetryEvent(
      id: 'id 2',
      type: TelemetryEventType.values[2 % TelemetryEventType.values.length],
      value: 'value 2',
      context: {
        'key1 3': 'value1 2',
        'key2 4': 'value2 3',
        'key3 5': 'value3 4',
      },
    ),
    TelemetryEvent(
      id: 'id 3',
      type: TelemetryEventType.values[3 % TelemetryEventType.values.length],
      value: 'value 3',
      context: null,
    ),
  ];

  static TelemetryEvent get sampleTelemetryEvent => telemetryEvents.first;

  static List<TelemetryEvent> get sampleList => telemetryEvents;

  static List<TelemetryEvent> get emptyList => <TelemetryEvent>[];

  static List<TelemetryEvent> get largeTelemetryEventList =>
      List.generate(100, (index) => _createTelemetryEvent(index + 1000));

  static TelemetryEvent _createTelemetryEvent(int seed) {
    return TelemetryEvent(
      id: 'id $seed',
      type: TelemetryEventType.values[seed % TelemetryEventType.values.length],
      value: 'value $seed',
      context: seed % 3 == 0
          ? null
          : {'key $seed': 'value $seed', 'key2 $seed': 'value2 $seed'},
    );
  }
}

// END GENERATED
