// GENERATED - DO NOT EDIT
// Generated by zfa for: TextListing
import '../../domain/entities/text_listing/text_listing.dart';

/// Mock data for TextListing
class TextListingMockData {
  static final List<TextListing> textListings = [
    TextListing(id: 'id 1', title: 'title 1', search: 'search 1'),
    TextListing(id: 'id 2', title: 'title 2', search: 'search 2'),
    TextListing(id: 'id 3', title: 'title 3', search: 'search 3'),
  ];

  static TextListing get sampleTextListing => textListings.first;

  static List<TextListing> get sampleList => textListings;

  static List<TextListing> get emptyList => <TextListing>[];

  static List<TextListing> get largeTextListingList =>
      List.generate(100, (index) => _createTextListing(index + 1000));

  static TextListing _createTextListing(int seed) {
    return TextListing(
      id: 'id $seed',
      title: 'title $seed',
      search: 'search $seed',
    );
  }
}

// END GENERATED
