// GENERATED - DO NOT EDIT
// Generated by zfa for: WalkthroughStep
import '../../domain/entities/walkthrough_step/walkthrough_step.dart';

/// Mock data for WalkthroughStep
class WalkthroughStepMockData {
  static final List<WalkthroughStep> walkthroughSteps = [
    WalkthroughStep(
      id: 'id 1',
      title: 'title 1',
      description: 'description 1',
      imagePath: 'imagePath 1',
      iconPath: 'iconPath 1',
      order: 1,
      buttonText: 'buttonText 1',
      targetWidget: 'targetWidget 1',
    ),
    WalkthroughStep(
      id: 'id 2',
      title: 'title 2',
      description: 'description 2',
      imagePath: 'imagePath 2',
      iconPath: 'iconPath 2',
      order: 2,
      buttonText: 'buttonText 2',
      targetWidget: 'targetWidget 2',
    ),
    WalkthroughStep(
      id: 'id 3',
      title: 'title 3',
      description: 'description 3',
      imagePath: null,
      iconPath: null,
      order: 3,
      buttonText: null,
      targetWidget: null,
    ),
  ];

  static WalkthroughStep get sampleWalkthroughStep => walkthroughSteps.first;

  static List<WalkthroughStep> get sampleList => walkthroughSteps;

  static List<WalkthroughStep> get emptyList => <WalkthroughStep>[];

  static List<WalkthroughStep> get largeWalkthroughStepList =>
      List.generate(100, (index) => _createWalkthroughStep(index + 1000));

  static WalkthroughStep _createWalkthroughStep(int seed) {
    return WalkthroughStep(
      id: 'id $seed',
      title: 'title $seed',
      description: 'description $seed',
      imagePath: seed % 3 == 0 ? null : 'imagePath $seed',
      iconPath: seed % 3 == 0 ? null : 'iconPath $seed',
      order: seed * 10,
      buttonText: seed % 3 == 0 ? null : 'buttonText $seed',
      targetWidget: seed % 3 == 0 ? null : 'targetWidget $seed',
    );
  }
}

// END GENERATED
