// GENERATED - DO NOT EDIT
// Generated by zfa for: ZikZak
import '../../domain/entities/enums/index.dart';
import '../../domain/entities/zik_zak/zik_zak.dart';
import 'listing_mock_data.dart';
import 'text_spark_mock_data.dart';

/// Mock data for ZikZak
class ZikZakMockData {
  static final List<ZikZak> zikZaks = [
    ZikZak(
      id: 'id 1',
      spark: TextSparkMockData.sampleTextSpark,
      listing: ListingMockData.sampleListing,
      origin: ZikZakOrigin.values[1 % ZikZakOrigin.values.length],
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
    ),
    ZikZak(
      id: 'id 2',
      spark: TextSparkMockData.sampleTextSpark,
      listing: ListingMockData.sampleListing,
      origin: ZikZakOrigin.values[2 % ZikZakOrigin.values.length],
      createdAt: DateTime.now().subtract(const Duration(days: 60)),
    ),
    ZikZak(
      id: 'id 3',
      spark: TextSparkMockData.sampleTextSpark,
      listing: ListingMockData.sampleListing,
      origin: ZikZakOrigin.values[3 % ZikZakOrigin.values.length],
      createdAt: DateTime.now().subtract(const Duration(days: 90)),
    ),
  ];

  static ZikZak get sampleZikZak => zikZaks.first;

  static List<ZikZak> get sampleList => zikZaks;

  static List<ZikZak> get emptyList => <ZikZak>[];

  static List<ZikZak> get largeZikZakList =>
      List.generate(100, (index) => _createZikZak(index + 1000));

  static ZikZak _createZikZak(int seed) {
    return ZikZak(
      id: 'id $seed',
      spark: TextSparkMockData.sampleTextSpark,
      listing: ListingMockData.sampleListing,
      origin: ZikZakOrigin.values[seed % ZikZakOrigin.values.length],
      createdAt: DateTime.now().subtract(Duration(days: seed * 30)),
    );
  }
}

// END GENERATED
