import 'package:dart_style/dart_style.dart';
import 'package:test/test.dart';
import 'package:zuraffa/src/plugins/mcp/builders/mcp_scaffold_builder.dart';

void main() {
  group('McpScaffoldBuilder', () {
    final builder = McpScaffoldBuilder();

    group('buildToolsFile()', () {
      test('emits the Generated-by-zfa stamp on the first line', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        expect(src.split('\n').first, '// Generated by zfa');
      });

      test('imports package:zuraffa/zuraffa.dart', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        expect(src, contains("import 'package:zuraffa/zuraffa.dart';"));
      });

      test('declares an EchoTool class implementing McpTool', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        expect(src, contains('class EchoTool implements McpTool'));
      });

      test('declares the mcpTools getter returning a List<McpTool>', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        expect(src, contains('List<McpTool> get mcpTools'));
        // DartFormatter may strip the trailing comma for single-element
        // lists — match `EchoTool()` (without trailing comma) instead.
        expect(src, contains('EchoTool()'));
      });

      test('the placeholder tool name is "echo"', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        expect(src, contains("return 'echo';"));
      });

      test(
        'the placeholder tool inputSchema declares the message property',
        () {
          final src = builder.buildToolsFile(appName: 'mcp_demo');
          expect(src, contains("'message'"));
          expect(src, contains("'required': ['message']"));
        },
      );
    });

    group('buildBinServer()', () {
      test('emits the Generated-by-zfa stamp on the first line', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src.split('\n').first, '// Generated by zfa');
      });

      test('imports package:zuraffa/zuraffa.dart', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src, contains("import 'package:zuraffa/zuraffa.dart';"));
      });

      test(
        'imports the app\'s tools.dart via package:<app>/src/mcp/tools.dart',
        () {
          final src = builder.buildBinServer(appName: 'mcp_demo');
          expect(
            src,
            contains("import 'package:mcp_demo/src/mcp/tools.dart';"),
          );
        },
      );

      test('registers McpServerPlugin with the mcpTools list', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src, contains('McpServerPlugin(tools: mcpTools)'));
      });

      test('boots the engine + bootstraps', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src, contains('ZuraffaEngine()..register(mcp)'));
        expect(src, contains('await engine.bootstrap()'));
      });

      test('dispatches --sse vs stdio based on args', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src, contains("args.contains('--sse')"));
        expect(src, contains('mcp.serveSse('));
        expect(src, contains('mcp.serveStdio()'));
      });

      test('supports --list-tools for zfa mcp list-tools', () {
        final src = builder.buildBinServer(appName: 'mcp_demo');
        expect(src, contains("args.contains('--list-tools')"));
        expect(src, contains("'tools'"));
      });

      test('outputDir=lib maps to package:<app>/mcp/tools.dart import', () {
        final src = builder.buildBinServer(appName: 'my_app', outputDir: 'lib');
        expect(src, contains("import 'package:my_app/mcp/tools.dart';"));
      });

      test(
        'outputDir=lib/src maps to package:<app>/src/mcp/tools.dart import',
        () {
          final src = builder.buildBinServer(
            appName: 'my_app',
            outputDir: 'lib/src',
          );
          expect(src, contains("import 'package:my_app/src/mcp/tools.dart';"));
        },
      );

      test(
        'outputDir with a trailing slash still yields a single separator',
        () {
          final src = builder.buildBinServer(
            appName: 'my_app',
            outputDir: 'lib/src/',
          );
          expect(src, contains("import 'package:my_app/src/mcp/tools.dart';"));
          expect(src, isNot(contains('src//mcp/tools.dart')));
        },
      );

      test('buildBinServer output formats cleanly (valid Dart syntax)', () {
        // buildBinServer() suppresses formatter errors internally, so
        // explicitly format its returned string rather than relying on
        // the builder's internal handling.
        final src = builder.buildBinServer(appName: 'mcp_demo');
        final formatted = DartFormatter(
          languageVersion: DartFormatter.latestLanguageVersion,
        ).format(src);
        expect(formatted, isNotEmpty);
      });

      test('buildToolsFile output formats cleanly (valid Dart syntax)', () {
        final src = builder.buildToolsFile(appName: 'mcp_demo');
        final formatted = DartFormatter(
          languageVersion: DartFormatter.latestLanguageVersion,
        ).format(src);
        expect(formatted, isNotEmpty);
      });
    });
  });
}
