// GENERATED - DO NOT EDIT
import 'package:zuraffa/zuraffa.dart';

import 'get_ai_conversation_usecase_di.dart';
import 'get_app_config_usecase_di.dart';
import 'get_app_notification_usecase_di.dart';
import 'get_auth_request_usecase_di.dart';
import 'get_authentication_usecase_di.dart';
import 'get_barcode_listing_usecase_di.dart';
import 'get_barcode_spark_usecase_di.dart';
import 'get_barcode_usecase_di.dart';
import 'get_category_usecase_di.dart';
import 'get_chat_message_usecase_di.dart';
import 'get_chat_session_usecase_di.dart';
import 'get_connected_account_usecase_di.dart';
import 'get_customer_address_usecase_di.dart';
import 'get_customer_usecase_di.dart';
import 'get_deal_usecase_di.dart';
import 'get_device_info_usecase_di.dart';
import 'get_device_usecase_di.dart';
import 'get_dynamic_form_field_usecase_di.dart';
import 'get_dynamic_form_usecase_di.dart';
import 'get_error_log_usecase_di.dart';
import 'get_extracted_invoice_usecase_di.dart';
import 'get_feedback_usecase_di.dart';
import 'get_form_option_usecase_di.dart';
import 'get_form_submission_usecase_di.dart';
import 'get_grocery_item_usecase_di.dart';
import 'get_grocery_price_comparison_usecase_di.dart';
import 'get_grocery_price_result_usecase_di.dart';
import 'get_grocery_product_usecase_di.dart';
import 'get_grocery_store_usecase_di.dart';
import 'get_grocery_sub_variety_usecase_di.dart';
import 'get_listing_offer_usecase_di.dart';
import 'get_listing_usecase_di.dart';
import 'get_locale_usecase_di.dart';
import 'get_metric_detail_usecase_di.dart';
import 'get_nearby_grocery_store_usecase_di.dart';
import 'get_price_alert_usecase_di.dart';
import 'get_price_check_invoice_usecase_di.dart';
import 'get_price_drop_notification_usecase_di.dart';
import 'get_store_price_usecase_di.dart';
import 'get_subscription_usecase_di.dart';
import 'get_telemetry_event_usecase_di.dart';
import 'get_text_listing_usecase_di.dart';
import 'get_text_spark_usecase_di.dart';
import 'get_url_listing_usecase_di.dart';
import 'get_url_spark_usecase_di.dart';
import 'get_user_usecase_di.dart';
import 'get_walkthrough_step_usecase_di.dart';
import 'get_walkthrough_usecase_di.dart';
import 'get_walkthrough_view_usecase_di.dart';
import 'get_zik_zak_config_usecase_di.dart';
import 'get_zik_zak_score_usecase_di.dart';
import 'get_zik_zak_usecase_di.dart';
import 'toggle_ai_conversation_usecase_di.dart';
import 'toggle_app_config_usecase_di.dart';
import 'toggle_app_notification_usecase_di.dart';
import 'toggle_auth_request_usecase_di.dart';
import 'toggle_authentication_usecase_di.dart';
import 'toggle_barcode_listing_usecase_di.dart';
import 'toggle_barcode_spark_usecase_di.dart';
import 'toggle_barcode_usecase_di.dart';
import 'toggle_category_usecase_di.dart';
import 'toggle_chat_message_usecase_di.dart';
import 'toggle_chat_session_usecase_di.dart';
import 'toggle_connected_account_usecase_di.dart';
import 'toggle_customer_address_usecase_di.dart';
import 'toggle_customer_usecase_di.dart';
import 'toggle_deal_usecase_di.dart';
import 'toggle_device_info_usecase_di.dart';
import 'toggle_device_usecase_di.dart';
import 'toggle_dynamic_form_field_usecase_di.dart';
import 'toggle_dynamic_form_usecase_di.dart';
import 'toggle_error_log_usecase_di.dart';
import 'toggle_extracted_invoice_usecase_di.dart';
import 'toggle_feedback_usecase_di.dart';
import 'toggle_form_option_usecase_di.dart';
import 'toggle_form_submission_usecase_di.dart';
import 'toggle_grocery_item_usecase_di.dart';
import 'toggle_grocery_price_comparison_usecase_di.dart';
import 'toggle_grocery_price_result_usecase_di.dart';
import 'toggle_grocery_product_usecase_di.dart';
import 'toggle_grocery_store_usecase_di.dart';
import 'toggle_grocery_sub_variety_usecase_di.dart';
import 'toggle_listing_offer_usecase_di.dart';
import 'toggle_listing_usecase_di.dart';
import 'toggle_locale_usecase_di.dart';
import 'toggle_metric_detail_usecase_di.dart';
import 'toggle_nearby_grocery_store_usecase_di.dart';
import 'toggle_price_alert_usecase_di.dart';
import 'toggle_price_check_invoice_usecase_di.dart';
import 'toggle_price_drop_notification_usecase_di.dart';
import 'toggle_store_price_usecase_di.dart';
import 'toggle_subscription_usecase_di.dart';
import 'toggle_telemetry_event_usecase_di.dart';
import 'toggle_text_listing_usecase_di.dart';
import 'toggle_text_spark_usecase_di.dart';
import 'toggle_url_listing_usecase_di.dart';
import 'toggle_url_spark_usecase_di.dart';
import 'toggle_user_usecase_di.dart';
import 'toggle_walkthrough_step_usecase_di.dart';
import 'toggle_walkthrough_usecase_di.dart';
import 'toggle_walkthrough_view_usecase_di.dart';
import 'toggle_zik_zak_config_usecase_di.dart';
import 'toggle_zik_zak_score_usecase_di.dart';
import 'toggle_zik_zak_usecase_di.dart';
import 'update_ai_conversation_usecase_di.dart';
import 'update_app_config_usecase_di.dart';
import 'update_app_notification_usecase_di.dart';
import 'update_auth_request_usecase_di.dart';
import 'update_authentication_usecase_di.dart';
import 'update_barcode_listing_usecase_di.dart';
import 'update_barcode_spark_usecase_di.dart';
import 'update_barcode_usecase_di.dart';
import 'update_category_usecase_di.dart';
import 'update_chat_message_usecase_di.dart';
import 'update_chat_session_usecase_di.dart';
import 'update_connected_account_usecase_di.dart';
import 'update_customer_address_usecase_di.dart';
import 'update_customer_usecase_di.dart';
import 'update_deal_usecase_di.dart';
import 'update_device_info_usecase_di.dart';
import 'update_device_usecase_di.dart';
import 'update_dynamic_form_field_usecase_di.dart';
import 'update_dynamic_form_usecase_di.dart';
import 'update_error_log_usecase_di.dart';
import 'update_extracted_invoice_usecase_di.dart';
import 'update_feedback_usecase_di.dart';
import 'update_form_option_usecase_di.dart';
import 'update_form_submission_usecase_di.dart';
import 'update_grocery_item_usecase_di.dart';
import 'update_grocery_price_comparison_usecase_di.dart';
import 'update_grocery_price_result_usecase_di.dart';
import 'update_grocery_product_usecase_di.dart';
import 'update_grocery_store_usecase_di.dart';
import 'update_grocery_sub_variety_usecase_di.dart';
import 'update_listing_offer_usecase_di.dart';
import 'update_listing_usecase_di.dart';
import 'update_locale_usecase_di.dart';
import 'update_metric_detail_usecase_di.dart';
import 'update_nearby_grocery_store_usecase_di.dart';
import 'update_price_alert_usecase_di.dart';
import 'update_price_check_invoice_usecase_di.dart';
import 'update_price_drop_notification_usecase_di.dart';
import 'update_store_price_usecase_di.dart';
import 'update_subscription_usecase_di.dart';
import 'update_telemetry_event_usecase_di.dart';
import 'update_text_listing_usecase_di.dart';
import 'update_text_spark_usecase_di.dart';
import 'update_url_listing_usecase_di.dart';
import 'update_url_spark_usecase_di.dart';
import 'update_user_usecase_di.dart';
import 'update_walkthrough_step_usecase_di.dart';
import 'update_walkthrough_usecase_di.dart';
import 'update_walkthrough_view_usecase_di.dart';
import 'update_zik_zak_config_usecase_di.dart';
import 'update_zik_zak_score_usecase_di.dart';
import 'update_zik_zak_usecase_di.dart';

void registerAllUseCases(GetIt getIt) {
  registerGetAiConversationUseCase(getIt);
  registerGetAppConfigUseCase(getIt);
  registerGetAppNotificationUseCase(getIt);
  registerGetAuthRequestUseCase(getIt);
  registerGetAuthenticationUseCase(getIt);
  registerGetBarcodeListingUseCase(getIt);
  registerGetBarcodeSparkUseCase(getIt);
  registerGetBarcodeUseCase(getIt);
  registerGetCategoryUseCase(getIt);
  registerGetChatMessageUseCase(getIt);
  registerGetChatSessionUseCase(getIt);
  registerGetConnectedAccountUseCase(getIt);
  registerGetCustomerAddressUseCase(getIt);
  registerGetCustomerUseCase(getIt);
  registerGetDealUseCase(getIt);
  registerGetDeviceInfoUseCase(getIt);
  registerGetDeviceUseCase(getIt);
  registerGetDynamicFormFieldUseCase(getIt);
  registerGetDynamicFormUseCase(getIt);
  registerGetErrorLogUseCase(getIt);
  registerGetExtractedInvoiceUseCase(getIt);
  registerGetFeedbackUseCase(getIt);
  registerGetFormOptionUseCase(getIt);
  registerGetFormSubmissionUseCase(getIt);
  registerGetGroceryItemUseCase(getIt);
  registerGetGroceryPriceComparisonUseCase(getIt);
  registerGetGroceryPriceResultUseCase(getIt);
  registerGetGroceryProductUseCase(getIt);
  registerGetGroceryStoreUseCase(getIt);
  registerGetGrocerySubVarietyUseCase(getIt);
  registerGetListingOfferUseCase(getIt);
  registerGetListingUseCase(getIt);
  registerGetLocaleUseCase(getIt);
  registerGetMetricDetailUseCase(getIt);
  registerGetNearbyGroceryStoreUseCase(getIt);
  registerGetPriceAlertUseCase(getIt);
  registerGetPriceCheckInvoiceUseCase(getIt);
  registerGetPriceDropNotificationUseCase(getIt);
  registerGetStorePriceUseCase(getIt);
  registerGetSubscriptionUseCase(getIt);
  registerGetTelemetryEventUseCase(getIt);
  registerGetTextListingUseCase(getIt);
  registerGetTextSparkUseCase(getIt);
  registerGetUrlListingUseCase(getIt);
  registerGetUrlSparkUseCase(getIt);
  registerGetUserUseCase(getIt);
  registerGetWalkthroughStepUseCase(getIt);
  registerGetWalkthroughUseCase(getIt);
  registerGetWalkthroughViewUseCase(getIt);
  registerGetZikZakConfigUseCase(getIt);
  registerGetZikZakScoreUseCase(getIt);
  registerGetZikZakUseCase(getIt);
  registerToggleAiConversationUseCase(getIt);
  registerToggleAppConfigUseCase(getIt);
  registerToggleAppNotificationUseCase(getIt);
  registerToggleAuthRequestUseCase(getIt);
  registerToggleAuthenticationUseCase(getIt);
  registerToggleBarcodeListingUseCase(getIt);
  registerToggleBarcodeSparkUseCase(getIt);
  registerToggleBarcodeUseCase(getIt);
  registerToggleCategoryUseCase(getIt);
  registerToggleChatMessageUseCase(getIt);
  registerToggleChatSessionUseCase(getIt);
  registerToggleConnectedAccountUseCase(getIt);
  registerToggleCustomerAddressUseCase(getIt);
  registerToggleCustomerUseCase(getIt);
  registerToggleDealUseCase(getIt);
  registerToggleDeviceInfoUseCase(getIt);
  registerToggleDeviceUseCase(getIt);
  registerToggleDynamicFormFieldUseCase(getIt);
  registerToggleDynamicFormUseCase(getIt);
  registerToggleErrorLogUseCase(getIt);
  registerToggleExtractedInvoiceUseCase(getIt);
  registerToggleFeedbackUseCase(getIt);
  registerToggleFormOptionUseCase(getIt);
  registerToggleFormSubmissionUseCase(getIt);
  registerToggleGroceryItemUseCase(getIt);
  registerToggleGroceryPriceComparisonUseCase(getIt);
  registerToggleGroceryPriceResultUseCase(getIt);
  registerToggleGroceryProductUseCase(getIt);
  registerToggleGroceryStoreUseCase(getIt);
  registerToggleGrocerySubVarietyUseCase(getIt);
  registerToggleListingOfferUseCase(getIt);
  registerToggleListingUseCase(getIt);
  registerToggleLocaleUseCase(getIt);
  registerToggleMetricDetailUseCase(getIt);
  registerToggleNearbyGroceryStoreUseCase(getIt);
  registerTogglePriceAlertUseCase(getIt);
  registerTogglePriceCheckInvoiceUseCase(getIt);
  registerTogglePriceDropNotificationUseCase(getIt);
  registerToggleStorePriceUseCase(getIt);
  registerToggleSubscriptionUseCase(getIt);
  registerToggleTelemetryEventUseCase(getIt);
  registerToggleTextListingUseCase(getIt);
  registerToggleTextSparkUseCase(getIt);
  registerToggleUrlListingUseCase(getIt);
  registerToggleUrlSparkUseCase(getIt);
  registerToggleUserUseCase(getIt);
  registerToggleWalkthroughStepUseCase(getIt);
  registerToggleWalkthroughUseCase(getIt);
  registerToggleWalkthroughViewUseCase(getIt);
  registerToggleZikZakConfigUseCase(getIt);
  registerToggleZikZakScoreUseCase(getIt);
  registerToggleZikZakUseCase(getIt);
  registerUpdateAiConversationUseCase(getIt);
  registerUpdateAppConfigUseCase(getIt);
  registerUpdateAppNotificationUseCase(getIt);
  registerUpdateAuthRequestUseCase(getIt);
  registerUpdateAuthenticationUseCase(getIt);
  registerUpdateBarcodeListingUseCase(getIt);
  registerUpdateBarcodeSparkUseCase(getIt);
  registerUpdateBarcodeUseCase(getIt);
  registerUpdateCategoryUseCase(getIt);
  registerUpdateChatMessageUseCase(getIt);
  registerUpdateChatSessionUseCase(getIt);
  registerUpdateConnectedAccountUseCase(getIt);
  registerUpdateCustomerAddressUseCase(getIt);
  registerUpdateCustomerUseCase(getIt);
  registerUpdateDealUseCase(getIt);
  registerUpdateDeviceInfoUseCase(getIt);
  registerUpdateDeviceUseCase(getIt);
  registerUpdateDynamicFormFieldUseCase(getIt);
  registerUpdateDynamicFormUseCase(getIt);
  registerUpdateErrorLogUseCase(getIt);
  registerUpdateExtractedInvoiceUseCase(getIt);
  registerUpdateFeedbackUseCase(getIt);
  registerUpdateFormOptionUseCase(getIt);
  registerUpdateFormSubmissionUseCase(getIt);
  registerUpdateGroceryItemUseCase(getIt);
  registerUpdateGroceryPriceComparisonUseCase(getIt);
  registerUpdateGroceryPriceResultUseCase(getIt);
  registerUpdateGroceryProductUseCase(getIt);
  registerUpdateGroceryStoreUseCase(getIt);
  registerUpdateGrocerySubVarietyUseCase(getIt);
  registerUpdateListingOfferUseCase(getIt);
  registerUpdateListingUseCase(getIt);
  registerUpdateLocaleUseCase(getIt);
  registerUpdateMetricDetailUseCase(getIt);
  registerUpdateNearbyGroceryStoreUseCase(getIt);
  registerUpdatePriceAlertUseCase(getIt);
  registerUpdatePriceCheckInvoiceUseCase(getIt);
  registerUpdatePriceDropNotificationUseCase(getIt);
  registerUpdateStorePriceUseCase(getIt);
  registerUpdateSubscriptionUseCase(getIt);
  registerUpdateTelemetryEventUseCase(getIt);
  registerUpdateTextListingUseCase(getIt);
  registerUpdateTextSparkUseCase(getIt);
  registerUpdateUrlListingUseCase(getIt);
  registerUpdateUrlSparkUseCase(getIt);
  registerUpdateUserUseCase(getIt);
  registerUpdateWalkthroughStepUseCase(getIt);
  registerUpdateWalkthroughUseCase(getIt);
  registerUpdateWalkthroughViewUseCase(getIt);
  registerUpdateZikZakConfigUseCase(getIt);
  registerUpdateZikZakScoreUseCase(getIt);
  registerUpdateZikZakUseCase(getIt);
}

// END GENERATED
