// GENERATED - DO NOT EDIT
// Generated by zfa for: Note
// zfa make Note --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/note/note.dart';

abstract class NoteRepository {
  Future<Note> get(QueryParams<Note> params);
  Future<Note> update(UpdateParams<String, NotePatch> params);
  Future<Note> toggle(ToggleParams<String, Field<Note, dynamic>> params);
}

// END GENERATED
