// GENERATED - DO NOT EDIT
// Generated by zfa for: DynamicFormField
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/dynamic_form_field/dynamic_form_field.dart';
import '../../repositories/dynamic_form_field_repository.dart';

class GetDynamicFormFieldUseCase
    extends UseCase<DynamicFormField, QueryParams<DynamicFormField>> {
  GetDynamicFormFieldUseCase(this._repository);

  final DynamicFormFieldRepository _repository;

  @override
  Future<DynamicFormField> execute(
    QueryParams<DynamicFormField> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
