// Generated by zfa
// zfa generate Todo --methods=get,watch,create,update,delete,getList,watchList --state

import 'package:zuraffa/zuraffa.dart';
import '../../../domain/entities/todo/todo.dart';

/// Immutable state for Todo
class TodoState {
  /// The current error, if any
  final AppFailure? error;

  /// The list of Todo entities
  final List<Todo> todoList;

  /// The single Todo entity
  final Todo? todo;

  /// Whether get operation is in progress
  final bool isGetting;

  /// Whether watch operation is in progress
  final bool isWatching;

  /// Whether create operation is in progress
  final bool isCreating;

  /// Whether update operation is in progress
  final bool isUpdating;

  /// Whether delete operation is in progress
  final bool isDeleting;

  /// Whether getList operation is in progress
  final bool isGettingList;

  /// Whether watchList operation is in progress
  final bool isWatchingList;

  const TodoState({
    this.error,
    this.todoList = const [],
    this.todo,
    this.isGetting = false,
    this.isWatching = false,
    this.isCreating = false,
    this.isUpdating = false,
    this.isDeleting = false,
    this.isGettingList = false,
    this.isWatchingList = false,
  });

  /// Create a copy of this state with the given fields replaced.
  TodoState copyWith({
    AppFailure? error,
    bool clearError = false,
    List<Todo>? todoList,
    Todo? todo,
    bool? isGetting,
    bool? isWatching,
    bool? isCreating,
    bool? isUpdating,
    bool? isDeleting,
    bool? isGettingList,
    bool? isWatchingList,
  }) {
    return TodoState(
      todoList: todoList ?? this.todoList,
      todo: todo ?? this.todo,
      error: clearError ? null : (error ?? this.error),
      isGetting: isGetting ?? this.isGetting,
      isWatching: isWatching ?? this.isWatching,
      isCreating: isCreating ?? this.isCreating,
      isUpdating: isUpdating ?? this.isUpdating,
      isDeleting: isDeleting ?? this.isDeleting,
      isGettingList: isGettingList ?? this.isGettingList,
      isWatchingList: isWatchingList ?? this.isWatchingList,
    );
  }

  /// Whether any operation is currently loading
  bool get isLoading =>
      isGetting ||
      isWatching ||
      isCreating ||
      isUpdating ||
      isDeleting ||
      isGettingList ||
      isWatchingList;

  /// Whether there is an error to display
  bool get hasError => error != null;

  /// Number of active (non-completed) todos
  int get activeCount => todoList.where((t) => !t.isCompleted).length;

  /// Number of completed todos
  int get completedCount => todoList.where((t) => t.isCompleted).length;

  /// Whether the list has any todos
  bool get hasTodos => todoList.isNotEmpty;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is TodoState &&
          runtimeType == other.runtimeType &&
          todoList == other.todoList &&
          todo == other.todo &&
          error == other.error &&
          isGetting == other.isGetting &&
          isWatching == other.isWatching &&
          isCreating == other.isCreating &&
          isUpdating == other.isUpdating &&
          isDeleting == other.isDeleting &&
          isGettingList == other.isGettingList &&
          isWatchingList == other.isWatchingList);

  @override
  int get hashCode =>
      todoList.hashCode ^
      todo.hashCode ^
      error.hashCode ^
      isGetting.hashCode ^
      isWatching.hashCode ^
      isCreating.hashCode ^
      isUpdating.hashCode ^
      isDeleting.hashCode ^
      isGettingList.hashCode ^
      isWatchingList.hashCode;

  @override
  String toString() =>
      'TodoState(todoList: ${todoList.length}, todo: $todo, isLoading: $isLoading, error: $error)';
}
