// Generated by zfa
// zfa generate Todo --methods=get,getList,create,update,delete,watch --vpc

import 'package:zuraffa/zuraffa.dart';
import '../../../domain/entities/todo/todo.dart';
import '../../../domain/repositories/todo_repository.dart';
import '../../../domain/usecases/todo/get_todo_usecase.dart';
import '../../../domain/usecases/todo/get_todo_list_usecase.dart';
import '../../../domain/usecases/todo/create_todo_usecase.dart';
import '../../../domain/usecases/todo/update_todo_usecase.dart';
import '../../../domain/usecases/todo/delete_todo_usecase.dart';
import '../../../domain/usecases/todo/watch_todo_usecase.dart';

class TodoPresenter extends Presenter {
  final TodoRepository todoRepository;

  late final GetTodoUseCase _getTodo;
  late final GetTodoListUseCase _getTodoList;
  late final CreateTodoUseCase _createTodo;
  late final UpdateTodoUseCase _updateTodo;
  late final DeleteTodoUseCase _deleteTodo;
  late final WatchTodoUseCase _watchTodo;

  TodoPresenter({
    required this.todoRepository,
  }) {
    _getTodo = registerUseCase(GetTodoUseCase(todoRepository));
    _getTodoList = registerUseCase(GetTodoListUseCase(todoRepository));
    _createTodo = registerUseCase(CreateTodoUseCase(todoRepository));
    _updateTodo = registerUseCase(UpdateTodoUseCase(todoRepository));
    _deleteTodo = registerUseCase(DeleteTodoUseCase(todoRepository));
    _watchTodo = registerUseCase(WatchTodoUseCase(todoRepository));
  }

  Future<Result<Todo, AppFailure>> getTodo(String id) {
    return _getTodo.call(QueryParams(id));
  }

  Future<Result<List<Todo>, AppFailure>> getTodoList([ListQueryParams params = const ListQueryParams()]) {
    return _getTodoList.call(params);
  }

  Future<Result<Todo, AppFailure>> createTodo(Todo todo) {
    return _createTodo.call(todo);
  }

  Future<Result<Todo, AppFailure>> updateTodo(String id, Partial<Todo> data) {
    return _updateTodo.call(UpdateParams(id: id, data: data));
  }

  Future<Result<void, AppFailure>> deleteTodo(String id) {
    return _deleteTodo.call(DeleteParams(id));
  }

  Stream<Result<Todo, AppFailure>> watchTodo(String? id) {
    return _watchTodo.call(QueryParams(id));
  }
}
