// Generated by zfa — X-Ray Control Deck registration barrel.
// This file is maintained by `zfa xray deck`. Each invocation
// appends a `register<Entity>XRayDeck()` call below. Safe to
// edit manually — `zfa xray deck` preserves existing calls.
import 'package:flutter/foundation.dart';

void registerAllXRayDecks() {
  if (kReleaseMode) return;
  // Registration calls are appended here by `zfa xray deck`.
  // Each `zfa xray deck --entity <Entity>` invocation adds a
  // `register<Entity>XRayDeck();` call below.
}
