/// Persistence test harness — Hive CE temp-box lifecycle, test clock,
/// corruption drills and the registrar gate (bug #833).
///
/// Specs 005 (caching), 089 (offline mode), 091, 092 and all cached
/// entities need real Hive CE behavior under test: TTL expiry, box
/// corruption, registrar failures. This harness gives every Hive-touching
/// test — generated by `zfa tdd gen` for a persistence-kind behavior or
/// hand-written against a cached entity — the same four pieces:
///
///   1. **Temp-box lifecycle** ([PersistenceTestHarness.bootstrap] /
///      [PersistenceTestHarness.teardown]): a fresh temp-directory box set
///      per test, closed + deleted per test, never shared.
///   2. **Test clock** ([TestClock.advanceTime]): TTL assertions advance
///      the clock virtually — no real sleeps in the suite.
///   3. **Corruption drills** ([PersistenceTestHarness.seedCorruptedBox] +
///      [PersistenceTestHarness.openWithRecovery]): a pre-corrupted box
///      fixture opens through the recovery path (clear + re-fetch per the
///      spec edge cases) and never touches data outside the temp box.
///   4. **Registrar gate** ([RegistrarGateError]): init-time adapter
///      registration failures surface deterministically from `bootstrap()`
///      — a red at init, never a runtime read crash (spec 005 US3-AC3).
///
/// ## Usage inside a test
///
/// ```dart
/// final harness = PersistenceTestHarness(
///   boxNames: ['listings'],
///   registerAdapters: () => Hive.registerAdapter(ListingAdapter()),
///   expectedTypeIds: {kListingTypeId},
/// );
///
/// setUp(() => harness.bootstrap());
/// tearDown(() => harness.teardown());
/// ```
library;

import 'dart:io';
import 'dart:math';

import 'package:hive_ce/hive_ce.dart';
import 'package:path/path.dart' as p;

/// Injectable clock for persistence assertions (bug #833, remediation 2).
///
/// TTL expiry is asserted virtually: [advanceTime] moves the clock forward
/// without the wall clock moving, so a 24-hour TTL costs microseconds, not
/// 24 hours — no real sleeps in the suite. The clock is an instance the
/// owning test controls; advancing it never affects anything else.
///
/// The class is callable (`DateTime Function()`), so it plugs directly into
/// every API that accepts a clock source, e.g. `TtlCachePolicy(clock: ...)`.
class TestClock {
  TestClock([DateTime? start]) : _now = start ?? DateTime.now();

  DateTime _now;

  /// The current (virtual) time.
  DateTime get now => _now;

  /// Move the clock forward by [duration] — virtually, never by sleeping.
  void advanceTime(Duration duration) => _now = _now.add(duration);

  /// The clock as a plain `DateTime` source.
  DateTime call() => _now;
}

/// Raised by [PersistenceTestHarness.bootstrap] when the init-time adapter
/// registration fails (bug #833, remediation 4 — the registrar gate).
///
/// A broken registrar (a thrown registration, a duplicate typeId, a missing
/// adapter) surfaces HERE — deterministically, at init — instead of as a
/// runtime read crash in the middle of a test body (spec 005 US3-AC3).
class RegistrarGateError extends Error {
  RegistrarGateError(this.message);

  final String message;

  @override
  String toString() => 'RegistrarGateError: $message';
}

/// Raised by [PersistenceTestHarness.openWithRecovery] when the corruption
/// drill's recovery contract is violated (bug #833, remediation 3).
class CorruptionDrillFailure extends Error {
  CorruptionDrillFailure(this.message);

  final String message;

  @override
  String toString() => 'CorruptionDrillFailure: $message';
}

/// Per-test Hive CE temp-box harness (bug #833, remediation 1).
///
/// Call [bootstrap] from the test's `setUp` and [teardown] from its
/// `tearDown`: every test gets a FRESH temp-directory box set and every
/// test's boxes are closed and deleted afterwards — the lifecycle is
/// per-test, never shared.
///
/// The harness also carries the corruption drill ([seedCorruptedBox] +
/// [openWithRecovery]) and the registrar gate ([registerAdapters] /
/// [expectedTypeIds] checked inside [bootstrap]).
class PersistenceTestHarness {
  PersistenceTestHarness({
    required this.boxNames,
    this.registerAdapters,
    this.expectedTypeIds = const <int>{},
  }) : assert(boxNames.isNotEmpty, 'the box set cannot be empty');

  /// The box names opened by [bootstrap] (lowercased by Hive internally).
  final List<String> boxNames;

  /// Init-time adapter registration, run INSIDE the registrar gate.
  ///
  /// Anything thrown here is rethrown as [RegistrarGateError] — a
  /// deterministic red at init, never a runtime read crash.
  final void Function()? registerAdapters;

  /// Adapter typeIds that MUST be registered for [bootstrap] to pass.
  ///
  /// A missing adapter surfaces as [RegistrarGateError] at init instead of
  /// as an `Unknown`-type read crash on the first entity read.
  final Set<int> expectedTypeIds;

  Directory? _tempDir;
  final Set<String> _openBoxNames = <String>{};

  /// Whether [bootstrap] ran for the current lifecycle.
  bool get isBootstrapped => _tempDir != null;

  /// The per-test temp directory backing the box set.
  Directory get tempDir {
    final dir = _tempDir;
    if (dir == null) {
      throw StateError(
        'persistence harness is not bootstrapped — call '
        'bootstrap() from the test setUp first',
      );
    }
    return dir;
  }

  /// Fresh temp directory + registrar gate + box set. Call from `setUp`.
  Future<void> bootstrap() async {
    if (_tempDir != null) {
      throw StateError(
        'persistence harness bootstrapped twice — the temp-box lifecycle '
        'is per-test; use one bootstrap per setUp and teardown per tearDown',
      );
    }
    final dir = await Directory.systemTemp.createTemp('zfa_persistence_');
    _tempDir = dir;
    // Hive resolves box files relative to the home directory set here; the
    // whole box set lives inside the per-test temp dir.
    Hive.init(dir.path);

    // ── Registrar gate (bug #833, remediation 4) ────────────────────────
    // Init-time registration failure => deterministic red HERE.
    if (registerAdapters != null) {
      try {
        registerAdapters!();
      } catch (error) {
        await _abortBootstrap(dir);
        throw RegistrarGateError(
          'init-time adapter registration failed: $error',
        );
      }
    }
    for (final typeId in expectedTypeIds) {
      if (!Hive.isAdapterRegistered(typeId)) {
        await _abortBootstrap(dir);
        throw RegistrarGateError(
          'no adapter registered for typeId $typeId at init time — the '
          'registrar gate refuses to open boxes that would crash on read',
        );
      }
    }

    for (final name in boxNames) {
      await Hive.openBox(name.toLowerCase());
      _openBoxNames.add(name.toLowerCase());
    }
  }

  /// Close the box set and destroy the temp directory. Call from
  /// `tearDown`.
  Future<void> teardown() async {
    final dir = _tempDir;
    if (dir == null) return;
    _resetLifecycle();
    await Hive.close();
    if (dir.existsSync()) {
      await dir.delete(recursive: true);
    }
  }

  /// The open box [name] from the per-test set.
  Box<E> box<E>(String name) {
    final key = name.toLowerCase();
    if (!_openBoxNames.contains(key)) {
      throw StateError(
        'box "$name" is not part of this harness box set ($boxNames) or the '
        'harness is not bootstrapped',
      );
    }
    return Hive.box<E>(key);
  }

  /// The path of [name]'s box file INSIDE the per-test temp directory.
  String boxPath(String name) =>
      p.join(tempDir.path, '${name.toLowerCase()}.hive');

  /// Seed a PRE-CORRUPTED box fixture for [name] inside the temp directory
  /// (bug #833, remediation 3).
  ///
  /// The box must be closed when called — corrupting a live box behind
  /// Hive's back is a shared-state bug, not a drill. The bytes are garbage
  /// Hive cannot parse as a frame header, so the subsequent open goes
  /// through the recovery path.
  void seedCorruptedBox(String name, {List<int>? bytes}) {
    final key = name.toLowerCase();
    if (Hive.isBoxOpen(key)) {
      throw StateError(
        'refusing to corrupt box "$name" while it is open — close it first',
      );
    }
    File(boxPath(key)).writeAsBytesSync(bytes ?? _garbageFrameBytes());
  }

  /// The corruption drill: open [name]'s pre-corrupted fixture through the
  /// recovery path (clear + re-fetch) and return the recovered, EMPTY box.
  ///
  /// Contract (spec 005 edge cases):
  ///   - the pre-corrupted fixture must exist inside the temp box;
  ///   - opening detects the corruption — Hive's crash recovery drops the
  ///     unreadable frames (or the open throws outright), and the drill
  ///     clears the fixture and reopens when the open refuses;
  ///   - the recovered box must be EMPTY — the caller re-fetches from the
  ///     source through the adapter;
  ///   - nothing outside the temp box is touched.
  ///
  /// Violations surface as [CorruptionDrillFailure] — a deterministic red.
  Future<Box<E>> openWithRecovery<E>(String name) async {
    final key = name.toLowerCase();
    final file = File(boxPath(key));
    if (!file.existsSync()) {
      throw CorruptionDrillFailure(
        'no pre-corrupted fixture for box "$name" — seed it with '
        'seedCorruptedBox("$name") before drilling',
      );
    }
    Box<E> box;
    try {
      box = await Hive.openBox<E>(key);
    } catch (error) {
      // The open refused the corruption outright — clear + re-fetch.
      await file.delete();
      box = await Hive.openBox<E>(key);
    }
    if (box.length != 0) {
      throw CorruptionDrillFailure(
        'recovery for box "$name" left ${box.length} frame(s) readable — '
        'the corrupted fixture must recover to an empty box (clear + '
        're-fetch), not partially decoded data',
      );
    }
    return box;
  }

  void _resetLifecycle() {
    _tempDir = null;
    _openBoxNames.clear();
  }

  /// A failed bootstrap owns the temp dir it just created — destroy it so
  /// the gate never leaks a directory behind the failing test.
  Future<void> _abortBootstrap(Directory dir) async {
    _resetLifecycle();
    await Hive.close();
    if (dir.existsSync()) {
      await dir.delete(recursive: true);
    }
  }

  /// Bytes that never form a valid Hive frame: a random-looking tail after
  /// a truncated header. Deterministic (fixed seed) so drills reproduce.
  static List<int> _garbageFrameBytes() {
    final rng = Random(833);
    return List<int>.generate(64, (_) => rng.nextInt(256));
  }
}
