// Spec 077 / issue #1109 — DI idempotency, executably (T008b, behaviors
// A4/A5/A6, U5/U6/U12).
//
// The structural #1102 tests (di_idempotent_test.dart) prove the emitted
// SOURCE carries unregister-first guards and resetDependencies. This suite
// goes one level deeper — the bar issue #1109 actually sets: it COMPILES
// the generated DI wiring inside a self-contained pure-Dart fixture
// package and EXECUTES it, proving that
//   (a) setupDependencies() is callable twice in the same process without
//       throwing ("LoginUseCase is already registered inside GetIt" was
//       the #1080 pilot killer), and
//   (b) resetDependencies() then setupDependencies() re-establishes every
//       registration and all types resolve.
//
// Fast-tier-safe pattern (repository_compile_test.dart): one temp package
// with a path dependency on this repo, `dart pub get` once, then
// `dart run` a driver that prints a machine envelope the test asserts on.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/core/generator_options.dart';
import 'package:zuraffa/src/models/generator_config.dart';
import 'package:zuraffa/src/plugins/di/di_plugin.dart';

import '../../helpers/project_root.dart';

void main() {
  late Directory projectRoot;
  late String repoRoot;

  setUpAll(() async {
    repoRoot = await findProjectRoot();
    projectRoot = await Directory.systemTemp.createTemp('zfa_di_exec_');

    await File(p.join(projectRoot.path, 'pubspec.yaml')).writeAsString('''
name: di_setup_execution_fixture
publish_to: none
environment:
  sdk: ^3.11.0
dependencies:
  zuraffa:
    path: $repoRoot
  get_it: ^9.2.1
''');

    // Hand-written data layer mirroring the generated shapes the DI
    // wiring imports (entity, datasource interface + remote impl,
    // repository interface + data impl).
    final libSrc = p.join(projectRoot.path, 'lib', 'src');
    await _write(
      p.join(libSrc, 'domain', 'entities', 'product', 'product.dart'),
      'class Product {\n'
      '  final String id;\n'
      '  const Product({required this.id});\n'
      '}\n',
    );
    await _write(
      p.join(libSrc, 'domain', 'repositories', 'product_repository.dart'),
      "import '../entities/product/product.dart';\n"
      'abstract class ProductRepository {\n'
      '  Future<Product?> get(String id) async => null;\n'
      '}\n',
    );
    await _write(
      p.join(
        libSrc,
        'data',
        'datasources',
        'product',
        'product_datasource.dart',
      ),
      "import '../../../domain/entities/product/product.dart';\n"
      'abstract class ProductDataSource {\n'
      '  Future<Product?> get(String id) async => null;\n'
      '}\n',
    );
    await _write(
      p.join(
        libSrc,
        'data',
        'datasources',
        'product',
        'product_remote_datasource.dart',
      ),
      "import '../../../domain/entities/product/product.dart';\n"
      "import 'product_datasource.dart';\n"
      'class ProductRemoteDataSource implements ProductDataSource {\n'
      '  const ProductRemoteDataSource();\n'
      '  @override\n'
      '  Future<Product?> get(String id) async => null;\n'
      '}\n',
    );
    await _write(
      p.join(libSrc, 'data', 'repositories', 'data_product_repository.dart'),
      "import '../../domain/entities/product/product.dart';\n"
      "import '../../domain/repositories/product_repository.dart';\n"
      "import '../datasources/product/product_datasource.dart';\n"
      'class DataProductRepository implements ProductRepository {\n'
      '  final ProductDataSource dataSource;\n'
      '  DataProductRepository(this.dataSource);\n'
      '  @override\n'
      '  Future<Product?> get(String id) async => dataSource.get(id);\n'
      '}\n',
    );

    // The system under test: the DI wiring generated by DiPlugin.
    await DiPlugin(
      outputDir: libSrc,
      options: const GeneratorOptions(dryRun: false, force: true),
    ).generate(
      GeneratorConfig(
        name: 'Product',
        methods: const ['get'],
        generateData: true,
        generateDi: true,
        generateDataSource: true,
        generateRepository: true,
        outputDir: libSrc,
      ),
    );

    // The executable driver: proves setup-twice and reset→setup never
    // throw and leave every type resolvable.
    await _write(p.join(projectRoot.path, 'tool', 'setup_driver.dart'), '''
import 'package:get_it/get_it.dart';
import 'package:di_setup_execution_fixture/src/data/datasources/product/product_remote_datasource.dart';
import 'package:di_setup_execution_fixture/src/domain/repositories/product_repository.dart';
import 'package:di_setup_execution_fixture/src/di/index.dart';

Future<void> main() async {
  final getIt = GetIt.instance;

  // (a) setupDependencies() twice in one process: unregister-first must
  // make the second call a no-throw replacement.
  setupDependencies(getIt);
  setupDependencies(getIt);

  // (b) resetDependencies() then setupDependencies(): teardown + rebuild
  // must leave every registration resolvable.
  resetDependencies(getIt);
  setupDependencies(getIt);

  // Throws StateError when a registration is missing — the resolvability
  // assert for both the datasource and the repository wiring.
  getIt<ProductRepository>();
  getIt<ProductRemoteDataSource>();
  print('SETUP_DRIVER_OK');
}
''');

    final pub = await Process.run('dart', [
      'pub',
      'get',
      '--no-example',
    ], workingDirectory: projectRoot.path);
    expect(
      pub.exitCode,
      0,
      reason:
          'dart pub get must succeed in the DI execution fixture.\n'
          '${pub.stdout}\n${pub.stderr}',
    );
  });

  tearDownAll(() async {
    if (projectRoot.existsSync()) {
      try {
        await projectRoot.delete(recursive: true);
      } on PathNotFoundException {
        // Already gone.
      }
    }
  });

  test('generated setupDependencies is callable twice, and reset→setup '
      're-establishes every registration (executable proof)', () async {
    final result = await Process.run('dart', [
      'run',
      'tool/setup_driver.dart',
    ], workingDirectory: projectRoot.path);
    final output = '${result.stdout}${result.stderr}';

    expect(
      result.exitCode,
      0,
      reason:
          'the generated DI wiring must execute without "already '
          'registered" failures. Output:\n$output',
    );
    expect(
      output,
      contains('SETUP_DRIVER_OK'),
      reason: 'driver envelope missing — run did not reach the asserts',
    );
    expect(
      output,
      isNot(contains('already registered')),
      reason:
          'get_it "already registered" must never fire (issue #1080 '
          'pilot killer)',
    );
  }, timeout: const Timeout(Duration(minutes: 4)));

  test('the generated DI files pass dart analyze (compile bar)', () async {
    final result = await Process.run('dart', [
      'analyze',
      '--no-fatal-warnings',
      'lib',
    ], workingDirectory: projectRoot.path);
    expect(
      result.exitCode,
      0,
      reason:
          'generated DI wiring must analyze clean.\n'
          '${result.stdout}\n${result.stderr}',
    );
  }, timeout: const Timeout(Duration(minutes: 4)));
}

Future<void> _write(String path, String content) async {
  final file = File(path);
  await file.parent.create(recursive: true);
  await file.writeAsString(content);
}
