// GENERATED - DO NOT EDIT
// Generated by zfa for: StorePrice
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/store_price/store_price.dart';
import '../../mock/store_price_mock_data.dart';
import 'store_price_datasource.dart';

/// Mock data source for StorePrice
class StorePriceMockDataSource
    with Loggable, FailureHandler
    implements StorePriceDataSource {
  StorePriceMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<StorePrice> get(QueryParams<StorePrice> params) async {
    logger.info('Getting StorePrice with params: $params');
    await Future.delayed(_delay);
    final item = StorePriceMockData.storePrices.query(params);
    logger.info('Successfully retrieved StorePrice');
    return item;
  }

  @override
  Future<StorePrice> update(
    UpdateParams<String, StorePricePatch> params,
  ) async {
    logger.info('Updating StorePrice: ${params.id}');
    await Future.delayed(_delay);
    final existing = StorePriceMockData.sampleStorePrice;
    logger.info('Successfully updated StorePrice');
    return existing;
  }

  @override
  Future<StorePrice> toggle(
    ToggleParams<String, Field<StorePrice, dynamic>> params,
  ) async {
    logger.info('Toggling StorePrice: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = StorePriceMockData.sampleStorePrice;
    logger.info('Successfully toggled StorePrice');
    return existing;
  }
}

// END GENERATED
