// GENERATED - DO NOT EDIT
// Generated by zfa for: ZikZak
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/zik_zak/zik_zak.dart';
import '../../repositories/zik_zak_repository.dart';

class GetZikZakUseCase extends UseCase<ZikZak, QueryParams<ZikZak>> {
  GetZikZakUseCase(this._repository);

  final ZikZakRepository _repository;

  @override
  Future<ZikZak> execute(
    QueryParams<ZikZak> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
