// Auto-generated by Zorphy
// Generated at: 2026-08-14T10:19:24.145208

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';
import '../enums/index.dart';

part 'form_submission.zorphy.dart';
part 'form_submission.g.dart';

/// FormSubmission entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $FormSubmission {
  String get id;
  String get templateId;
  Map<String, dynamic> get inputValues;
  FormSubmissionStatus get status;
}
