/// The mock failure preset builder (spec 1110, issue #1110): the
/// `<Entity>FailingMockProvider`.
///
/// `zfa mock create <Entity> --fail` generates a throwing double beside
/// the succeeding mock artifacts: a class implementing the entity's
/// `<Entity>DataSource` interface whose EVERY method throws the
/// framework's sealed failure type (`ServerFailure`, an `AppFailure`
/// subtype). This is the framework feature that replaces the pilot's
/// hand-written `_FailingAuthService` (005-login-engine) — the
/// failure-path twin of the certified mock, so a cycle can target a
/// failure-path behavior without hand-rolling the double.
///
/// The generated file lands next to the mock datasource (the engine-tree
/// injection seam) at
/// `<outputDir>/data/datasources/<snake>/<snake>_failing_mock_provider.dart`.
library;

import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;

import '../../../core/builder/shared/spec_library.dart';
import '../../../core/context/file_system.dart';
import '../../../core/generator_options.dart';
import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/entity_utils.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';

class FailingMockProviderBuilder {
  final String outputDir;
  final GeneratorOptions options;
  final SpecLibrary specLibrary;
  final FileSystem fileSystem;

  FailingMockProviderBuilder({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    SpecLibrary? specLibrary,
    FileSystem? fileSystem,
  }) : specLibrary = specLibrary ?? const SpecLibrary(),
       fileSystem = fileSystem ?? FileSystem.create();

  /// The failing provider class name for [entityName].
  static String className(String entityName) =>
      '${entityName}FailingMockProvider';

  /// The failing provider path under [outputDir].
  static String failingProviderPath(String entityName, String outputDir) {
    final snake = StringUtils.camelToSnake(entityName);
    return path.join(
      outputDir,
      'data',
      'datasources',
      snake,
      '${snake}_failing_mock_provider.dart',
    );
  }

  /// Generates the failing provider for [config] (entity mode). The
  /// method set mirrors the mock datasource generation: every method in
  /// [GeneratorConfig.methods] is emitted with the interface's exact
  /// signature and a throwing body.
  Future<GeneratedFile> generateFailingMockProvider(
    GeneratorConfig config,
  ) async {
    final entityName = config.repo != null
        ? config.repo!.replaceAll('Repository', '')
        : config.name;
    final entitySnake = StringUtils.camelToSnake(entityName);
    final filePath = failingProviderPath(entityName, outputDir);

    // Issue #942 parity: hide exactly the entity's own symbols when the
    // zuraffa barrel exports colliding names, so the entity's local
    // definitions win resolution (the same contract the mock datasource
    // import applies).
    final barrelHide = <String>{
      if (config.isEntityBased) ...EntityUtils.barrelHideNames(entityName),
    }.toList();

    final directives = [
      // Canonical zuraffa-native mock marker + the sealed failure
      // hierarchy (ServerFailure ⊂ AppFailure) and the params family.
      Directive.import('package:zuraffa/mock.dart', hide: barrelHide),
      if (config.isEntityBased)
        Directive.import(
          '../../../domain/entities/$entitySnake/$entitySnake.dart',
        ),
      Directive.import('${entitySnake}_datasource.dart'),
    ];

    final methods = <Method>[];
    for (final method in config.methods) {
      final failing = _failingMethod(entityName, config, method);
      if (failing != null) methods.add(failing);
    }

    final clazz = Class(
      (c) => c
        ..name = className(entityName)
        ..docs.addAll([
          '/// Spec 1110 failure preset: every method throws the sealed',
          '/// failure type — a throwing double for failure-path behaviors.',
          '/// Generated by `zfa mock create $entityName --fail`; the',
          '/// succeeding mock (`${entityName}MockDataSource`) is certified',
          '/// separately via `zfa mock create $entityName --certify`.',
        ])
        ..implements.add(refer('${entityName}DataSource'))
        ..methods.addAll(methods),
    );

    if (config.revert) {
      return FileUtils.deleteFile(
        filePath,
        'failing_mock_provider',
        dryRun: options.dryRun,
        verbose: options.verbose,
        fileSystem: fileSystem,
      );
    }

    final content = specLibrary.emitLibrary(
      specLibrary.library(specs: [clazz], directives: directives),
      leadingComment:
          '// Mock failure preset (spec 1110, issue #1110): '
          'every method throws ServerFailure.',
    );

    return FileUtils.writeFile(
      filePath,
      content,
      'failing_mock_provider',
      force: options.force,
      dryRun: options.dryRun,
      verbose: options.verbose,
      revert: config.revert,
      skipRevertIfExisted: true,
      fileSystem: fileSystem,
    );
  }

  /// One failing method: the interface's exact signature, a throwing
  /// body. Returns null for a method outside the known CRUD/watch
  /// vocabulary (the datasource builder skips those the same way).
  Method? _failingMethod(
    String entityName,
    GeneratorConfig config,
    String method,
  ) {
    final idType = config.idFieldType;
    final failure = refer('ServerFailure').constInstance([
      literalString(
        '$entityName mock failure (spec 1110 --fail preset): method $method',
      ),
    ]);

    Method build({
      required String returns,
      required String paramsType,
      String paramName = 'params',
      bool stream = false,
    }) {
      return Method(
        (m) => m
          ..name = method
          ..annotations.add(refer('override'))
          ..returns = refer(returns)
          ..modifier = stream ? null : MethodModifier.async
          ..requiredParameters.add(
            Parameter(
              (p) => p
                ..name = paramName
                ..type = refer(paramsType),
            ),
          )
          ..body = stream
              ? refer('Stream').property('error').call([failure]).code
              : failure.thrown.code,
      );
    }

    switch (method) {
      case 'get':
        return build(
          returns: 'Future<$entityName>',
          paramsType: 'QueryParams<$entityName>',
        );
      case 'getList':
        return build(
          returns: 'Future<List<$entityName>>',
          paramsType: 'ListQueryParams<$entityName>',
        );
      case 'create':
        return Method(
          (m) => m
            ..name = 'create'
            ..annotations.add(refer('override'))
            ..returns = refer('Future<$entityName>')
            ..modifier = MethodModifier.async
            ..requiredParameters.add(
              Parameter(
                (p) => p
                  ..name = 'item'
                  ..type = refer(entityName),
              ),
            )
            ..body = failure.thrown.code,
        );
      case 'update':
        return build(
          returns: 'Future<$entityName>',
          paramsType: 'UpdateParams<$idType, ${entityName}Patch>',
        );
      case 'toggle':
        return build(
          returns: 'Future<$entityName>',
          paramsType: 'ToggleParams<$idType, Field<$entityName, dynamic>>',
        );
      case 'delete':
        return build(
          returns: 'Future<void>',
          paramsType: 'DeleteParams<$idType>',
        );
      case 'watch':
        return build(
          returns: 'Stream<$entityName>',
          paramsType: 'QueryParams<$entityName>',
          stream: true,
        );
      case 'watchList':
        return build(
          returns: 'Stream<List<$entityName>>',
          paramsType: 'ListQueryParams<$entityName>',
          stream: true,
        );
      default:
        // Unknown method vocabulary: the failing provider mirrors the
        // mock datasource contract, which also only emits the known set.
        return null;
    }
  }
}
