import 'package:zuraffa/zuraffa.dart';

import '../domain_state.dart';
import '../view_state.dart';

/// A presenter that strictly separates **DomainState** (auto-generated,
/// immutable, regenerated) from **ViewState** (developer-editable, preserved).
///
/// ## Architecture
///
/// ```
/// ┌─────────────────────────────────────┐
/// │      DualLayerPresenter             │
/// │  ┌─────────────┐  ┌─────────────┐   │
/// │  │ DomainState │  │  ViewState  │   │
/// │  │ (generated) │  │ (hand-edited)│  │
/// │  │ SignalSlices│  │ Signal<T>   │   │
/// │  └─────────────┘  └─────────────┘   │
/// └─────────────────────────────────────┘
/// ```
///
/// ## Usage
///
/// ```dart
/// class ProductDetailPresenter extends DualLayerPresenter {
///   ProductDetailPresenter() : super(
///     domain: ProductDetailDomainState(presenter: slicePresenter),
///     view: ProductDetailViewState(),
///   );
/// }
/// ```
abstract class DualLayerPresenter {
  DualLayerPresenter({
    required DomainState domain,
    required ViewState view,
    // ignore: avoid_unused_constructor_parameters
    ZuraffaContext? context,
  }) : _domain = domain,
       _view = view;

  final DomainState _domain;
  final ViewState _view;

  /// The auto-generated domain state. Read-only, regenerated by `zfa build`.
  DomainState get domain => _domain;

  /// The developer-editable view state. Safe to modify, never overwritten.
  ViewState get view => _view;

  /// Combined backward-compatible state map.
  ///
  /// Exposes all domain slice data as a single map.
  /// This is O(N) in slice count and intended for migration bridges only.
  /// ViewState signals are not included — access them via [view] directly.
  Map<String, dynamic> get combinedState {
    final map = <String, dynamic>{};
    // Domain slices
    for (final key in _domain.sliceKeys) {
      map[key] = _domain.slice<dynamic>(key)?.data;
    }
    return map;
  }

  /// Dispose both layers.
  void dispose() {
    _view.dispose();
    _domain.dispose();
  }
}
