// Auto-generated by Zorphy
// Generated at: 2026-08-14T10:19:24.100509

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';

part 'form_option.zorphy.dart';
part 'form_option.g.dart';

/// FormOption entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $FormOption {
  String get id;
  String get value;
  String get label;
}
