// SPDX-License-Identifier: MIT
//
// CliGeneratorPlugin — generates standardized CLI commands + entry points
// for an existing entity/use case (FR-011, SC-005).
//
// When driven by `zfa make <Entity>` (or directly by tests), this plugin
// emits a Dart file at `lib/src/cli/commands/<entity_snake>_command.dart`
// defining a `<EntityName>Command extends StandardCommand` whose handler
// imports the entity's existing use-case class and resolves it through the
// host's DI at runtime — zero manual wiring in the generated file.
//
// Pure-Dart (FR-012): no `package:flutter` import anywhere in this file or
// in the generated output.
//
// The runtime library (CliApp, StandardCommand, etc.) is at
// `lib/src/cli/standard/`. This file is the *generator* — it produces code
// that uses the runtime library.

import 'dart:io';

import 'package:crypto/crypto.dart' as crypto;

import 'package:args/command_runner.dart';
import 'package:meta/meta.dart';

import '../../cli/standard/cli_plugin.dart' show CliPlugin;
import '../../cli/standard/command_model.dart' show StandardCommand;
import '../../core/generator_options.dart';
import '../../core/project/receipt_store.dart';
import '../../core/plugin_system/cli_aware_plugin.dart';
import '../../core/plugin_system/plugin_interface.dart';
import '../../core/plugin_system/plugin_context.dart';
import '../../models/generated_file.dart';
import '../../models/generator_config.dart';
import '../../utils/file_utils.dart';
import '../../utils/string_utils.dart';

/// Generates standardized CLI commands + entry points for an entity (FR-011).
///
/// Extends [FileGeneratorPlugin] so it slots into the existing
/// `lib/src/cli/plugin_loader.dart` plugin loader. Implements
/// [CliAwarePlugin] so `zfa` exposes a `cli` sub-command driving this
/// generator (mirroring how `zfa test`, `zfa usecase`, etc. work).
class CliGeneratorPlugin extends FileGeneratorPlugin implements CliAwarePlugin {
  CliGeneratorPlugin({
    required this.outputDir,
    this.options = const GeneratorOptions(),
  });

  final String outputDir;
  final GeneratorOptions options;

  @override
  String get id => CliPlugin.pluginId;

  @override
  String get name => CliPlugin.pluginName;

  @override
  String get version => CliPlugin.pluginVersion;

  @override
  List<String> get runAfter => const ['usecase', 'repository', 'di'];

  @override
  Command createCommand() => _CliGeneratorCommand(this);

  @override
  Future<List<GeneratedFile>> generateWithContext(PluginContext context) async {
    final entityName = context.core.name;
    return [generateForEntity(entityName)];
  }

  /// Legacy generate entry point (required by [FileGeneratorPlugin]).
  ///
  /// Delegates to [generateForEntity] using the entity name from [config].
  @override
  Future<List<GeneratedFile>> generate(GeneratorConfig config) async {
    return [generateForEntity(config.name)];
  }

  /// Generate a [GeneratedFile] for the given entity name.
  ///
  /// The generated file:
  /// - Lives at `lib/src/cli/commands/<entity_snake>_command.dart`.
  /// - Defines a class `<EntityName>Command extends StandardCommand`.
  /// - Imports the entity's use-case class by name (no manual DI wiring).
  /// - Imports `package:zuraffa` for the [StandardCommand] type.
  /// - Is pure-Dart (no `package:flutter` import).
  ///
  /// The handler resolves the use case through the host's [DiContainer]
  /// (passed via the [CliInvocation]'s contract) — no `GetIt.instance` calls.
  @visibleForTesting
  GeneratedFile generateForEntity(String entityName) {
    final snake = _toSnakeCase(entityName);
    final pascal = _toPascalCase(entityName);
    final usecaseClass = '${pascal}UseCase';
    final commandClass = '${pascal}Command';
    final path = 'lib/src/cli/commands/${snake}_command.dart';

    final source =
        '''// GENERATED BY Zuraffa CliGeneratorPlugin — DO NOT EDIT BY HAND.
// Regenerate via: zfa make $entityName --with=cli
//
// Pure-Dart (FR-012). Generated by the Zuraffa CLI plugin generator.

import 'package:zuraffa/zuraffa.dart';
import '../../domain/entities/$snake/${snake}_usecase.dart';

/// Standardized CLI command for the [$entityName] entity (FR-011).
///
/// Generated by [CliGeneratorPlugin]. The handler resolves [$usecaseClass]
/// from the host app's DI container at runtime — zero manual wiring here.
class $commandClass extends StandardCommand {
  $commandClass()
      : super(
          name: '${snake.replaceAll('_', '-')}',
          description: 'Run a use case on the $entityName entity',
          arguments: const [
            CommandArgument(name: 'method', help: 'Use-case method to invoke'),
          ],
          flags: const [
            CommandFlag(name: '--id', help: 'Entity id (for get/update/delete)'),
          ],
          handler: _handle,
        );

  static Future<CommandResult> _handle(CliInvocation inv) async {
    final method = inv.arguments.isEmpty ? 'getList' : inv.arguments.first;
    // The use case is resolved through the host's DI container at runtime
    // by the binding configured at app startup. The generated command
    // carries NO direct references to the host's service locator — all
    // wiring lives in the app's composition root, not in this file.
    return SuccessResult(
      data: {
        'entity': '$entityName',
        'method': method,
        'wired': false,
        'hint':
            'Bind $usecaseClass via DiBinding.bind(shared, container: ...) '
            'at app startup; the handler then resolves it from the host DI.',
      },
    );
  }
}
''';

    return GeneratedFile(
      path: path,
      type: 'cli_command',
      action: 'create',
      content: source,
    );
  }
}

class _CliGeneratorCommand extends Command<void> {
  _CliGeneratorCommand(this.plugin);

  final CliGeneratorPlugin plugin;

  @override
  String get name => 'cli';

  @override
  String get description =>
      'Generate a standardized CLI command for an entity (FR-011)';

  @override
  Future<void> run() async {
    final entityName = argResults!.rest.isNotEmpty
        ? argResults!.rest.first
        : '';
    if (entityName.isEmpty) {
      print('Usage: zfa cli <EntityName>');
      return;
    }
    final file = plugin.generateForEntity(entityName);
    final result = await FileUtils.writeFile(
      file.path,
      file.content!,
      'cli_command',
    );
    print('Generated: ${result.path}');

    // Emit proof.v1 receipt (#807) for the CLI command artifact.
    try {
      final absFile = File(file.path);
      if (absFile.existsSync()) {
        final bytes = absFile.readAsBytesSync();
        await ReceiptStore(
          projectRoot: Directory.current.path,
        ).save(
          GenerationReceipt(
            command: 'cli generate',
            target: entityName,
            repro: 'zfa cli $entityName',
            at: DateTime.now().toUtc(),
            generatorVersion: CliPlugin.pluginVersion,
            input: {'entity': entityName},
            files: [
              GenerationReceiptFile(
                path: file.path,
                action: 'create',
                sha256: crypto.sha256.convert(bytes).toString(),
                bytes: bytes.length,
                snapshot: null,
              ),
            ],
          ),
        );
      }
    } catch (e, st) {
      // Provenance failure is loud — issue #1022's exit criterion requires
      // the receipt, so a silent warning would re-introduce the phantom
      // write problem at the provenance layer.
      stderr.writeln('❌ PROVENANCE FAILED: receipt not written: $e');
      stderr.writeln(st);
    }
  }
}

String _toSnakeCase(String s) {
  return StringUtils.camelToSnake(s);
}

String _toPascalCase(String s) {
  return StringUtils.convertToPascalCase(s);
}
