// GENERATED - DO NOT EDIT
// Generated by zfa for: UrlSpark
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/url_spark/url_spark.dart';
import '../../repositories/url_spark_repository.dart';

class ToggleUrlSparkUseCase
    extends UseCase<UrlSpark, ToggleParams<String, Field<UrlSpark, dynamic>>> {
  ToggleUrlSparkUseCase(this._repository);

  final UrlSparkRepository _repository;

  @override
  Future<UrlSpark> execute(
    ToggleParams<String, Field<UrlSpark, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
