// GENERATED - DO NOT EDIT
// Generated by zfa for: ZikZakScore
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/zik_zak_score/zik_zak_score.dart';
import '../../repositories/zik_zak_score_repository.dart';

class ToggleZikZakScoreUseCase
    extends
        UseCase<
          ZikZakScore,
          ToggleParams<String, Field<ZikZakScore, dynamic>>
        > {
  ToggleZikZakScoreUseCase(this._repository);

  final ZikZakScoreRepository _repository;

  @override
  Future<ZikZakScore> execute(
    ToggleParams<String, Field<ZikZakScore, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
