// GENERATED - DO NOT EDIT
// Generated by zfa for: ConnectedAccount
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/connected_account/connected_account.dart';
import '../../repositories/connected_account_repository.dart';

class GetConnectedAccountUseCase
    extends UseCase<ConnectedAccount, QueryParams<ConnectedAccount>> {
  GetConnectedAccountUseCase(this._repository);

  final ConnectedAccountRepository _repository;

  @override
  Future<ConnectedAccount> execute(
    QueryParams<ConnectedAccount> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
