// GENERATED - DO NOT EDIT
// Generated by zfa for: ConnectedAccount
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/connected_account/connected_account.dart';
import '../../repositories/connected_account_repository.dart';

class ToggleConnectedAccountUseCase
    extends
        UseCase<
          ConnectedAccount,
          ToggleParams<String, Field<ConnectedAccount, dynamic>>
        > {
  ToggleConnectedAccountUseCase(this._repository);

  final ConnectedAccountRepository _repository;

  @override
  Future<ConnectedAccount> execute(
    ToggleParams<String, Field<ConnectedAccount, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
