/// The golden contract world (bug #832, VISION §9).
///
/// `SimulationWorld` spins the certified simulation for the TDD loop:
///
/// - **load** — reads `specs/<feature>/tdd/fixtures/` (or an explicit
///   fixtures dir), verifies every fixture byte against the committed
///   SHA-256 manifest, and boots the five adapter families from them.
/// - **boot** — load + `NetworkIsolationGuard.install()`: every test
///   running against the world is certified socket-free.
/// - **bindTo** — registers the certified adapters into
///   `ZuraffaContainer` under the production contracts. Data sources
///   generated by `zfa make` resolve the SAME interface they resolve in
///   production — different (certified) binding, zero code change.
/// - **play** — deterministically replays the golden contract through
///   the adapters and reports per-play results for the machine verdict.
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import '../core/di/zuraffa_container.dart';
import 'fixture_registry.dart';
import 'network_isolation_guard.dart';
import 'simulation_adapters.dart';

/// One deterministic golden replay result.
final class PlayResult {
  const PlayResult({
    required this.family,
    required this.name,
    required this.passed,
    required this.detail,
  });

  final String family;
  final String name;
  final bool passed;
  final String detail;

  @override
  String toString() =>
      'PlayResult($family/$name, ${passed ? 'GREEN' : 'RED'}) $detail';
}

/// The certified simulation world for one feature.
final class SimulationWorld {
  SimulationWorld._({
    required this.fixturesDir,
    required this.manifest,
    this.auth,
    this.vendure,
    this.rest,
    this.admob,
    this.otel,
  });

  /// The fixtures directory the world was loaded from.
  final String fixturesDir;

  /// The verified manifest (`digest`, per-file hashes, families).
  final Map<String, dynamic> manifest;

  /// Firebase Auth family (scriptable auth states), or `null` when the
  /// committed world does not include this family.
  final FirebaseAuthAdapter? auth;

  /// Vendure family (GraphQL golden fixtures), or `null` when the
  /// committed world does not include this family.
  final VendureAdapter? vendure;

  /// REST family (Market Fiyati / Google Shopping / generic JSON), or
  /// `null` when the committed world does not include this family.
  final RestAdapter? rest;

  /// AdMob family (load/show/fail callbacks), or `null` when the
  /// committed world does not include this family.
  final AdMobAdapter? admob;

  /// OpenTelemetry family (capture-and-assert exporter), or `null` when
  /// the committed world does not include this family.
  final OtelAdapter? otel;

  bool _guardInstalled = false;

  /// Load and verify the world under [fixturesDir]. Throws
  /// [FixtureMismatch] when the committed fixtures drift from the
  /// certified manifest.
  static Future<SimulationWorld> load(String fixturesDir) async {
    final registry = FixtureRegistry(fixturesDir);
    final manifest = await registry.readManifest();
    await registry.verifyManifest();

    Future<Map<String, dynamic>> read(String fileName) async {
      final file = File(p.join(fixturesDir, fileName));
      return jsonDecode(await file.readAsString()) as Map<String, dynamic>;
    }

    final families = (manifest['families'] as List? ?? const []).cast<String>();
    return SimulationWorld._(
      fixturesDir: fixturesDir,
      manifest: manifest,
      auth: families.contains('firebase-auth')
          ? FirebaseAuthAdapter(world: await read('auth-world.json'))
          : null,
      vendure: families.contains('vendure')
          ? VendureAdapter(world: await read('vendure-golden.json'))
          : null,
      rest: families.contains('rest')
          ? RestAdapter(world: await read('rest-world.json'))
          : null,
      admob: families.contains('admob')
          ? AdMobAdapter(world: await read('admob-world.json'))
          : null,
      otel: families.contains('otel') ? OtelAdapter() : null,
    );
  }

  /// Load the world for [featureDir] (`<featureDir>/tdd/fixtures/`).
  static Future<SimulationWorld> forFeature(String featureDir) =>
      load(p.join(featureDir, 'tdd', 'fixtures'));

  /// Load the world and install the network-isolation guard, so every
  /// test running against this world is certified socket-free.
  static Future<SimulationWorld> boot({
    String? featureDir,
    String? fixturesDir,
  }) async {
    final dir = featureDir != null
        ? p.join(featureDir, 'tdd', 'fixtures')
        : (fixturesDir ??
            (throw ArgumentError('boot requires featureDir or fixturesDir')));
    final world = await load(dir);
    NetworkIsolationGuard.install();
    world._guardInstalled = true;
    return world;
  }

  /// Whether the world booted with the network-isolation guard active.
  bool get guardActive => _guardInstalled && NetworkIsolationGuard.isActive;

  /// Bind the certified adapters into [container] under the production
  /// contracts. The test bootstrap calls this once; generated data
  /// sources resolve exactly as they do against the live bindings.
  void bindTo(ZuraffaContainer container) {
    final rest = this.rest;
    if (rest != null) container.registerInstance<RestContract>(rest);
    final auth = this.auth;
    if (auth != null) container.registerInstance<AuthContract>(auth);
    final vendure = this.vendure;
    if (vendure != null) container.registerInstance<VendureContract>(vendure);
    final admob = this.admob;
    if (admob != null) container.registerInstance<AdContract>(admob);
  }

  /// Deterministic golden replay: every recorded fixture is driven
  /// through its certified adapter and compared with its recorded
  /// expectation. Scripted failures replay as expected failures. Pass
  /// [family] to replay a single family.
  Future<List<PlayResult>> play({String? family}) async {
    final results = <PlayResult>[];
    bool wants(String f) => family == null || family == f;
    final rest = this.rest;
    final auth = this.auth;
    final vendure = this.vendure;
    final admob = this.admob;
    final otel = this.otel;

    if (wants('rest') && rest != null) {
      final restWorld = manifest['families'].contains('rest')
          ? await _readWorld('rest-world.json')
          : null;
      if (restWorld != null) {
        final fixtures =
            (restWorld['fixtures'] as Map<String, dynamic>? ?? const {})
                .cast<String, dynamic>();
        final faults =
            (restWorld['scriptedFaults'] as Map<String, dynamic>? ?? const {})
                .cast<String, dynamic>();
        for (final entry in fixtures.entries) {
          final key = entry.key;
          if (!key.startsWith('GET ')) continue; // GET-only golden replay
          final path = key.substring(4);
          try {
            final body = await rest.get(path);
            final expected = (entry.value as Map<String, dynamic>)['body'];
            results.add(PlayResult(
              family: 'rest',
              name: key,
              passed: jsonEncode(body) == jsonEncode(expected),
              detail: 'replayed body vs golden',
            ));
          } on SimulatedHttpException catch (e) {
            results.add(PlayResult(
              family: 'rest',
              name: key,
              passed: false,
              detail: 'unexpected HTTP failure: $e',
            ));
          }
        }
        for (final entry in faults.entries) {
          final key = entry.key;
          if (!key.startsWith('GET ')) continue;
          final path = key.substring(4);
          try {
            await rest.get(path);
            results.add(PlayResult(
              family: 'rest',
              name: key,
              passed: false,
              detail: 'expected scripted ${entry.value} failure, got success',
            ));
          } on SimulatedHttpException catch (e) {
            results.add(PlayResult(
              family: 'rest',
              name: key,
              passed: e.statusCode == (entry.value as num).toInt(),
              detail: 'scripted fault replayed (${e.statusCode})',
            ));
          }
        }
      }
    }

    if (wants('vendure') && vendure != null) {
      final vendureWorld = manifest['families'].contains('vendure')
          ? await _readWorld('vendure-golden.json')
          : null;
      if (vendureWorld != null) {
        final goldenQueries =
            (vendureWorld['goldenQueries'] as Map<String, dynamic>? ?? const {})
                .cast<String, dynamic>();
        final goldenMutations =
            (vendureWorld['goldenMutations'] as Map<String, dynamic>? ?? const {})
                .cast<String, dynamic>();
        final scripted =
            (vendureWorld['scriptedErrors'] as Map<String, dynamic>? ?? const {})
                .cast<String, dynamic>();
        for (final operation in goldenQueries.keys) {
          results.add(await _playVendure(
            'vendure',
            'query $operation',
            () => vendure.query('query $operation { $operation { __typename } }'),
            goldenQueries[operation],
          ));
        }
        for (final operation in goldenMutations.keys) {
          results.add(await _playVendure(
            'vendure',
            'mutation $operation',
            () => vendure.mutation(
              'mutation $operation { $operation { __typename } }',
            ),
            goldenMutations[operation],
          ));
        }
        for (final operation in scripted.keys) {
          results.add(await _playVendureError(
            'vendure',
            'error $operation',
            () => vendure.query('query $operation { $operation { __typename } }'),
            scripted[operation] as List,
          ));
        }
      }
    }

    if (wants('firebase-auth') && auth != null) {
      final authWorld = manifest['families'].contains('firebase-auth')
          ? await _readWorld('auth-world.json')
          : null;
      if (authWorld != null) {
        final scriptedErrors = {
          for (final e in (authWorld['scriptedErrors'] as List? ?? const [])
              .cast<Map<String, dynamic>>())
            e['email'] as String: e['code'] as String,
        };
        for (final user
            in (authWorld['users'] as List? ?? const [])
                .cast<Map<String, dynamic>>()) {
          final email = user['email'] as String;
          if (scriptedErrors.containsKey(email)) {
            try {
              await auth.signIn(
                email: email,
                password: user['password'] as String,
              );
              results.add(PlayResult(
                family: 'firebase-auth',
                name: 'scripted $email',
                passed: false,
                detail:
                    'expected scripted ${scriptedErrors[email]}, got sign-in',
              ));
            } on SimulatedAuthException catch (e) {
              results.add(PlayResult(
                family: 'firebase-auth',
                name: 'scripted $email',
                passed: e.code == scriptedErrors[email],
                detail: 'scripted ${e.code} replayed',
              ));
            }
            continue;
          }
          try {
            final signedIn = await auth.signIn(
              email: email,
              password: user['password'] as String,
            );
            final ok = signedIn.uid == user['uid'] && auth.isSignedIn;
            await auth.signOut();
            results.add(PlayResult(
              family: 'firebase-auth',
              name: 'sign-in $email',
              passed: ok && !auth.isSignedIn,
              detail: 'certified credential path replayed',
            ));
          } on SimulatedAuthException catch (e) {
            results.add(PlayResult(
              family: 'firebase-auth',
              name: 'sign-in $email',
              passed: false,
              detail: 'unexpected auth failure: ${e.code}',
            ));
          }
        }
      }
    }

    if (wants('admob') && admob != null && manifest['families'].contains('admob')) {
      final events = <String>[];
      await admob.load(
        callbacks: AdCallbacks(
          onAdLoaded: () => events.add('loaded'),
          onAdFailed: (code) => events.add('failed:$code'),
        ),
      );
      await admob.show(
        callbacks: AdCallbacks(
          onAdShown: () => events.add('shown'),
          onAdDismissed: () => events.add('dismissed'),
          onAdFailed: (code) => events.add('show-failed:$code'),
        ),
      );
      admob.clearScripts();
      results.add(PlayResult(
        family: 'admob',
        name: 'load/show happy path',
        passed: events.join(',') == 'loaded,shown,dismissed',
        detail: events.join(','),
      ));
    }

    if (wants('otel') && otel != null && manifest['families'].contains('otel')) {
      final otelWorld = await _readWorld('otel-world.json');
      final expected = (otelWorld?['expectedSpans'] as List? ?? const [])
          .cast<String>();
      // The capture-and-assert exporter is armed by boot. A fresh world
      // has produced no spans in this process yet; once spans flow, every
      // expected span must be captured.
      final armed = !otel.isShutdown;
      final capturedSomething = otel.captured.isNotEmpty;
      final allExpectedPresent =
          expected.every(otel.hasSpan) || !capturedSomething;
      results.add(PlayResult(
        family: 'otel',
        name: 'capture-and-assert exporter',
        passed: armed && allExpectedPresent,
        detail: !capturedSomething
            ? 'exporter armed; no spans produced in this process yet'
            : 'captured ${otel.captured.length} spans; expected spans all '
                'present',
      ));
    }

    return results;
  }

  Future<Map<String, dynamic>?> _readWorld(String fileName) async {
    final file = File(p.join(fixturesDir, fileName));
    if (!file.existsSync()) return null;
    return jsonDecode(await file.readAsString()) as Map<String, dynamic>;
  }

  Future<PlayResult> _playVendure(
    String family,
    String name,
    Future<Map<String, dynamic>> Function() call,
    dynamic golden,
  ) async {
    try {
      final response = await call();
      return PlayResult(
        family: family,
        name: name,
        passed: jsonEncode(response) == jsonEncode(golden),
        detail: 'replayed response vs golden',
      );
    } on SimulatedGraphQLError catch (e) {
      return PlayResult(
        family: family,
        name: name,
        passed: false,
        detail: 'unexpected GraphQL error: $e',
      );
    }
  }

  Future<PlayResult> _playVendureError(
    String family,
    String name,
    Future<Map<String, dynamic>> Function() call,
    List expectedErrors,
  ) async {
    try {
      await call();
      return PlayResult(
        family: family,
        name: name,
        passed: false,
        detail: 'expected scripted error surface, got a response',
      );
    } on SimulatedGraphQLError catch (e) {
      return PlayResult(
        family: family,
        name: name,
        passed: jsonEncode(e.errors) == jsonEncode(expectedErrors),
        detail: 'scripted error surface replayed',
      );
    }
  }

  /// Undo the world's process-global effects (the network guard).
  void dispose() {
    if (_guardInstalled) NetworkIsolationGuard.uninstall();
  }
}
