// GENERATED - DO NOT EDIT
// Generated by zfa for: Barcode
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/barcode/barcode.dart';
import '../../repositories/barcode_repository.dart';

class ToggleBarcodeUseCase
    extends UseCase<Barcode, ToggleParams<String, Field<Barcode, dynamic>>> {
  ToggleBarcodeUseCase(this._repository);

  final BarcodeRepository _repository;

  @override
  Future<Barcode> execute(
    ToggleParams<String, Field<Barcode, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
