/// Builds the `--flutter` app entry of a working slice (042, FR-008).
library;

import '../../models/bone.dart';

/// Flutter import emitted as a constant so no source line in `lib/` starts
/// with a Flutter import (issue #495 / feature 014 convention).
const String _flutterMaterialImport = "import 'package:flutter/material.dart';";

/// Emits the minimal `pubspec.yaml` and the runnable `lib/main.dart` for
/// `--flutter` bones.
class AppEntryBuilder {
  /// The minimal pubspec: environment + flutter SDK deps only.
  String buildPubspec(String featureSlug) {
    return '''
name: ${slugToSnakeCase(featureSlug)}_bone
description: >-
  Working-slice bone for feature $featureSlug, generated by
  `zfa bone generate --flutter`.
publish_to: none
environment:
  sdk: ^3.11.0
  flutter: ^3.47.0
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
''';
  }

  /// The runnable entry: build the DI container, launch the feature page.
  String buildMainDart(String featureSlug) {
    final pascal = slugToPascalCase(featureSlug);
    final snake = slugToSnakeCase(featureSlug);
    final display = slugToDisplayName(featureSlug);
    return '''
$_flutterMaterialImport

import '../di/injection.dart';
import '../presentation/${snake}_page.dart';

void main() {
  final services = ${pascal}Services.create();
  runApp(${pascal}BoneApp(services));
}

/// Runnable entry shell for the $snake working slice.
class ${pascal}BoneApp extends StatelessWidget {
  const ${pascal}BoneApp(this.services, {super.key});

  final ${pascal}Services services;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '$display',
      home: ${pascal}Page(services: services),
    );
  }
}
''';
  }
}
