/// Builds the self-contained DI container of a working slice (042, FR-006).
library;

import '../../models/bone.dart';

/// Emits `di/injection.dart`: a dependency container registering every
/// repository wired to mock or firebase data sources, with the generation-time
/// `--di` choice baked in as the default and a runtime override available.
///
/// The container is deliberately dependency-free: `dart:*` and bone-relative
/// imports only, so bones stay self-contained.
class InjectionBuilder {
  /// Builds the container for [featureSlug] over [entities]
  /// (name + fields pairs).
  String build({
    required String featureSlug,
    required List<(String, List<EntityField>)> entities,
    required DiChoice diChoice,
  }) {
    final pascal = slugToPascalCase(featureSlug);
    final buffer = StringBuffer();

    // Imports — sorted for deterministic output.
    final imports = <String>[];
    for (final (name, _) in entities) {
      final snake = pascalToSnake(name);
      imports.add('../data/datasources/${snake}_firebase.dart');
      imports.add('../data/datasources/${snake}_mock.dart');
      imports.add('../data/repositories/data_${snake}_repository.dart');
      imports.add('../domain/repositories/${snake}_repository.dart');
      imports.add('../domain/usecases/create_${snake}_usecase.dart');
      imports.add('../domain/usecases/delete_${snake}_usecase.dart');
      imports.add('../domain/usecases/get_${snake}_usecase.dart');
      imports.add('../domain/usecases/update_${snake}_usecase.dart');
    }
    imports.sort();
    for (final import in imports) {
      buffer.writeln("import '$import';");
    }
    buffer.writeln();
    buffer.writeln('/// Which data-source backend the container wires.');
    buffer.writeln('enum BoneBackend { mock, firebase }');
    buffer.writeln();
    buffer.writeln('/// Firebase credentials for [BoneBackend.firebase].');
    buffer.writeln('class FirebaseConfig {');
    buffer.writeln(
      '  const FirebaseConfig({'
      'required this.projectId, '
      'required this.apiKey, '
      'this.idToken,'
      '});',
    );
    buffer.writeln();
    buffer.writeln('  /// Firestore project id.');
    buffer.writeln('  final String projectId;');
    buffer.writeln();
    buffer.writeln('  /// Firebase API key authorized for [projectId].');
    buffer.writeln('  final String apiKey;');
    buffer.writeln();
    buffer.writeln('  /// Optional Firebase ID token forwarded to the data');
    buffer.writeln(
      '  /// source so Firestore Security Rules requiring auth pass.',
    );
    buffer.writeln('  final String? idToken;');
    buffer.writeln('}');
    buffer.writeln();
    buffer.writeln(
      "/// Dependency container for the ${slugToDisplayName(featureSlug)} "
      'working slice.',
    );
    buffer.writeln('///');
    buffer.writeln(
      "/// Generated by `zfa bone generate --di ${diChoice.requested}` "
      '(resolved: ${diChoice.backendName}, source: ${diChoice.sourceName}).',
    );
    buffer.writeln('class ${pascal}Services {');
    buffer.writeln('  ${pascal}Services._(');
    buffer.writeln('    this.backend,');
    for (final (name, _) in entities) {
      buffer.writeln('    this._${pascalToCamel(name)}Repository,');
    }
    buffer.writeln('  );');
    buffer.writeln();
    buffer.writeln('  /// The backend this instance was wired with.');
    buffer.writeln('  final BoneBackend backend;');
    buffer.writeln();
    for (final (name, _) in entities) {
      buffer.writeln(
        '  final ${name}Repository _${pascalToCamel(name)}Repository;',
      );
    }
    buffer.writeln();
    buffer.writeln('  /// Builds the container.');
    buffer.writeln('  ///');
    buffer.writeln('  /// [backend] overrides the generation-time default;');
    buffer.writeln(
      '  /// [firebaseConfig] is required when the effective backend is',
    );
    buffer.writeln('  /// [BoneBackend.firebase].');
    buffer.writeln('  factory ${pascal}Services.create({');
    buffer.writeln('    BoneBackend? backend,');
    buffer.writeln('    FirebaseConfig? firebaseConfig,');
    buffer.writeln('  }) {');
    buffer.writeln(
      '    final effective = backend ?? BoneBackend.${diChoice.backendName};',
    );
    buffer.writeln(
      '    if (effective == BoneBackend.firebase && firebaseConfig == null) {',
    );
    buffer.writeln('      throw StateError(');
    buffer.writeln("        'Firebase credentials missing: provide '");
    buffer.writeln(
      "        'FirebaseConfig(projectId:, apiKey:) to use the firebase backend.',",
    );
    buffer.writeln('      );');
    buffer.writeln('    }');
    buffer.writeln('    return ${pascal}Services._(');
    buffer.writeln('      effective,');
    for (final (name, _) in entities) {
      buffer.writeln('      _wire$name(effective, firebaseConfig),');
    }
    buffer.writeln('    );');
    buffer.writeln('  }');
    buffer.writeln();
    for (final (name, _) in entities) {
      buffer.writeln('  static ${name}Repository _wire$name(');
      buffer.writeln('    BoneBackend backend,');
      buffer.writeln('    FirebaseConfig? firebaseConfig,');
      buffer.writeln('  ) =>');
      buffer.writeln('      backend == BoneBackend.firebase');
      buffer.writeln(
        '          ? Data${name}Repository(${name}FirebaseDataSource(',
      );
      buffer.writeln('              projectId: firebaseConfig!.projectId,');
      buffer.writeln('              apiKey: firebaseConfig.apiKey,');
      buffer.writeln('              idToken: firebaseConfig.idToken,');
      buffer.writeln('            ))');
      buffer.writeln(
        '          : Data${name}Repository(${name}MockDataSource());',
      );
      buffer.writeln();
    }
    for (final (name, _) in entities) {
      final camel = pascalToCamel(name);
      buffer.writeln('  /// The $name repository.');
      buffer.writeln(
        '  ${name}Repository get ${camel}Repository => _${camel}Repository;',
      );
      buffer.writeln();
      buffer.writeln('  /// Use cases over the $name repository.');
      buffer.writeln(
        '  Get${name}UseCase get get$name => Get${name}UseCase(_${camel}Repository);',
      );
      buffer.writeln(
        '  Create${name}UseCase get create$name => Create${name}UseCase(_${camel}Repository);',
      );
      buffer.writeln(
        '  Update${name}UseCase get update$name => Update${name}UseCase(_${camel}Repository);',
      );
      buffer.writeln(
        '  Delete${name}UseCase get delete$name => Delete${name}UseCase(_${camel}Repository);',
      );
      buffer.writeln();
    }
    buffer.writeln('}');
    return buffer.toString();
  }
}
