// Auto-generated by Zorphy
// Generated at: 2026-08-13T21:11:57.587449

import 'package:zorphy_annotation/zorphy_annotation.dart';
import '../metric_detail/metric_detail.dart';

part 'zik_zak_score.zorphy.dart';
part 'zik_zak_score.g.dart';

/// ZikZakScore entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ZikZakScore {
  String? get id;
  String? get barcode;
  String? get url;
  String? get title;
  int get totalScore;
  int get authenticityScore;
  int get brandScore;
  int get performanceScore;
  int get valueScore;
  int get competitionScore;
  DateTime get calculatedAt;
  bool get isCached;
  List<$MetricDetail> get metrics;
}
