import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Scaffold contract test for specs/031-scaffold-todo-example.
///
/// Written TEST-FIRST (before any `zfa` scaffold command ran): every
/// assertion here failed at the initial red run — the entity, the use
/// cases, the data layer, the codegen artifacts, and the presentation
/// layer did not exist yet. The zfa CLI scaffold flow turns each section
/// green; this file is the automated proof of spec US1-US3 + SC-001,
/// SC-004 (structure) and pins the hand-written presentation boundary
/// (US4).
///
/// All paths are relative to the example package root (the working
/// directory of `flutter test`).
void main() {
  group('A1/U1 — Todo entity generated by zfa entity create', () {
    test('entity source exists with zorphy structure markers', () {
      // Current CLI fixed layout (zorphy 2.3.1 EntityCreator + zuraffa v5
      // ZfaConfig.fixedEntityOutput): lib/src/domain/entities/<snake>/<snake>.dart
      final f = File('lib/src/domain/entities/todo/todo.dart');
      expect(
        f.existsSync(),
        isTrue,
        reason:
            'zfa entity create -n Todo must emit '
            'lib/src/domain/entities/todo/todo.dart',
      );
      final src = f.readAsStringSync();
      expect(
        src,
        contains('@Zorphy('),
        reason: 'entity must be zorphy-annotated (generator marker)',
      );
      expect(src, contains("part 'todo.zorphy.dart';"));
    });

    test('entity declares all 8 spec fields with correct types', () {
      final src = File(
        'lib/src/domain/entities/todo/todo.dart',
      ).readAsStringSync();
      expect(src, contains('int get id;'));
      expect(src, contains('String get title;'));
      expect(src, contains('String get description;'));
      expect(src, contains('bool get isCompleted;'));
      expect(src, contains('TodoPriority get priority;'));
      expect(src, contains('List<String> get tags;'));
      expect(src, contains('DateTime get createdAt;'));
      expect(src, contains('DateTime get completedAt;'));
    });

    test('TodoPriority enum generated via zfa entity enum (FR-006)', () {
      final f = File('lib/src/domain/entities/enums/todo_priority.dart');
      expect(
        f.existsSync(),
        isTrue,
        reason:
            'zfa entity enum -n TodoPriority must emit '
            'lib/src/domain/entities/enums/todo_priority.dart',
      );
      final src = f.readAsStringSync();
      expect(src, contains('enum TodoPriority'));
      for (final v in ['low', 'medium', 'high']) {
        expect(src, contains(v));
      }
    });
  });

  group('A2/U3 — zfa make --preset=crud generates the full architecture', () {
    test('one use case file per method (7) exists', () {
      // File names as emitted by `zfa make`: the list-style methods keep
      // their full method name in the file (`get_todo_list_usecase.dart`,
      // `watch_todo_list_usecase.dart`).
      const files = [
        'create_todo_usecase.dart',
        'get_todo_usecase.dart',
        'get_todo_list_usecase.dart',
        'update_todo_usecase.dart',
        'delete_todo_usecase.dart',
        'watch_todo_usecase.dart',
        'watch_todo_list_usecase.dart',
      ];
      for (final f in files) {
        expect(
          File('lib/src/domain/usecases/todo/$f').existsSync(),
          isTrue,
          reason: 'missing lib/src/domain/usecases/todo/$f',
        );
      }
    });

    test('repository abstract + implementation exist', () {
      expect(
        File('lib/src/domain/repositories/todo_repository.dart').existsSync(),
        isTrue,
        reason: 'repository abstraction (domain layer) missing',
      );
      expect(
        File(
          'lib/src/data/repositories/data_todo_repository.dart',
        ).existsSync(),
        isTrue,
        reason: 'repository implementation (data layer) missing',
      );
    });

    test('datasource abstract + implementation exist', () {
      expect(
        File('lib/src/data/datasources/todo/todo_datasource.dart').existsSync(),
        isTrue,
        reason: 'datasource abstraction missing',
      );
      final dir = Directory('lib/src/data/datasources/todo');
      final impls = dir.existsSync()
          ? dir
                .listSync()
                .whereType<File>()
                .map((f) => f.uri.pathSegments.last)
                .where(
                  (n) => n.endsWith('.dart') && n != 'todo_datasource.dart',
                )
                .toList()
          : <String>[];
      expect(
        impls,
        isNotEmpty,
        reason:
            'datasource implementation missing under '
            'lib/src/data/datasources/todo/',
      );
    });

    test('DI wiring for the use cases exists', () {
      final hits = <String>[];
      final di = Directory('lib/src/di');
      if (di.existsSync()) {
        di.listSync(recursive: true).whereType<File>().forEach((f) {
          if (!f.path.endsWith('.dart')) return;
          final src = f.readAsStringSync();
          if (src.contains('registerFactory') || src.contains('GetIt')) {
            hits.add(f.path);
          }
        });
      }
      expect(
        hits,
        isNotEmpty,
        reason: 'no DI registration emitted anywhere under lib/src/di',
      );
    });
  });

  group('A3/U9 — zfa build codegen artifacts', () {
    test('zorphy part file with comparisons/copyWith emitted', () {
      final f = File('lib/src/domain/entities/todo/todo.zorphy.dart');
      expect(
        f.existsSync(),
        isTrue,
        reason: 'build_runner must emit todo.zorphy.dart',
      );
      final src = f.readAsStringSync();
      expect(
        src,
        contains('copyWith'),
        reason: 'zorphy comparisons/patch surface missing',
      );
    });

    test('Hive adapter artifacts emitted', () {
      final g = File('lib/src/cache/hive_registrar.g.dart');
      expect(
        g.existsSync(),
        isTrue,
        reason: 'hive_ce_generator must emit hive_registrar.g.dart',
      );
      expect(g.readAsStringSync(), contains('TodoAdapter'));
      expect(
        File('lib/src/cache/hive_registrar.dart').existsSync(),
        isTrue,
        reason: 'hive_registrar.dart (zfa cache adapter) missing',
      );
    });
  });

  group('A6 — flat layout matches the #219 reference', () {
    test('domain/data/presentation sit directly under lib/src', () {
      expect(Directory('lib/src/domain').existsSync(), isTrue);
      expect(Directory('lib/src/data').existsSync(), isTrue);
      expect(Directory('lib/src/presentation').existsSync(), isTrue);
      // Flat: layer folders sit at src root; entity files nest at most
      // one level (entities/<snake>/<snake>.dart — the current CLI's fixed
      // layout; #219's flat entities/todo.dart predates zorphy 2.3). The
      // no-deep-nesting invariant: no directory under domain/data holds
      // more than one nesting level below its layer root.
      expect(Directory('lib/src/domain/entities').existsSync(), isTrue);
      final deep = <String>[];
      for (final root in ['lib/src/domain', 'lib/src/data']) {
        Directory(
          root,
        ).listSync(recursive: true).whereType<Directory>().forEach((d) {
          final rel = d.path.substring(root.length + 1);
          if (rel.split(Platform.pathSeparator).length > 3) {
            deep.add(d.path);
          }
        });
      }
      expect(
        deep,
        isEmpty,
        reason:
            'deep nesting breaks the flat #219 layer convention: '
            '$deep',
      );
    });
  });

  group('A7 — no hand-written domain/data layer code', () {
    test('every domain/data source file carries a generator marker', () {
      final offenders = <String>[];
      for (final dirName in [
        'lib/src/domain',
        'lib/src/data',
        'lib/src/cache',
      ]) {
        final dir = Directory(dirName);
        if (!dir.existsSync()) continue;
        dir.listSync(recursive: true).whereType<File>().forEach((f) {
          if (!f.path.endsWith('.dart')) return;
          final src = f.readAsStringSync();
          // Every CLI writer emits a GENERATED/Auto-generated header; a
          // hand-written file would carry neither the header nor a
          // framework import. `part of` files (e.g. todo.zorphy.dart,
          // emitted by the zorphy build_runner generator) cannot exist
          // without their generated parent, so they count as generated.
          final generated =
              src.toLowerCase().contains('generated') ||
              src.contains('part of') ||
              src.contains('package:zuraffa') ||
              src.contains('package:zorphy_annotation') ||
              src.contains('package:hive_ce');
          if (!generated) offenders.add(f.path);
        });
      }
      expect(
        offenders,
        isEmpty,
        reason:
            'files without generator markers are hand-written: '
            '$offenders',
      );
    });
  });

  group('A8/A9 — hive field-index yaml matches the entity 1:1', () {
    test('yaml exists and carries the Todo type', () {
      // hive_ce_generator emits the field-index yaml next to the file that
      // carries @GenerateAdapters (lib/src/cache/hive_registrar.dart) —
      // emitted as hive_registrar.g.yaml.
      final f = File('lib/src/cache/hive_registrar.g.yaml');
      expect(
        f.existsSync(),
        isTrue,
        reason: 'hive field-index yaml must be generated',
      );
      expect(f.readAsStringSync(), contains('Todo:'));
    });

    test('every Todo field has its index, 1:1 with the entity', () {
      final src = File(
        'lib/src/cache/hive_registrar.g.yaml',
      ).readAsStringSync();
      const expected = {
        'id': 0,
        'title': 1,
        'description': 2,
        'isCompleted': 3,
        'priority': 4,
        'tags': 5,
        'createdAt': 6,
        'completedAt': 7,
      };
      expected.forEach((field, index) {
        final re = RegExp('$field:\\s*\n\\s*index: $index\\b');
        expect(
          re.hasMatch(src),
          isTrue,
          reason: 'field "$field" must map to index $index',
        );
      });
      final indices = RegExp(
        r'index:\s*(\d+)',
      ).allMatches(src).map((m) => m.group(1)!);
      expect(
        indices.toSet().length,
        expected.length,
        reason:
            'field index set must be exactly 0..7 — no missing, '
            'no extra fields',
      );
      expect(src, contains('nextIndex: 8'));
    });
  });

  group('A10 — hand-written presentation boundary (US4)', () {
    test('presentation files exist', () {
      for (final name in [
        'lib/src/presentation/todo_controller.dart',
        'lib/src/presentation/todo_page.dart',
        'lib/src/presentation/todo_presenter.dart',
        'lib/src/presentation/todo_state.dart',
      ]) {
        expect(File(name).existsSync(), isTrue, reason: 'missing $name');
      }
    });

    test('app entry points exist', () {
      expect(File('lib/main.dart').existsSync(), isTrue);
      expect(File('lib/setup.dart').existsSync(), isTrue);
    });
  });

  group('U4-U7 — generated use case test files', () {
    test('one test file per use case (7) exists under test/domain', () {
      const files = [
        'create_todo_usecase_test.dart',
        'get_todo_usecase_test.dart',
        'get_todo_list_usecase_test.dart',
        'update_todo_usecase_test.dart',
        'delete_todo_usecase_test.dart',
        'watch_todo_usecase_test.dart',
        'watch_todo_list_usecase_test.dart',
      ];
      for (final name in files) {
        expect(
          File('test/domain/usecases/todo/$name').existsSync(),
          isTrue,
          reason: 'missing generated test test/domain/usecases/todo/$name',
        );
      }
    });
  });
}
