import 'dart:io';
import 'package:code_builder/code_builder.dart';
import 'package:path/path.dart' as path;
import '../../models/generated_file.dart';
import '../../utils/file_utils.dart';
import 'ast_helper.dart';
import 'append_executor.dart';
import 'strategies/append_strategy.dart';

/// Builder for generating Dart Augmentation Libraries.
class AugmentationBuilder {
  final String outputDir;

  const AugmentationBuilder({required this.outputDir});

  /// Generates or updates an augmentation file for the given [hostPath].
  Future<GeneratedFile> generate({
    required String hostPath,
    required String className,
    required List<Spec> members,
    List<String> imports = const [],
    bool dryRun = false,
  }) async {
    final hostFileName = path.basename(hostPath);
    final augmentFileName = hostFileName.replaceFirst('.dart', '.augment.dart');
    final augmentPath = path.join(path.dirname(hostPath), augmentFileName);

    final emitter = DartEmitter(
      useNullSafetySyntax: true,
      orderDirectives: true,
    );
    final helper = const AstHelper();

    if (File(augmentPath).existsSync()) {
      var source = await File(augmentPath).readAsString();

      // Add missing imports to the augmentation file
      for (final import in imports) {
        source = helper.addImport(source: source, importPath: import);
      }

      for (final member in members) {
        final memberSource = member.accept(emitter).toString();
        // Use a specialized request for augment class
        final request = AppendRequest.method(
          source: source,
          className: className,
          memberSource: memberSource,
        );
        final result = const AppendExecutor().execute(request);
        source = result.source;
      }

      return FileUtils.writeFile(
        augmentPath,
        source,
        'augmentation',
        force: true,
        dryRun: dryRun,
      );
    }

    final buffer = StringBuffer();
    buffer.writeln("// Generated by zfa - Augmentation Library");
    buffer.writeln("augment library '$hostFileName';");
    buffer.writeln();

    for (final import in imports) {
      buffer.writeln("import '$import';");
    }
    if (imports.isNotEmpty) buffer.writeln();

    // Note: code_builder doesn't natively support the 'augment' keyword yet
    // in its emitters for classes, so we wrap the class output.
    buffer.writeln("augment class $className {");
    for (final member in members) {
      final memberSource = member.accept(emitter).toString();
      // Indent member source
      final indented = memberSource.split('\n').map((l) => '  $l').join('\n');
      buffer.writeln(indented);
    }
    buffer.writeln("}");

    final content = buffer.toString();

    return FileUtils.writeFile(
      augmentPath,
      content,
      'augmentation',
      force:
          true, // Augmentations are always overwritten/regenerated in our model
      dryRun: dryRun,
    );
  }

  /// Removes methods from an augmentation file for the given [hostPath].
  Future<GeneratedFile?> remove({
    required String hostPath,
    required String className,
    required List<Spec> members,
    bool dryRun = false,
  }) async {
    final hostFileName = path.basename(hostPath);
    final augmentFileName = hostFileName.replaceFirst('.dart', '.augment.dart');
    final augmentPath = path.join(path.dirname(hostPath), augmentFileName);

    if (!File(augmentPath).existsSync()) return null;

    var source = await File(augmentPath).readAsString();
    final emitter = DartEmitter(
      useNullSafetySyntax: true,
      orderDirectives: true,
    );
    final helper = const AstHelper();

    for (final member in members) {
      final memberSource = member.accept(emitter).toString();
      final request = AppendRequest.method(
        source: source,
        className: className,
        memberSource: memberSource,
      );
      final result = const AppendExecutor().undo(request);
      source = result.source;
    }

    // If the class is now empty, delete the augmentation file
    if (helper.isClassEmpty(source, className)) {
      return FileUtils.deleteFile(augmentPath, 'augmentation', dryRun: dryRun);
    }

    return FileUtils.writeFile(
      augmentPath,
      source,
      'augmentation',
      force: true,
      dryRun: dryRun,
    );
  }
}
