// GENERATED - DO NOT EDIT
// Generated by zfa for: DynamicForm
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/dynamic_form/dynamic_form.dart';
import '../../repositories/dynamic_form_repository.dart';

class GetDynamicFormUseCase
    extends UseCase<DynamicForm, QueryParams<DynamicForm>> {
  GetDynamicFormUseCase(this._repository);

  final DynamicFormRepository _repository;

  @override
  Future<DynamicForm> execute(
    QueryParams<DynamicForm> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
