#!/usr/bin/env python3
"""
Generate human-readable MD Doctor report.
"""

import json
from pathlib import Path
from datetime import datetime

FACTS_FILE = Path("/Users/ahmettok/Developer/zuraffa/.specify/memory/md-doctor/facts.json")
REPORT_DIR = Path("/Users/ahmettok/Developer/zuraffa/.specify/memory/md-doctor/reports")
TODAY = datetime(2026, 8, 31)

def generate_report():
    """Generate the human-readable report."""
    # Load facts
    with open(FACTS_FILE) as f:
        data = json.load(f)
    
    files = data["files"]
    
    # Calculate statistics
    total_files = len(files)
    avg_truthfulness = sum(f["truthfulness"] for f in files) / total_files
    
    # Count by verdict
    verdicts = {}
    for f in files:
        v = f["verdict"]
        verdicts[v] = verdicts.get(v, 0) + 1
    
    # Count by action
    actions = {}
    for f in files:
        a = f["action"]
        actions[a] = actions.get(a, 0) + 1
    
    # Get most problematic files (lowest truthfulness)
    problematic = sorted(files, key=lambda x: x["truthfulness"])[:10]
    
    # Get best files (highest truthfulness)
    best = sorted(files, key=lambda x: x["truthfulness"], reverse=True)[:10]
    
    # Generate report
    report = f"""# MD Doctor Scan Report

**Generated**: {TODAY.strftime('%Y-%m-%d')}
**Total Files Scanned**: {total_files}
**Average Truthfulness**: {avg_truthfulness:.1f}/100

## Verdict Summary

| Verdict | Count | Percentage |
|---------|-------|------------|
"""
    
    for verdict in ["truthful", "stale", "false", "obsolete"]:
        count = verdicts.get(verdict, 0)
        percentage = (count / total_files) * 100
        report += f"| {verdict} | {count} | {percentage:.1f}% |\n"
    
    report += f"""
## Action Queue

| Action | Count | Description |
|--------|-------|-------------|
"""
    
    for action in ["keep", "update", "delete", "create"]:
        count = actions.get(action, 0)
        if action == "keep":
            desc = "File is truthful, no action needed"
        elif action == "update":
            desc = "File needs updating (stale or false claims)"
        elif action == "delete":
            desc = "File should be deleted (obsolete or false)"
        else:
            desc = "File should be created (missing documentation)"
        report += f"| {action} | {count} | {desc} |\n"
    
    report += f"""
## Most Problematic Files (Lowest Truthfulness)

| File | Truthfulness | Verdict | Rationale |
|------|--------------|---------|-----------|
"""
    
    for f in problematic:
        report += f"| {f['path']} | {f['truthfulness']} | {f['verdict']} | {f['rationale'][:60]}... |\n"
    
    report += f"""
## Best Files (Highest Truthfulness)

| File | Truthfulness | Verdict | Rationale |
|------|--------------|---------|-----------|
"""
    
    for f in best:
        report += f"| {f['path']} | {f['truthfulness']} | {f['verdict']} | {f['rationale'][:60]}... |\n"
    
    report += f"""
## Files Needing Update

The following files have been identified as needing updates:
"""
    
    update_files = [f for f in files if f["action"] == "update"]
    for f in update_files[:20]:  # Show first 20
        report += f"- **{f['path']}** (truthfulness: {f['truthfulness']})\n"
    
    if len(update_files) > 20:
        report += f"- ... and {len(update_files) - 20} more files\n"
    
    report += f"""
## Summary

The MD Doctor scan identified **{verdicts.get('false', 0)} false** files and **{verdicts.get('stale', 0)} stale** files that need attention. 
The average truthfulness score of {avg_truthfulness:.1f} indicates that while many files are accurate, 
there are significant gaps in documentation accuracy.

**Recommended Actions:**
1. Update {actions.get('update', 0)} files with stale or false claims
2. Review {actions.get('delete', 0)} files marked for deletion
3. Focus on files with truthfulness scores below 50

---
*Report generated by MD Doctor scan*
"""
    
    # Write report
    report_file = REPORT_DIR / f"scan-{TODAY.strftime('%Y%m%dT%H%M%S')}.md"
    with open(report_file, 'w') as f:
        f.write(report)
    
    print(f"Report generated: {report_file}")
    return report_file

if __name__ == "__main__":
    generate_report()
