// GENERATED - DO NOT EDIT
// Generated by zfa for: PriceAlert
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/price_alert/price_alert.dart';
import '../../repositories/price_alert_repository.dart';

class TogglePriceAlertUseCase
    extends
        UseCase<PriceAlert, ToggleParams<String, Field<PriceAlert, dynamic>>> {
  TogglePriceAlertUseCase(this._repository);

  final PriceAlertRepository _repository;

  @override
  Future<PriceAlert> execute(
    ToggleParams<String, Field<PriceAlert, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
