import 'package:path/path.dart' as path;

import '../../../core/builder/patterns/common_patterns.dart';
import '../../../core/context/file_system.dart';
import '../../../core/generator_options.dart';
import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/file_utils.dart';
import '../../../utils/string_utils.dart';

/// Generates FetchStrategy skeletons for a given domain.
///
/// Produces four categories of files for each strategy-enabled provider:
///
/// 1. **Abstract base** (`data/providers/{domain}/strategies/{name_snake}_strategy.dart`):
///    Domain-typed abstract class extending `FetchStrategy<Input, Output>`.
///
/// 2. **Concrete variants** (`data/providers/{domain}/strategies/{variant}_{name_snake}_strategy.dart`):
///    One file per named variant, each with `canHandle` and `fetchOne` stubs.
///
/// 3. **Selector** (`data/providers/{domain}/strategies/{name_snake}_strategy_selector.dart`):
///    Wires a `StrategySelector<Input, Output>` with constructor injection of
///    every concrete variant, in priority order.
///
/// Strategies live in `data/providers/{domain}/strategies/` — NOT in the domain
/// layer. They are data-layer concerns: they know about scraping internals,
/// channel configs, AI endpoints. The abstract `FetchStrategy<I, O>` in Zuraffa
/// core is the only domain-layer contract.
class StrategyBuilder {
  final String outputDir;
  final GeneratorOptions options;
  final FileSystem fileSystem;

  StrategyBuilder({
    required this.outputDir,
    this.options = const GeneratorOptions(),
    FileSystem? fileSystem,
  }) : fileSystem = fileSystem ?? FileSystem.create();

  /// Generates all strategy files for [config].
  Future<List<GeneratedFile>> generate(GeneratorConfig config) async {
    if (!config.enableStrategy || config.strategyNames.isEmpty) {
      return [];
    }

    final files = <GeneratedFile>[];

    files.add(await _generateAbstractBase(config));

    for (final variantName in config.strategyNames) {
      files.add(await _generateConcreteVariant(config, variantName));
    }

    files.add(await _generateSelector(config));

    return files;
  }

  /// `data/providers/{domain}/strategies/{name_snake}_strategy.dart`
  Future<GeneratedFile> _generateAbstractBase(GeneratorConfig config) async {
    final domain = config.effectiveDomain;
    final nameSnake = config.nameSnake;
    final className = config.name;
    final input = config.paramsType ?? 'dynamic';
    final output = config.returnsType ?? 'dynamic';
    final entityImportsStr = _buildEntityImports(config);

    final filePath = path.join(
      outputDir,
      'data',
      'providers',
      domain,
      'strategies',
      '${nameSnake}_strategy.dart',
    );

    final content =
        '''
// Generated by zfa strategy — do not delete. Extend this, never modify it.

import 'package:zuraffa/zuraffa.dart';
$entityImportsStr
/// Abstract strategy for the [$className] fetch domain.
///
/// Extend this for each concrete pipeline variant (scraper, AI, cache, etc.).
/// The [StrategySelector] in `${nameSnake}_strategy_selector.dart` wires all
/// variants together, evaluating [canHandle] in priority order at runtime.
///
/// Selection logic belongs in [canHandle]. Fetch logic belongs in [fetchOne].
/// Never put pipeline-selection conditionals in a [${className}Strategy] subclass.
abstract class ${className}Strategy extends FetchStrategy<$input, $output> {}
''';

    return FileUtils.writeFile(
      filePath,
      content,
      'strategy_base',
      force: config.force,
      dryRun: config.dryRun,
      verbose: config.verbose,
      revert: config.revert,
      fileSystem: fileSystem,
    );
  }

  /// `data/providers/{domain}/strategies/{variant}_{name_snake}_strategy.dart`
  Future<GeneratedFile> _generateConcreteVariant(
    GeneratorConfig config,
    String variantName,
  ) async {
    final domain = config.effectiveDomain;
    final nameSnake = config.nameSnake;
    final className = config.name;
    final variantPascal = StringUtils.convertToPascalCase(
      StringUtils.camelToSnake(variantName),
    );
    final variantSnake = StringUtils.camelToSnake(variantName);
    final input = config.paramsType ?? 'dynamic';
    final output = config.returnsType ?? 'dynamic';
    final concreteClass = '$variantPascal${className}Strategy';
    final entityImportsStr = _buildEntityImports(config);

    final filePath = path.join(
      outputDir,
      'data',
      'providers',
      domain,
      'strategies',
      '${variantSnake}_${nameSnake}_strategy.dart',
    );

    final content =
        '''
// Generated by zfa strategy — implement the TODOs, then remove this comment.

import 'package:zuraffa/zuraffa.dart';
$entityImportsStr
import '${nameSnake}_strategy.dart';

/// [$variantPascal] pipeline implementation for the [$className] fetch domain.
///
/// [canHandle]: returns true when this strategy is applicable to the input.
///   This is the ONLY place that asks "should I run?". Do not put selection
///   logic in [fetchOne] — it must be pure execution.
///
/// [fetchOne]: executes the [$variantPascal] pipeline and returns a single
///   [$output] for the given [$input]. Throw an [AppFailure] subclass for
///   expected/recoverable errors; let unexpected exceptions propagate.
class $concreteClass extends ${className}Strategy {
  // TODO: inject the dependencies this strategy needs.
  // Do NOT inject the parent provider — that creates a circular dependency.
  // Inject only the low-level collaborators (repositories, services, clients).
  const $concreteClass();

  @override
  String get name => '$concreteClass';

  @override
  Future<bool> canHandle($input input) async {
    // TODO: implement selection logic.
    // Return true  → this strategy will be selected.
    // Return false → the selector moves to the next candidate.
    throw UnimplementedError('$concreteClass.canHandle is not implemented');
  }

  @override
  Future<$output> fetchOne($input input, {CancelToken? cancelToken}) async {
    // TODO: implement fetch logic.
    throw UnimplementedError('$concreteClass.fetchOne is not implemented');
  }
}
''';

    return FileUtils.writeFile(
      filePath,
      content,
      'strategy_variant',
      force: config.force,
      dryRun: config.dryRun,
      verbose: config.verbose,
      revert: config.revert,
      fileSystem: fileSystem,
    );
  }

  /// `data/providers/{domain}/strategies/{name_snake}_strategy_selector.dart`
  Future<GeneratedFile> _generateSelector(GeneratorConfig config) async {
    final domain = config.effectiveDomain;
    final nameSnake = config.nameSnake;
    final className = config.name;
    final input = config.paramsType ?? 'dynamic';
    final output = config.returnsType ?? 'dynamic';
    final entityImportsStr = _buildEntityImports(config);

    final filePath = path.join(
      outputDir,
      'data',
      'providers',
      domain,
      'strategies',
      '${nameSnake}_strategy_selector.dart',
    );

    // Build imports and constructor params
    final imports = config.strategyNames
        .map((v) {
          final snake = StringUtils.camelToSnake(v);
          return "import '${snake}_${nameSnake}_strategy.dart';";
        })
        .join('\n');

    final constructorParams = config.strategyNames
        .map((v) {
          final pascal = StringUtils.convertToPascalCase(
            StringUtils.camelToSnake(v),
          );
          final camel = StringUtils.pascalToCamel(pascal);
          return '    required $pascal${className}Strategy $camel,';
        })
        .join('\n');

    final superList = config.strategyNames
        .map((v) {
          final pascal = StringUtils.convertToPascalCase(
            StringUtils.camelToSnake(v),
          );
          return StringUtils.pascalToCamel(pascal);
        })
        .join(', ');

    final content =
        '''
// Generated by zfa strategy — wire your DI container to this selector.

import 'package:zuraffa/zuraffa.dart';
$entityImportsStr
import '${nameSnake}_strategy.dart';
$imports

/// Wires all [${className}Strategy] variants and selects the first applicable
/// one at runtime, in priority order.
///
/// Priority (highest → lowest):
${config.strategyNames.map((v) => '///   - ${StringUtils.convertToPascalCase(StringUtils.camelToSnake(v))}${className}Strategy').join('\n')}
///
/// Register this as a singleton in your DI container and inject it into the
/// use case or provider that drives the [$className] fetch pipeline.
class ${className}StrategySelector extends StrategySelector<$input, $output> {
  ${className}StrategySelector({
$constructorParams
  }) : super([$superList]);
}
''';

    return FileUtils.writeFile(
      filePath,
      content,
      'strategy_selector',
      force: config.force,
      dryRun: config.dryRun,
      verbose: config.verbose,
      revert: config.revert,
      fileSystem: fileSystem,
    );
  }

  /// Resolves entity import statements for [config.paramsType] and [config.returnsType].
  ///
  /// Uses [CommonPatterns.entityImports] to resolve types to their entity file paths,
  /// skipping known types (String, int, dynamic, etc.). The depth is 4 levels up
  /// because generated files live in `data/providers/{domain}/strategies/`.
  String _buildEntityImports(GeneratorConfig config) {
    final importPaths = CommonPatterns.entityImports(
      [config.paramsType, config.returnsType],
      config,
      depth: 4,
      fileSystem: fileSystem,
    );
    if (importPaths.isEmpty) return '';
    return '${importPaths.map((p) => "import '$p';").join('\n')}\n';
  }
}
