// Generated by zfa for: Feedback
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'feedback_controller.dart';
import 'feedback_presenter.dart';

class FeedbackView extends CleanView {
  const FeedbackView({super.key, super.routeObserver});

  @override
  State<FeedbackView> createState() {
    return _FeedbackViewState(FeedbackController(FeedbackPresenter()));
  }
}

class _FeedbackViewState
    extends CleanViewState<FeedbackView, FeedbackController, void> {
  _FeedbackViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('Feedback')),
      body: ControlledWidgetBuilder<FeedbackController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
