// Auto-generated by Zorphy
// Generated at: 2026-08-13T13:46:01.937624

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'listing_offer.zorphy.dart';
part 'listing_offer.g.dart';

/// ListingOffer entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $ListingOffer {
  String? get id;
  String? get code;
  double? get price;
  double? get originalPrice;
  double? get unitPrice;
  String? get unitPriceText;
  String? get url;
  String? get website;
  String? get seller;
  String? get sellerId;
  String? get title;
  double? get sellerScore;
  String? get availability;
  double? get shippingCost;
  String? get shippingInfo;
  String? get sellerIcon;
  List<String>? get badges;
  String? get brand;
  String? get sku;
  String? get imageUrl;
  List<String>? get images;
  double? get ratingScore;
  int? get reviewCount;
  String? get productId;
}
