#!/usr/bin/env bash
# Copy the current zread wiki into the published static site.
#
# Source of truth: .zread/wiki/ (regenerated by `zread generate`).
# Destination:     website/static/docs/ — the markdown is generated, not
#                  committed (see .gitignore); only the viewer index.html is.
#
# Used by the GitHub Pages workflows and for local preview:
#   bash tools/sync-website-docs.sh
#   (cd website/static && python3 -m http.server 8899)  # → /docs/
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
wiki="$root/.zread/wiki"
dest="$root/website/static/docs"

current="$wiki/current"
if [ ! -f "$current" ]; then
  echo "error: $current not found — run 'zread generate' first" >&2
  exit 1
fi

rel="$(tr -d '[:space:]' < "$current")"
case "$rel" in
  versions/*) src="$wiki/$rel" ;;
  *)          src="$wiki/versions/$rel" ;;
esac

if [ ! -d "$src" ]; then
  echo "error: wiki version directory not found: $src" >&2
  exit 1
fi
if [ ! -f "$src/wiki.json" ]; then
  echo "error: $src/wiki.json not found — the viewer needs the page index" >&2
  exit 1
fi
if [ ! -f "$dest/index.html" ]; then
  echo "error: $dest/index.html not found — the docs viewer is missing" >&2
  exit 1
fi

mkdir -p "$dest"
rm -f "$dest"/*.md "$dest"/wiki.json
cp "$src"/*.md "$src/wiki.json" "$dest"/

echo "synced $(basename "$src") → website/static/docs ($(ls -1 "$dest"/*.md | wc -l | tr -d ' ') pages)"
