/// Emits one [McpTool] subclass Dart source file per UseCase (FR-005, SC-001).
///
/// The emitted file lives at `lib/src/agent/tools/{entity}_{verb}_tool.dart`
/// and contains:
///   - imports for `McpTool`, `McpToolResult`, `getIt`, and the
///     UseCase + Params types
///   - a `class {Verb}{Entity}Tool extends McpTool` with the canonical
///     tool name, description, inputSchema, outputSchema, and a `call`
///     method that resolves the UseCase from `getIt`, invokes it, and
///     wraps the result into an `McpToolResult`.
library;

import 'dart:convert';

import 'schema_deriver.dart';
import 'usecase_introspector.dart';

/// Emits a single tool wrapper file's source code.
class ToolWrapperEmitter {
  /// Namespace prefix for the tool name (e.g. `app`).
  final String namespace;

  /// Snake-case entity name (e.g. `listing`).
  final String entitySnake;

  /// The host app's package import root, e.g. `package:my_app/`.
  /// Used to import the generated UseCase + Params types.
  final String packageRoot;

  const ToolWrapperEmitter({
    required this.namespace,
    required this.entitySnake,
    required this.packageRoot,
  });

  /// Emits the wrapper source for [metadata].
  ///
  /// Returns a (filename, source) pair where filename is
  /// `{entitySnake}_{verb}_tool.dart` and source is the formatted Dart
  /// source.
  ({String fileName, String source}) emit(UseCaseMetadata metadata) {
    final className = metadata.className; // e.g. CreateListingUseCase
    final pascal = _toPascalCase(metadata.verb); // e.g. Create
    final toolClassName = '$pascal${_toPascalCase(entitySnake)}Tool';
    final fileName = '${entitySnake}_${metadata.verb}_tool.dart';
    final toolName = '$namespace.$entitySnake.${metadata.verb}';

    // Derive schemas.
    final deriver = const SchemaDeriver();
    final inputSchema = _deriveInputSchema(metadata, deriver);
    final outputSchema = deriver.derive(metadata.returnType);

    final inputSchemaJson = const JsonEncoder.withIndent(
      '  ',
    ).convert(inputSchema);
    final outputSchemaJson = const JsonEncoder.withIndent(
      '  ',
    ).convert(outputSchema);

    final description =
        '${metadata.verb} $entitySnake via $className (generated by AgentPlugin).';

    final source =
        '''
import 'dart:convert';

import 'package:get_it/get_it.dart';
import 'package:zuraffa/src/core/module/mcp_tool.dart';

import '$packageRoot/domain/usecases/$entitySnake/${_snakeFromClassName(className)}.dart';

/// Generated MCP tool wrapper for [$className].
///
/// Auto-generated by [AgentPlugin] (specs/029-agent-plugin-mcp-wrappers).
/// DO NOT EDIT inside the GENERATED markers — manual edits outside markers
/// survive regeneration.
class $toolClassName extends McpTool {
  const $toolClassName();

  @override
  String get name => ${_dartStringLiteral(toolName)};

  @override
  String get description => ${_dartStringLiteral(description)};

  @override
  Map<String, dynamic> get inputSchema =>
      const <String, dynamic>$inputSchemaJson;

  Map<String, dynamic>? get outputSchema =>
      const <String, dynamic>$outputSchemaJson;

  @override
  Future<McpToolResult> call(Map<String, dynamic> arguments) async {
    try {
      final useCase = getIt<$className>();
      final params = _buildParams(arguments);
      final result = await useCase.call(params);
      return McpToolResult(
        text: jsonEncode({'ok': true, 'result': _safeEncode(result)}),
        data: <String, dynamic>{'result': result},
      );
    } catch (e, st) {
      return McpToolResult(
        isError: true,
        text: 'Error invoking \$toolName: \$e\\n\$st',
      );
    }
  }

  /// Builds the UseCase's Params from the args map. The exact mapping is
  /// UseCase-specific; the default impl passes the args map through to
  /// a `Params.fromJson(arguments)` factory if available, falling back
  /// to direct construction.
  dynamic _buildParams(Map<String, dynamic> arguments) {
    // Pass through to the usecase's expected Params type. The UseCase's
    // Params type MAY provide a fromJson; if not, callers can override
    // _buildParams in a manually-written subclass outside the markers.
    return arguments;
  }

  dynamic _safeEncode(dynamic v) {
    try {
      jsonEncode(v);
      return v;
    } catch (_) {
      return v.toString();
    }
  }
}
''';

    return (fileName: fileName, source: source);
  }

  Map<String, dynamic> _deriveInputSchema(
    UseCaseMetadata metadata,
    SchemaDeriver deriver,
  ) {
    if (metadata.paramsFields.isEmpty) {
      // If the UseCase's Params type is the entity itself (e.g.
      // `UseCase<Listing, Listing>`) or a NoParams-style class, fall back
      // to an empty object schema or derive from the params type name.
      if (metadata.paramsType == 'NoParams' ||
          metadata.paramsType == 'void' ||
          metadata.paramsType == 'Null') {
        return {'type': 'object', 'properties': {}};
      }
      return deriver.derive(metadata.paramsType);
    }
    final properties = <String, dynamic>{};
    final required = <String>[];
    for (final f in metadata.paramsFields) {
      properties[f.name] = deriver.derive(f.type);
      if (f.isRequired) required.add(f.name);
    }
    return {
      'type': 'object',
      'properties': properties,
      if (required.isNotEmpty) 'required': required,
    };
  }

  String _toPascalCase(String s) {
    if (s.isEmpty) return s;
    return s[0].toUpperCase() + s.substring(1);
  }

  String _snakeFromClassName(String className) {
    // Convert e.g. CreateListingUseCase → create_listing_usecase
    // (we keep the entity-name boundary that's already present in the
    // generated file naming convention).
    final buf = StringBuffer();
    for (var i = 0; i < className.length; i++) {
      final c = className[i];
      if (c.toUpperCase() == c && c.toLowerCase() != c) {
        if (i > 0) buf.write('_');
        buf.write(c.toLowerCase());
      } else {
        buf.write(c);
      }
    }
    return buf.toString().toLowerCase();
  }

  /// Returns a Dart string literal for [s] with proper escaping.
  String _dartStringLiteral(String s) {
    final escaped = s
        .replaceAll(r'\\', r'\\\\')
        .replaceAll("'", r"\'")
        .replaceAll('\n', r'\n')
        .replaceAll('\r', r'\r')
        .replaceAll('\t', r'\t');
    return "'$escaped'";
  }
}
