// GENERATED - DO NOT EDIT
// Generated by zfa for: FormOption
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/form_option/form_option.dart';
import '../../repositories/form_option_repository.dart';

class UpdateFormOptionUseCase
    extends UseCase<FormOption, UpdateParams<String, FormOptionPatch>> {
  UpdateFormOptionUseCase(this._repository);

  final FormOptionRepository _repository;

  @override
  Future<FormOption> execute(
    UpdateParams<String, FormOptionPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
