// GENERATED - DO NOT EDIT
// Generated by zfa for: GroceryItem
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/grocery_item/grocery_item.dart';
import '../../repositories/grocery_item_repository.dart';

class ToggleGroceryItemUseCase
    extends
        UseCase<
          GroceryItem,
          ToggleParams<String, Field<GroceryItem, dynamic>>
        > {
  ToggleGroceryItemUseCase(this._repository);

  final GroceryItemRepository _repository;

  @override
  Future<GroceryItem> execute(
    ToggleParams<String, Field<GroceryItem, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
