// Generated by zfa for: ExtractedInvoice
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'extracted_invoice_controller.dart';
import 'extracted_invoice_presenter.dart';

class ExtractedInvoiceView extends CleanView {
  const ExtractedInvoiceView({super.key, super.routeObserver});

  @override
  State<ExtractedInvoiceView> createState() {
    return _ExtractedInvoiceViewState(
      ExtractedInvoiceController(ExtractedInvoicePresenter()),
    );
  }
}

class _ExtractedInvoiceViewState
    extends
        CleanViewState<ExtractedInvoiceView, ExtractedInvoiceController, void> {
  _ExtractedInvoiceViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('ExtractedInvoice')),
      body: ControlledWidgetBuilder<ExtractedInvoiceController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
