// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomerAddress
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/customer_address/customer_address.dart';
import '../../repositories/customer_address_repository.dart';

class GetCustomerAddressUseCase
    extends UseCase<CustomerAddress, QueryParams<CustomerAddress>> {
  GetCustomerAddressUseCase(this._repository);

  final CustomerAddressRepository _repository;

  @override
  Future<CustomerAddress> execute(
    QueryParams<CustomerAddress> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
