// GENERATED - DO NOT EDIT
// Generated by zfa for: CustomerAddress
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/customer_address/customer_address.dart';
import '../../repositories/customer_address_repository.dart';

class UpdateCustomerAddressUseCase
    extends
        UseCase<CustomerAddress, UpdateParams<String, CustomerAddressPatch>> {
  UpdateCustomerAddressUseCase(this._repository);

  final CustomerAddressRepository _repository;

  @override
  Future<CustomerAddress> execute(
    UpdateParams<String, CustomerAddressPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
