// GENERATED - DO NOT EDIT
// Generated by zfa for: AiConversation
// zfa make AiConversation --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/ai_conversation/ai_conversation.dart';

abstract class AiConversationRepository {
  Future<AiConversation> get(QueryParams<AiConversation> params);
  Future<AiConversation> update(
    UpdateParams<String, AiConversationPatch> params,
  );
  Future<AiConversation> toggle(
    ToggleParams<String, Field<AiConversation, dynamic>> params,
  );
}

// END GENERATED
