// GENERATED - DO NOT EDIT
// Generated by zfa for: BarcodeListing
// zfa make BarcodeListing --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/barcode_listing/barcode_listing.dart';

abstract class BarcodeListingRepository {
  Future<BarcodeListing> get(QueryParams<BarcodeListing> params);
  Future<BarcodeListing> update(
    UpdateParams<String, BarcodeListingPatch> params,
  );
  Future<BarcodeListing> toggle(
    ToggleParams<String, Field<BarcodeListing, dynamic>> params,
  );
}

// END GENERATED
