// GENERATED - DO NOT EDIT
// Generated by zfa for: ErrorLog
// zfa make ErrorLog --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/error_log/error_log.dart';

abstract class ErrorLogRepository {
  Future<ErrorLog> get(QueryParams<ErrorLog> params);
  Future<ErrorLog> update(UpdateParams<String, ErrorLogPatch> params);
  Future<ErrorLog> toggle(
    ToggleParams<String, Field<ErrorLog, dynamic>> params,
  );
}

// END GENERATED
