// GENERATED - DO NOT EDIT
// Generated by zfa for: Feedback
// zfa make Feedback --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/feedback/feedback.dart';

abstract class FeedbackRepository {
  Future<Feedback> get(QueryParams<Feedback> params);
  Future<Feedback> update(UpdateParams<String, FeedbackPatch> params);
  Future<Feedback> toggle(
    ToggleParams<String, Field<Feedback, dynamic>> params,
  );
}

// END GENERATED
