// GENERATED - DO NOT EDIT
// Generated by zfa for: FormSubmission
// zfa make FormSubmission --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/form_submission/form_submission.dart';

abstract class FormSubmissionRepository {
  Future<FormSubmission> get(QueryParams<FormSubmission> params);
  Future<FormSubmission> update(
    UpdateParams<String, FormSubmissionPatch> params,
  );
  Future<FormSubmission> toggle(
    ToggleParams<String, Field<FormSubmission, dynamic>> params,
  );
}

// END GENERATED
