// GENERATED - DO NOT EDIT
// Generated by zfa for: FormOption
// zfa make FormOption --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/form_option/form_option.dart';

abstract class FormOptionRepository {
  Future<FormOption> get(QueryParams<FormOption> params);
  Future<FormOption> update(UpdateParams<String, FormOptionPatch> params);
  Future<FormOption> toggle(
    ToggleParams<String, Field<FormOption, dynamic>> params,
  );
}

// END GENERATED
