// GENERATED - DO NOT EDIT
// Generated by zfa for: Listing
// zfa make Listing --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/listing/listing.dart';

abstract class ListingRepository {
  Future<Listing> get(QueryParams<Listing> params);
  Future<Listing> update(UpdateParams<String, ListingPatch> params);
  Future<Listing> toggle(ToggleParams<String, Field<Listing, dynamic>> params);
}

// END GENERATED
