// GENERATED - DO NOT EDIT
// Generated by zfa for: PriceCheckInvoice
// zfa make PriceCheckInvoice --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/price_check_invoice/price_check_invoice.dart';

abstract class PriceCheckInvoiceRepository {
  Future<PriceCheckInvoice> get(QueryParams<PriceCheckInvoice> params);
  Future<PriceCheckInvoice> update(
    UpdateParams<String, PriceCheckInvoicePatch> params,
  );
  Future<PriceCheckInvoice> toggle(
    ToggleParams<String, Field<PriceCheckInvoice, dynamic>> params,
  );
}

// END GENERATED
