// GENERATED - DO NOT EDIT
// Generated by zfa for: PriceDropNotification
// zfa make PriceDropNotification --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/price_drop_notification/price_drop_notification.dart';

abstract class PriceDropNotificationRepository {
  Future<PriceDropNotification> get(QueryParams<PriceDropNotification> params);
  Future<PriceDropNotification> update(
    UpdateParams<String, PriceDropNotificationPatch> params,
  );
  Future<PriceDropNotification> toggle(
    ToggleParams<String, Field<PriceDropNotification, dynamic>> params,
  );
}

// END GENERATED
