// GENERATED - DO NOT EDIT
// Generated by zfa for: TextSpark
// zfa make TextSpark --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/text_spark/text_spark.dart';

abstract class TextSparkRepository {
  Future<TextSpark> get(QueryParams<TextSpark> params);
  Future<TextSpark> update(UpdateParams<String, TextSparkPatch> params);
  Future<TextSpark> toggle(
    ToggleParams<String, Field<TextSpark, dynamic>> params,
  );
}

// END GENERATED
