// GENERATED - DO NOT EDIT
// Generated by zfa for: User
// zfa make User --methods=get,update,toggle --repository
import 'package:zuraffa/zuraffa.dart';

import '../entities/user/user.dart';

abstract class UserRepository {
  Future<User> get(QueryParams<User> params);
  Future<User> update(UpdateParams<String, UserPatch> params);
  Future<User> toggle(ToggleParams<String, Field<User, dynamic>> params);
}

// END GENERATED
