// GENERATED - DO NOT EDIT
// Generated by zfa for: AppConfig
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/app_config/app_config.dart';
import '../../repositories/app_config_repository.dart';

class GetAppConfigUseCase extends UseCase<AppConfig, QueryParams<AppConfig>> {
  GetAppConfigUseCase(this._repository);

  final AppConfigRepository _repository;

  @override
  Future<AppConfig> execute(
    QueryParams<AppConfig> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
