// GENERATED - DO NOT EDIT
// Generated by zfa for: AppConfig
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/app_config/app_config.dart';
import '../../repositories/app_config_repository.dart';

class ToggleAppConfigUseCase
    extends
        UseCase<AppConfig, ToggleParams<String, Field<AppConfig, dynamic>>> {
  ToggleAppConfigUseCase(this._repository);

  final AppConfigRepository _repository;

  @override
  Future<AppConfig> execute(
    ToggleParams<String, Field<AppConfig, dynamic>> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.toggle(params);
  }
}

// END GENERATED
