// Auto-generated by Zorphy
// Generated at: 2026-08-13T13:45:31.988344

import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'walkthrough_step.zorphy.dart';
part 'walkthrough_step.g.dart';

/// WalkthroughStep entity
@Zorphy(generateJson: true, generateCompareTo: true)
abstract class $WalkthroughStep {
  String get id;
  String get title;
  String get description;
  String? get imagePath;
  String? get iconPath;
  int get order;
  String? get buttonText;
  String? get targetWidget;
}
