// GENERATED - DO NOT EDIT
// Generated by zfa for: Category
import 'dart:async';

import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/category/category.dart';
import '../../mock/category_mock_data.dart';
import 'category_datasource.dart';

/// Mock data source for Category
class CategoryMockDataSource
    with Loggable, FailureHandler
    implements CategoryDataSource {
  CategoryMockDataSource([Duration? delay])
    : _delay = delay ?? const Duration(milliseconds: 100);

  final Duration _delay;

  @override
  Future<Category> get(QueryParams<Category> params) async {
    logger.info('Getting Category with params: $params');
    await Future.delayed(_delay);
    final item = CategoryMockData.categorys.query(params);
    logger.info('Successfully retrieved Category');
    return item;
  }

  @override
  Future<Category> update(UpdateParams<String, CategoryPatch> params) async {
    logger.info('Updating Category: ${params.id}');
    await Future.delayed(_delay);
    final existing = CategoryMockData.sampleCategory;
    logger.info('Successfully updated Category');
    return existing;
  }

  @override
  Future<Category> toggle(
    ToggleParams<String, Field<Category, dynamic>> params,
  ) async {
    logger.info('Toggling Category: ${params.id} on field ${params.field}');
    await Future.delayed(_delay);
    final existing = CategoryMockData.sampleCategory;
    logger.info('Successfully toggled Category');
    return existing;
  }
}

// END GENERATED
