// GENERATED - DO NOT EDIT
// Generated by zfa for: GrocerySubVariety
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/grocery_sub_variety/grocery_sub_variety.dart';
import '../../repositories/grocery_sub_variety_repository.dart';

class GetGrocerySubVarietyUseCase
    extends UseCase<GrocerySubVariety, QueryParams<GrocerySubVariety>> {
  GetGrocerySubVarietyUseCase(this._repository);

  final GrocerySubVarietyRepository _repository;

  @override
  Future<GrocerySubVariety> execute(
    QueryParams<GrocerySubVariety> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.get(params);
  }
}

// END GENERATED
