// GENERATED - DO NOT EDIT
// Generated by zfa for: GrocerySubVariety
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/grocery_sub_variety/grocery_sub_variety.dart';
import '../../repositories/grocery_sub_variety_repository.dart';

class UpdateGrocerySubVarietyUseCase
    extends
        UseCase<
          GrocerySubVariety,
          UpdateParams<String, GrocerySubVarietyPatch>
        > {
  UpdateGrocerySubVarietyUseCase(this._repository);

  final GrocerySubVarietyRepository _repository;

  @override
  Future<GrocerySubVariety> execute(
    UpdateParams<String, GrocerySubVarietyPatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
