// GENERATED - DO NOT EDIT
// Generated by zfa for: PriceCheckInvoice
import 'package:zuraffa/zuraffa.dart';

import '../../../domain/entities/price_check_invoice/price_check_invoice.dart';
import '../../repositories/price_check_invoice_repository.dart';

class UpdatePriceCheckInvoiceUseCase
    extends
        UseCase<
          PriceCheckInvoice,
          UpdateParams<String, PriceCheckInvoicePatch>
        > {
  UpdatePriceCheckInvoiceUseCase(this._repository);

  final PriceCheckInvoiceRepository _repository;

  @override
  Future<PriceCheckInvoice> execute(
    UpdateParams<String, PriceCheckInvoicePatch> params,
    CancelToken? cancelToken,
  ) async {
    cancelToken?.throwIfCancelled();
    return _repository.update(params);
  }
}

// END GENERATED
