// Auto-generated by Zorphy
// Generated at: 2026-08-14T10:19:31.129337

import 'package:zorphy_annotation/zorphy_annotation.dart';
import 'package:uuid/uuid.dart';
import '../locale/locale.dart';

part 'zik_zak_config.zorphy.dart';
part 'zik_zak_config.g.dart';

/// ZikZakConfig entity
@Zorphy(autoId: true, generateJson: true, generateCompareTo: true)
abstract class $ZikZakConfig {
  String get id;
  String get environment;
  String get mode;
  String get logLevel;
  $Locale get locale;
}
