import 'package:path/path.dart' as path;

import '../../../models/generated_file.dart';
import '../../../models/generator_config.dart';
import '../../../utils/file_utils.dart';

class DataSourceInterfaceGenerator {
  final String outputDir;
  final bool dryRun;
  final bool force;
  final bool verbose;

  DataSourceInterfaceGenerator({
    required this.outputDir,
    required this.dryRun,
    required this.force,
    required this.verbose,
  });

  Future<GeneratedFile> generate(GeneratorConfig config) async {
    final entityName = config.name;
    final entitySnake = config.nameSnake;
    final entityCamel = config.nameCamel;
    final dataSourceName = '${entityName}DataSource';
    final fileName = '${entitySnake}_data_source.dart';

    final dataSourceDirPath = path.join(
      outputDir,
      'data',
      'data_sources',
      entitySnake,
    );
    final filePath = path.join(dataSourceDirPath, fileName);

    final methods = <String>[];

    if (config.generateInit) {
      methods.add('  Stream<bool> get isInitialized;');
      methods.add('  Future<void> initialize(InitializationParams params);');
    }

    for (final method in config.methods) {
      switch (method) {
        case 'get':
          methods.add(
            '  Future<$entityName> get(QueryParams<$entityName> params);',
          );
          break;
        case 'getList':
          methods.add(
            '  Future<List<$entityName>> getList(ListQueryParams<$entityName> params);',
          );
          break;
        case 'create':
          methods.add('  Future<$entityName> create($entityName $entityCamel);');
          break;
        case 'update':
          final dataType = config.useZorphy
              ? '${config.name}Patch'
              : 'Partial<${config.name}>';
          methods.add(
            '  Future<${config.name}> update(UpdateParams<${config.idType}, $dataType> params);',
          );
          break;
        case 'delete':
          methods.add(
            '  Future<void> delete(DeleteParams<${config.idType}> params);',
          );
          break;
        case 'watch':
          methods.add(
            '  Stream<$entityName> watch(QueryParams<$entityName> params);',
          );
          break;
        case 'watchList':
          methods.add(
            '  Stream<List<$entityName>> watchList(ListQueryParams<$entityName> params);',
          );
          break;
      }
    }

    final content =
        '''
// Generated by zfa
// zfa generate $entityName --methods=${config.methods.join(',')} --data

import 'package:zuraffa/zuraffa.dart';
import '../../../domain/entities/$entitySnake/$entitySnake.dart';

abstract class $dataSourceName with Loggable, FailureHandler {
${methods.join('\n')}
}
''';

    return FileUtils.writeFile(
      filePath,
      content,
      'datasource',
      force: force,
      dryRun: dryRun,
      verbose: verbose,
    );
  }

}
