// Issue #626 — zfa setup ships a red day-zero baseline.
//
// The spec 041 gates, executed end-to-end against a real `zfa setup` run in
// a temp sandbox:
//
//   FR-006 (the day-zero gate): after `zfa setup <app>` finishes,
//   `flutter test` invoked from inside the generated project MUST exit 0.
//
//   FR-001 + the naming contract (maintainer decision recorded on #626):
//   the smoke test asserts the zfa-generated app module — a DI container
//   whose symbol derives from the app name (`zik_zak_tdd` →
//   `ZikZakTddContainer`) — emitted at `lib/app.dart` by `zfa setup`.
//
//   Upgrade path: `zfa app shell` succeeds on a fresh setup (bootstrap DI)
//   and the smoke test stays green after the upgrade.
//
// Spec 1395 adds the dependency-declaration gate: the day-zero app module
// imports `package:zuraffa_flutter/zuraffa_flutter.dart` and uses `GetIt`,
// so the SAME pass that writes the module must declare `zuraffa_flutter` +
// `get_it` under `dependencies:` (idempotently) and the fresh tree must
// `dart analyze` with 0 errors — the #942 build gate's severity contract,
// which the acceptance composition (A2 phase 2) refuses on otherwise.
//
// These tests spawn `flutter create` / `flutter pub get` / `flutter test`
// and are therefore tagged slow + integration.
@Tags(['slow', 'integration'])
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../helpers/run_zfa_source.dart';

void main() {
  setUpAll(() async {
    await initZfaSourceBin();
  });

  group(
    'day-zero smoke gate (issue #626, spec 041 FR-006)',
    timeout: const Timeout(Duration(minutes: 12)),
    () {
      test(
        'fresh zfa setup emits the app-name container and flutter test exits 0',
        () async {
          final sandbox = await Directory.systemTemp.createTemp(
            'zfa_dayzero_gate_',
          );
          try {
            const app = 'zik_zak_tdd';
            final appDir = p.join(sandbox.path, app);

            final setup = await runZfaSource([
              'setup',
              app,
              '--platforms=linux',
              '--no-git',
            ], workingDirectory: sandbox.path);
            expect(
              setup.exitCode,
              0,
              reason: 'zfa setup must succeed: ${combinedOutput(setup)}',
            );
            expect(combinedOutput(setup), contains('Setup complete!'));

            // FR-001 + naming contract: the zfa-attributable app module
            // must exist day zero and expose the app-name-derived
            // container symbol the smoke test asserts.
            final appModule = File(p.join(appDir, 'lib', 'app.dart'));
            expect(
              appModule.existsSync(),
              isTrue,
              reason:
                  'zfa setup must emit lib/app.dart (the day-zero app '
                  'module asserted by the smoke test)',
            );
            final appModuleSrc = appModule.readAsStringSync();
            expect(
              appModuleSrc,
              contains('class ZikZakTddContainer'),
              reason:
                  'the container symbol derives from the app name '
                  '(PascalCase + Container)',
            );
            expect(
              appModuleSrc,
              contains('Generated by zfa'),
              reason: 'the emitted app surface must be zfa-attributable',
            );

            final smoke = File(
              p.join(appDir, 'test', 'bootstrap_smoke_test.dart'),
            );
            expect(smoke.existsSync(), isTrue);
            expect(
              smoke.readAsStringSync(),
              contains('ZikZakTddContainer'),
              reason: 'the smoke test asserts the exact container symbol',
            );

            // FR-006: the day-zero suite must be green immediately.
            final flutterTest = await _runFlutterTest(appDir);
            expect(
              flutterTest.exitCode,
              0,
              reason:
                  'FR-006: flutter test must exit 0 right after zfa setup '
                  '(day-zero baseline must be green). Output:\n'
                  '${combinedOutput(flutterTest)}',
            );
          } finally {
            if (sandbox.existsSync()) {
              await sandbox.delete(recursive: true);
            }
          }
        },
      );

      test(
        'upgrade path: zfa app shell succeeds on a fresh setup and stays green',
        () async {
          final sandbox = await Directory.systemTemp.createTemp(
            'zfa_dayzero_upgrade_',
          );
          try {
            const app = 'zik_zak_tdd';
            final appDir = p.join(sandbox.path, app);

            final setup = await runZfaSource([
              'setup',
              app,
              '--platforms=linux',
              '--no-git',
            ], workingDirectory: sandbox.path);
            expect(
              setup.exitCode,
              0,
              reason: 'zfa setup must succeed: ${combinedOutput(setup)}',
            );

            // The upgrade must not require an entity first (bootstrap DI).
            final shell = await runZfaSource([
              'app',
              'shell',
            ], workingDirectory: appDir);
            expect(
              shell.exitCode,
              0,
              reason:
                  'zfa app shell must succeed on a fresh setup via the '
                  'bootstrap DI index. Output:\n${combinedOutput(shell)}',
            );

            // The smoke test must still pass after the upgrade.
            final flutterTest = await _runFlutterTest(appDir);
            expect(
              flutterTest.exitCode,
              0,
              reason:
                  'the day-zero smoke test must stay green after the '
                  'app-shell upgrade. Output:\n${combinedOutput(flutterTest)}',
            );
          } finally {
            if (sandbox.existsSync()) {
              await sandbox.delete(recursive: true);
            }
          }
        },
      );
    },
  );

  group(
    'spec 1395: the day-zero app module declares its deps (setup pass)',
    timeout: const Timeout(Duration(minutes: 12)),
    () {
      test('fresh zfa setup declares zuraffa_flutter + get_it and dart analyze '
          'reports 0 errors; a re-run does not duplicate', () async {
        final sandbox = await Directory.systemTemp.createTemp(
          'zfa_spec1395_deps_',
        );
        try {
          const app = 'zik_zak_tdd';
          final appDir = p.join(sandbox.path, app);

          final setup = await runZfaSource([
            'setup',
            app,
            '--platforms=linux',
            '--no-git',
          ], workingDirectory: sandbox.path);
          expect(
            setup.exitCode,
            0,
            reason: 'zfa setup must succeed: ${combinedOutput(setup)}',
          );
          final setupOut = combinedOutput(setup);
          expect(setupOut, contains('lib/app.dart'));

          // The #1395 contract: the SAME pass that wrote lib/app.dart
          // declared the module's runtime deps. Both land under
          // `dependencies:` (runtime — lib/app.dart is runtime source).
          final pubspecFile = File(p.join(appDir, 'pubspec.yaml'));
          final pubspec = pubspecFile.readAsStringSync();
          expect(
            pubspec,
            contains('zuraffa_flutter:'),
            reason:
                'the generated lib/app.dart imports '
                'package:zuraffa_flutter/zuraffa_flutter.dart — the '
                'day-zero pass must declare it (spec 1395)',
          );
          expect(
            pubspec,
            contains('get_it:'),
            reason:
                'the generated app module exposes '
                '`final GetIt di = GetIt.instance` — the day-zero pass '
                'must declare get_it (spec 1395)',
          );
          final depsMatch = RegExp(
            r'^dependencies:',
            multiLine: true,
          ).firstMatch(pubspec)!;
          final devMatch = RegExp(
            r'^dev_dependencies:',
            multiLine: true,
          ).firstMatch(pubspec);
          final barrelIdx = pubspec.indexOf('zuraffa_flutter');
          final getItIdx = pubspec.indexOf('get_it');
          expect(barrelIdx, greaterThan(depsMatch.start));
          expect(getItIdx, greaterThan(depsMatch.start));
          if (devMatch != null) {
            expect(barrelIdx, lessThan(devMatch.start));
            expect(getItIdx, lessThan(devMatch.start));
          }

          // The #942 gate severity contract on the fresh tree: 0 errors
          // (info lints are style, non-fatal by design — issue #1035).
          final analyze = await Process.run('dart', [
            'analyze',
            'lib',
          ], workingDirectory: appDir);
          final analyzeOut = '${analyze.stdout}\n${analyze.stderr}';
          expect(
            RegExp(r'^\s*error - ', multiLine: true).hasMatch(analyzeOut),
            isFalse,
            reason:
                'the fresh consumer tree must analyze with 0 errors after '
                'zfa setup (spec 1395 / the #942 gate). Output:\n'
                '$analyzeOut',
          );

          // Cross-command idempotency: re-running `zfa tdd init` (whose
          // #1349 self-heal shares the patcher) must not duplicate the
          // deps.
          final reinit = await runZfaSource([
            'tdd',
            'init',
          ], workingDirectory: appDir);
          expect(
            reinit.exitCode,
            0,
            reason:
                'zfa tdd init must succeed on the setup-created tree: '
                '${combinedOutput(reinit)}',
          );
          final repubspec = pubspecFile.readAsStringSync();
          expect(
            'zuraffa_flutter:'.allMatches(repubspec).length,
            1,
            reason: 'a re-run must not duplicate the barrel dependency',
          );
          expect(
            'get_it:'.allMatches(repubspec).length,
            1,
            reason: 'a re-run must not duplicate get_it',
          );
        } finally {
          if (sandbox.existsSync()) {
            await sandbox.delete(recursive: true);
          }
        }
      });
    },
  );
}

/// Runs `flutter test` in [appDir]. Supervised with a kill-on-timeout guard
/// so a wedged flutter_tester never leaks past the group timeout.
Future<ProcessResult> _runFlutterTest(String appDir) async {
  final process = await Process.start('flutter', [
    'test',
  ], workingDirectory: appDir);
  final stdoutBuf = StringBuffer();
  final stderrBuf = StringBuffer();
  final stdoutDone = process.stdout
      .transform(utf8.decoder)
      .listen(stdoutBuf.write, cancelOnError: true)
      .asFuture<void>();
  final stderrDone = process.stderr
      .transform(utf8.decoder)
      .listen(stderrBuf.write, cancelOnError: true)
      .asFuture<void>();

  final exitCode = await process.exitCode.timeout(
    const Duration(minutes: 8),
    onTimeout: () {
      process.kill(ProcessSignal.sigkill);
      throw TimeoutException(
        'flutter test exceeded its 8-minute child timeout in $appDir',
      );
    },
  );
  await stdoutDone;
  await stderrDone;
  return ProcessResult(
    process.pid,
    exitCode,
    stdoutBuf.toString(),
    stderrBuf.toString(),
  );
}
