// Issue #626 — zfa setup ships a red day-zero baseline.
//
// The spec 041 gates, executed end-to-end against a real `zfa setup` run in
// a temp sandbox:
//
//   FR-006 (the day-zero gate): after `zfa setup <app>` finishes,
//   `flutter test` invoked from inside the generated project MUST exit 0.
//
//   FR-001 + the naming contract (maintainer decision recorded on #626):
//   the smoke test asserts the zfa-generated app module — a DI container
//   whose symbol derives from the app name (`zik_zak_tdd` →
//   `ZikZakTddContainer`) — emitted at `lib/app.dart` by `zfa setup`.
//
//   Upgrade path: `zfa app shell` succeeds on a fresh setup (bootstrap DI)
//   and the smoke test stays green after the upgrade.
//
// These tests spawn `flutter create` / `flutter pub get` / `flutter test`
// and are therefore tagged slow + integration.
@Tags(['slow', 'integration'])
library;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../helpers/run_zfa_source.dart';

void main() {
  setUpAll(() async {
    await initZfaSourceBin();
  });

  group(
    'day-zero smoke gate (issue #626, spec 041 FR-006)',
    timeout: const Timeout(Duration(minutes: 12)),
    () {
      test(
        'fresh zfa setup emits the app-name container and flutter test exits 0',
        () async {
          final sandbox = await Directory.systemTemp.createTemp(
            'zfa_dayzero_gate_',
          );
          try {
            const app = 'zik_zak_tdd';
            final appDir = p.join(sandbox.path, app);

            final setup = await runZfaSource([
              'setup',
              app,
              '--platforms=linux',
              '--no-git',
            ], workingDirectory: sandbox.path);
            expect(
              setup.exitCode,
              0,
              reason: 'zfa setup must succeed: ${combinedOutput(setup)}',
            );
            expect(combinedOutput(setup), contains('Setup complete!'));

            // FR-001 + naming contract: the zfa-attributable app module
            // must exist day zero and expose the app-name-derived
            // container symbol the smoke test asserts.
            final appModule = File(p.join(appDir, 'lib', 'app.dart'));
            expect(
              appModule.existsSync(),
              isTrue,
              reason:
                  'zfa setup must emit lib/app.dart (the day-zero app '
                  'module asserted by the smoke test)',
            );
            final appModuleSrc = appModule.readAsStringSync();
            expect(
              appModuleSrc,
              contains('class ZikZakTddContainer'),
              reason:
                  'the container symbol derives from the app name '
                  '(PascalCase + Container)',
            );
            expect(
              appModuleSrc,
              contains('Generated by zfa'),
              reason: 'the emitted app surface must be zfa-attributable',
            );

            final smoke = File(
              p.join(appDir, 'test', 'bootstrap_smoke_test.dart'),
            );
            expect(smoke.existsSync(), isTrue);
            expect(
              smoke.readAsStringSync(),
              contains('ZikZakTddContainer'),
              reason: 'the smoke test asserts the exact container symbol',
            );

            // FR-006: the day-zero suite must be green immediately.
            final flutterTest = await _runFlutterTest(appDir);
            expect(
              flutterTest.exitCode,
              0,
              reason:
                  'FR-006: flutter test must exit 0 right after zfa setup '
                  '(day-zero baseline must be green). Output:\n'
                  '${combinedOutput(flutterTest)}',
            );
          } finally {
            if (sandbox.existsSync()) {
              await sandbox.delete(recursive: true);
            }
          }
        },
      );

      test(
        'upgrade path: zfa app shell succeeds on a fresh setup and stays green',
        () async {
          final sandbox = await Directory.systemTemp.createTemp(
            'zfa_dayzero_upgrade_',
          );
          try {
            const app = 'zik_zak_tdd';
            final appDir = p.join(sandbox.path, app);

            final setup = await runZfaSource([
              'setup',
              app,
              '--platforms=linux',
              '--no-git',
            ], workingDirectory: sandbox.path);
            expect(
              setup.exitCode,
              0,
              reason: 'zfa setup must succeed: ${combinedOutput(setup)}',
            );

            // The upgrade must not require an entity first (bootstrap DI).
            final shell = await runZfaSource([
              'app',
              'shell',
            ], workingDirectory: appDir);
            expect(
              shell.exitCode,
              0,
              reason:
                  'zfa app shell must succeed on a fresh setup via the '
                  'bootstrap DI index. Output:\n${combinedOutput(shell)}',
            );

            // The smoke test must still pass after the upgrade.
            final flutterTest = await _runFlutterTest(appDir);
            expect(
              flutterTest.exitCode,
              0,
              reason:
                  'the day-zero smoke test must stay green after the '
                  'app-shell upgrade. Output:\n${combinedOutput(flutterTest)}',
            );
          } finally {
            if (sandbox.existsSync()) {
              await sandbox.delete(recursive: true);
            }
          }
        },
      );
    },
  );
}

/// Runs `flutter test` in [appDir]. Supervised with a kill-on-timeout guard
/// so a wedged flutter_tester never leaks past the group timeout.
Future<ProcessResult> _runFlutterTest(String appDir) async {
  final process = await Process.start('flutter', [
    'test',
  ], workingDirectory: appDir);
  final stdoutBuf = StringBuffer();
  final stderrBuf = StringBuffer();
  final stdoutDone = process.stdout
      .transform(utf8.decoder)
      .listen(stdoutBuf.write, cancelOnError: true)
      .asFuture<void>();
  final stderrDone = process.stderr
      .transform(utf8.decoder)
      .listen(stderrBuf.write, cancelOnError: true)
      .asFuture<void>();

  final exitCode = await process.exitCode.timeout(
    const Duration(minutes: 8),
    onTimeout: () {
      process.kill(ProcessSignal.sigkill);
      throw TimeoutException(
        'flutter test exceeded its 8-minute child timeout in $appDir',
      );
    },
  );
  await stdoutDone;
  await stderrDone;
  return ProcessResult(
    process.pid,
    exitCode,
    stdoutBuf.toString(),
    stderrBuf.toString(),
  );
}
