/// The view-generation contract (EPIC 3 / issue #1134, lane 2 — the
/// view pipeline cleanup): the shared seam the two view generators
/// consult — the FIRST code `zfa view` (dynamic, mock-probed) and
/// `zfa tdd view` (deterministic, machine-contracted) share,
/// deliberately.
///
/// The epic's stated problem: "Two view generators exist … they share
/// zero code." This contract is the merge point that does NOT merge
/// the generators (they serve different lanes — entity CRUD
/// scaffolding vs behavior-driven minimal views) but FENCES them:
///
/// - **Ownership** ([inspect]): a target view file is classified by
///   the generator markers — the mainline `// Generated by zfa for:`
///   leading comment, the tdd generator's `View-builder subject for
///   behavior` doc comment, or hand-written (neither; the #1005 seam,
///   tracked by receipt). The tdd marker WINS when both are present —
///   the stricter ownership, never a silent guess.
/// - **The deterministic contract** ([machineSummary],
///   [MainlineViewOutcome]): the mainline `zfa view` ported the tdd
///   view's outcome vocabulary (`scaffolded`, `already-implemented`,
///   `error` — [ViewOutcome.label]'s grammar) and the machine summary
///   line — same declared inputs, same output bytes, same verdict; a
///   resumed pipeline re-running the step stays green and greppable.
///
/// Pure and synchronous: file content in, ownership/machine lines out.
/// Constitution VII holds (no Flutter imports).
library;

/// The outcome labels of the mainline view generator's machine
/// contract — the same vocabulary `zfa tdd view`'s [ViewOutcome]
/// emits, so pipeline greps see ONE grammar across both generators.
enum MainlineViewOutcome {
  /// The view files were written (created or overwritten).
  scaffolded('scaffolded'),

  /// The subject already exists (generator-written or hand-written):
  /// nothing scaffolded, exit 0 — the ported already-implemented
  /// verdict.
  alreadyImplemented('already-implemented'),

  /// The run refused or failed: nothing written, exit non-zero.
  error('error');

  /// The machine-line label (the `outcome=` token).
  final String label;

  const MainlineViewOutcome(this.label);
}

/// The ownership classification of a view file ([inspect]).
enum ViewFileKind {
  /// No file (or empty content) at the target path.
  notFound,

  /// The mainline generator's output (carries its generation marker).
  generatorWritten,

  /// The `zfa tdd view` generator's subject (carries the
  /// behavior-subject doc comment — the fence: the mainline generator
  /// refuses to clobber it without `--force`).
  tddSubject,

  /// Hand-written code (neither marker; the #1005 seam) — never
  /// silently overwritten; reads as already-implemented.
  handWritten,
}

/// The shared view-generation contract (issue #1134 lane 2).
abstract final class ViewGenerationContract {
  /// The mainline generator's leading comment — the ownership marker
  /// `_generateViewFile` writes via `leadingComment` (`// Generated by
  /// zfa for: <Entity>`).
  static const String mainlineMarker = '// Generated by zfa for:';

  /// The tdd view generator's subject doc comment — the ownership
  /// marker both the gen'd stub (bug #830) and the scaffolded view
  /// (issue #939) carry.
  static const String tddSubjectMarker = 'View-builder subject for behavior';

  /// Classify a view file's ownership from its content (null/empty
  /// content → [ViewFileKind.notFound]). The tdd marker WINS over the
  /// mainline marker when both are present: a file carrying both is
  /// the behavior-driven generator's output, and the stricter
  /// ownership governs the fence.
  static ViewFileKind inspect(String? content) {
    if (content == null || content.trim().isEmpty) {
      return ViewFileKind.notFound;
    }
    if (content.contains(tddSubjectMarker)) return ViewFileKind.tddSubject;
    if (content.contains(mainlineMarker)) {
      return ViewFileKind.generatorWritten;
    }
    return ViewFileKind.handWritten;
  }

  /// The machine summary line — the deterministic contract the tdd
  /// view emits (`view: behavior=… outcome=… feature=…`) ported to
  /// the mainline generator's vocabulary:
  /// `view: entity=<n> outcome=<label> files=<written>`. Same inputs,
  /// same bytes — pipelines grep for it.
  static String machineSummary({
    required String entity,
    required MainlineViewOutcome outcome,
    int files = 0,
  }) => 'view: entity=$entity outcome=${outcome.label} files=$files';
}
