/// Day-zero app-surface writers (issue #626).
///
/// `zfa setup` used to emit only flutter-create's Hello-World `main.dart`
/// plus a smoke test asserting `package:<app>/app.dart` + `AppContainer` —
/// an app surface no command produced on a fresh project (three-way
/// contract mismatch, GitHub issue #626). These writers make day zero
/// self-consistent with the STRONG smoke assertion intact:
///
///  * [AppModuleWriter] — `lib/app.dart`, the minimal zfa-generated app
///    module: a bootstrap DI container whose symbol derives from the app
///    name (naming contract from the maintainer decision on #626:
///    `zfa setup zik_zak_tdd` emits `ZikZakTddContainer`).
///  * [BootstrapDiIndexWriter] — `lib/src/di/index.dart` with an empty
///    `setupDependencies(GetIt getIt)` so `zfa app shell` can run (and
///    upgrade the minimal shell) before the first entity exists. Real DI
///    generation appends into this function via the AST append engine.
///  * [BootstrapRoutingIndexWriter] — `lib/src/routing/index.dart` with an
///    empty `getAllRoutes()` so the app shell's `app_router.dart` compiles
///    day zero. Route generation regenerates this index from the route
///    modules.
///
/// All three mirror the [SmokeTestWriter] contract: skip-if-exists (never
/// clobber user or generator content), `dryRun`-aware, and stamped with a
/// `// Generated by zfa` header so the provenance audit can attribute the
/// day-zero app surface to zfa.
library;

import 'dart:io';

import '../../../utils/string_utils.dart';

/// Writes `lib/app.dart` — the day-zero app module asserted by the smoke
/// test (spec 041 FR-001).
class AppModuleWriter {
  /// Whether the target is a Flutter project (imports `zuraffa_flutter`)
  /// or a pure-Dart one (imports `zuraffa` directly).
  const AppModuleWriter({this.isFlutter = true});

  final bool isFlutter;

  /// The DI container symbol for [appName] — PascalCase of the app name
  /// plus the `Container` suffix (issue #626 naming contract:
  /// `zik_zak_tdd` -> `ZikZakTddContainer`).
  ///
  /// The smoke test writer derives the asserted symbol from this same
  /// helper so the two can never disagree again.
  static String containerSymbolFor(String appName) =>
      '${StringUtils.convertToPascalCase(appName)}Container';

  String render(String appName) {
    final diImport = isFlutter
        ? 'package:zuraffa_flutter/zuraffa_flutter.dart'
        : 'package:zuraffa/zuraffa.dart';
    final symbol = containerSymbolFor(appName);
    return '''
// Generated by zfa — day-zero app module (issue #626).
//
// This is the app surface the day-zero smoke test asserts (spec 041
// FR-001): a zfa-generated DI container whose symbol derives from the
// app name (`$appName` -> $symbol). The bootstrap graph is empty —
// `zfa di <Entity>` / `zfa make <Entity> --with=di` populate it, and
// `zfa app shell` upgrades the minimal shell with the generated routing
// tree. Constructing the container must never throw, so `flutter test`
// is green from the first minute (spec 041 FR-006).
import '$diImport';

/// Bootstrap DI container for `$appName`.
///
/// Day zero the dependency graph is empty: [di] exposes the GetIt
/// registry the zfa-generated `setupDependencies(GetIt getIt)` wires
/// into, and [bootstrap] registers nothing until entities exist.
/// `zfa app shell` upgrades this minimal module into the generated app
/// shell; construction stays side-effect-free so the smoke test can
/// assert it unconditionally.
class $symbol {
  /// The dependency-injection registry backing this container.
  ///
  /// The same GetIt instance the generated DI barrel wires into. Empty
  /// until `zfa di` / `zfa make --with=di` populate the graph.
  final GetIt di = GetIt.instance;

  /// Bootstrap the (day-zero empty) dependency graph.
  ///
  /// A deliberate no-op until the DI generators upgrade this module;
  /// calling it must never throw (spec 041 FR-001).
  void bootstrap() {}
}
''';
  }

  Future<String?> write(
    String projectRoot,
    String appName, {
    bool dryRun = false,
  }) async {
    final file = File('$projectRoot/lib/app.dart');
    final content = render(appName);

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      return null;
    }

    await file.parent.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }
}

/// Writes `lib/src/di/index.dart` — the bootstrap DI barrel with an empty
/// `setupDependencies(GetIt getIt)` (issue #626).
///
/// The bootstrap file satisfies the app-shell preflight
/// (`AppShellBuilder.hasSetupDependenciesDeclaration`) and main.dart's
/// `setupDependencies(GetIt.instance)` call on a fresh project. It uses
/// the same signature the canonical `zfa di` output declares, so the real
/// generator appends registrations into it via the AST append engine.
class BootstrapDiIndexWriter {
  const BootstrapDiIndexWriter();

  String render() {
    return '''
// Generated by zfa — bootstrap DI index (issue #626).
//
// Day-zero empty graph: `setupDependencies` registers nothing until
// `zfa di <Entity>` / `zfa make <Entity> --with=di` generate the real
// registrations (they append into this function). `zfa app shell` reads
// this barrel to wire the generated entrypoint.
import 'package:zuraffa/zuraffa.dart';

void setupDependencies(GetIt getIt) {}
''';
  }

  Future<String?> write(String projectRoot, {bool dryRun = false}) async {
    final file = File('$projectRoot/lib/src/di/index.dart');
    final content = render();

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      return null;
    }

    await file.parent.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }
}

/// Writes `lib/src/routing/index.dart` — the bootstrap routing barrel with
/// an empty `getAllRoutes()` (issue #626).
///
/// The bootstrap file satisfies the app-shell preflight (the barrel must
/// mention `getAllRoutes`) and lets the app shell's `app_router.dart`
/// compile on a fresh project. Route generation regenerates this index
/// from the `*_routes.dart` modules it writes.
class BootstrapRoutingIndexWriter {
  const BootstrapRoutingIndexWriter();

  String render() {
    return '''
// Generated by zfa — bootstrap routing index (issue #626).
//
// Day-zero empty route table: `getAllRoutes()` returns no routes until
// `zfa route <Entity>` / `zfa make <Entity> --with=route` generate the
// route modules (they regenerate this index). `zfa app shell` reads
// this barrel to wire the GoRouter.
import 'package:go_router/go_router.dart';

List<RouteBase> getAllRoutes() => const [];
''';
  }

  Future<String?> write(String projectRoot, {bool dryRun = false}) async {
    final file = File('$projectRoot/lib/src/routing/index.dart');
    final content = render();

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      return null;
    }

    await file.parent.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }
}
