/// `DartTestYamlWriter` — writes `dart_test.yaml` at a generated project's
/// root.
library;

import 'dart:io';

class DartTestYamlWriter {
  const DartTestYamlWriter();

  static const String content = '''# dart_test.yaml — generated by `zfa setup`.
# Configures the dart/flutter test runner.

color: true
concurrency: 4
timeout: 30s
retry: 0
pause_after_load: false

# Test tiers (bug #835): the default run excludes the slow tier; every
# slow test carries a tier tag (declared below so a test using one never
# prints the unspecified-tag warning). The ffi golden fixture lane lives
# in the integration tier and is gated by:
#   dart test --preset=integration
tags:
  slow:
  integration:

exclude_tags: slow

presets:
  integration:
    include_tags: integration
    exclude_tags: "false"
''';

  Future<String?> write(String projectRoot, {bool dryRun = false}) async {
    final file = File('$projectRoot/dart_test.yaml');

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      final existing = await file.readAsString();
      if (existing.trim() == content.trim()) {
        return null;
      }
      return null;
    }

    await file.writeAsString(content);
    return file.path;
  }
}
