/// `SmokeTestWriter` — writes `test/bootstrap_smoke_test.dart` for a
/// generated project.
///
/// Issue #664: the writer is project-flavor aware. A Flutter project gets
/// the Flutter smoke test (`package:flutter_test` + the zfa-generated app
/// module assertion); a pure Dart package gets a Dart-compatible smoke test
/// that only relies on `package:test` — the runner recorded in the project's
/// `tdd-profile.md` — so `dart test` is green on day zero instead of failing
/// with "Couldn't resolve the package 'flutter_test'".
///
/// Issue #1673: the Flutter flavor's shell-pumping half (the
/// `lib/src/app/<stem>.dart` import plus the routing group) is gated so only
/// a caller that knows the shell exists emits it — see [SmokeTestWriter.write]
/// `probeShell`. `zfa tdd init` never creates the shell, so an unconditional
/// import would break the day-zero-green contract that keeps this writer
/// useful (#664).
library;

import 'dart:io';

import '../../../plugins/app_shell/builders/app_shell_builder.dart';
import 'app_module_writer.dart';

class SmokeTestWriter {
  /// Whether the target project is a Flutter project.
  ///
  /// Defaults to `true` to preserve the historical Flutter-first behavior
  /// for callers that generate into Flutter scaffolds (e.g. `zfa setup`).
  const SmokeTestWriter({this.isFlutter = true});

  final bool isFlutter;

  /// Renders the smoke-test source for [appName].
  ///
  /// [hasShell] gates the Flutter flavor's shell-pumping half — the
  /// `lib/src/app/<stem>.dart` import plus the routing group — so a caller
  /// that cannot guarantee the app shell exists never emits an import of a
  /// missing file (issue #1673). See [write]'s `probeShell`.
  String render(String appName, {bool hasShell = true}) => isFlutter
      ? _renderFlutter(appName, hasShell: hasShell)
      : _renderPureDart();

  /// Pure Dart smoke test (issue #664): no `package:flutter_test`, no app
  /// module — only `package:test`, matching the project's `dart_test.yaml`
  /// and the `tdd-profile.md` runner (`package:test (^1.24.0)`).
  String _renderPureDart() {
    return '''// Generated by `zfa tdd init`. Do not edit; re-run `zfa tdd init` to refresh.
import 'package:test/test.dart';

void main() {
  group('bootstrap smoke', () {
    test('the pure Dart test runner is wired and green on day zero', () {
      // A pure Dart package has no zfa-generated app module or DI container
      // to construct, so the day-zero smoke check proves the baseline
      // itself is wired: `dart test` resolves package:test (the runner
      // recorded in .specify/memory/tdd-profile.md) and this assertion
      // runs to green (spec 041 FR-001; issue #664).
      expect(true, isTrue);
    });
  });
}
''';
  }

  String _renderFlutter(String appName, {bool hasShell = true}) {
    // Issue #626 naming contract: the container symbol derives from the
    // app name (`zik_zak_tdd` -> `ZikZakTddContainer`). The symbol comes
    // from the same helper that renders lib/app.dart, so the assertion and
    // the emitted app module can never drift apart again.
    final containerSymbol = AppModuleWriter.containerSymbolFor(appName);
    // Issue #1673: the shell identity follows the app name, and the day
    // zero pump asserts the router actually resolves `/` — the zero-route
    // GoRouter crash (`no route for location: /`) was invisible to a
    // smoke test that only constructed the DI container. The shell import
    // and the routing group ship only when the shell file exists: the
    // `zfa tdd init` flow creates `lib/app.dart` but never
    // `lib/src/app/<stem>.dart`, so an unconditional import would be
    // compile-red on a project this repo did not scaffold.
    final naming = AppShellNaming.fromAppName(appName);
    final shellImport = hasShell
        ? "import 'package:$appName/src/app/${naming.stem}.dart';\n"
        : '';
    final routingGroup = hasShell
        ? '''
  group('bootstrap routing (issue #1673)', () {
    testWidgets('the initial location / resolves without throwing', (
      tester,
    ) async {
      // Pump the real shell — the same widget `flutter run` mounts — so
      // the router resolves `/` exactly like a launch. Day zero the route
      // table is empty (`getAllRoutes() => const []`, issue #626) and the
      // emitted `app_router.dart` claims `/` with the day-zero placeholder
      // plus an errorBuilder (issue #1673). After the first
      // `zfa route <Entity>` regenerates the index, a real view claims `/`
      // instead — both are healthy launches. What this test pins is the
      // regression class: the router must never throw
      // `no route for location: /` on the initial location.
      await tester.pumpWidget(const ${naming.widgetClass}());
      await tester.pump();
      expect(tester.takeException(), isNull);
    });
  });
'''
        : '';
    return '''// Generated by `zfa setup`. Do not edit; re-run `zfa tdd init` to refresh.
import 'package:flutter_test/flutter_test.dart';
import 'package:$appName/app.dart';
$shellImport
void main() {
  group('bootstrap smoke', () {
    test('the app module and DI container can be constructed', () {
      // The generated app module (lib/app.dart) exposes a zfa-generated
      // DI container named after the app: $containerSymbol. Constructing
      // it without throwing proves the DI graph is satisfiable at runtime
      // — the day-zero precondition for any TDD work on the generated app
      // (spec 041 FR-001; the container is emitted by `zfa setup`,
      // issue #626).
      final container = $containerSymbol();
      expect(container, isNotNull);
    });
  });
$routingGroup}
''';
  }

  /// Writes `test/bootstrap_smoke_test.dart` unless it is already there.
  ///
  /// [probeShell] (issue #1673): when true, the Flutter flavor checks this
  /// project for the emitted app shell (`lib/src/app/<stem>.dart`) and emits
  /// the shell-pumping routing group only when that file is on disk. `zfa
  /// tdd init` sets it — that flow creates `lib/app.dart` but never the
  /// shell, so importing it unconditionally made the day-zero baseline
  /// compile-red on a non-zfa-scaffolded Flutter app. `zfa setup` leaves it
  /// false: setup writes this file BEFORE emitting the shell, so a disk
  /// probe on that path would always miss.
  Future<String?> write(
    String projectRoot,
    String appName, {
    bool dryRun = false,
    bool probeShell = false,
  }) async {
    final dir = Directory('$projectRoot/test');
    final file = File('${dir.path}/bootstrap_smoke_test.dart');
    final content = render(
      appName,
      hasShell: probeShell ? _shellExists(projectRoot, appName) : true,
    );

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      return null;
    }

    await dir.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }

  /// Whether the emitted app shell — the file the Flutter flavor's routing
  /// group imports and pumps — exists under [projectRoot].
  static bool _shellExists(String projectRoot, String appName) => File(
    '$projectRoot/lib/src/app/'
    '${AppShellNaming.fromAppName(appName).stem}.dart',
  ).existsSync();
}
