/// `TddProfileWriter` — writes `.specify/memory/tdd-profile.md` for a
/// generated Flutter project.
library;

import 'dart:io';

import '../../../plugins/tdd/models/tdd_profile.dart';

class TddProfileWriter {
  const TddProfileWriter({this.profile = TddProfile.flutter});

  final TddProfile profile;

  Future<String?> write(String projectRoot, {bool dryRun = false}) async {
    final dir = Directory('$projectRoot/.specify/memory');
    final file = File('${dir.path}/tdd-profile.md');
    final content = _render(profile);

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      final existing = await file.readAsString();
      if (existing.trim() == content.trim()) {
        return null;
      }
      throw StateError(
        'tdd-profile.md already exists at ${file.path} with different '
        'content; refusing to overwrite. Delete the file first if you want '
        'to regenerate.',
      );
    }

    await dir.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }

  String _render(TddProfile p) {
    final isFlutterProfile = p.runner == 'flutter_test';
    final platform = isFlutterProfile ? 'Flutter' : 'Dart';
    final runnerHint = isFlutterProfile
        ? '`flutter_test`. Invoked as `flutter test`.'
        : '`dart test`. Invoked as `dart test`.';
    final langNote = isFlutterProfile ? '. Flutter 3.41+ on PATH' : '';
    return '''# TDD Profile — $platform (generated by `zfa setup`)

This profile is read by the `tdd` spec-kit extension.

## Stack

- **Language**: Dart (latest stable)$langNote.
- **Test runner**: $runnerHint
- **Static analysis**: `dart analyze`. Configured via `analysis_options.yaml`.
- **Mutation tool**: opt-in via the `mutation_test` dev_dependency.
- **Coverage**: `${p.resolveCoverage()}` then
  `dart run coverage:format_coverage`.

## Commands

- Single test: `${p.resolveSingle(file: '{file}', name: '{name}')}'
- Whole file: `${p.resolveFile('{file}')}'
- Full suite: `${p.resolveSuite()}'
- Coverage: `${p.resolveCoverage()}'

## Keys (machine-readable)

```yaml
runner: ${p.runner}
single: '${p.single}'
file: '${p.file}'
suite: '${p.suite}'
coverage: '${p.coverage}'
```
''';
  }
}
