/// `TddProfileWriter` — writes `.specify/memory/tdd-profile.md` for a
/// generated Flutter project.
library;

import 'dart:io';

import '../../../plugins/tdd/models/tdd_profile.dart';

class TddProfileWriter {
  const TddProfileWriter({this.profile = TddProfile.flutter});

  final TddProfile profile;

  /// Write the profile to `.specify/memory/tdd-profile.md`.
  ///
  /// Detection is layered:
  ///   1. **Lenient runner-family check** (existing frontmatter is parsed
  ///      for its `runner:` value): if the existing file's runner is in
  ///      the same family as the one we're writing (both Flutter or both
  ///      non-Flutter), it's accepted as a no-op. This handles the
  ///      common case where a previous `zfa tdd init` (or a CI detector
  ///      or a manual author) wrote an equally-valid Dart runner such
  ///      as `package:test (^1.24.0)`.
  ///   2. **Exact-content match** (Flutter family only): if the existing
  ///      file's runner is `flutter_test`/`flutter` AND its body matches
  ///      what we'd render, it's accepted as a no-op.
  ///   3. **`--force` override**: when the existing file is in the same
  ///      family and content differs, [force] lets the caller clobber
  ///      it instead of throwing.
  ///   4. **Hard conflict**: cross-family runner (Flutter runner in a
  ///      Dart-targeting init, or vice versa) is rejected with
  ///      [StateError]; [force] does NOT bypass this because changing
  ///      the test runner is a real semantic change.
  ///
  /// When [dryRun] is true the file is not touched and the would-be
  /// path is returned.
  Future<String?> write(
    String projectRoot, {
    bool force = false,
    bool dryRun = false,
  }) async {
    final dir = Directory('$projectRoot/.specify/memory');
    final file = File('${dir.path}/tdd-profile.md');
    final content = _render(profile);

    if (dryRun) {
      return file.path;
    }

    if (await file.exists()) {
      final existing = await file.readAsString();

      // Lenient check: extract the runner from the existing frontmatter.
      // If the existing file already uses a Dart runner (non-Flutter), accept it
      // — it may have been written by a different tool (e.g. a previous
      // `zfa tdd init` run, a CI detector, or a manual author) with a different
      // but equally-valid runner value (e.g. "package:test (^1.24.0)" vs the
      // hardcoded 'dart' literal). The only conflict we reject is a Flutter
      // runner in a Dart-targeting init (or vice-versa).
      final frontmatterRunner = _extractRunner(existing);
      final existingIsFlutterRunner =
          frontmatterRunner == 'flutter_test' ||
          frontmatterRunner == 'flutter';
      final writingDartProfile = !isFlutterProfile;

      if (existingIsFlutterRunner && writingDartProfile) {
        throw StateError(
          'tdd-profile.md already exists with a Flutter runner '
          '("$frontmatterRunner") but `zfa tdd init` is targeting a Dart '
          'project. Delete the file first to re-detect.',
        );
      }

      // Same runner family: non-Flutter runners are all equally valid for a
      // Dart profile. Accept the existing file and return null (no-op).
      if (!existingIsFlutterRunner) {
        return null;
      }

      // Same runner family (Flutter) and content differs: exact-content match
      // is required.
      if (existing.trim() == content.trim()) {
        return null;
      }

      // Same Flutter family but content actually differs. --force lets
      // the caller clobber it; otherwise reject with a clear message.
      if (!force) {
        throw StateError(
          'tdd-profile.md already exists at ${file.path} with different '
          'content; refusing to overwrite. Pass --force to overwrite or '
          'delete the file first if you want to regenerate.',
        );
      }
      // force + different content: fall through and overwrite.
    }

    await dir.create(recursive: true);
    await file.writeAsString(content);
    return file.path;
  }

  bool get isFlutterProfile => profile.runner == 'flutter_test';

  String _extractRunner(String content) {
    // Match `runner: <value>` in the YAML frontmatter block.
    // Handles both single and double-quoted values.
    final match = RegExp(r'''^\s*runner:\s*["']([^"']+)["']''', multiLine: true)
        .firstMatch(content);
    return match?.group(1)?.trim() ?? '';
  }

  String _render(TddProfile p) {
    final platform = isFlutterProfile ? 'Flutter' : 'Dart';
    final runnerHint = isFlutterProfile
        ? '`flutter_test`. Invoked as `flutter test`.'
        : '`dart test`. Invoked as `dart test`.';
    final langNote = isFlutterProfile ? '. Flutter 3.41+ on PATH' : '';
    return '''# TDD Profile — $platform (generated by `zfa setup`)

This profile is read by the `tdd` spec-kit extension.

## Stack

- **Language**: Dart (latest stable)$langNote.
- **Test runner**: $runnerHint
- **Static analysis**: `dart analyze`. Configured via `analysis_options.yaml`.
- **Mutation tool**: opt-in via the `mutation_test` dev_dependency.
- **Coverage**: `${p.resolveCoverage()}` then
  `dart run coverage:format_coverage`.

## Commands

- Single test: `${p.resolveSingle(file: '{file}', name: '{name}')}'
- Whole file: `${p.resolveFile('{file}')}'
- Full suite: `${p.resolveSuite()}'
- Coverage: `${p.resolveCoverage()}'

## Keys (machine-readable)

```yaml
runner: ${p.runner}
single: '${p.single}'
file: '${p.file}'
suite: '${p.suite}'
coverage: '${p.coverage}'
```
''';
  }
}
