// Generated by zfa for: CustomerAddress
// ignore_for_file: no_logic_in_create_state
import 'package:flutter/material.dart';
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

import 'customer_address_controller.dart';
import 'customer_address_presenter.dart';

class CustomerAddressView extends CleanView {
  const CustomerAddressView({super.key, super.routeObserver});

  @override
  State<CustomerAddressView> createState() {
    return _CustomerAddressViewState(
      CustomerAddressController(CustomerAddressPresenter()),
    );
  }
}

class _CustomerAddressViewState
    extends
        CleanViewState<CustomerAddressView, CustomerAddressController, void> {
  _CustomerAddressViewState(super.controller);

  @override
  void onInitState() {
    super.onInitState();
  }

  @override
  Widget get view {
    return Scaffold(
      key: globalKey,
      appBar: AppBar(title: const Text('CustomerAddress')),
      body: ControlledWidgetBuilder<CustomerAddressController>(
        builder: (context, controller) {
          return Container();
        },
      ),
    );
  }
}
