@Tags(['slow'])
// Issue #1330 — the gated one-shot make falls back to the subject edit.
//
// When the #829 entity gate drops `entity create` (the contract-row entity
// already exists), a sibling acceptance/entity-traced behavior's plan starts
// with the bare `make <Entity>` — the one-shot scaffold whose inner plugin
// plan resolves to NOTHING on an already-generated entity. The bug-#826
// pre-flight then aborted the WHOLE make with `verdict: no-op` — wasting the
// `tdd wire` subject-edit step that turned the earlier siblings green and
// wedging the run (phase 2 re-plans the identical steps, no-ops identically,
// honest-stops at `<id>:make`).
//
// These tests drive the PUBLIC CLI surface (`zfa tdd make`) in-process
// WITHOUT `--zfa-bin`, so the bug-#826 pre-flight is active (it only fires
// when the pipeline entrypoint is not overridden). In-process the pipeline's
// entrypoint resolution fails fast after the fallback (the test kernel is
// not a CLI), so the fast tests assert the DECISION — the fallback lines
// printed, no no-op verdict, the hand-tuned entity untouched — and tolerate
// the pipeline's graded outcome; the real green is proven by the sc_024 e2e.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

import 'helpers/tdd_fixture.dart';

/// Build the CLI args for `zfa tdd make`, pinning the project root.
/// Deliberately NO `--zfa-bin`: the pre-flight fires only without it.
List<String> makeArgs(TddFixture fx, {String? id}) {
  final args = <String>['tdd', 'make', '--project', fx.root.path];
  if (id != null) args.add(id);
  return args;
}

/// The pre-seeded hand-tuned entity file for the `DispatchService`
/// contract row.
File dispatchServiceEntityFile(TddFixture fx) => File(
  p.join(
    fx.root.path,
    'lib',
    'src',
    'domain',
    'entities',
    'dispatch_service',
    'dispatch_service.dart',
  ),
);

/// Seed a certified-red ACCEPTANCE behavior whose description routes to the
/// CRUD/service branch naming the `DispatchService` contract row — the exact
/// issue-repro shape. The plan is
/// `[entity create -n DispatchService, make DispatchService,
///   tdd wire A1 --entity DispatchService, build]`;
/// with the entity file pre-seeded the #829 gate reduces it to
/// `[make DispatchService, tdd wire A1, build]` — bare make FIRST.
Future<void> seedAcceptanceBehavior(TddFixture fx) async {
  const description = 'the DispatchService repository records a delivery';
  await fx.seedCertifiedRed(
    id: 'A1',
    description: description,
    sourceCriterion: 'FR-001',
    testContent: TddFixture.subjectDrivenTest('A1', description),
  );
}

void main() {
  late TddFixture fx;

  setUp(() async {
    fx = await TddFixture.create();
  });

  tearDown(() {
    fx.dispose();
    exitCode = 0;
  });

  group(
    'issue 1330 — the gated one-shot make falls back to the subject edit',
    () {
      test(
        'U-1330-1: when the entity already exists and the inner make resolves '
        'to nothing, the pre-flight falls back to the subject edit instead of '
        'the no-op verdict — the hand-tuned entity is untouched',
        () async {
          await seedAcceptanceBehavior(fx);
          // The contract-row entity ALREADY exists (generated by a sibling
          // behavior's make in the issue repro) and carries hand-tuned
          // content the #829 reuse contract must preserve.
          await dispatchServiceEntityFile(fx).parent.create(recursive: true);
          await dispatchServiceEntityFile(
            fx,
          ).writeAsString('// hand-tuned entity\n');

          final runner = CliRunner(exitOnCompletion: false);
          final out = await runner.runCapturing(makeArgs(fx, id: 'A1'));

          // THE FIX: the no-op verdict is replaced by the subject-edit
          // fallback (FR-001) — greppable, never silent.
          expect(out, contains('issue #1330'), reason: 'out:\n$out');
          expect(out, contains('falling back'), reason: 'out:\n$out');
          expect(
            out,
            isNot(contains('verdict: no-op')),
            reason: 'the no-op must not be a hard stop (FR-002); out:\n$out',
          );
          expect(
            out,
            isNot(contains('no subprocess was attempted')),
            reason: 'the pipeline proceeds to the subject edit; out:\n$out',
          );
          // The entity is reused AS-IS (FR-003) — byte-identical.
          expect(
            await dispatchServiceEntityFile(fx).readAsString(),
            '// hand-tuned entity\n',
            reason: 'the hand-tuned entity must survive the fallback',
          );
          // The make proceeded past the pre-flight and graded a real
          // post-pipeline outcome. In-process (no --zfa-bin) the pipeline's
          // entrypoint resolution fails fast → generation-error; with a
          // resolvable entrypoint the wire step can turn it green.
          expect(
            out,
            anyOf(
              contains('outcome=green'),
              contains('outcome=generation-error'),
            ),
            reason: 'out:\n$out',
          );
        },
      );

      test(
        'U-1330-2: a plan with NO subject-edit step keeps the bug #826 no-op '
        'verdict verbatim (fail-closed backward compatibility)',
        () async {
          // Non-acceptance CRUD shape (repository keyword, no acceptance id):
          // [make <slug> --no-entity, build] — the bare make resolves to
          // nothing and the remaining plan carries no tdd wire/func step, so
          // there is no subject-edit path to fall back to. The #826 verdict
          // stands (today's behavior, preserved by the fix).
          await fx.seedCertifiedRed(
            id: 'B-001',
            description: 'the Order repository records deliveries',
            sourceCriterion: 'FR-001',
          );

          final runner = CliRunner(exitOnCompletion: false);
          final out = await runner.runCapturing(makeArgs(fx, id: 'B-001'));

          expect(exitCode, 1, reason: 'out:\n$out');
          expect(out, contains('verdict: no-op'), reason: 'out:\n$out');
          expect(out, contains('no active plugins'), reason: 'out:\n$out');
          expect(
            out,
            contains('no subprocess was attempted'),
            reason: 'out:\n$out',
          );
        },
      );
    },
  );
}
