@Tags(['regression', 'e2e'])
// Spec 1692 — the tdd make path must consult the 016 id-gate BEFORE
// generation: a unit behavior whose FR traces to a Key Entity that
// resolves ID-LESS (no `id`, no `*Id` field, no `autoId`, not a value
// object) and whose plan carries an id-dependent surface (`mock create`
// for the traced entity) refuses upfront with the #307 remediation text,
// never spawning a pipeline step. The mock certification backstop stays
// as the second line of defense (it is what caught the bug downstream
// before this gate existed).
//
// Drives the public CLI surface (`zfa tdd make`) against a real temp
// fixture project whose registry records gen-style artifacts, using the
// scripted fake `zfa` bin — the same pattern as `make_command_test.dart`.
// The gate runs in-process BEFORE any subprocess, so the fake bin's
// invocation log is the "generation ran?" oracle.
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

import 'helpers/tdd_fixture.dart';

List<String> makeArgs(
  TddFixture fx, {
  String? id,
  String? zfaBin,
  bool stub = false,
}) {
  final args = <String>['tdd', 'make', '--project', fx.root.path];
  if (zfaBin != null) args.addAll(['--zfa-bin', zfaBin]);
  if (stub) args.add('--stub');
  if (id != null) args.add(id);
  return args;
}

const _userSessionDescription =
    'The system SHALL let the user manage a UserSession by its token '
    'and email through the UserSessionRepository domain contract.';

/// The test list a `zfa tdd plan` writes for the 1692 repro: a unit row
/// whose description names the Key Entity plus the `## Key entities`
/// section the traced-entity resolution reads.
Future<void> seedTestListWithKeyEntity(
  TddFixture fx, {
  required String fields,
}) async {
  await Directory(p.join(fx.featureDir, 'tdd')).create(recursive: true);
  await File(fx.testListPath).writeAsString('''
# Test List: ${fx.featureName}

## Inner loop: unit behaviors

| id | behavior | traces | state |
| -- | -------- | ------ | ----- |
| U1 | $_userSessionDescription | FR-001 | PENDING |

## Key entities

| entity | fields | purpose |
| ------ | ------ | ------- |
| UserSession | $fields | The signed-in session |
''');
}

/// An id-less Zorphy entity on disk (`token` + `email`, no identity
/// field) — exactly what phase 0 creates from the repro's Key Entity row.
Future<void> seedEntityFile(
  TddFixture fx, {
  required String fieldGetters,
}) async {
  final file = File(
    p.join(
      fx.root.path,
      'lib',
      'src',
      'domain',
      'entities',
      'user_session',
      'user_session.dart',
    ),
  );
  await file.parent.create(recursive: true);
  await file.writeAsString('''
// Auto-generated by Zorphy
import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'user_session.zorphy.dart';
part 'user_session.g.dart';

/// UserSession entity
@Zorphy(generateJson: true)
abstract class \$UserSession {

$fieldGetters
}
''');
}

void main() {
  late TddFixture fx;

  setUp(() async {
    fx = await TddFixture.create();
  });

  tearDown(() {
    fx.dispose();
    exitCode = 0;
  });

  group('spec 1692 — the 016 id-gate on the tdd make path', () {
    test('U1: id-less traced entity + id-dependent plan refuses BEFORE '
        'generation with the #307 remediation text', () async {
      await seedTestListWithKeyEntity(
        fx,
        fields: 'token: String, email: String',
      );
      await seedEntityFile(
        fx,
        fieldGetters: '  String get token;\n  String get email;',
      );
      await fx.seedCertifiedRed(id: 'U1', description: _userSessionDescription);
      final testTreeBefore = fx.checksumTestTree();

      // Any pipeline invocation would land in this log; the refusal must
      // fire BEFORE the first spawn.
      final zfaBin = await fx.writeFakeZfaBin(logPath: fx.fakeZfaLogPath);

      final runner = CliRunner(exitOnCompletion: false);
      final out = await runner.runCapturing(
        makeArgs(fx, id: 'U1', zfaBin: zfaBin),
      );

      // The #307 diagnostic + remediation reach the output verbatim.
      expect(
        out,
        contains(
          'Cannot generate architecture for "UserSession": the entity has '
          'no id field.',
        ),
      );
      expect(out, contains('--> fix: add `id: String` to UserSession'));
      expect(out, contains('narrow the traced contract to id-neutral methods'));

      // The summary line classifies the refusal (not generation-error —
      // nothing was generated).
      expect(
        out,
        contains(
          'make: behavior=U1 outcome=unexpressible feature=${fx.featureName}',
        ),
      );
      expect(exitCode, isNot(0), reason: 'refusal must exit non-zero');

      // Refusal BEFORE generation: not a single pipeline step spawned.
      expect(
        await fx.readFakeZfaLog(),
        isEmpty,
        reason: 'the 016 gate must refuse before any pipeline invocation',
      );

      // No green entry, test tree untouched.
      final log = await File(fx.cycleLogPath).readAsString();
      expect(log, isNot(contains('## Cycle: U1 (green)')));
      expect(fx.checksumTestTree(), equals(testTreeBefore));
    });

    test('regression guard: id-bearing traced entity keeps the entity '
        'pipeline — generation runs and certifies green', () async {
      await seedTestListWithKeyEntity(fx, fields: 'id: String, token: String');
      await seedEntityFile(
        fx,
        fieldGetters:
            '  String get id;\n  String get token;\n  String get email;',
      );
      await fx.seedCertifiedRed(
        id: 'U1',
        description: _userSessionDescription,
        testContent: TddFixture.subjectDrivenTest(
          'U1',
          _userSessionDescription,
        ),
      );

      // The fake pipeline turns the subject green on the wire step (the
      // terminal build is skipped by the #1587 no-change guard in this
      // fixture — no builder-consumable input changed).
      final zfaBin = await fx.writeFakeZfaBin(
        logPath: fx.fakeZfaLogPath,
        sideEffectByArgv: {
          'wire': fx.overwriteSubjectCommands(
            'U1',
            TddFixture.subjectReturning('U1', 42),
          ),
        },
      );

      final runner = CliRunner(exitOnCompletion: false);
      final out = await runner.runCapturing(
        makeArgs(fx, id: 'U1', zfaBin: zfaBin),
      );

      expect(
        out,
        contains('make: behavior=U1 outcome=green feature=${fx.featureName}'),
      );
      expect(exitCode, 0, reason: 'id-bearing entity generation must certify');

      // The id-dependent surfaces ran (mock create + build at minimum).
      final calls = await fx.readFakeZfaLog();
      expect(
        calls.join('\n'),
        contains('mock create'),
        reason: 'id-bearing entities keep the full entity pipeline',
      );

      // Green evidence appended.
      final log = await File(fx.cycleLogPath).readAsString();
      expect(log, contains('## Cycle: U1 (green)'));
    });

    test('U1: id-less traced entity on a STUB row refuses BEFORE '
        'generation — the `make <Traced>` id-dependent shape', () async {
      // The gate's second recognized shape: the stub branch plans
      // `make UserSession` (no `--no-entity`, generation_planner's stub
      // route) instead of `mock create --name UserSession`. The same
      // #307 refusal must fire for it, before any step spawns.
      await seedTestListWithKeyEntity(
        fx,
        fields: 'token: String, email: String',
      );
      await seedEntityFile(
        fx,
        fieldGetters: '  String get token;\n  String get email;',
      );
      await fx.seedCertifiedRed(id: 'U1', description: _userSessionDescription);
      final testTreeBefore = fx.checksumTestTree();

      final zfaBin = await fx.writeFakeZfaBin(logPath: fx.fakeZfaLogPath);

      final runner = CliRunner(exitOnCompletion: false);
      final out = await runner.runCapturing(
        makeArgs(fx, id: 'U1', zfaBin: zfaBin, stub: true),
      );

      expect(
        out,
        contains(
          'Cannot generate architecture for "UserSession": the entity has '
          'no id field.',
        ),
      );
      expect(
        out,
        contains(
          'make: behavior=U1 outcome=unexpressible feature=${fx.featureName}',
        ),
      );
      expect(exitCode, isNot(0), reason: 'refusal must exit non-zero');

      expect(
        await fx.readFakeZfaLog(),
        isEmpty,
        reason: 'the 016 gate must refuse before any pipeline invocation',
      );
      expect(fx.checksumTestTree(), equals(testTreeBefore));
    });

    test('regression guard: id-bearing traced entity on a STUB row keeps '
        'the entity pipeline — `make <Traced>` passes the gate', () async {
      await seedTestListWithKeyEntity(fx, fields: 'id: String, token: String');
      await seedEntityFile(
        fx,
        fieldGetters:
            '  String get id;\n  String get token;\n  String get email;',
      );
      await fx.seedCertifiedRed(
        id: 'U1',
        description: _userSessionDescription,
        testContent: TddFixture.subjectDrivenTest(
          'U1',
          _userSessionDescription,
        ),
      );

      final zfaBin = await fx.writeFakeZfaBin(
        logPath: fx.fakeZfaLogPath,
        sideEffectByArgv: {
          'wire': fx.overwriteSubjectCommands(
            'U1',
            TddFixture.subjectReturning('U1', 42),
          ),
        },
      );

      final runner = CliRunner(exitOnCompletion: false);
      final out = await runner.runCapturing(
        makeArgs(fx, id: 'U1', zfaBin: zfaBin, stub: true),
      );

      expect(
        out,
        contains('make: behavior=U1 outcome=green feature=${fx.featureName}'),
      );
      expect(exitCode, 0, reason: 'id-bearing entity generation must certify');

      // The stub branch's id-dependent `make <Entity>` step ran.
      final calls = await fx.readFakeZfaLog();
      expect(
        calls.join('\n'),
        contains('make UserSession'),
        reason: 'the stub-branch entity generation step must run',
      );
    });
  });
}
