// Fast unit tests for `WireCommand` — the subject-wiring pipeline step
// (bug #610; epic 045 precondition 5).
//
// Drives the public CLI surface (`zfa tdd wire`) in-process against a
// TddFixture carrying the gen artifacts (registry record + Unimplemented-
// Error subject stub, the exact shape SubjectWriter emits). The real
// end-to-end wiring — entity create → wire → build → green — is proven
// by sc_017_real_pipeline_wires_subject_test.dart; these tests pin the
// command's own contract:
//   U-W1: a stub subject is rewritten to the wired implementation
//         (no UnimplementedError, entity imported + referenced).
//   U-W2: idempotent — an already-implemented subject reports
//         already-wired and exits 0.
//   U-W3: a missing subject file is a hard runner-error (gen first).
//   U-W4: a missing entity file is a hard runner-error (create first).
//   U-W5: an unrecognized UnimplementedError shape is refused, never
//         guessed at.
//   U-W6: --entity is required — wiring without an entity anchor would
//         be hand-implementation, not generation.
library;

import 'dart:io';

import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

import 'helpers/tdd_fixture.dart';

/// The gen-shaped stub SubjectWriter emits for a unit behavior
/// (function name = the behavior's target, `subject_<snake id>`).
String genStyleStub(String id) {
  final symbol = id.toLowerCase().replaceAll('-', '_');
  return '''
// GENERATED STUB — `zfa tdd gen $id` (spec 044-test-tdd-generation).
library;

/// Subject for behavior $id.
int subject_$symbol() => throw UnimplementedError('subject_$symbol not implemented');
''';
}

void main() {
  late TddFixture fx;

  setUp(() async {
    fx = await TddFixture.create();
    // The entity the behavior is wired to, as `zfa entity create -n User`
    // would have laid it out (entities/<snake>/<snake>.dart).
    final entity = File(
      '${fx.root.path}/lib/src/domain/entities/user/user.dart',
    );
    await entity.create(recursive: true);
    await entity.writeAsString('''
// Auto-generated by Zorphy
import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'user.zorphy.dart';

/// User entity
@Zorphy(generateJson: true)
abstract class \$User {}
''');
  });

  tearDown(() {
    fx.dispose();
    exitCode = 0;
  });

  Future<String> runWire({String? entity = 'User', String? id = 'B-001'}) {
    final runner = CliRunner(exitOnCompletion: false);
    final args = <String>[
      'tdd',
      'wire',
      ?id,
      '--project',
      fx.root.path,
      if (entity != null) ...['--entity', entity],
    ];
    return runner.runCapturing(args);
  }

  test('U-W1: a gen-shaped stub subject is rewritten to the wired '
      'implementation', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));

    final out = await runWire();

    expect(exitCode, 0, reason: 'out: $out');
    expect(
      out,
      contains('wire: behavior=B-001 outcome=wired feature=${fx.featureName}'),
    );
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(subject, isNot(contains('UnimplementedError')));
    expect(subject, contains("import 'package:tdd_fixture/"));
    expect(subject, contains('entities/user/user.dart'));
    expect(subject, contains('final Type wiredEntityAnchor = User;'));
    // The function signature is preserved so the paired (immutable)
    // test still compiles against it.
    expect(subject, contains('int subject_b_001() {'));
  });

  test('U-W2: an already-implemented subject is a no-op (already-wired, '
      'exit 0) so a resumed pipeline stays green', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString('''
library;

int subject_b_001() => 42;
''');

    final out = await runWire();

    expect(exitCode, 0, reason: 'out: $out');
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=already-wired '
        'feature=${fx.featureName}',
      ),
    );
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(
      subject,
      contains('=> 42'),
      reason: 'an implemented subject is left untouched',
    );
  });

  test('U-W3: a missing subject file is a hard runner-error naming the '
      'gen remediation', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
      // registerBehavior records subject_path but writes no subject
      // file — the missing-artifact case exactly.
    );

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('missing subject file'));
    expect(out, contains('zfa tdd gen B-001'));
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=runner-error '
        'feature=${fx.featureName}',
      ),
    );
  });

  test('U-W4: a missing entity file is a hard runner-error naming the '
      'entity create remediation (misfire-stop, not papered over)', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));
    await Directory(
      '${fx.root.path}/lib/src/domain/entities/user',
    ).delete(recursive: true);

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('no generated entity "User" found'));
    expect(out, contains('zfa entity create -n User'));
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=runner-error '
        'feature=${fx.featureName}',
      ),
    );
  });

  test('U-W5: an unrecognized UnimplementedError shape is refused — wire '
      'never rewrites a file it did not generate', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString('''
library;

class Weird {
  void run() {
    throw UnimplementedError('hand-written shape');
  }
}
''');

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('unrecognized shape'));
    // The unrecognized file is untouched.
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(subject, contains('class Weird'));
  });

  test('U-W6: --entity is required — a wire without an entity anchor is a '
      'usage error', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));

    final out = await runWire(entity: null);

    expect(exitCode, isNot(0));
    expect(out, contains('--entity <Name> is required'));
    expect(
      out,
      contains('wire: behavior=B-001 outcome=runner-error feature=unknown'),
    );
  });
}
