// Fast unit tests for `WireCommand` — the subject-wiring pipeline step
// (bug #610; epic 045 precondition 5).
//
// Drives the public CLI surface (`zfa tdd wire`) in-process against a
// TddFixture carrying the gen artifacts (registry record + Unimplemented-
// Error subject stub, the exact shape SubjectWriter emits). The real
// end-to-end wiring — entity create → wire → build → green — is proven
// by sc_017_real_pipeline_wires_subject_test.dart; these tests pin the
// command's own contract:
//   U-W1: a stub subject is rewritten to the wired implementation
//         (no UnimplementedError, entity imported + referenced).
//   U-W2: idempotent — an already-implemented subject reports
//         already-wired and exits 0.
//   U-W3: a missing subject file is a hard runner-error (gen first).
//   U-W4: a missing entity file is a hard runner-error (create first).
//   U-W5: an unrecognized UnimplementedError shape is refused, never
//         guessed at.
//   U-W6: --entity is required — wiring without an entity anchor would
//         be hand-implementation, not generation.
library;

import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';
import 'package:zuraffa/src/cli/cli_runner.dart';

import 'helpers/tdd_fixture.dart';

/// The gen-shaped stub SubjectWriter emits for a unit behavior
/// (function name = the behavior's target, `subject_<snake id>`).
String genStyleStub(String id) {
  final symbol = id.toLowerCase().replaceAll('-', '_');
  return '''
// GENERATED STUB — `zfa tdd gen $id` (spec 044-test-tdd-generation).
library;

/// Subject for behavior $id.
int subject_$symbol() => throw UnimplementedError('subject_$symbol not implemented');
''';
}

void main() {
  late TddFixture fx;

  setUp(() async {
    fx = await TddFixture.create();
    // The entity the behavior is wired to, as `zfa entity create -n User`
    // would have laid it out (entities/<snake>/<snake>.dart).
    final entity = File(
      '${fx.root.path}/lib/src/domain/entities/user/user.dart',
    );
    await entity.create(recursive: true);
    await entity.writeAsString('''
// Auto-generated by Zorphy
import 'package:zorphy_annotation/zorphy_annotation.dart';

part 'user.zorphy.dart';

/// User entity
@Zorphy(generateJson: true)
abstract class \$User {}
''');
  });

  tearDown(() {
    fx.dispose();
    exitCode = 0;
  });

  Future<String> runWire({String? entity = 'User', String? id = 'B-001'}) {
    final runner = CliRunner(exitOnCompletion: false);
    final args = <String>[
      'tdd',
      'wire',
      ?id,
      '--project',
      fx.root.path,
      if (entity != null) ...['--entity', entity],
    ];
    return runner.runCapturing(args);
  }

  test('U-W1: a gen-shaped stub subject is rewritten to the wired '
      'implementation', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));

    final out = await runWire();

    expect(exitCode, 0, reason: 'out: $out');
    expect(
      out,
      contains('wire: behavior=B-001 outcome=wired feature=${fx.featureName}'),
    );
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(subject, isNot(contains('UnimplementedError')));
    expect(subject, contains("import 'package:tdd_fixture/"));
    expect(subject, contains('entities/user/user.dart'));
    expect(subject, contains('final Type wiredEntityAnchor = User;'));
    // The function signature is preserved so the paired (immutable)
    // test still compiles against it.
    expect(subject, contains('int subject_b_001() {'));
  });

  test('U-W2: an already-implemented subject is a no-op (already-wired, '
      'exit 0) so a resumed pipeline stays green', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString('''
library;

int subject_b_001() => 42;
''');

    final out = await runWire();

    expect(exitCode, 0, reason: 'out: $out');
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=already-wired '
        'feature=${fx.featureName}',
      ),
    );
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(
      subject,
      contains('=> 42'),
      reason: 'an implemented subject is left untouched',
    );
  });

  test('U-W3: a missing subject file is a hard runner-error naming the '
      'gen remediation', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
      // registerBehavior records subject_path but writes no subject
      // file — the missing-artifact case exactly.
    );

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('missing subject file'));
    expect(out, contains('zfa tdd gen B-001'));
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=runner-error '
        'feature=${fx.featureName}',
      ),
    );
  });

  test('U-W4: a missing entity file is a hard runner-error naming the '
      'entity create remediation (misfire-stop, not papered over)', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));
    await Directory(
      '${fx.root.path}/lib/src/domain/entities/user',
    ).delete(recursive: true);

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('no generated entity "User" found'));
    expect(out, contains('zfa entity create -n User'));
    expect(
      out,
      contains(
        'wire: behavior=B-001 outcome=runner-error '
        'feature=${fx.featureName}',
      ),
    );
  });

  test('U-W5: an unrecognized UnimplementedError shape is refused — wire '
      'never rewrites a file it did not generate', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString('''
library;

class Weird {
  void run() {
    throw UnimplementedError('hand-written shape');
  }
}
''');

    final out = await runWire();

    expect(exitCode, isNot(0));
    expect(out, contains('unrecognized shape'));
    // The unrecognized file is untouched.
    final subject = await File(fx.subjectPathOf('B-001')).readAsString();
    expect(subject, contains('class Weird'));
  });

  test('U-W6: --entity is required — a wire without an entity anchor is a '
      'usage error', () async {
    await fx.registerBehavior(
      id: 'B-001',
      description: 'create entity User with email',
    );
    await File(fx.subjectPathOf('B-001')).writeAsString(genStyleStub('B-001'));

    final out = await runWire(entity: null);

    expect(exitCode, isNot(0));
    expect(out, contains('--entity <Name> is required'));
    expect(
      out,
      contains('wire: behavior=B-001 outcome=runner-error feature=unknown'),
    );
  });

  for (final externalPath in <String, String Function()>{
    'relative traversal': () => p.join('..', 'outside_subject.dart'),
    'absolute path': () => p.join(fx.root.parent.path, 'outside_subject.dart'),
  }.entries) {
    test('U-W7: a registry subject outside the project root is rejected '
        '(${externalPath.key})', () async {
      await fx.registerBehavior(
        id: 'B-001',
        description: 'create entity User with email',
      );
      final registry =
          jsonDecode(await File(fx.artifactsPath).readAsString())
              as Map<String, dynamic>;
      final records = registry['records'] as List<dynamic>;
      (records.single as Map<String, dynamic>)['subject_path'] = externalPath
          .value();
      await File(fx.artifactsPath).writeAsString(jsonEncode(registry));

      final out = await runWire();

      expect(exitCode, isNot(0));
      expect(out, contains('points outside the project root'));
      expect(
        out,
        contains(
          'wire: behavior=B-001 outcome=runner-error '
          'feature=${fx.featureName}',
        ),
      );
    });
  }

  group('bug 829: wire accepts every pipeline-generated subject', () {
    test('U-829a: a func-scaffolded subject (the gen stub header survives '
        'the func scaffold, so its doc comment still mentions '
        'UnimplementedError) is already implemented — already-wired, '
        'exit 0, never an unrecognized-shape refusal', () async {
      await fx.registerBehavior(
        id: 'B-001',
        description: 'create entity User with email',
      );
      // The exact shape `zfa tdd func` leaves on disk: the gen stub's
      // header comment (which mentions UnimplementedError in PROSE) plus
      // the scaffolded implementation body.
      await File(fx.subjectPathOf('B-001')).writeAsString('''
// GENERATED STUB — `zfa tdd gen B-001` (spec 044-test-tdd-generation).
//
// behavior_id: B-001
// source_criterion: FR-001
// description: The system shall persist a User with a name.
//
// This is a MINIMAL COMPILABLE STUB. It compiles cleanly (FR-011) but
// does NOT satisfy the behavior described above — the paired test will
// fail on first execution with an assertion-level failure (honest red).
// Replace this stub body with real implementation to make the test pass.
library;

/// Subject for behavior B-001.
///
/// Throws [UnimplementedError] until the real implementation lands.
String subject_b_001() {
  return 'subject_b_001';
}
''');

      final out = await runWire();

      expect(exitCode, 0, reason: 'out: $out');
      expect(
        out,
        contains(
          'wire: behavior=B-001 outcome=already-wired '
          'feature=${fx.featureName}',
        ),
      );
      // The implemented subject is left untouched.
      final subject = await File(fx.subjectPathOf('B-001')).readAsString();
      expect(subject, contains("return 'subject_b_001';"));
    });

    test('U-829b: an executable UnimplementedError in a non-stub shape is '
        'STILL refused — the U-W5 contract survives the comment-aware '
        'classification', () async {
      await fx.registerBehavior(
        id: 'B-001',
        description: 'create entity User with email',
      );
      await File(fx.subjectPathOf('B-001')).writeAsString('''
library;

class Weird {
  void run() {
    throw UnimplementedError('hand-written shape');
  }
}
''');

      final out = await runWire();

      expect(exitCode, isNot(0));
      expect(out, contains('unrecognized shape'));
      final subject = await File(fx.subjectPathOf('B-001')).readAsString();
      expect(subject, contains('class Weird'));
    });

    test('U-920: wired subject infers signature from description', () async {
      await fx.registerBehavior(
        id: 'B-002',
        description: 'render returns a non-empty string for task',
      );
      await File(
        fx.subjectPathOf('B-002'),
      ).writeAsString(genStyleStub('B-002'));

      final out = await runWire(id: 'B-002');

      expect(exitCode, 0, reason: 'out: $out');
      final subject = await File(fx.subjectPathOf('B-002')).readAsString();
      expect(subject, contains('String subject_b_002() {'));
      expect(subject, contains('final Type wiredEntityAnchor = User;'));
      expect(subject, contains("return 'subject_b_002';"));
    });

    test(
      'U-920a: wired subject preserves a signed integer return value',
      () async {
        await fx.registerBehavior(
          id: 'B-003',
          description: 'returns -42 when invoked with no args',
        );
        await File(
          fx.subjectPathOf('B-003'),
        ).writeAsString(genStyleStub('B-003'));

        final out = await runWire(id: 'B-003');

        expect(exitCode, 0, reason: 'out: $out');
        final subject = await File(fx.subjectPathOf('B-003')).readAsString();
        expect(subject, contains('int subject_b_003() {'));
        expect(subject, contains('return -42;'));
      },
    );

    test('U-920b: wired subject preserves a decimal return value', () async {
      await fx.registerBehavior(
        id: 'B-004',
        description: 'returns 3.14 when invoked with no args',
      );
      await File(
        fx.subjectPathOf('B-004'),
      ).writeAsString(genStyleStub('B-004'));

      final out = await runWire(id: 'B-004');

      expect(exitCode, 0, reason: 'out: $out');
      final subject = await File(fx.subjectPathOf('B-004')).readAsString();
      expect(subject, contains('double subject_b_004() {'));
      expect(subject, contains('return 3.14;'));
    });
  });
}
